vyperlang/vyper

- docs/built-in-functions.rst
Learning how extract32() works
Thanks to @skellet0r 
before
```python
@external
@view
def foo(Bytes[32]) -> address:
return extract32(b, 12, output_type=address)
```
after:
```python
@external
@view
def foo(b: Bytes[32]) -> address:
return extract32(b, 0, output_type=address)
```
> Update extract32() description

- vyper/__init__.py
The existing way doesn't work if `python setup.py install` hasn't been run yet.
This way works both with pyinstaller and regular setup.py.
`make docs` works without running `make` first. `make freeze` still produces a binary with a correct version.
> fix a bug in usage of scm-setuptools

- setup.py
normally setuptools_scm strips the commit hash when building from an
exact tag (e.g. git tag is v1.1.1); this adds it back on
Override the `"local_scheme"` parameters in setuptools_scm
Locally create a test tag like v0.3.2, `make install` and check that `vyper --version` has commit hash in it.
> add commit hash to --version even on tags

- tests/conftest.py
- vyper/compiler/output.py
- vyper/compiler/utils.py
- vyper/evm/opcodes.py
Fix #2552
First of all the LLL `codeload` macro had an incorrect gas estimate, second of all the heuristic for finding the runtime LLL was wrong.
> fix: gas estimate in presence of immutables

- tests/parser/features/external_contracts/test_external_contract_calls.py
- vyper/__init__.py
- vyper/old_codegen/external_call.py
- vyper/semantics/types/function.py
Implement #2550 
Pretty straightforward, thread the argument through typechecker and codegen
See tests
Add `omit_contract_check` kwarg as an external call option
> feat: implement skip_contract_check kwarg

- setup.py
- tests/base_conftest.py
- tests/conftest.py
- tests/parser/functions/test_return.py
- tests/parser/syntax/test_chainid.py
Fix for issue #2470 
1. Set `base_fee_per_gas` to `0` in the genesis header for the `tester` and `get_contract_module` fixtures in `tests/base_conftest.py` and `tests/conftest.py` respectively. Thanks to guidance from @fubuloubu, and also reference was made to [this change in py-evm](https://github.com/ethereum/py-evm/commit/94573ef783419cf306c59c37fbd6b00df9c165de).
2. Set `gasPrice` to `0` in a `buildTransaction` method call in the `test_correct_abi_right_padding` test at `tests/parser/functions/test_return.py`. 
3. Update the assertion for default chain ID value in `test_chain_id_operation` test at `tests/syntax/test_chainid.py`from `0` to `131277322940537` following the London hard fork. For more details, refer to [this change in …
> fix: update test suite to py-evm 0.5.0

- docs/types.rst
Removed variable ``z`` in the 'Arithmetic Operators' section for uint256.
This variable was originally used for ``uint256_mulmod`` and ``uint256_addmod`` functions, which has been moved to 'Built in Functions', and which documentation was removed from this section in #2081.
NA
NA
Improve documentation for uint256 type.
> docs: remove unreferenced var in uint256

- vyper/lll/compile_lll.py
This shaves 1 instruction (push1 32) and 5 gas off the implementation of
ceil32. This LLL op is a hot path because zero-pad uses it.
To verify the formula for y, check the edge cases:
0: and(not(sub(0, 1)), 31) == 0
1: and(not(sub(1, 1)), 31) == 31
2: and(not(sub(1, 1)), 31) == 30
30: and(not(sub(31, 1)), 31) == 2
31: and(not(sub(31, 1)), 31) == 1
Optimize ceil32 implementation
> optimize ceil32

- setup.py
- tests/base_conftest.py
- tests/cli/outputs/test_storage_layout.py
- tests/conftest.py
- tests/parser/functions/test_return.py
- vyper/semantics/types/indexable/mapping.py
The way it is currently written, e.g. `HashMap[x, y]` gets serialized as
`HashMap[x, y][x, y]`. This doesn't affect much since most outputs use
ABI typenames but the `-f layout` output uses this serializer.
Check `vyper -f layout` before and after for this contract:
```python
x: public(HashMap[uint256, uint256])
```
> fix the serialization of HashMap type

- tests/functional/context/validation/test_cyclic_function_calls.py
- vyper/semantics/validation/module.py
Fixes https://github.com/vyperlang/vyper/issues/2536 by filtering `internal_calls` by functions defined within the module. Considering the use of `internal_calls` attribute is only for this semantic analysis `_find_cyclic_call`, this filtering makes sense to me.
The error due to the invalid calls (like in the issue's snippet) will be catched naturally in the later phase of semantic analysis, so I didn't craft anything for that.
see "What I did"
I added a test case `test_global_ann_assign_callable_no_crash` based on the snippet from the issue, which would cause a crash in `_find_cyclic_call` without this PR's change.
I didn't run the full test yet locally, so I'd like to see CI if this change brings any regressions.
NA?
P.S.
Recently, I started to read some code around Ethereum's ecosystem …
> fix(semantics): fix crash when calling non callable self members

- docs/control-structures.rst
- tests/functional/codegen/test_abi_encode.py
- tests/functional/codegen/test_struct_return.py
- tests/parser/features/decorators/test_nonreentrant.py
- tests/parser/features/decorators/test_private.py
- tests/parser/features/external_contracts/test_external_contract_calls.py
- tests/parser/features/external_contracts/test_self_call_struct.py
- tests/parser/features/test_clampers.py
- tests/parser/features/test_internal_call.py
- tests/parser/functions/test_return_struct.py
PR for various tests associated with #2471 
Iterate through the list of functionalities fixed.
Run the test suite.
> test: tests for functionality fixed in #2471

- tests/parser/syntax/test_immutables.py
- vyper/semantics/validation/module.py
Fixes https://github.com/vyperlang/vyper/issues/2554
There already exists an error message when immutable variables don't have initialization in a constructor.
I added one more check to see if there's `self.(immutable name)` within module ast and prepared an specialized error message for such possibly common wrong usage.
Added a test case `test_compilation_fails_with_exception_message` in `tests/parser/syntax/test_immutables.py`.
P.S.
Happy new year! I hope I'm not disturbing maintainers during holidays.
I appreciate the code review, but please feel free to postpone it if you're in a busy time.
Thank you!
> fix: improve error message for `self.(immutable name)`

- tests/parser/types/test_lists.py
- vyper/semantics/validation/annotation.py
- vyper/semantics/validation/utils.py
Fix type checker issue in #2534 and #2130.
The type checking for `Subscript` VyperNode type currently assumes that an exact type can be derived for its `value`. Ordinarily, this does not raise an issue for array variables as the `value` of the `Subscript` node in this instance would be a `Name` node type, from which an exact type can be determined. 
However, where the array is a constant, the `value` of the `Subscript` node is now a `List` node. When deriving the type for a `List` node, a list of possible types are returned instead of a specific type (e.g. an array of [0, 1, 2] will return a list of `uint8`, `int128`, `int256` and `uint256`). As a result, a `StructureException` of 'Ambiguous type' will be thrown when there is more than one possible type for an array.
Relax the assumption …
> fix: type check for constant arrays

- tests/base_conftest.py
- tests/conftest.py
- tests/examples/auctions/test_blind_auction.py
- tests/examples/auctions/test_simple_open_auction.py
- tests/examples/crowdfund/test_crowdfund_example.py
- tests/examples/market_maker/test_on_chain_market_maker.py
- tests/examples/safe_remote_purchase/test_safe_remote_purchase.py
- tests/examples/wallet/test_wallet.py
- tests/parser/features/decorators/test_nonreentrant.py
- tests/parser/features/decorators/test_payable.py
- tests/parser/features/decorators/test_private.py
- tests/parser/features/external_contracts/test_external_contract_calls.py
- tests/parser/features/external_contracts/test_self_call_struct.py
- tests/parser/features/test_assert.py
- tests/parser/features/test_assert_unreachable.py
- tests/parser/features/test_clampers.py
- tests/parser/features/test_logging.py
- tests/parser/features/test_logging_from_call.py
- tests/parser/functions/test_create_with_code_of.py
- tests/parser/functions/test_default_function.py
- tests/parser/functions/test_raw_call.py
- tests/parser/functions/test_send.py
- tests/parser/integration/test_crowdfund.py
- tests/parser/syntax/test_self_balance.py
Update the test suite to the latest web3py function names.
The syntax for the following web3.py functions (currently v5.21.0 in `setup.py`) has changed as follows:
- `getBalance` has been deprecated in favour of `get_balance` (in v5.14.0)
- `getBlock` has been deprecated in favour of `get_block` (in v5.15.0)
- `blockNumber` has been deprecated in favour of `block_number` (in v5.16.0)
- `getCode` has been deprecated in favour of `get_code` (in v5.16.0)
- `sendTransaction` has been deprecated in favour of `send_transaction` (in v5.17.0)
- `getTransactionReceipt` has been deprecated in favour of `get_transaction_receipt` (in v5.18.0)
- `setGasPriceStrategy` has been deprecated in favour of `set_gas_price_strategy` (in v5.18.0)
Use `sed`, as suggested by @fubuloubu. 
Example:
```grep -rl …
```
> chore: update web3py function names for test suite

- tests/parser/syntax/test_list.py
- tests/parser/syntax/test_raw_call.py
- vyper/semantics/validation/utils.py
Fix for #2502. 
The issue highlighted the lack of a helpful error message for arrays of `String`. While working on the fix, I observed the same issue for `Bytes`, and extended the fix to cover it.
If there is only one possible type for a `List` node, check if it is a `String` or `Bytes`. If yes, raise a `StructureException` with the error message that `String arrays are not supported` / `Bytes arrays are not supported`.
See tests.
Improve exception handling for string and byte arrays
> fix: error handling for string and byte arrays

- docs/built-in-functions.rst
I tested immutable variable in slice func.
```
OWNER: immutable(address)
START: constant(uint256) = 1
LOOP: constant(uint256) = 3
SLICE_BYTE: immutable(uint256)
@external
def __init__(_slice: uint256):
OWNER = msg.sender
SLICE_BYTE = _slice
@external
@view
def test_slice():
idx: uint256 = 0
start_slice: uint256 = 0
swap_string: Bytes[96] = concat(
convert(msg.sender, bytes32),
convert(1234567891, bytes32),
convert(OWNER, bytes32))
for i in range(START, LOOP):
slice_string: Bytes[32] = slice(swap_string, start_slice, SLICE_BYTE)
idx += 1
start_slice = idx * SLICE_BYTE
```
```
START: constant(uint256) = 1
LOOP: constant(uint256) = 3
SLICE_BYTE: constant(uint256) = 32
@external
@view
def test_slice():
idx: uint256 = 0
start_slice: uint256 = 0
swap_string: Bytes[96] = concat( …
```
> length in the slice function must be constant.

- vyper/ast/signatures/function_signature.py
- vyper/codegen/module.py
- vyper/compiler/__init__.py
- vyper/compiler/output.py
- vyper/compiler/phases.py
This commit adds a "metadata" output format which is intended to be
useful for downstream tooling. Right now it is limited to function
signatures and their metadata, but it could be extended to more metadata
about modules such as type definitions and in-scope interfaces
(basically everything in GlobalContext).
```python
@internal
def foo() -> (uint256, uint256, uint256):
return 1, 2, 3
@internal
def bar():
pass
@external
def baz():
self.foo()
self.bar()
```
```
$ vyper -f metadata tmp/foo.vy
/home/charles/.venvs/vyper/lib/python3.8/site-packages/vyper-0.3.2+commit.b77ab184-py3.8.egg/vyper/compiler/output.py:93: UserWarning: metadata output format is unstable!
warnings.warn("metadata output format is unstable!")
{"function_signatures": {"foo": {"name": "foo", "args": [], "return_type": …
```
> add "metadata" output format

- tests/base_conftest.py
- tests/examples/safe_remote_purchase/test_safe_remote_purchase.py
Resolve warnings in CI from `hypothesis.HealthCheck` for the `@given` decorator.
Assign `module` scope to the `tester`, `w3`, `get_contract` and `assert_tx_failed` fixtures in `tests/base_conftest.py`.
Run tests, and see number of warnings drop.
Resolve hypothesis health check by assigning module scope to test fixtures
> test: resolve hypothesis healthcheck

- tests/cli/vyper_json/test_compile_from_input_dict.py
- tests/cli/vyper_json/test_output_dict.py
- tests/cli/vyper_json/test_output_selection.py
- tests/cli/vyper_json/test_parse_args_vyperjson.py
- vyper/cli/vyper_json.py
- vyper/compiler/__init__.py
> fix: ir and metadata outputs for vyper-json

- vyper/compiler/output.py
since `_lll_identifier` is a cached property, it doesn't show up as a
property until it is called for the first time. this forces it into the
metadata output
> fix: `_lll_identifier` caching

- tests/parser/types/test_lists.py
- vyper/codegen/core.py
- vyper/codegen/types/types.py
it was failing for the new uint8 type
fixes #2585
> generalize get_element_ptr to all integer types

- tests/parser/features/iteration/test_for_in_list.py
- vyper/codegen/stmt.py
- vyper/semantics/validation/local.py
Allow iterators for dynamic arrays, e.g.
```python
xs: DynArray[uint256, 5] = [1,2,3]
for x in xs:
if x == 2:
return x
return -1
```
add cases to `parse_For_list` and refactor to use more general functions
see tests
add iterators for dynamic array types
> allow dynamic array iterators

- tests/parser/syntax/test_interfaces.py
- vyper/codegen/stmt.py
- vyper/codegen/types/types.py
fix parsing of interface types in AnnAssign and tuples. respective examples:
```python
x: Foo = Foo(msg.sender)  # Foo is an interface
```
```python
@external
def foo() -> (bool, Foo):  # Foo is an interface
pass
```
fix missing arguments to `parse_type`
also change "optional" arguments to parse_type into required arguments so this doesn't happen in the future.
see tests
fix interface types in certain annotations
> fix AnnAssign for interface types

- tests/parser/features/iteration/test_for_in_list.py
- tests/parser/syntax/test_nested_list.py
- vyper/codegen/lll_node.py
- vyper/codegen/stmt.py
- vyper/codegen/types/convert.py
- vyper/semantics/validation/local.py
allow lists of any type as loop variable
added a function `new_type_to_old_type` so that we can use the results of the type checker directly. eventually this can replace the old `parse_type` function.
```python
struct X:
y: uint256
@external
def foo(xs: DynArray[X, 5]) -> uint256:
sum: uint256 = 0
for x in xs:
sum += x.y
return sum
```
> allow lists of any type as loop variable

- docs/constants-and-vars.rst
- tests/parser/functions/test_tx.py
- tests/parser/syntax/test_block.py
- vyper/codegen/expr.py
- vyper/semantics/environment.py
Add `gasprice` to `tx` namespace
Check test
feat: add gasprice to tx object namespace
> feat: add gasprice to tx object namespace

- tests/parser/features/test_immutable.py
- vyper/codegen/expr.py
fix #2626 
with the name as is, it won't get picked up by the branch in
`parse_Name` which checks `context.vars`, and so a fresh memory location
gets allocated. this commit changes the key inserted into context.vars
so that it will get picked up properly.
before:
```
/* A = _a */ [mstore, 224 <A>, [codeload, /* _a */ [with, val, ~codelen, val]]],
/* self.a = A */ [sstore, 0 <self.a>, [mload, 256 <A>]],  # <-- SHOULD BE mload 224
```
after:
```
/* A = _a */ [mstore, 224 <A>, [codeload, /* _a */ [with, val, ~codelen, val]]],
/* self.a = A */ [sstore, 0 <self.a>, [mload, 224 <A>]],
```
i guess i can write a test too
fix references to immutable variables in constructor
> fix references to immutable variables in constructor

- tests/conftest.py
- tests/parser/types/numbers/test_constants.py
- tests/parser/types/test_dynamic_array.py
- tests/parser/types/test_lists.py
- vyper/ast/folding.py
- vyper/semantics/validation/local.py
- vyper/semantics/validation/utils.py
Fix #2592.
Based on the issue, the following code compiles when it should not:
```
MY_CONSTANT: constant(uint256[3]) = [1,2,3]
@external
def foo() -> uint8[3]:
return MY_CONSTANT
```
While looking into this, I discovered two other similar code snippets that also compile when they should not:
```
MY_CONSTANT: constant(uint256[3]) = [1,2,3]
@external
def foo() -> uint8:
return MY_CONSTANT[0]
```
```
MY_LIST: constant(uint256[6]) = [1,2,3]
@external
def ix(i: uint256) -> uint8:
return MY_LIST[i]
```
The bug does not appear to be limited to constant arrays, however. The following code snippet also compiles when it should not:
```
MY_CONSTANT: constant(uint256) = 1
@external
def foo() -> uint8:
return MY_CONSTANT
```
Propagate the type definition of a constant when it is folded (i.e. replaced …
> fix: type check for constants

- tests/parser/features/decorators/test_private.py
- tests/parser/functions/test_default_parameters.py
- tests/parser/syntax/test_msg_data.py
- vyper/codegen/expr.py
- vyper/semantics/validation/local.py
Fix #2631 
Remove the restrictions, fix tests
Check tests
re-enable msg.* env variables in internal functions
> re-enable msg.* env variables in internal functions

- vyper/cli/vyper_json.py
- vyper/compiler/__init__.py
- vyper/compiler/output.py
add output format `ir_runtime` which returns only the runtime IR (strips off the constructor code)
> add ir_runtime output

- tests/cli/vyper_json/test_interfaces.py
- vyper/cli/utils.py
- vyper/cli/vyper_compile.py
- vyper/cli/vyper_json.py
Allow loading ABI types from ethPM manifest files
Hacking
The whole imports system needs a lot of work
Load interfaces from an ethPM Manifest file
> feat: support loading types from ethPM Manifest

- tests/parser/functions/test_slice.py
- vyper/builtin_functions/convert.py
- vyper/builtin_functions/functions.py
- vyper/codegen/core.py
fix case for converting Bytes to bytes32 - https://github.com/vyperlang/vyper/issues/2652
use bit ops to ensure the lower bytes are zeroed
see test
This commit fixes a bug in converting between Bytes types and bytes32.
Because of how bytes copying (and bytes zeroing -- `bytes = b""`) works,
a bytearray may have dirty bytes in its last word past the end of the
runtime length of the bytestring. For instance, the bytestring "a" maybe
be represented as
```
length | data
0x01   | 0x6162
```
This commit fixes that by ensuring that any dirty bytes get zeroed out
in the result by using bitwise operations.
This commit also changes the order of arguments in the convenience
functions shl()/shr()/sar() to match the argument order of the EVM.
> fix convert to bytes32

- vyper/codegen/core.py
when the subtype needs clamping, we can't use straight bytes copy, we
have to run make_setter in a loop (which performs clamping)
add a condition for looping in make_setter_dynarray
https://github.com/vyperlang/vyper/pull/2640/files#diff-d791908f2752921e3a897668bf4c1ed864af3ee089228e1e0f21577bf1f33285R414 should work
> fix lack of clamping for dynarray make_setter

- tests/parser/exceptions/test_invalid_literal_exception.py
- tests/parser/exceptions/test_invalid_type_exception.py
- tests/parser/syntax/test_list.py
- tests/parser/types/test_dynamic_array.py
- vyper/codegen/core.py
- vyper/codegen/expr.py
- vyper/codegen/types/convert.py
- vyper/semantics/validation/annotation.py
- vyper/semantics/validation/utils.py
this now compiles
```python
@external
def foo():
xs: DynArray[uint256, 5] = []
```
> add empty list literals for dynarray

- docs/constants-and-vars.rst
- docs/vyper-by-example.rst
> docs: msg.sender is available even in internal fns

- docs/types.rst
Clarify that dynamic arrays can be of value type or reference type (i.e. allows nesting).
Update documentation, and an ABI example.
See docs.
Improve dynamic array documentation.
> docs: add nested dynamic arrays

- setup.py
Fix for #2667.
Update `eth_tester` version to `0.6.0b6`.
Change the version number in `setup.py`.
Run `python setup.py test`.
Update eth_tester version to 0.6.0b6
> chore: update eth_tester version

- tests/parser/syntax/test_abi_encode.py
- vyper/semantics/validation/annotation.py
Fix for #2661.
When visiting a list node, we pop from the list of possible types derived only if its length is greater than 1. Since constant arrays will have only one possible type after constant folding, this fix relaxes the assertion to greater than or equal to 1. 
Add `=`.
See test case.
Fix _abi_encode for constant arrays
> fix: _abi_encode for constant arrays

- tests/parser/exceptions/test_invalid_type_exception.py
- tests/parser/features/test_logging_bytes_extended.py
- vyper/codegen/events.py
- vyper/codegen/stmt.py
fix https://github.com/vyperlang/vyper/issues/2663
previously event logging allocated the buffer prior to generating the
code for abi_encode + issuing log instruction; this is no longer
necessary in the new calling convention, so simplify the code so that
the codegen and buffer allocation happen in the same place.
see tests
> fix: refactor events and fix bad assertion

- .github/workflows/build.yml
- Makefile
- pyproject.toml
- setup.py
- vyper/__init__.py
- fix version string in `make freeze` generated binaries
- also fix the binary name in the "build.yml" workflow
- see https://gitlab.com/python-devs/importlib_metadata/-/issues/71
- remove pyproject.toml usage of setuptools_scm as it generates a  
conflicting version string depending on build context
(`setup.py install`, `pip install`, `make freeze`)
fix the case where the setuptools_scm default version string takes over
```bash
$ make freeze
...
12198 INFO: Building PKG (CArchive) vyper.0.3.2+commit.c47ce229.linux.pkg completed successfully.
....
$ dist/vyper.0.3.2+commit.c47ce229.linux --version
0.3.2+commit.cf5fad74
```
also testing the artifact workflow here: https://github.com/vyperlang/vyper/actions/runs/1854199900
> fix version string

- .github/workflows/build.yml
This will allow people to test new features before a new release, and when new stuff gets merged into master
> update build artifacts CI to build a binary when master updates

- README.md
no longer required as github has vyper syntax highlighting now
> chore: remove instructions for linguist-language

- vyper/cli/vyper_compile.py
minor quality of life addition - sometimes it's easier to look at constants in hex.
```bash
vyper --ir-hex -f ir /dev/stdin <<EOF
@external
def foo() -> uint256:
return 2
EOF
```
> feat: add CLI option to output hex for constants

- vyper/builtin_functions/functions.py
- vyper/lll/README.md
- vyper/lll/compile_lll.py
- vyper/utils.py
this is an optimizing opcode for ternary operations. this is useful
because even in the presence of perfect liveness analysis, branches
still need to issue more POPs than are required with a specialized
`select` opcode.
this commit also modifies the `min/max` to use the new opcode, as an
example.
fixes https://github.com/vyperlang/vyper/issues/2382
h/t to @yaronvel - https://twitter.com/yaron_velner/status/1499461195073568769
tests still pass
> feat: add `select` opcode to LLL

- tests/parser/functions/test_unsafe_math.py
- vyper/builtin_functions/functions.py
- vyper/codegen/expr.py
- vyper/utils.py
introduce unsafe math ops for https://github.com/vyperlang/vyper/issues/2429
add unsafe add/sub/mul/div builtins. for int types that are smaller than 256 bits, they perform wrapping arithmetic
check the tests
(tbd)
Add `unsafe_` arithmetic ops which don't use checked arithmetic
> feat: add unsafe arithmetic ops

- vyper/codegen/module.py
ensure basic block hygiene by closing with a terminating instruction (goto)
> feat: close external section with goto fallback

- examples/factory/Exchange.vy
- examples/factory/Factory.vy
- tests/parser/syntax/test_interfaces.py
- vyper/ast/signatures/function_signature.py
- vyper/codegen/expr.py
- vyper/codegen/external_call.py
- vyper/codegen/global_context.py
- vyper/codegen/module.py
- vyper/codegen/stmt.py
- vyper/codegen/types/types.py
fix #2696 
```
`global_context.py` had some old helper function called               
`get_item_name_and_attributes` which behaved incorrectly for complex  
types containing interfaces (specifically, an array of interfaces like
`MyInterface[3]`). Luckily, `parse_type` works better now and the code
seems to work after removing `get_item_name_and_attributes`. We also had    
a ContractRecord class which is now unused, so I removed it.          
Also now allow interfaces in interface signatures
```
> fix type of storage variables containing interface

- tests/parser/syntax/test_for_range.py
- vyper/codegen/types/convert.py
- vyper/semantics/types/__init__.py
following code was failing:
```python
xs: MyInterface[N]
for x in self.xs:
...
```
there was a missing case in a helper function
see tests
> fix interface list in `for`

- tests/parser/functions/test_unsafe_math.py
- tests/parser/syntax/test_list.py
- tests/parser/syntax/test_raw_call.py
- vyper/builtin_functions/functions.py
- vyper/builtin_functions/signatures.py
- vyper/codegen/core.py
- vyper/codegen/types/convert.py
- vyper/codegen/types/types.py
- vyper/semantics/environment.py
- vyper/semantics/types/__init__.py
- vyper/semantics/types/abstract.py
- vyper/semantics/types/function.py
- vyper/semantics/types/indexable/sequence.py
- vyper/semantics/types/value/address.py
- vyper/semantics/types/value/array_value.py
- vyper/semantics/types/value/bytes_fixed.py
- vyper/semantics/types/value/numeric.py
- vyper/utils.py
resolves https://github.com/vyperlang/vyper/issues/2559
> add all integer and bytes types

- tests/ast/test_folding.py
- tests/parser/features/external_contracts/test_external_contract_calls.py
- tests/parser/functions/test_default_parameters.py
- tests/parser/syntax/test_constants.py
- tests/parser/syntax/test_structs.py
- vyper/ast/folding.py
- vyper/semantics/types/function.py
- vyper/semantics/types/utils.py
- vyper/semantics/validation/module.py
Fix for #1430, extending on #2396.
The following code results in an error in v0.3.1:
```
struct Foo:
a: uint256
b: uint256
CONST_BAR: constant(Foo) = Foo({a: 7, b: 2})
```
```
vyper.exceptions.StateAccessViolation: Value must be a literal
contract "contracts/constantStruct1.vy", line 7:27 
6
---> 7 CONST_BAR: constant(Foo) = Foo({a: 7, b: 2})
----------------------------------^
8
```
[UPDATE]
After the above changes, attempting to return a struct constant or any of its member values resulted in an unhandled compiler error (see comments below) due to struct constants not being propagated during constant folding. I have made changes to handle constant propagation for folding of struct constants, and a minor change to handle constant struct members.
Type checking for struct constants
- …
> fix: allow struct constants

- examples/tokens/ERC721.vy
- tests/examples/tokens/test_erc721.py
- tests/parser/exceptions/test_type_mismatch_exception.py
- vyper/ast/annotation.py
- vyper/builtin_functions/functions.py
- vyper/builtin_interfaces/ERC165.py
- vyper/codegen/expr.py
update ERC721 to use bytes4, and fix some issues with bytes literals
notably, hex literals are always interpreted as bytesN now (not Bytes), and vice versa - bytes literals are always Bytes, not bytesN
> chore: update ERC721 to use bytes4

- vyper/builtin_functions/functions.py
Fixed input validation of function "as_wei_value", a compilation error was thrown when the type of parameter "value" is uint8.
Issue:  [2711](https://github.com/vyperlang/vyper/issues/2711)
I added an additional check to the line that checked if the type of "value" was uint256.
Fixed input validation of function "as_wei_value", a compilation error was thrown when the type of parameter "value" is uint8.
> Fix input validation of function "as_wei_value"

- tests/parser/exceptions/test_invalid_type_exception.py
- tests/parser/exceptions/test_vyper_exception_pos.py
- tests/parser/features/external_contracts/test_modifiable_external_contract_calls.py
- vyper/exceptions.py
check the following code
```vyper
foo: immutable(uint256)
bar: immutable(uint256)
@external
def __init__():
self.foo = 1  # SyntaxException
self.bar = 2  # SyntaxException
```
on master, the exception constructor fails. with this patch, the compiler correctly throws multiple syntax exceptions
```
The pretty-printed error message was arbitrarily choosing the first
exception in the list to use as the top-level exception. This commit
changes the behavior to use a generic VyperException (which is OK
because the child exceptions retain their names in the final output).
```
> fix error construction with ExceptionList

- vyper/compiler/output.py
when `seq` has no arguments (i.e., it is a no-op), it shows up in the
JSON representation as `"seq"`, instead of `{"seq": []}`. this commit
changes the representation to be the same in both cases, making it so
that downstream tools do not need to handle this inconsistency.
> fix: ad-hoc rule for json serialization of seq

- tests/grammar/test_grammar.py
it would throw on the following code string: `#\r""""""`. this commit
changes the grammar test function to use the same code path as
`vyper.compile_codes`.
> fix an occasional bug in grammar fuzzing

- examples/tokens/ERC20.vy
- vyper/codegen/core.py
this commit optimizes the make_byte_array_copier and
make_dynarray_copier routines. specifically, it reduces the number of
words to copy in the main loop by 1. for batch copies
(memory/calldata/code -> memory), this reduces gas by 3, and for
non-batch copies (e.g. storage -> memory), this reduces gas by one loop
iteration and one read. importantly, when the number of bytes is small
(e.g. copy Bytes[32]), this triggers an optimization in copy_bytes so
the whole copy operation is a single load/store (plus the load/store
for the length)
check tests still pass, check output of ERC20.vy and see there are no loops - bytecode is now 1342 bytes :)
> feat: optimize byte array copier

- .github/workflows/test.yml
in recent builds, the test are unevenly distributed to one runner. reset
the durations cache to fix.
e.g. https://github.com/vyperlang/vyper/runs/5686498127
> chore: bump durations cache

- setup.py
- vyper/address_space.py
- vyper/ast/signatures/function_signature.py
- vyper/builtin_functions/functions.py
- vyper/codegen/abi_encoder.py
- vyper/codegen/core.py
- vyper/codegen/expr.py
- vyper/codegen/external_call.py
- vyper/codegen/function_definitions/external_function.py
- vyper/codegen/ir_node.py
- vyper/codegen/return_.py
- vyper/codegen/self_call.py
- vyper/codegen/stmt.py
- vyper/codegen/types/types.py
add address space abstraction to help clarify the purpose of the `location` field on `IRnode`.
> refactor: add address space abstraction

- vyper/builtin_functions/convert.py
- vyper/builtin_functions/functions.py
- vyper/codegen/abi_encoder.py
- vyper/codegen/context.py
- vyper/codegen/core.py
- vyper/codegen/events.py
- vyper/codegen/expr.py
- vyper/codegen/external_call.py
- vyper/codegen/function_definitions/common.py
- vyper/codegen/function_definitions/external_function.py
- vyper/codegen/function_definitions/internal_function.py
- vyper/codegen/ir_node.py
- vyper/codegen/keccak256_helper.py
- vyper/codegen/return_.py
- vyper/codegen/self_call.py
- vyper/codegen/stmt.py
- vyper/ir/compile_ir.py
- vyper/ir/optimizer.py
this way we don't have to pass `pos` around everywhere in the call
stack. might make source maps easier to read, too
> refactor: add source_pos info in Expr/Stmt ctors

- tests/parser/exceptions/test_function_declaration_exception.py
- vyper/semantics/types/function.py
Fix for #2718.
Raise a `FunctionDeclarationException` if there is a return type for constructor.
See test cases.
```
fix: throw exception for return type in constructor
Raise a `FunctionDeclarationException` if there is a return 
type for constructor.
resolves: #2718
```
> throw exception for return type in constructor

- tests/parser/types/test_dynamic_array.py
- vyper/semantics/types/indexable/sequence.py
Throw an exception for string and bytes arrays.
Check for strings and bytes arrays as the value type of a dynamic array.
See tests.
fix: throw exception for dynarrays of strings and bytes arrays
Throw exception for string and bytes arrays
> Throw exception for string and bytes arrays

- tests/parser/types/test_dynamic_array.py
- vyper/codegen/stmt.py
- vyper/semantics/types/bases.py
- vyper/semantics/types/function.py
- vyper/semantics/types/indexable/mapping.py
- vyper/semantics/types/indexable/sequence.py
- vyper/semantics/validation/annotation.py
- vyper/semantics/validation/local.py
- vyper/semantics/validation/utils.py
fix several bugs in dynamic arrays typechecking.
existing code gives false negatives when typechecker allows something
but the types are not equal, for instance:
```vyper
x: DynArray[int128, 5] = []
x.append(1)  # 1 has type uint256
y: DynArray[String[32], 5] = []
x.append("hello")  # "hello" has type String[5]
```
existing code also fails to check state access and constancy violations for dynamic arrays.
fix dynamic array type from annotation
also, separate validate_index_type and get_subscripted_type, to separate
the concerns of validating an Index expression and getting the type of a
Subscript expression.
slight refactor of validate_modification. state access checks are always
performed right next to validate_modification, so move the state access
check logic down into …
> fix: dynamic array typechecker bugs

- tests/base_conftest.py
- vyper/codegen/core.py
fix #2744, and get rid of a spurious optimization in vyper.codegen.core (which was left in to deal with a related issue)
bump the block gas limit so the base fee does not adjust
tests pass
> fix: test failures due to basefee calc

- tests/parser/functions/test_empty.py
- tests/parser/syntax/test_bool.py
- vyper/codegen/expr.py
Fix for #2704.
Handle comparison of byte arrays (bytes, strings) that are `empty(String[N])` or `empty(Bytes[N])` by adding a flag to check for instances where both byte arrays are of equal max length and at least one value is `~empty`. If yes, check the length of the non-empty side against 0.
[UPDATE]
Comparison of byte arrays that are empty (i.e. "", b"") are updated to use the same codepath, instead of applying keccak to both values.
See tests.
```
This commit fixes an issue with equality checks involving empty(byte arrays)
(i.e. empty(Bytes[N]), empty(String[N])). 
A new flag is introduced to check if comparison involves an empty(byte array).
If yes, check the length of the non-empty side against 0.
Additionally, another flag is introduced to check if comparison involves a byte array …
```
> fix empty byte array comparison

- tests/parser/types/test_dynamic_array.py
- vyper/semantics/validation/annotation.py
- vyper/semantics/validation/local.py
e.g.
```vyper
dyn_array.append(self.foo[msg.sender])
```
fix the relevant case during type annotation. push down the known type from `MemberFunction.arg_types`.
see tests -- note that the new test in https://github.com/vyperlang/vyper/pull/2769/commits/eb46e1ccfb1242dff475ea74427f90c804a70903 will fail before the fix applied in https://github.com/vyperlang/vyper/pull/2769/commits/39810f8ca3235ad338860a62299714b70bcc20d5.
(save the manatees)
> fix: type inference on MemberFunction args

- tests/parser/functions/test_concat.py
- vyper/builtin_functions/functions.py
fix concat for `bytesM` where `M < 32` (new bytes types).
fix the codegen, also use routines from vyper.codegen.core.
h/t to @hedgar2017 for reporting
see tests
> fix: concat for bytesM, M<32

- tests/parser/types/test_bytes.py
- vyper/semantics/types/value/bytes_fixed.py
fix https://github.com/vyperlang/vyper/issues/2778
bytesM cannot be assigned from Bytes[M] in the typechecker, but the
following literal assignment bypasses the typechecker rule:
```vyper
name: public(bytes6)
@external
def __init__():
self.name = b"Celina"
```
block interpretation of literal Bytes as bytes
see tests
> fix: bytesM literal validation

- tests/ast/nodes/test_hex.py
- tests/functional/context/types/test_pure_types.py
- tests/parser/functions/test_convert.py
- vyper/ast/nodes.py
- vyper/codegen/expr.py
- vyper/semantics/types/value/address.py
- vyper/semantics/types/value/bytes_fixed.py
- vyper/semantics/validation/annotation.py
- vyper/utils.py
fix https://github.com/vyperlang/vyper/issues/2780
also fix https://github.com/vyperlang/vyper/issues/2790 by blocking underscores in hex literals.
propagate more type info down into codegen. note the bandaid in expr.py due to type annotations sometimes missing.
see tests
> fix bytes20 literals

- tests/parser/features/test_clampers.py
- tests/parser/functions/test_interfaces.py
```
add additional tests for recently fixed and added behavior.
tests include:
- validation of returndata inside concat (cf. 049dbdc647b2ce83)
- signed/unsigned integer clamps
- bytes_m clamps
```
> add additional tests for recently added behavior

- vyper/ast/nodes.py
It's more user friendly to complain about the underscores first
> fix order of literal hex validation rules

- tests/parser/globals/test_setters.py
- tests/parser/syntax/test_ann_assign.py
- tests/parser/syntax/test_no_none.py
- vyper/codegen/abi_encoder.py
- vyper/semantics/types/user/struct.py
the following example generated incorrect code:
```vyper
struct A:
a: uint256
b: uint256
@external
def foo() -> A
return A({b: 2, a: 1})  # returns (1, 2) instead of (2, 1)
```
After this commit, this code should raise `InvalidAttribute`.
In order to handle out of order keys in a sane way, we would be required
to change the order of execution. Assuming that keys being out of order
from the type definition is a code smell, block the behavior during
semantic analysis.
Also remove some dead code
(Note: unexpected order of execution was used for the first place of the underhanded solidity contest this year: https://blog.soliditylang.org/2022/04/09/announcing-the-underhanded-contest-winners-2022/.)
see test update
> fix: block struct literals with keys out of order

- docs/types.rst
Clarify that arithmetic is not available for all new types
> add some notes to docs

- vyper/semantics/namespace.py
- vyper/semantics/types/bases.py
- vyper/semantics/types/user/struct.py
- vyper/semantics/types/utils.py
- vyper/semantics/validation/levenshtein_utils.py
- vyper/semantics/validation/module.py
- vyper/semantics/validation/utils.py
- vyper/utils.py
Fix for #2767 
Refer to Brownie and docopt-ng. Helper function is extracted from the source at [docopt-ng](https://github.com/jazzband/docopt-ng/blob/bbed40a2335686d2e14ac0e6c3188374dc4784da/docopt.py).
Use Levenshtein distance for better error messages
Use Levenshtein distance for better error messages
> Use levenshtein distance for better error messages

- README.md
changed vyper.fun link to https://learn.vyperlang.org/
> doc: update learn.vyperlang.org hyperlink

- tests/parser/features/external_contracts/test_external_contract_calls.py
- tests/parser/features/test_internal_call.py
- vyper/semantics/types/function.py
Fix for #2525 
Throw an `ArgumentException` error during validation of kwargs other than `gas`, `value` and `skip_contract_check`.
See tests.
Better error message for unsupported kwargs in function calls.
Better error message for unsupported kwargs in function calls.
> Better error message for unsupported kwargs in function calls

- vyper/semantics/types/bases.py
> fix: signature for get_type_from_annotation 

- vyper/ast/nodes.py
- vyper/builtin_functions/functions.py
- vyper/utils.py
equivalent of nomic's console.log
> add print builtin

- tests/cli/outputs/test_storage_layout.py
- tests/functional/context/types/test_size_in_bytes.py
- tests/functional/test_storage_slots.py
- vyper/semantics/types/indexable/sequence.py
> fix off-by-one in dynamic array length calculation

- vyper/builtin_functions/convert.py
- vyper/builtin_functions/functions.py
- vyper/codegen/abi_encoder.py
- vyper/codegen/core.py
- vyper/semantics/types/function.py
> Missing `f` prefix on f-strings fix

- docs/control-structures.rst
was missed in 43f491fd801 (#2659)
> docs: rm note about msg.sender being unavailable

- tests/cli/outputs/test_storage_layout.py
- tests/cli/outputs/test_storage_layout_overrides.py
- vyper/semantics/validation/data_positions.py
- vyper/semantics/validation/module.py
publish immutables layout. since the output is a single dict of variable names (see below for ex.), I was a bit concerned about collisions between immutables and storage variables, so I went ahead and blocked those.
```json
{"foo": {"type": "uint256", "location": "code", "offset": 0, "length": 32}, "x": {"type": "uint256", "location": "storage", "slot": 0}}
```
add code offsets dict to the `-f layout` output
try
```vyper
vyper -f layout /dev/stdin <<EOF
x: uint256
y: immutable(uint256)
@external
def __init__():
y = 1
EOF
```
> feat: publish immutables layout

- vyper/semantics/types/user/struct.py
Fix typo in struct declaration error message
Fix the typo.
See updated error message.
Fix typo in struct declaration error message
Fix typo in struct declaration error message
> fix: struct declaration error message

- tests/parser/exceptions/test_structure_exception.py
- vyper/semantics/types/indexable/mapping.py
- vyper/semantics/validation/local.py
Fix for #2779 and #2802 
For 2779: Check for `Int` and `Name` AST node for a `Subscript` node's slice's value (should be `Tuple` for HashMap) when creating from annotation. This could potentially catch `Name` AST nodes that are not of positive integer types, but I think the array error precedes this.
For 2802: Block HashMaps without a key on the LHS of `Assign` AST node. 
See tests.
```
Improve error messages for HashMap syntax errors.
Fix #2779, Fix #2802
```
> fix: improve error messages for hashmaps

- docs/built-in-functions.rst
- vyper/builtin_functions/functions.py
the codegen was generic in the number of arguments, just need to remove
the check during `fetch_call_return`
> fix: allow varargs for print

- docs/built-in-functions.rst
- examples/tokens/ERC721.vy
- tests/examples/tokens/test_erc721.py
- tests/parser/functions/test_method_id.py
- tests/parser/functions/test_raw_call.py
- tests/parser/syntax/test_abi_encode.py
- vyper/builtin_functions/functions.py
Fix #2811.
Replace `bytes32` with `bytes4`, and set it as default.
See updated tests.
```
Update method_id output_type
Replace bytes32 with bytes4, and set bytes4 as default return type.
```
Update method_id output_type
> fix: update method_id output_type

- vyper/exceptions.py
this commit reverses the order in which multiple exceptions are
reported. this is a usability issue because sometimes when exceptions
cascade, the first error is the most meaningful (other errors depend on
the first error being fixed).
> ux: reverse order in which exceptions are reported

- LICENSE
Add a clause to the vyper license restricting use to machine learning algorithms, as there are legal and ethical issues with the Copilot program. Cf. https://www.fsf.org/blogs/licensing/fsf-funded-call-for-white-papers-on-philosophical-and-legal-questions-around-copilot.
> license: add copilot clause

- tests/parser/functions/test_block.py
- tests/parser/functions/test_create_with_code_of.py
some tests would fail in parallelized environments, because they implicitly depended on tests in the module being run in a certain order.
see the commit messages
tests pass
> fix: tests that fail in parallelized environments

- examples/stock/company.vy
- tests/conftest.py
- tests/parser/features/test_immutable.py
- tests/parser/features/test_init.py
- vyper/ast/signatures/__init__.py
- vyper/ast/signatures/function_signature.py
- vyper/ast/signatures/interface.py
- vyper/codegen/context.py
- vyper/codegen/function_definitions/__init__.py
- vyper/codegen/function_definitions/common.py
- vyper/codegen/function_definitions/external_function.py
- vyper/codegen/global_context.py
- vyper/codegen/ir_node.py
- vyper/codegen/module.py
- vyper/codegen/self_call.py
- vyper/compiler/output.py
- vyper/compiler/phases.py
- vyper/compiler/utils.py
- vyper/ir/compile_ir.py
- vyper/ir/optimizer.py
- vyper/semantics/types/function.py
- vyper/semantics/validation/annotation.py
allow calling internal functions from constructor. fixes https://github.com/vyperlang/vyper/issues/1631 and https://github.com/vyperlang/vyper/issues/2318
```
this commit allows the user to call internal functions from the     
`__init__` function. it does this by generating a call graph during the
annotation phase and then generating code for the functions called from
the init function for during deploy code generation                 
this also has a performance benefit (compiler time) because we can get
rid of the two-pass method for tracing frame size.                  
now that we have a call graph, this commit also introduces a topsort of
functions based on the call dependency tree. this ensures we can compile
functions that call functions that occur after them in the source code. …
```
> feat: call internal functions from constructor

- vyper/semantics/types/function.py
Fixed the spelling of the word cannot
Removed a letter
Check the spelling
It's a tiny change.
_Fixed a minor spelling error_
> fix typo in function validation error message

- tests/parser/features/iteration/test_continue.py
- vyper/semantics/validation/local.py
Fix #2858.
Visit `Continue` nodes in local validation and check if there is a `For` node in its ancestors.
See new tests.
```
Fix: throw exception for `continue` outside `for` loop
```
Throw exception for `continue` outside `for` loop
> fix: throw exception for `continue` outside `for` loop

- tests/parser/syntax/test_code_size.py
- vyper/codegen/expr.py
fix #2876
the check for `self` in `.codesize` codegen was a little too strict on the type of the AST node. change to not assume `expr.value` is a `Name` AST node.
see tests
> fix: .codesize codegen on complex attribute

- tests/compiler/ir/test_optimize_ir.py
- tests/parser/features/test_internal_call.py
- vyper/codegen/ir_node.py
- vyper/ir/optimizer.py
fix overly aggressive optimizations introduced in #2647
roll back the optimization if a side-effecting operation is not found in the optimized result. the heuristic is overly conservative, which i am ok with.
see code, tests
> fix: optimizer regression

- tests/parser/features/iteration/test_for_in_list.py
- vyper/semantics/validation/local.py
Fix #2866.
Check if `iter` is a storage variable by checking its child nodes for `Name` with `id` attribute set to `self`.
See new tests
```
fix: improve modification check for storage variable iterators
Fix #2866
```
Improve modification check of storage variables used as iterators
> fix: improve modification check of storage variables used as iterator

- docs/vyper-by-example.rst
Recent changes to the crowdfund.vy contract meant the codeblocks were off in the vyper by example blocks.
Also removed references to nextFunderIndex & refundIndex, as both were also removed in the updated code.
> Fixes to 'crowdfund' example

- docs/vyper-by-example.rst
Code blocks seems to have been thrown off by changes to the contract code (May 10th)
Also changed type ``currrency_value`` to type ``uint256``.
Fixed Company stock code blocks in vyper by example.
> Update 'Company Stock' section of vyper-by-example

- .github/workflows/test.yml
note: pending durations file to be pushed to https://github.com/vyperlang/vyper-test-durations
```
our tests are imbalanced now, and the job to rebuild the durations file
takes too long to run (times out on GH actions 6 hour limit). going
forward we will maintain the `.test_durations` file in the auxiliary
`vyper-test-durations` repo, and manually rebuild it as needed.
```
> fix: move .test_durations file to auxiliary repo

- docs/compiling-a-contract.rst
- docs/scoping-and-declarations.rst
Add documentation for storage layout overrides. #2593 
I wasn't 100% sure whether the best place to add this documentation would be. I thought maybe adding it with the section on variable declaration, but am open to other ideas.
Updated `docs/scoping-and-declarations.rst`
Ran locally with no issues.
Add documentation for storage layout overrides
> docs: storage layout override

- tests/parser/features/external_contracts/test_external_contract_calls.py
- tests/parser/functions/test_default_function.py
- vyper/codegen/function_definitions/external_function.py
Fix #1730.
Add a clamper for calldata to be at least of minimum ABI size + 4 bytes for method ID.
See additional tests.
```
fix: ensure calldata is of minimum length
Added a clamper to calldata to ensure its length is at least 
equal to or greater than the minimum ABI size + 4 bytes for
method ID.
Fix #1730.
```
Ensure calldata is at least of minimum length.
> fix: per-method calldatasize checks

- .github/workflows/test.yml
- tests/parser/types/numbers/test_signed_ints.py
- tests/parser/types/numbers/test_unsigned_ints.py
bring CI from ~60 minutes back down to ~30 minutes
tuning, reduce # of fuzzer cases and increase # workers
> tune arithmetic ops CI

- vyper/builtin_functions/functions.py
the existing implementation used a single mstore, but the first byte of
the length might be dirty. to ensure the entire bytestring is clean, use
two mstores.
> fix: avoid dirty byte edge case in uint2str

- tests/parser/features/decorators/test_nonreentrant.py
- tests/signatures/test_invalid_function_decorators.py
- vyper/codegen/function_definitions/utils.py
- vyper/semantics/types/function.py
on view functions, the sstores are not issued, but the sload check is
> allow "nonreentrant" on view functions

- vyper/codegen/function_definitions/utils.py
after berlin (istanbul?), it is cheaper to use a nonzero slot. this brings the total
cost of a nonreentrancy lock down from 4400 gas to 2300 gas.
> optimize runtime values for nonreentrant slots

- docs/control-structures.rst
- nonreentrant storage slots
- view function restrictions
- what nonreentrant on view function means
- gas costs for storage slots
- other formatting fixes
> docs: add details on nonreentrant implementation

- .github/workflows/test.yml
- vyper/codegen/expr.py
- vyper/codegen/ir_node.py
- vyper/ir/optimizer.py
unique_symbols() (introduced in https://github.com/vyperlang/vyper/pull/2914) is a perf hotspot, apparently causing deadline timeouts for compile-time sensitive tests:
https://github.com/vyperlang/vyper/actions/runs/2536751038
https://github.com/vyperlang/vyper/actions/runs/2536641822
https://github.com/vyperlang/vyper/actions/runs/2542723731
https://github.com/vyperlang/vyper/actions/runs/2537669543
```
`unique_symbols()` (introduced 2fddbdeb49) is apparently a perf hotspot,
causing CI deadline timeouts. this commit reduces computation of
`unique_symbols()` by turning it into a `cached_property`
```
> reduce compile time

- .github/workflows/test.yml
- tests/base_conftest.py
- tests/parser/functions/test_create_functions.py
- vyper/builtin_functions/functions.py
as title. the motivation for this is that people might deploy factories with custom prefixes (e.g. `0xFE` INVALID to prevent execution of the factory as a standalone/runtime contract, or as part of an EOF container). this enables that usage by adding a `code_offset` which allows people to offset into the factory contract address for the EXTCODECOPY. (implementation note: the implementation does check that `code_offset < extcodesize target`).
see tests
(By Yathin S Krishnappa - Own work, CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=24224663)
> feat: add `code_offset=` kwarg to `create_from_factory`

- setup.py
- vyper/cli/vyper_ir.py
as title. also allow it to be run directly like `python vyper/cli/vyper_ir.py`.
> chore: rename vyper-ir to fang

- examples/tokens/ERC721.vy
In EIP-721, the ERC-721 Non-Fungible Token Standard, optional metadata extension.  Defined a function called "tokenURI"
`
function tokenURI(uint256 _tokenId) external view returns (string);
`
https://eips.ethereum.org/EIPS/eip-721
I changed "tokenURL" to "tokenURI"
> fix: change tokenURL to tokenURI, according to EIP-721

- vyper/ir/compile_ir.py
```
fix: create unique revert labels per compilation
when importing vyper as a library, the revert labels can run into
collisions. to avoid that, this commit creates a new revert label on
every call to `compile_to_assembly`
```
> fix: create unique revert labels per compilation

- tests/compiler/test_source_map.py
- vyper/codegen/arithmetic.py
- vyper/codegen/core.py
- vyper/codegen/ir_node.py
- vyper/codegen/module.py
- vyper/codegen/stmt.py
- vyper/ir/compile_ir.py
- vyper/ir/optimizer.py
add an error map to source_map output. this makes it easier for downstream tooling to detect why a revert was issued (without having to rely on heuristics or explicit returndata). this also paves the way for brownie-style dev revert strings to be supported by at the language level.
> feat: error map

- vyper/ast/nodes.py
in IPython, if an exception is thrown, apparently certain AST nodes can
get annotated with a `.parent` member. this later collides with the
`parent=` kwargs when constructing vyper nodes.
> fix: ast.AST node corruption

- tests/functional/context/types/test_type_from_annotation.py
- tests/grammar/vyper.lark
- tests/parser/types/test_lists.py
- vyper/semantics/types/indexable/sequence.py
- vyper/semantics/types/utils.py
Fix #2951.
Set `_as_array` to `True` for `DynamicArrayPrimitive`, and add condition that `Subscript.slice.value` must not be `vy_ast.Tuple` for array type in `get_type_from_annotation` to exclude plain dynamic arrays.
See new tests.
```
fix: allow static arrays of dynamic arrays
Allows static arrays of dynamic arrays.
Fix #2951.
```
Allow static arrays of dynamic arrays.
> fix: allow static array of dynamic array

- vyper/ast/signatures/function_signature.py
- vyper/compiler/output.py
`FrameInfo` is not JSON serializable; implement a serializer for it
`vyper -f metadata` works
> fix metadata serialization

- .github/ISSUE_TEMPLATE/bug.md
- vyper/cli/vyper_compile.py
```
the `--debug` flag is a bit confusing since it sounds like it turns on a
debugger mode for the compiler, when in fact it just tells the compiler
to be more verbose in its output.
this rename will also be helpful if we add a true debugger mode to the
compiler in the (near?) future.
```
> chore: rename --debug flag to --verbose

- tests/parser/types/numbers/test_decimals.py
- vyper/utils.py
some non-CPython stdlibs (i.e. pypy) trigger this in the decimal ctor.
relax the restriction so that no-op setattrs are ok
> fix: relax restriction on changing decimal precision

- tests/grammar/vyper.lark
- tests/parser/functions/test_bitwise.py
Fix operator precedence in test grammar.
Update test grammar according to the stipulated precedence.
See new tests.
```
fix: operator precedence in grammar
Align operator precedence with python's grammar.
```
Fix operator precedence in test grammar.
> fix: operator precedence in grammar

- docs/built-in-functions.rst
- tests/base_conftest.py
- tests/parser/functions/test_create_functions.py
- vyper/builtin_functions/functions.py
based on the premise that factory is already overloaded with other
meanings
> chore: rename factory to blueprint

- vyper/ir/compile_ir.py
as title.
tests still pass
```
feat: optimize initcode size
if initcode is going to be deployed as part of a factory pattern, we
need to try to optimize the codesize of initcode (which previously was
not a priority, since codesize is only constrained for runtime code).
this commit optimizes PUSH instructions for memory symbols -- memory
locations of immutable variables. it does this by assembling the runtime
code as the first pass in assembly_to_evm, and then using the smallest
possible PUSH instruction which will handle all the memory symbols that
will be generated.
```
Optimize initcode size
> feat: optimize initcode size

- docs/built-in-functions.rst
Changing a part of the doc about the `raw_call` function
* Removed a line about "a duplicated contract", which has nothing to do with the `raw_call` function
* Tried to re-arrange the paragraph
docs: raw_call function cleaning
Cleaning a line from the raw_call function documentation
> docs: raw_call function cleaning

- tests/ast/nodes/test_replace_in_tree.py
- vyper/ast/expansion.py
- vyper/ast/folding.py
- vyper/ast/nodes.py
- vyper/utils.py
reduce build time.
time vyper Vault.vy went from `0m13.121s` to `0m3.521s`
time vyper CurveCryptoSwap2.vy went from `0m53.054s` to `0m5.259s`
investigating the time spent in various compiler phases, turns out 90% was spent in just three places.
the relevant lines triggered re-traversals of the entire AST, resulting
in O(n^2) build times. for non-trivial contracts near the 24KB limit,
this resulted in near-minute long build times.
this commit also adds timer utility functions so that the profiling can be easily done again.
> perf: remove compiler hotspots

- docs/types.rst
- tests/parser/functions/test_convert.py
- vyper/builtin_functions/convert.py
- vyper/codegen/types/types.py
> feat: add convert for enum

- docs/built-in-functions.rst
Documentation -> Grammar
Minor corrections in `built-in-functions.rst`.
> Docs — Minor fixes in `built-in-functions.rst` 

- tests/fuzzing/test_exponents.py
- tests/parser/types/numbers/test_signed_ints.py
- tests/parser/types/numbers/test_unsigned_ints.py
- vyper/codegen/arithmetic.py
fix #2984, #2986, #2987, #2989
> fix: edge cases in safepow

- docs/structure-of-a-contract.rst
See #2997.
`Replace broken link to npm semver docs`
> Replace broken link to npm semver docs

- tests/cli/vyper_compile/test_compile_files.py
- vyper/cli/vyper_compile.py
- vyper/compiler/__init__.py
- vyper/compiler/output.py
- vyper/compiler/phases.py
add output format which deploys blueprint contracts
futz around with codecopy
try `vyper -f blueprint_bytecode <foo.vy>`
> add blueprint bytecode output

- tests/parser/functions/test_create_functions.py
- vyper/builtin_functions/functions.py
```vyper
@external
def foo(addr: address, argdata: Bytes[1024]) -> address:
return create_from_blueprint(addr, argdata, raw_args=True)
```
```
this commit adds a `raw_args` kwarg to `create_from_blueprint`, allowing
the user to append arbitrary data to the initcode after extcodecopy
(instead of ABI encoding the provided varargs). this is important for
a variety of use cases:
- generic create (where the initcode args cannot be specialized at
compile time)
- custom arg decoders in the initcode (which may for instance be written
in assembly)
- other use cases for arbitrary auxdata which haven't been thought of
yet :)
```
> feat: add raw_args kwarg to create_from_blueprint

- vyper/ir/compile_ir.py
so disassemblers/analyzers can reliably detect where the code ends and
the CBOR metadata starts
fix #3009
compile a vyper contract and inspect last 13 bytes
```
add binary encoded length to the end of the CBOR metadata so
disassemblers can reliably detect where code ends and metadata starts
```
add length to CBOR metadata so bytecode analysis can reliably demarcate it
> add cbor length metadata

- tests/parser/types/test_enum.py
- vyper/codegen/expr.py
UX fix: enum members accessed directly with `self` would throw a compiler panic
fix namespace detection in codegen
see tests
enum members accessed directly with `self` would throw a compiler panic
> fix: enum variables accessed via `self.`

- tests/parser/functions/test_default_parameters.py
- tests/parser/syntax/test_constants.py
- vyper/builtin_functions/functions.py
- vyper/semantics/types/utils.py
Fix #3004. Also fixes `empty` for constant.
Add `_kwargable` attribute to `Empty` builtin.
See tests.
```
fix: allow empty builtin in kwargs and constants
```
Allow empty builtin in kwargs and constants.
> fix: empty builtin in kwargs and constants

- vyper/semantics/types/bases.py
Fixed typo.
```
overriden -> overridden
```
> refactor: fix typo in bases.py

- docs/built-in-functions.rst
Added uint2str to docs.
added uint2str to the docs
> docs: uint2str

- docs/built-in-functions.rst
Added the missing space on the Built-in Functions documents.
It was missing a space, so I added it. Checked it by compiling .rst file after.
Check out the Note on the [Built-in Functions docs](https://vyper.readthedocs.io/en/stable/built-in-functions.html), it's not rendered correctly.
docs: fix small typo
Added missing space.
> docs: fix small typo

- vyper/codegen/core.py
`convert(x, uint64)` didn't produce an error message. this adds some missing messages
> fix: add some missing error messages

- tests/compiler/test_source_map.py
- vyper/compiler/output.py
the compressed source map had a trailing semicolon. (previously it was
moot because the runtime bytecode did not have any trailing
instructions, now it does because of the CBOR encoded metadata).
fix #3022
> fix: trailing semicolon in compressed source map

- tests/parser/features/decorators/test_pure.py
- vyper/semantics/validation/local.py
Fix for #3021 
Check for standalone accesses to `self` by filtering out `Name` nodes with an ancestor that is not an `Attribute` node.
See test
```
fix: access to `self` in pure functions
```
Disable access to `self` in pure functions
> fix: `self` in pure functions

- tests/ast/nodes/test_evaluate_compare.py
- tests/compiler/ir/test_optimize_ir.py
- tests/parser/types/test_dynamic_array.py
- vyper/ast/nodes.py
- vyper/codegen/expr.py
- vyper/ir/optimizer.py
for list literals, the following
```
x in [a, b, c]
```
can be unrolled to
```
x == a or x == b or x == c
```
likewise,
```
x not in [a, b, c]
```
can be unrolled to
```
x != a and x != b and x != c
```
this commit also slightly refactors the code for logical and and logical or
to make this easier
check tests still pass. may want to update the tests to ensure we are testing `in/not in` for both literals and non-literals.
comparison of before/after
```vyper
@external
def foo(x: uint256) -> bool:
return x in [1,2,3,4,5]
```
```
In [1]: import boa; t = boa.load("tmp/in.vy")  # this branch
In [2]: t.foo(5); t._computation.get_gas_used()
Out[2]: 233
```
```
In [1]: import boa; t = boa.load("tmp/in.vy")  # v0.3.4
In [2]: t.foo(5); t._computation.get_gas_used()
Out[2]: 542
```
Commit message for …
> unroll `in` and `not in` expressions

- tests/ast/nodes/test_evaluate_compare.py
- tests/parser/types/test_dynamic_array.py
- vyper/ast/expansion.py
fix #3016 
see tests
```
DynArray getter AST expansion had a regression in be2c59a604. the
removed lines 70-73 modified the return node ID, which incidentally
patched the fact that the type unpacking logic in the previous lines
didn't account for DynArrays properly. this commit handles the DynArray
case properly
```
> fix: public DynArray getters

- docs/vyper-by-example.rst
Corrected some explanations to match the code.
> doc: correct explanations in `vyper-by-example.rst`

- tests/parser/features/test_comparison.py
- vyper/codegen/expr.py
fix #3034 
dereference pointers properly
```
fix a regression introduced in 2db84a90cd. when the members of a list
literal are not themselves literals, they need to be dereferenced.
```
> fix: `in` expr when list members are vars

- README.md
- docs/contributing.rst
Update Discord link.
See docs
See docs
docs: update Discord link
Update Discord link in documentation
> chore: update discord link in docs

- examples/auctions/blind_auction.vy
- examples/name_registry/name_registry.vy
- examples/tokens/ERC1155ownable.vy
- examples/tokens/ERC20.vy
- examples/tokens/ERC721.vy
- examples/voting/ballot.vy
- examples/wallet/wallet.vy
Fixed the compile warnings in `examples`
:%s/ZERO_ADDRESS/empty\(address\)/g
> fix(examples): compile warnings

- tests/functions/folding/test_epsilon.py
- vyper/builtin_functions/functions.py
Added an epsilon() builtin which returns the smallest non-zero value for a decimal type.
Closes #2992
In `vyper/builtin_functions/functions.py` I implemented a new class `Epsilon`. The function that this class represents should always be folded. 
Instead of adding to the duplication between MinMaxValue and MethodID, I created a new base class `FoldedFunction` which contains all the logic for enforcing a function should always be folded.
In `Epsilon`'s `evaluate` function, we check the type that was passed in, ensure it is a `FixedAbstractType` (which is the parent class for Decimal and any other decimal classes to be supported later).
Then we call the appropriate `_eval_<type>` function after checking which type was passed in. This currently only supports "decimal" but sets up a pattern …
> feat: add epsilon builtin

- examples/crowdfund.vy
Changed "the goal has been reached" to "the goal has not been reached" in assert description as in case of an assertion failed that would mean that goal is not reached and this could be misleading.
It was fast and easy, just a typo
Follow the links:
https://raw.githubusercontent.com/vyperlang/vyper/master/examples/crowdfund.vy
https://raw.githubusercontent.com/nfwsncked/vyper/master/examples/crowdfund.vy
improvement: assert description in Crowdfund.finalize()
Fixed a typo in Crowdfund.finalize() assertion description
> improvement: assert description in Crowdfund.finalize()

- tests/parser/exceptions/test_invalid_type_exception.py
- vyper/semantics/validation/utils.py
QOL improvement for #3062. 
When declaring an address literal, the compiler throws an `InvalidType` exception if it is not checksummed. This PR improves the error message by checking if the user meant the checksummed value.
Add an error message if expected type is address and the only possible type is bytes20.
NA
```
chore: improve error message for non-checksummed address literal
```
Improve error message for non-checksummed address literal
> chore: improve error message for non-checksummed address literal

- tests/parser/types/test_dynamic_array.py
- vyper/semantics/validation/utils.py
Fix #3048. 
Check for empty dynamic arrays recursively.
Add a helper function `_is_empty_list` to recursively determine if a literal list is empty.
See tests.
```
fix: allow variable length empty dynamic arrays
```
Allow variable length empty dynamic arrays
> fix: empty nested dynamic arrays

- docs/versioning.rst
Fix typos in docs.
See changes.
Read the changes.
docs: fix typos in versioning
Fix typos in versioning.rst
> docs: fix typos

- .github/workflows/test.yml
- Dockerfile
- setup.py
- tox.ini
drop tests for 3.7 since isqrt does not exist in 3.8. note that vyper can still be installed on 3.7 but we no longer officially test it.
> drop 3.7 support

- examples/tokens/ERC721.vy
Arose from #3066. Following EIP-721, the function onERC721Received from the interface should be a state-modifying callback.
Replaced "view" mutability to "nonpayable" as the onERC721Received function should read from and write to the contract state.
^^
Check the file changes. 
Changed mutability of onERC721Received to nonpayable
> fix: change mutability of example ERC721 interface

- vyper/builtin_functions/functions.py
minimizes stack traffic. based on local benchmarks, reduces `isqrt` worst case performance from ~650 gas to ~500 gas.
> chore: optimize isqrt by rewriting in IR

- tests/parser/functions/test_interfaces.py
- vyper/builtin_functions/functions.py
Fix #3077.
- Modify `FoldedFunction` class to set `_kwargable` attribute to True, and ensure `fetch_call_return` provides the return type.
- Add a new `TypenameFoldedFunction` for foldable builtin functions that take a single typename argument.
See tests.
```
fix: import of interfaces with foldable builtin functions as kwargs
Fix import of interfaces with foldable builtin functions 
as kwargs.
Adds a new TypenameFoldedFunction class for 
empty, min_value and max_value.
```
Fix import of interfaces with foldable builtin functions as kwargs.
> fix: import of interfaces with foldable builtin functions as kwargs

- docs/constants-and-vars.rst
- tests/compiler/test_opcodes.py
- tests/parser/syntax/test_block.py
- vyper/codegen/expr.py
- vyper/evm/opcodes.py
- vyper/semantics/environment.py
[EIP-4399](https://eips.ethereum.org/EIPS/eip-4399) renames the `DIFFICULTY (0x44)` opcode to `PREVRANDAO (0x44)`. The return value of the `DIFFICULTY (0x44)` instruction after this change is the output of the randomness beacon provided by the beacon chain.
With my brain.
Ask Vitalik's masternode.
```
feat: add `block.prevrandao` as alias for `block.difficulty`
per paris merge, EIP-4399 renames the `DIFFICULTY (0x44)` opcode to
`PREVRANDAO (0x44)`. the return value of the `DIFFICULTY (0x44)`
instruction after this change is the output of the randomness beacon
provided by the beacon chain.
```
Add  `block.prevrandao` as alias for `block.difficulty`.
> feat: introduce `block.prevrandao` as alias for `block.difficulty`

- tests/parser/features/external_contracts/test_external_contract_calls.py
- vyper/codegen/function_definitions/external_function.py
a37bbbca706 (https://github.com/vyperlang/vyper/pull/2911) introduced per-method calldatasize checks. however, for the case where calldata is statically sized (in the ABI sense), this check is too strict, since users might want to append extra bytes to the calldata and manipulate msg.data directly for some application-level reasons.
change "eq" to "ge"
see the tests
> fix: relax check for statically sized calldata

- vyper/exceptions.py
Added lineno at the end of the part of the exception that mentions the contract throwing the error. This is similar to how python does exceptions, for example:
```
venv/lib/python3.10/site-packages/vyper/semantics/validation/local.py:66: in validate_functions
err_list.raise_if_not_empty()
```
The added advantage of this is that it allows IDEs to navigate directly to the line that invokes the exception via `cmd+click` or `ctrl+click` (on, for example, VSCode).
Just add `node.lineno` in the exception string where the contract's dir is printed.
you'll need to have a contract that borks. The exception will look something like:
```
vyper.exceptions.VyperException: Compilation failed with the following errors:
E           
E           StructureException: Value is not callable
E …
```
> feat: add lineno at the end of exception string pointing to file

- examples/tokens/ERC721.vy
- vyper/builtin_interfaces/ERC721.py
In the official [EIP-721](https://eips.ethereum.org/EIPS/eip-721), the following functions are declared as `payable`:
```solidity
function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) external payable;
function safeTransferFrom(address _from, address _to, uint256 _tokenId) external payable;
function transferFrom(address _from, address _to, uint256 _tokenId) external payable;
function approve(address _approved, uint256 _tokenId) external payable;
```
I changed the functions `safeTransferFrom(address,address,uint256)`, `safeTransferFrom(address,address,uint256,bytes)`, `transferFrom(address,address,uint256)`, and `approve(address,uint256)` to be `payable`.
Fixes https://github.com/vyperlang/vyper/issues/3096.
Check the built-in interface and example code.
```
💵 …
```
> feat: make built-in `ERC721` interface functions `payable`

- SECURITY.md
Fixed broken links in SECURITY.md policy.
Replaced Consensys links with correct routing, and replaced Computable.io homepage link with their repo as the homepage is not hosted anymore.
Check commit.
> fix: update broken links in SECURITY.md

- README.md
- docs/built-in-functions.rst
- examples/wallet/wallet.vy
- tests/parser/functions/test_ecrecover.py
- vyper/builtin_functions/functions.py
Since vyper has uint8 now, ecrecover v should be using uint8.
> feat: ecrecover copy solidity interface

- setup.py
fixes: #3103
* Upgrade semantic version to 2.10
* Loosen pin to include a wider range
Was:
```python
"semantic-version==2.8.5",
```
Now:
```python
"semantic-version>=2.10,<3",
```
Test it out on 2.10
Change `semantic-version` library requirement from `==2.8.5` to `>=2.10,<3`.
🐍
> chore: loosen and upgrade semantic version

- vyper/cli/vyper_compile.py
- vyper/compiler/__init__.py
- vyper/compiler/output.py
- vyper/compiler/phases.py
- vyper/ir/compile_ir.py
Optionally disable metadata in bytecode
Added the flag `--no-bytecode-metadata` to the cli and pass the parameters in the respective components
Compile a contract with and without the flag. Bytecode produced will include or not the metadata (e.g. vyper signature) at the end
feat: optionally disable metadata in bytecode
cli: optionally disable metadata in bytecode with `--no-bytecode-metadata`
> feat: optionally disable metadata in bytecode

- docs/compiling-a-contract.rst
- vyper/cli/vyper_json.py
Fix #3110.
Add "bytecodeMetadata" as a field under "settings" in JSON files.
Compile JSON file with and without the "bytecodeMetadata" field under "settings".
```
fix: optionally disable metadata in bytecode for json input
```
Add bytecode matadata option for vyper-json.
> fix: add bytecode metadata option to vyper-json

- docs/interfaces.rst
Added a description of the different kwargs that can be passed with an external call to the `Interfaces/Declaring and using Interfaces` section of the docs.
Edited `docs/interfaces.rst`
Document optional kwargs for external calls
> Document optional kwargs for external calls

- vyper/ast/grammar.lark
The `event_body` rule in the Lark grammar uses `variable` instead of the `event_member` declared 2 lines above:
`event_body: _NEWLINE _INDENT ((variable | indexed_event_arg) _NEWLINE)+ _DEDENT` 
This causes event members to be parsed as the generic `variable`. Using `event_member` instead parses event member with their own specific type.
Update `grammar.lark`
Parsing:
```
event Event:
a: uint256
b: uint256
```
returns:
```
module
event_def
Event
event_body
event_member
a
type	uint256
event_member
b
type	uint256
```
instead of:
```
module
event_def
Event
event_body
variable
a
type	uint256
variable
b
type	uint256
```
Use event_member for event_body in Lark grammar
> Use event_member for event_body in Lark grammar

- vyper/ast/grammar.lark
Modified the lark grammar to support expressions when specifying array length on definition.
For instance trying to parse the following valid Vyper code with lark:
```a: public((uint256[4 & 4]))```
or 
```
B: constant(uint256) = 2
c: DynArray[uint256, B**2]
@external
def __init__(
initial_prices: uint256[3+B-2%1]
):
pass
```
Will currently raise an `UnexpectedToken` exception
Replaced `(DEC_NUMBER | NAME)` with `_expr` in `grammar.lark` for `array_def` and `dyn_array_def`
Parsing the following code:
```
a: public((uint256[4 & 4]))
B: constant(uint256) = 2
c: DynArray[uint256, B**2]
@external
def __init__(
initial_prices: uint256[3+B-2%1]
):
pass
```
Properly returns the following tree:
```
Tree(Token('RULE', 'module'), [Tree(Token('RULE', 'variable_def'), [Tree(Token('RULE', …
```
> Use _expr in array definitions

- vyper/ast/annotation.py
Fixed typo.
```
seperate -> separate
```
> chore: fix typo in annotation.py

- vyper/semantics/types/function.py
- vyper/semantics/types/utils.py
When specifying the `default_return_value` on a call to a void external function, the compiler currently only returns the following error message `AttributeError: 'NoneType' object has no attribute 'compare_type'`. 
I added a more explicit exception so that the error can be caught and addressed more easily.
I added a check for a return type when `default_return_value` is set. If there's no return type, an `ArgumentException` is raised.
Compiling this contract:
```
interface FooBar:
def foo(): payable
@external
def bar():
FooBar(empty(address)).foo(default_return_value=True)
```
will now generate the following error:
```
vyper.exceptions.ArgumentException: default_return_value specified but foo is void
contract "dist/simple.vy:6", function "bar", line 6:52 
5 def bar():
---> 6 …
```
> Add explicit error message when specifying default_return_value on void function call

- vyper/semantics/validation/utils.py
- vyper/utils.py
Fix #3133 
I modified `collision_str` in `validate_unique_method_ids` so that we look for the collision ID in lists of IDs instead of looking for it in lists of function signature
Trying to compile the following contract will now output the name of the functions having a collision:
```Vyper
@external
def OwnerTransferV7b711143(a : uint256) : 
pass
@external
def withdraw(a : uint256):
pass
```
fix: improve error message for conflicting methods IDs
Improve error message for conflicting methods IDs
> fix: improve error message for conflicting methods IDs

- docs/built-in-functions.rst
- tests/parser/features/test_reverting.py
- vyper/builtin_functions/functions.py
- vyper/codegen/external_call.py
- vyper/codegen/function_definitions/external_function.py
- vyper/codegen/stmt.py
- vyper/utils.py
Added `raw_revert` as a builtin function, working similarly to `raw_log` and `raw_call`
Created a new `RawRevert` class. This represents a built-in function that stores any data passed to it to memory, and then passes the right `offset` and `size` to `revert` in IR.
Run ` ./quicktest.sh tests/parser/features/test_reverting.py`
I also tested this in Foundry using VyperDeployer and verified that custom errors coming from solidity and the equivalent vyper `raw_revert` arguments created the same error data
Implement `raw_revert` built-in function
Add `raw_revert`
> Raw revert for custom errors

- setup.py
- vyper/ast/annotation.py
Loosen pin on [asttokens](https://github.com/gristlabs/asttokens) to include a wider range
Was
```json
"asttoken==2.0.5",
```
Now
```json
"asttokens>=2.0.5,<3"
```
Build and pass tests.
Loosen dependency on asttokens to >=2.0.5,<3
Resolves: #3148
Change `asttokens` library requirement from `==2.0.5` to `>=2.0.5,<3`.
My new puppy:
> chore: loosen dependency on asttokens

- docs/built-in-functions.rst
Corrected a `delete` to `deletes` in the documentation for `selfdestruct()`
Correct typo in `selfdestruct()` documentation
Correct typo in `selfdestruct()` documentation
> Fix typo in selfdestruct description

- docs/built-in-functions.rst
- tests/parser/functions/test_slice.py
Removed the caveats on not being allowed to use variables/immutables as length arguments for `slice()`
I think these applied in a previous version of Vyper, but as of at least v0.3.7 the restriction doesn't seem to apply anymore
Tests with variables for length arguments exist already in `tests/parser/functions/test_slice.py`, such as `test_basic_slice()`
A `test_slice_immutable_length_arg()` was also added to demonstrate that the functionality is available
Remove slice() length documentation caveats
Remove `slice()` length documentation caveats
> Remove slice() length documentation caveats

- vyper/ast/signatures/interface.py
Importing interfaces from ABI failed with some types such as `uint8`.
For instance, importing the following interface:
```
[
{
"constant": true,
"inputs": [],
"name": "decimals",
"outputs": [{ "name": "", "type": "uint8" }],
"payable": false,
"stateMutability": "view",
"type": "function"
}
]
```
Will cause an error: `vyper.exceptions.StructureException: Type uint8 not supported by vyper.`
Changed supported types in ast to abi conversion in `interface.py` from `("int128", "uint256", "bool", "address", "bytes32")` to `{"address", "bool"} | BYTES_M_TYPES | INTEGER_TYPES`. 
Importing the interface from the snippet above.
Add support for all base types when importing interface from ABI
> Add support for all base types when importing interface from ABI

- tests/parser/globals/test_getters.py
- vyper/ast/grammar.lark
Add dynamic tests to check public constants & immutable vars have getters as per: https://github.com/vyperlang/vyper/pull/3024#pullrequestreview-1102266104
Added test cases to `tests/parser/globals/test_getters.py`, updated lark grammar to allow for the declaration of public immutable & constants.
Run the tests
Add tests for public constant & immutable var getters
)
> Chore: Add tests to check public constants & immutable vars have getters

- tests/parser/exceptions/test_syntax_exception.py
- vyper/ast/annotation.py
it should have been disabled, but there was some code which was never removed which bypassed the check.
fix #3173 
> fix: disable uadd operator

- tox.ini
updated tox to be compatible with python 3.9, 3.10
by changing basepython from python3.8 to python3
tox breaks if user's machine does not have python 3.8
fixed by changing basepython = python3.8 to --> basepython = python3
> updated tox to be compatible with multiple python versions

- docs/built-in-functions.rst
- tests/parser/functions/test_bitwise.py
- vyper/builtins/functions.py
Fix #3159.
Update the bounds check for `shift` when folding.
See tests.
```
fix: update literal bounds for shift
```
Update literal bounds for shift
> fix: update literal bounds for shift

- setup.py
- vyper/ast/signatures/function_signature.py
- vyper/codegen/global_context.py
- vyper/codegen/ir_node.py
- vyper/compiler/phases.py
- vyper/semantics/types/base.py
- vyper/utils.py
previously we used a backport for the `cached_property` decorator; since now we only support python3.8+, we no longer need the backport.
> chore: remove cached_property backport dependency

- docs/built-in-functions.rst
Improved the documentation to reflect the fact that the intermediate results of `uint256_addmod` and `uint256_mulmod` can exceed the bounds of the type `uint256` and are not wrapped. 
Modified the documentation.
This behavior come from the fact that the two builtin functions replicates the semantics of their respective homonymous EVM opcode.
It can be verified by evaluating `unsafe_add(max_value(uint256), 3) % 10` which should evaluate to `2` and not `8` which `uint256_addmod(max_value(uint256), 3, 10)` evaluates to.
docs: improve the doc of uint256_addmod and uint256_mulmod
Updated uint256_addmod and uint256_mulmod documentation.
> docs: improve uint256_addmod and uint256_mulmod documentation

- setup.py
relax the restriction that the python version required is <3.11
related to https://github.com/vyperlang/vyper/pull/3129, but instead of explicitly supporting 3.11 (i.e., does not add it to the test matrix), just stop restricting people from using it so they can try it.
> chore: relax python version restriction

- docs/scoping-and-declarations.rst
Fixed #3139
Changed the section to reflect the latest Vyper's semantics regarding shadowing:
- It is now possible to shadow storage variable's name with calldata or memory variables.
- It is not possible to shadow constant or immutable variable with calldata or memory variables.
The compiler would fail to compile the examples in the doc as expected.
docs: fix docs of shadowing to reflect current behaviours
> doc: updated shadowing section of the doc

- docs/types.rst
Update base type for static and dynamic arrays.
Dynamic arrays support bytestrings, strings and enums, but not arrays.
Update docs.
See docs.
```
docs: update base type for arrays
```
Update base type for arrays in documentation.
> docs: update base type for arrays

- examples/tokens/ERC1155ownable.vy
The ERC-1155 event `URI` is defined like that:
```sol
event URI(string _value, uint256 indexed _id);
```
Fix the missing index in the example contract `ERC1155ownable`.
Check here: https://eips.ethereum.org/EIPS/eip-1155.
index `id` param in `URI` event of `ERC1155ownable`
Index `id` param in `URI` event of example contract `ERC1155ownable`.
> index `id` param in `URI` event of `ERC1155ownable`

- vyper/semantics/namespace.py
fix #3171: added unreachable to the list of reserved keywords so that UNREACHABLE can no longer act as a shadow variable.
fix: add unreachable to reserved keywords
Before, one could set UNREACHABLE as the name of a variable, then get surprised when calling assert or raise UNREACHABLE that it gets overshadowed by the custom semantic of UNREACHABLE, which reverts to the opcode INVALID. Now if you try to set UNREACHABLE as a variable you get a syntax exception that unreachable is a reserved keyword.
> fix: add unreachable to reserved keywords

- docs/interfaces.rst
Fixes https://github.com/vyperlang/vyper/issues/3204.
Add note on return value bounds in interfaces and the corresponding behavior in the implementation.
`docs: add a note on return value bounds in interfaces`
docs: add a note on return value bounds in interfaces
> docs: add note on return value bounds in interfaces

- vyper/codegen/function_definitions/external_function.py
the IR generated inside of a function (that is not generated in stmt.py or expr.py) was not annotated with the source pos. this annotates the root node of the function with the source pos as the fallback.
fix #3200
> fix: missing pc map for empty functions

- tests/parser/features/iteration/test_for_in_list.py
- vyper/semantics/analysis/local.py
Fix #3144.
Check for an empty `elements` list if `iter` is a `List` node.
See tests.
```
fix: guard against iterating over empty list in for loop
```
Guard against iterating over empty list in for loop
> fix: guard against iterating over empty list in for loop

- vyper/builtins/interfaces/ERC721.py
As title.
Added the missing `ERC165` function `supportsInterface` to built-in `ERC721` interface.
https://eips.ethereum.org/EIPS/eip-721#specification.
> Every ERC-721 compliant contract must implement the ERC721 and ERC165 interfaces (subject to “caveats” below):
Add missing `ERC165` function `supportsInterface` to built-in `ERC721` interface
Add missing `ERC165` function `supportsInterface` to built-in `ERC721` interface
> Add missing `ERC165` function `supportsInterface` to built-in `ERC721` interface

- tests/parser/syntax/test_bool.py
- tests/parser/types/numbers/test_decimals.py
- tests/parser/types/numbers/test_signed_ints.py
- tests/parser/types/numbers/test_unsigned_ints.py
- vyper/semantics/types/primitives.py
Fix #3217 
Added `vy_ast.Not` to `IntegerT` and `DecimalT`'s  `_invalid_ops`
See tests.
fix: block boolean not operator on numeric types
Block boolean not operator on numeric types
> fix: block boolean not operator on numeric types

- tests/ast/nodes/test_replace_in_tree.py
Fixed typo.
```
seperately -> separately
```
> test: fix typo in test_replace_in_tree.py

- tests/parser/syntax/test_for_range.py
- vyper/semantics/analysis/local.py
Fixed #3241 
Added a check to raise an exception if the iterator of a loop is not a `Name`.
See test
fix: enforce that loop's iterators are valid names
Enforce that loop's iterators are valid names
> fix: enforce that loop's iterators are valid names

- tests/parser/syntax/test_enum.py
- vyper/semantics/types/user.py
- Fixed #3239
- Added the node of the enum declaration to the exception raised when it is empty to indicate its location.
Added checks that the fields of an `enum` must be `Expr` statements with values that are `Name`
See tests
fix: prevent enum members to have unexpected structures
Enforce enum members to be simple names
> fix: prevent enum members to have unexpected structures

- tests/parser/syntax/test_enum.py
- vyper/ast/folding.py
Fix #3233.
Do not replace a `Name` node during folding of user-defined constants if it has an `EnumDef` node as its parent.
See test.
```
fix: skip enum members in folding of user-defined constants
```
Skip enum members in in folding of user-defined constants
> fix: skip enum members in folding of user-defined constants

- tests/builtins/folding/test_bitwise.py
- vyper/ast/nodes.py
Fix #3218. 
Reuse `(2 ** 256 - 1) - value` from `BitwiseNot` instead of `operator.inv`, which can return a negative number.
See updated tests.
```
fix: folding of bitwise not literals
```
Fix folding of bitwise not literals.
> fix: folding of bitwise not literals

- tests/parser/syntax/test_enum.py
- vyper/semantics/types/user.py
Fix #3262 
Set `EnumT._helper._id` to the same name as the `EnumT`.
See test.
```
chore: improve error message for undeclared enum member
```
Improve error message for undeclared enum member
> chore: improve error message for undeclared enum member

- tests/parser/features/test_address_balance.py
- vyper/semantics/analysis/annotation.py
Fix #3258.
Remove `visit_Hex`, which was overriding `visit_Constant`. This caused the propagated type to be ignored and overriden with the `None` value.
On an unrelated but similar reasoning, I also removed `visit_Int` and `visit_Bytes`.
See tests.
```
fix: allow accessing members of constant address
```
Allow accessing members of constant address
> fix: allow accessing members of constant address

- tests/parser/syntax/test_interfaces.py
- vyper/semantics/types/user.py
Fix #3248.
Check if decorator list is empty for `FunctionDef` node in an interface.
See test
```
fix: guard against decorators in interface
```
Guard against decorators in interface
> fix: guard against decorators in interface

- tests/parser/exceptions/test_constancy_exception.py
- tests/parser/types/test_dynamic_array.py
- vyper/semantics/analysis/utils.py
Fix #3225 
Add a branch to `get_expr_info` for `Subscript` nodes, and propagate the info from `Subscript.value`.
See tests.
```
fix: guard against writing to calldata array
```
Guard against writing to calldata array
> fix: guard against writing to calldata array

- docs/resources.rst
- docs/toctree.rst
I created a new documentation page that contains links to the useful Vyper resources outside the official Vyper repos.
I mostly used the content from Vyper section that I have maintained at ethereum.org now and then.
See that Sphinx docs get the new page built:
Creating initial additional resources page
Creating initial additional resources page
```
*##X        
*###*       
####X       
*#                           ####X#       
X#X                          #X##X#       
X           *##                          ###X#X       
X#     *XX*  *##X                         X####        
##*  *######XX# #                         *##X         
#X###X      X  ##          ***####         ##*         
#X  XX      *###X        #####X  X#       *#X*         
##X#*       *  ##*     *#   X    X# …
```
> Creating initial additional resources page

- tests/builtins/folding/test_fold_as_wei_value.py
- tests/builtins/folding/test_min_max.py
- vyper/builtins/functions.py
Fix #3282 
- Changed `>= 2 ** 127` by ` > SizeLimits.MAX_AST_DECIMAL`
- Changed `< -(2 ** 127)` by ` < SizeLimits.MIN_AST_DECIMAL`
See the modified tests that should have failed (depending on the generation of the input by the fuzzer) with the old code.
fix: range check for decimal values in evaluation of builtin functions
Fix the range check for decimal values in evaluation of builtin functions
> fix: range check for decimal values in evaluation of builtin functions

- vyper/builtins/_utils.py
Fix #3286 
Removed the redundant semantic check of the body of `sqrt` builtin
See that the removed check is performed just before as part of the initialisation of the `FunctionNodeVisitor`.
chore: remove redundant semantic check of sqrt body
Remove redundant semantic check of sqrt body
> chore: remove redundant semantic check of sqrt body

- docs/built-in-functions.rst
- tests/parser/functions/test_length.py
- vyper/codegen/core.py
Fix #3275.
Also adds `DynArray` to `len()` in docs for builtins.
Add `~empty` case.
See tests
```
fix: length of empty byte arrays and dynamic arrays
```
Fix length of empty byte arrays and dynamic arrays
> fix: length of empty byte arrays and dynamic arrays

- vyper/builtins/interfaces/ERC4626.py
I added the `asset` function to `ERC4626` built-in interface. I also used the official parameter names from the [EIP-4626](https://eips.ethereum.org/EIPS/eip-4626) event definitions, and also quickly reordered the function sequence according to the official EIP sequence.
Brain and eyes.
You can review the interface here: https://eips.ethereum.org/EIPS/eip-4626.
`fix: add missing asset function to ERC4626 built-in interface`
Add missing `asset` function to `ERC4626` built-in interface.
> fix: add missing `asset` function to `ERC4626` built-in interface

- docs/built-in-functions.rst
Fixed the displaying of the doc after I messed it up in #3146
chore: fix uint256_addmod doc
Fix uint256_addmod doc
> chore: fix uint256_addmod doc

- tests/parser/syntax/test_interfaces.py
- vyper/ast/nodes.py
- vyper/semantics/analysis/module.py
Fix #3297, fix #3298.
For 3297, change the exception from `UnexpectedNodeType` to `StructureException`.
For 3298, as suggested in issue.
See tests
```
chore: improve exceptions for `implements` syntax
```
Improve exceptions for `implements` syntax
> chore: improve exceptions for `implements` syntax

- docs/built-in-functions.rst
- tests/parser/functions/test_empty.py
- vyper/builtins/functions.py
Fix #3301.
Check for `HashMapT` in the `empty` builtin.
See test.
```
fix: block `empty` for mappings
```
Block `empty` builtin for mappings.
> fix: block `empty` for mappings

- tests/parser/syntax/test_structs.py
- vyper/semantics/analysis/local.py
Unassigned structs currently run into an error while raising an exception:
```
struct Foo:
a: uint256
@external
def foo():
Foo({a: 1})
```
```
AttributeError: 'TYPE_T' object has no attribute '_id'
```
This is due to `TYPE_T` not having an `_id` attribute: https://github.com/vyperlang/vyper/blob/8ebabc5ce277942ee470845e2d04df5f8a2e6ad6/vyper/semantics/analysis/local.py#L512-L520
Even if we remove `._id`, the error message is still not precise because it is a struct creation and not a function call:
```
vyper.exceptions.StructureException: Function 'type(Foo declaration object)' cannot be called without assigning the result
contract "contracts/struct_assign.vy:8", function "foo", line 8:4 
7 def foo():
---> 8     Foo({a: 1})
-----------^
9
```
Added a new branch to catch unassigned …
> chore: improve error message for unassigned structs

- vyper/semantics/analysis/utils.py
Remove a redundant sanity check. It always passes because `t` was assigned with the same operation just three lines above and has not been mutated.
```
chore: remove redundant sanity check
```
Remove redundant sanity check
> chore: remove redundant sanity check

- vyper/semantics/analysis/module.py
Set the `DataLocation` of constants to `UNSET` instead of `STORAGE`
Add a branch for constants
Tests pass.
```
chore: fix data location of constant declarations
```
Fix data location of constant declarations
> chore: fix data location of constants

- tests/parser/functions/test_ceil.py
Fixed typo.
```
yeild -> yield
```
> chore: fix typo in test_ceil.py

- vyper/cli/vyper_serve.py
Fix #3075.
Cast `ir_runtime` to `str`.
1. Run `vyper-serve` in a console.
2. Run `curl -X POST localhost:8000/compile -H "Content-Type: application/json" -d '{"code": "\n\n# @version ^0.3.7\n\n@external\ndef foo():\n    pass\n"}'` in another console. The compiled code should be printed in console.
```
chore: serialize ir_runtime output for vyper-serve
```
Serialize ir_runtime output for vyper-serve
> chore: serialize ir_runtime output for vyper-serve

- tests/parser/syntax/test_address_code.py
- tests/parser/syntax/test_msg_data.py
- vyper/semantics/analysis/local.py
Check usage of `address.code` and `msg.data` in `AugAssign` nodes.
This contract throws during IR generation but it should fail at typechecking:
```
a: HashMap[Bytes[10], uint256]
@external
def foo(a: uint256):
self.a[msg.data] += 1
```
Visit the `target` attribute of `AugAssign` nodes in `_LocalExpressionVisitor`
See new tests
```
fix: check usage of `address.code` and `msg.data` in `AugAssign` nodes
```
Check usage of `address.code` and `msg.data` in `AugAssign` nodes
> fix: check usage of `address.code` and `msg.data` in `AugAssign` nodes

- vyper/semantics/types/user.py
Removed dead code in `_get_module_definitions`. Since Vyper does not allow overloaded functions, this is never reachable. 
Q: Was this meant for interfaces? Even the error message refers to interface.
Select and delete.
Tests still pass.
```
chore: remove dead code in `_get_module_definitions`
```
Remove dead code in `_get_module_definitions`
> chore: remove dead code in `_get_module_definitions`

- vyper/semantics/types/function.py
Remove check for `Call` node in the return type of a function. No existing type is a `Call` node.
Delete code.
Existing tests pass
```
chore: remove redundant check for call node in function return type
```
Remove redundant check for call node in function return type
> chore: remove redundant check for call node in function return type

- tests/parser/syntax/test_tuple_assign.py
- vyper/semantics/analysis/utils.py
The following contract that tries to re-assign values to immutable variables in a tuple fails at IR generation when it should fail at typechecking:
```
A: immutable(uint256)
B: immutable(uint256)
@external
def __init__(a: uint256, b: uint256):
A = a
B = b
@internal
def foo() -> (uint256, uint256):
return (1, 2)
@external
def bar():
A, B = self.foo()
```
Propagate the `is_immutable` attribute of a tuple's members to the tuple's `ExprInfo`.
See new test.
```
fix: propagate tuple members' immutability to tuple's expression
```
Propagate tuple members' immutability to tuple's expression
> fix: propagate tuple members' immutability to tuple's expression

- tests/parser/syntax/test_interfaces.py
- vyper/semantics/analysis/module.py
Fix #3329.
Getters for public constants and immutables were not added to the `self` namespace, causing validation of implementing an interface to fail.
Add the getters to namespace
See tests
```
fix: add getters for public constants and immutables to `self` namespace
```
Add getters for public constants and immutables to `self` namespace
> fix: add getters for public constants and immutables to `self` namespace

- tests/parser/syntax/test_unbalanced_return.py
- vyper/builtins/functions.py
- vyper/codegen/core.py
Set `raw_revert` terminus as a terminal statement, similar to `selfdestruct`.
For example, this contract should not compile because the last statement can never be reached.
```
@external
def foo(a: Bytes[100]) -> uint256:
raw_revert(a)
b: uint256 = 76
```
For `RawRevert`, set `_is_terminus = True` and `_return_type = None`.
See new tests.
```
chore: set `raw_revert` builtin as terminus
```
Set `raw_revert` builtin as terminus.
> chore: set `raw_revert` terminus as terminus

- vyper/codegen/arithmetic.py
for some reason, safediv and safemul were switched
> fix: error messages on some safemath operations

- tests/parser/exceptions/test_syntax_exception.py
- vyper/ast/nodes.py
`posonlyargs` are allowed in Python but not in Vyper. This contract compiles when it should not:
```
@internal
def f(a:uint256,/):
return
@external
def g():
self.f()
```
Require `posonlyargs` to be empty.
See new test.
```
fix: guard against `posonlyargs` in function arguments
`posonlyargs` are allowed in Python but not in Vyper.
```
Guard against `posonlyargs` in function arguments
> fix: guard against `posonlyargs` in function arguments

- vyper/semantics/analysis/utils.py
A literal list cannot be a `Tuple` node. Therefore, it is incorrect for the branch in `validate_expected_type` that is handling literal lists to include `Tuple` nodes.
Delete
Tests still pass
```
fix: remove tuple node check in `validate_expected_type` for literal list
A literal list cannot be a `Tuple` node. Therefore, it is incorrect for the 
branch in `validate_expected_type` that is handling literal lists to include 
`Tuple` nodes.
```
Remove tuple node check in `validate_expected_type` for literal list
> fix: remove tuple node check in `validate_expected_type` for literal list

- docs/built-in-functions.rst
- vyper/cli/vyper_compile.py
the `blueprint_bytecode` output format was undocumented, document it
> docs: document `blueprint_bytecode` output format

- docs/built-in-functions.rst
As title. I also added a note on the default value of `max_outsize`.
N/A.
`max_outsize` cannot be negative.
`Fix max_outsize type in raw_call docs`
Fix `max_outsize` type in `raw_call` docs.
> Fix `max_outsize` type in `raw_call` docs

- tests/parser/functions/test_interfaces.py
- vyper/codegen/expr.py
code like <MyInterface>.address would result being tagged with the wrong type during codegen - InterfaceT instead of AddressT.
this was a regression introduced in 3abe588e0, and for some reason there were no existing tests for <MyInterface>.address codegen. this fixes the type tagging during codegen and adds a test to prevent this regression in the future.
> fix: code generation for `<MyInterface>.address`

- docs/built-in-functions.rst
- vyper/builtins/functions.py
Fixes #3277.
Add the following warning if `selfdestruct` is used:
```bash
`selfdestruct` is deprecated! The opcode is no longer recommended for use.
```
I also updated the docs.
Run the following function:
```vyper
@external
def foo():
selfdestruct(msg.sender)
```
```bash
Warning: `selfdestruct` is deprecated! The opcode is no longer recommended for use.
0x61003961000f6000396100396000f360003560e01c346100285763c2985578811861002157600436106100285733ff005b5060006000fd5b600080fda1657679706572830001000a
```
`Add deprecation warning for selfdestruct usage`
Add deprecation warning for `selfdestruct` usage.
> Add deprecation warning for `selfdestruct` usage

- tests/builtins/folding/test_bitwise.py
for cases where `a << b` is an int256 between `max_value(int256)` and `max_value(uint256)`, the typechecker will fail with TypeMismatch instead of OverflowException. this fixes the test to catch the case. note that the code was correctly failing to compile, just the test was not catching both exception types.
(this test case was found in https://github.com/vyperlang/vyper/actions/runs/4886254516/jobs/8721370863?pr=3370):
```
E           vyper.exceptions.InvalidType: <unprintable InvalidType object>
vyper/semantics/analysis/utils.py:578: InvalidType
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_bitwise_shift_signed(
get_contract=<function tests.base_conftest.get_contract.<locals>.get_contract>,
a=16,
b=251,
op='<<',
)
```
Commit …
> chore: fix fuzzer test case

- tests/parser/test_call_graph_stability.py
- vyper/semantics/types/function.py
- vyper/utils.py
the use of `set` (which does not guarantee order of its elements) instead of `dict` (which guarantees insertion order) led to instability across runs of the compiler between different versions of python. this commit patches the problem by using a derivation of `dict` to track the call graph instead of `set`.
fix #3369 
> fix: call graph stability

- tests/parser/features/test_string_map_keys.py
- vyper/builtins/functions.py
- vyper/codegen/events.py
- vyper/codegen/expr.py
- vyper/codegen/keccak256_helper.py
fix #3291 
see test
```
fix: codegen for hashmaps with `String[...]` keys.
```
> fix: codegen for hashmaps with string keys

- docs/interfaces.rst
> docs: clarify that skip_contract_check=True can result in undefined behavior

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- Dockerfile
per title. builds are also with python 3.11 now too. two reasons:
1. faster
2. universal2 images for darwin are only available on >=3.11, see https://github.com/actions/setup-python/issues/439#issuecomment-1247646682
> chore: update published build to python 3.11

- tests/parser/functions/test_convert.py
- vyper/builtins/_convert.py
Conversion of string to bool should follow that of `BytesT` to compare non-zero bytes, but it currently compares pointer instead.
Add `StringT` to condition
See tests
```
fix: string to bool conversion
```
Fix string to bool conversion
> fix: string to bool conversion

- tests/base_conftest.py
- vyper/compiler/output.py
`-f metadata` output was not working for some functions. this fixes the issue and also checks that `metadata` output is successfully produced in the `get_contract` fixture to avoid this in the future.
> fix: metadata output

- .github/workflows/era-tester.yml
- .github/workflows/integrators.yml
Add integrator CI to check for regressions.
```
chore: add era compiler test suite to CI
this commit adds the era compiler test suite to the CI, as they have
good test cases and coverage of our compiler through IR codegen.
this is intended as a diagnostic tool to help catch compiler regressions
and notify us when a change breaks downstream. as explained in the
comments in the workflow file, it is not intended as a CI blocker since
an update in our code could break downstream, and we do not want to wait
on downstream as a blocker.
```
Add integrators CI to check for regressions.
> chore: add integrator test CI

- tests/parser/syntax/test_list.py
- vyper/semantics/analysis/utils.py
This contract should compile but throws:
```
@external
def foo():
for i in [[], []]:
pass
```
```
TypeError: _BytestringT.compare_type() missing 1 required positional argument: 'other'
```
The issue is that the possible types for an empty list include class objects (e.g. `BytesT`, `StringT`) in `types_from_List`. This causes `get_common_types` to throw the above error when we perform `self.value_type.compare_type(other.value_type)` in `DArrayT.compare_type()`.
```
fix: allow iteration of list of empty lists
```
Allow iteration of list of empty lists.
> fix: type inference for empty lists

- tests/base_conftest.py
- tests/parser/types/test_lists.py
- vyper/codegen/expr.py
- vyper/exceptions.py
- vyper/semantics/analysis/annotation.py
codes like the following would panic during codegen:
```vyper
@external
def foo() -> uint256:
arr: uint256[9] = empty(uint256[9])
i: uint8 = 3
return arr[i + 1]  # <-- panics with uint8 != uint256
```
```
the index type was being incorrectly annotated in the frontend in the
case where the index type was not uint256. this would lead to a panic
during codegen. an example which would lead to this bug is:
\```vyper
@external
def foo(xs: uint256[5], ix: uint8):
return xs[ix + 1]  # <-- panics with uint8 != uint256
\```
this commit also improves the `VyperInternalException` class so it can
include a node for prettier traceback
```
> fix: type annotation of Subscript nodes

- tests/parser/syntax/test_constants.py
- vyper/semantics/analysis/module.py
The first contract compiles, but the second raises a namespace collision. The behaviour should be consistent, similar to immutables where both would fail compilation.
```
a: constant(uint256) = 1
a: uint256
```
```
a: uint256
a: constant(uint256) = 1
```
Check constants with `self` namespace.
See new tests.
```
fix: enforce namespace collisions between globals
collisions between constants, immutables and storage variables were
dependent on declaration order; this commit fixes that.
```
Prevent namespace collision for constants regardless of order
> fix: enforce namespace collisions between globals

- vyper/semantics/analysis/utils.py
As per #3214, trying to reference a yet undeclared constant variable in the type annotation of another variable's declaration results in a fairly unhelpful error message: `vyper.exceptions.UndeclaredDefinition: 'self' has not been declared. `
This fix ensures that a more detailed exception is raised.
The exception is raised when trying to check whether the variable is a storage variable by checking if its name is in `self.namespace["self"].typ.members`. 
However this check can happen before `self` is added to the namespace. When the constant variable is referenced in a type annotation, the check will happen during folding and before validation, so there will be no `self` key in namespace, leading to the previous exception being raised.
A simple check on whether the key is present suffices …
> Raise clearer exception when using a yet undeclared variable in a type annotation

- tests/parser/features/test_assignment.py
- vyper/codegen/context.py
- vyper/codegen/expr.py
- vyper/codegen/ir_node.py
- vyper/codegen/stmt.py
- vyper/semantics/analysis/base.py
fix #2418 
check that rhs and lhs do not overlap in parse_Assign. if they do, copy rhs to a temporary buffer, then copy to the lhs. this might not be the most efficient approach, but it is safe (and it's a relatively rare case to see in user code).
note that this doesn't touch `make_setter` directly because it would need access to the memory allocator (to allocate the temporary buffer). this would result in the fix not working in other cases where the arguments to `make_setter` overlap. i don't think there are any cases of those, but if there were, they would need to be fixed on a case by case basis.
test cases fail on master (97ff017c5e8d1aa5b0bc) but pass on this branch.
Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit …
> fix: assignment when rhs is complex type and references lhs

- tests/compiler/asm/test_asm_optimizer.py
- tests/functional/semantics/analysis/test_for_loop.py
- tests/parser/features/test_comparison.py
- tests/parser/features/test_immutable.py
- tests/parser/features/test_init.py
- vyper/codegen/context.py
- vyper/codegen/expr.py
- vyper/codegen/function_definitions/common.py
- vyper/codegen/module.py
fix #3206, fix #3292 
add constructor context to codegen, skip cleverness with `called_functions`
```
this commit fixes two related issues with initcode generation:
- nested internal functions called from the constructor would cause a
compiler panic
- internal functions called from the constructor would not read/write
from the correct immutables space
the relevant examples reproducing each issue are in the tests. this
commit fixes the issue by
- not trying to traverse the call graph to figure out which internal
functions to include in the initcode. instead, all internal functions
are included, and we rely on the dead code eliminator to remove unused
functions
- adding a "constructor" flag to the codegen, so we can distinguish
between internal calls which are being generated to include in …
```
> fix: constructor context for internal functions

- tests/functional/semantics/analysis/test_cyclic_function_calls.py
- vyper/semantics/analysis/module.py
A function that calls itself is already caught in `_find_cyclic_call`. This PR removes a duplicate check.
Delete code.
See added test.
```
chore: remove duplicate check for a function call into itself
```
Remove duplicate check for a function call into itself
> chore: remove duplicate check for a function call into itself

- tests/parser/syntax/test_enum.py
- tests/parser/syntax/test_interfaces.py
- vyper/semantics/types/user.py
typechecking for user-defined types was busted as of 046ea166. fix the typechecker rules and add a test
> fix: typechecking for user-defined types

- .github/workflows/era-tester.yml
in the era compiler tester workflow, we were always saving the cache, which wastes time if we had a cache hit (and could also lead to some strange race conditions)
> chore: only save cache on cache miss

- tests/compiler/asm/test_asm_optimizer.py
- tests/parser/test_call_graph_stability.py
- vyper/codegen/function_definitions/common.py
- vyper/codegen/function_definitions/internal_function.py
- vyper/codegen/self_call.py
for backends which only have a single compilation context (i.e., they do not split initcode and runtime code like EVM), they need separate names for the two different codes generated per-function as of https://github.com/vyperlang/vyper/commit/c202c4e3ec884c6ddb28f738e45e8b9aa3d209b4. this is also hygienic - since the two functions actually have different codes as of c202c4e3ec88, give them different names.
```
for backends (like zksync) which only have a single compilation context
(i.e., they do not split initcode and runtime code like EVM), they need
separate names for the two different codes generated per-function as of
c202c4e3ec8. this is also hygienic - since the two functions actually
have different codes as of c202c4e3ec8, give them different names.
```
> fix: generate separate function names depending on context

- vyper/evm/opcodes.py
per 1ac8362df0c, the DEFAULT_EVM_VERSION is updated to shanghai. however, entry points into the compiler which don't use the `@evm_wrapper` wrapper might continue using paris. this commit fixes the issue by calculating `active_evm_version` from `DEFAULT_EVM_VERSION` so that only one value needs to be updated going forward.
```
per 1ac8362df0c, the `DEFAULT_EVM_VERSION` is updated to shanghai, while
`active_evm_version` still points to paris. so entry points into the
compiler which don't use the @evm_wrapper wrapper might continue using
paris. this commit fixes the issue by calculating active_evm_version
from `DEFAULT_EVM_VERSION` so that only one value needs to be updated
going forward.
```
> fix: calculate `active_evm_version` from `DEFAULT_EVM_VERSION`

- .github/workflows/build.yml
- .github/workflows/era-tester.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
installing dependencies takes about 1min per job. pip caching should speed it up. note that in theory, this caches "correctly" in that it doesn't cache the dependency graph or install directories, just the wheels. so if upstream packages are updated, they should get reinstalled.
> chore: cache pip in setup-python

- vyper/codegen/function_definitions/__init__.py
- vyper/codegen/function_definitions/common.py
- vyper/codegen/module.py
this moves generation of func_t._ir_info to be closer to where it is used (and where FuncIRInfo is defined!). since FuncIRInfo is no longer imported anywhere, it can be changed to a private member of the function_definitions/common.py module.
> chore: make FuncIRInfo generation private

- .github/workflows/deploy-docker.yml
- .github/workflows/ghcr.yml
publish and tag docker images continuously to ghcr.io. i wanted to add custom tagging (so we can retain every commit) in docker hub, but i didn't really like the fact that for docker hub, in order to have custom tags, you need to set up a regular user and log in via that user. the authentication is much cleaner in github actions for ghcr.
(note docker hub pulls are still staying the same, this is just an alternative form of retention going forward).
can preview test builds here: https://github.com/charles-cooper/vyper/pkgs/container/vyper
> ci: deploy to ghcr on push

- .github/workflows/ghcr.yml
use `latest` for latest release, `dev` for continuous, and tag dev builds with `-dev`. also remove the 'master' tag since that's redundant with `dev`.
see example packages on https://github.com/charles-cooper/vyper/pkgs/container/vyper/ -
a "dev" build:
a release build:
> chore: fix up ghcr tags

- .github/workflows/build.yml
python3.11 uses a new libc which is not compatible with ubuntu 20.04.
> chore: build for old ubuntus

- tests/compiler/asm/test_asm_optimizer.py
- tests/parser/functions/test_create_functions.py
- vyper/codegen/module.py
- vyper/ir/compile_ir.py
```
this commit fixes a regression in c202c4e3ec8. the commit message states
that we rely on the dead code eliminator to prune unused internal
functions in the initcode, but the dead code eliminator does not prune
dead code in all cases, including nested internal functions and loops.
this commit reintroduces the reachability analysis in
`vyper/codegen/module.py` as a stopgap until the dead code eliminator is
more robust.
```
> fix: initcode blowup

- vyper/cli/vyper_json.py
source_map_full output fails with a KeyError when user requests evm.sourceMapFull but not evm.sourceMap. this commit fixes
> fix: source_map_full output in vyper-json

- vyper/codegen/function_definitions/external_function.py
- vyper/codegen/module.py
prevent a performance regression for sending eth to contracts with a payable default function by (mostly) reverting the changes introduced in #3408 and #3104.
```
prevent a performance regression for sending eth to contracts with a
payable default function by (mostly) reverting the changes introduced in
9ecb97b4b6f and 02339dfda0. the `skip_nonpayable_check=False` for the
default function is introduced to address GHSA-vxmm-cwh2-q762 (which
02339dfda0 inadvertently fixed, and a test for which was added in
903727006c).
```
> fix: add back global calldatasize check

- docs/release-notes.rst
I added a snake name (Common Adder) the release notes for Vyper 0.3.9
Updated release notes
Check the diff
Added snake name to release
Added snake name for Vyper release, starting with Common Adder, which is first on the [Wikipedia snake name list](https://en.wikipedia.org/wiki/List_of_snakes_by_common_name), so that future releases can move down the list successively (or in the preference of the maintainers)
> Add snake name to the release

- .github/workflows/build.yml
- .github/workflows/era-tester.yml
- .github/workflows/ghcr.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
as title. also removed the ghcr build on `tag` events (since it's redundant with the `release` and we end up with orphaned images, since two images get tagged with ex. v0.3.9)
tested a release at https://github.com/charles-cooper/vyper/releases/tag/TEST_RELEASE (example ci run at https://github.com/charles-cooper/vyper/actions/runs/5117099747/jobs/9199915521)
> ci: auto-upload release assets on release event

- tests/parser/syntax/test_ternary.py
- vyper/semantics/analysis/annotation.py
Fixed incorrect variable reference. However, I haven't been able to find an example that triggers this bug.
Tests still pass
```
fix: wrong variable in type annotation of `IfExp`
```
> fix: wrong variable in type annotation of `IfExp`

- vyper/codegen/module.py
remove an unneeded declared var
```
it was apparently there as a type hint but it is no longer needed
```
> chore: rm redundant var declaration

- tests/parser/features/test_assignment.py
- vyper/codegen/function_definitions/internal_function.py
- vyper/semantics/analysis/local.py
Fix #3449.
Update attributes in `VarInfo` and `VariableRecord`.
See tests.
```
feat: let params of internal functions be mutable
This PR sets the data location of internal functions' params to
memory. Additionally, they are now mutable unlike an external
function's params.
```
Let params of internal functions be mutable.
> feat: let params of internal functions be mutable

- .github/workflows/build.yml
mac users were reporting bugs like:
```
OSError: Cannot load native module 'Crypto.Hash._keccak': Not found '_keccak.cpython-311-darwin.so', Cannot load '_keccak.abi3.so': Failed to load dynlib/dll '/<some directory>/Crypto/Util/../Hash/_keccak.abi3.so'. Most likely this dynlib/dll was not found when the application was frozen., Not found '_keccak.so'
```
rebuild pycryptodome during packaging
build verified by @hedgar2017
> fix: pycryptodome on arm

- vyper/codegen/ir_node.py
- vyper/codegen/return_.py
- vyper/codegen/self_call.py
- vyper/ir/compile_ir.py
fix some issues with well-formedness of generated IR (which were getting hidden by the `rewrite_return_sequences` routine). this shouldn't affect correctness of current vyper programs, but may help programs which consume vyper IR directly.
> chore: polish some codegen issues

- vyper/compiler/output.py
- vyper/compiler/phases.py
- vyper/ir/compile_ir.py
it's going at the end of initcode instead, which is cheaper but still possible to pick up the vyper version by looking at the create tx.
> chore: remove vyper signature from runtime

- tests/parser/syntax/test_addmulmod.py
- vyper/builtins/functions.py
Fix #3486
The `eval` functions of the builtins having integer arguments now expect `Int` instead of `Num`.
The following contract now fails to compile with `InvalidType` instead of a `CompilerPanic`.
```Vyper
@external
def foo():
ds:uint256 = uint256_addmod(1.1,2.2,2)
```
fix: typechecking of folded builtins.
Prevent decimals from being passed as parameters to builtins expecting integers.
> fix: typechecking of folded builtins

- vyper/ast/validation.py
Fixed the displaying of ``ArgumentException``
The change is pretty self-explanatory.
```Vyper
@internal
@view
def bar():
pass
@external
def foo():
self.bar(12)
```
Was failing to compile with:
``vyper.exceptions.ArgumentException: Invalid argument count for call to 'bar': expected 0 to 0, got 1``
And now fail to compile with:
``vyper.exceptions.ArgumentException: Invalid argument count for call to 'bar': expected 0, got 1``
fix: displaying of ArgumentException
fix displaying of ArgumentException
> fix: displaying of ``ArgumentException``

- tests/parser/functions/test_slice.py
- vyper/codegen/core.py
include the length word in the batch copy instead of issuing a separate store instruction.
brings CurveStableSwapMetaNG.vy down by 315 bytes (~1.5%) and VaultV3.vy by 45 bytes (0.25%) in both `--optimize codesize` and `--optimize gas` modes.
```
include the length word in the batch copy instead of issuing a separate
store instruction.
brings CurveStableSwapMetaNG.vy down by 315 bytes (~1.5%) and VaultV3.vy
by 45 bytes (0.25%) in both `--optimize codesize` and `--optimize gas`
modes.
```
> feat: optimize dynarray and bytearray copies

- setup.py
fixes: #3509 
fix how packages are found
exclude kwarg was not working as expected i dont think, that seems to be for file globs within the found packages
uninstall
reininstall in editable mode
go somewhere else (cd)
```sh
python -c "import tests; print(tests.__path__)"
```
^ should not output anything about vyper
> fix: issue with finding installed packages in editable mode

- vyper/ast/pre_parser.py
allow `# pragma ...` in addition to `#pragma ...`
also fix a small bug in version parsing (it only affected the error message formatting, not the parsed version)
> chore: relax pragma parsing

- tests/parser/exceptions/test_invalid_reference.py
- vyper/semantics/analysis/utils.py
Fix #3518 
Move the statement catching the exception from the `except` branch to the `try` branch.
See tests.
```
chore: improve error message for invalid references to public constants and immutables
```
Improve error message for invalid references to public constants and immutables
> chore: improve error message for invalid references to public constants and immutables

- vyper/ir/optimizer.py
```
merge_dload was defined in 5dc3ac7, but was not applied.
this commit also adds a rewrite rule for single dload/mstore patterns,
any `(mstore dst (dload src))` (which compiles to a `codecopy` followed
by an `mload` and `mstore`) is rewritten to a `dloadbytes` (which
compiles directly to a `codecopy`).
this rule saves 4 bytes / ~10 gas per rewrite. for instance, it shaves
25 bytes off `VaultV3.vy`, 50 bytes off `CurveTricryptoOptimizedWETH.vy`
and 75 bytes off `CurveStableSwapMetaNG.vy` (basically 0.1%-0.3%).
```
> feat: optimize dload/mstore sequences

- tests/functional/semantics/analysis/test_for_loop.py
- tests/parser/features/iteration/test_for_range.py
- vyper/codegen/stmt.py
- vyper/ir/compile_ir.py
- vyper/semantics/analysis/annotation.py
- vyper/semantics/analysis/local.py
implements https://github.com/vyperlang/vyper/issues/2527. 
> implement bound= in ranges

- tests/parser/globals/test_getters.py
- vyper/ast/expansion.py
- vyper/ast/nodes.py
- vyper/compiler/phases.py
- vyper/semantics/analysis/__init__.py
fix https://github.com/vyperlang/vyper/issues/3535
move ast expansion to before local validation
```
public getters for arrays would panic at codegen because type
information for the array members was not available. this is because
type annotation would occur before getter expansion. this commit moves
the type annotation phase to right before getter expansion, so that the
generated ast nodes will get annotated.
it also fixes a small bug when trying to deepcopy the nodes generated by
ast expansion - the generated nodes have no node_id and raise an
exception when deepcopy tries to perform `__eq__` between two of the
generated FunctionDefs.
```
> fix: public constant arrays

- docs/release-notes.rst
Fixed typo.
unitialized -> uninitialized
> docs: fix typo in release-notes.rst

- vyper/codegen/stmt.py
since https://github.com/vyperlang/vyper/commit/d48438e10722db8fc9e74d8ed434745e3b0d31cf, loops can revert depending on user input. add it to the error map so it's easier to debug.
edit -- actually, since 3de1415ee77a9244eb04bdb695e249d3ec9ed868
> add message to error map for repeat range check

- docs/release-notes.rst
As title.
```
Add note on security advisory in release notes for versions `0.2.15`, `0.2.16`, and `0.3.0`
```
Add note on security advisory in release notes for versions `0.2.15`, `0.2.16`, and `0.3.0`.
> docs: note on security advisory in release notes for versions `0.2.15`, `0.2.16`, and `0.3.0`

- docs/built-in-functions.rst
I added a note on the recent security advisory for `ecrecover` in the docs. I also replaced `0` with `empty(address)` in case of error.
Added a `note` section in the `ecrecover` docs.
Reference: https://github.com/vyperlang/vyper/security/advisories/GHSA-f5x6-7qgp-jhf3
```
Add note on security advisory for `ecrecover` in docs
```
Add note on security advisory for `ecrecover` in docs.
> Add note on security advisory for `ecrecover` in docs

- tests/parser/syntax/test_for_range.py
- vyper/semantics/analysis/local.py
Fix #3550 
Check kwargs for range expressions with two arguments.
See tests.
```
fix: guard against kwargs for `range` expressions with two arguments
Keyword arguments are not supported for `range(N, M)` and
`range(x, x + N)` expressions.
```
Guard against kwargs for `range` expressions with two arguments
> fix: guard against kwargs for `range` expressions with two arguments

- vyper/codegen/expr.py
- vyper/semantics/types/user.py
`_is_function_implemented` did not use its parameter `fn_name`, it used the captured `name` variable, which happened to be the same as `fn_name`.
chainsec june 2023 review 6.2
> chore: fix dead parameter usages

- vyper/codegen/expr.py
add sanity check in parse_BinOp, we can be stricter in the case where it's a shift binop.
chainsec june review 5.4
> chore: add sanity check in parse_BinOp

- vyper/semantics/types/function.py
`validate_call_args` takes kwargs, the list of valid keywords as an argument and makes sure that when a call is made, the given keywords are valid according to the passed kwargs. however, vyper does not allow kwargs when calling internal functions, so we should actually pass no kwargs to `validate_call_args`.
note that this PR does not actually introduce observed changes in compiler behavior, as the later check in `fetch_call_return` correctly validates there are no call site kwargs for internal functions.
chainsec june 2023 review 5.7
> fix: kwargs passed to `validate_call_args`

- vyper/codegen/context.py
the Context class has an `in_assertion` flag which, when set, indicates that the context should be constant according to is_constant() definition. however, this flag is never set during code generation, specifically, it is possible to have non-constant expression in an assert statement. For example, the following contract compiles:
```vyper
x: uint256
@internal
def bar() -> uint256:
self.x = 1
return self.x
@external
def foo():
assert self.bar() == 1
```
chainsec june 2023 review 5.5
> chore: note `Context.in_assertion` is dead

- vyper/codegen/module.py
move internal function generation to after ctor generation. prior to this commit, the existing code relies on the fact that the code generation of runtime internal functions properly sets the frame information of the ctor's callees. if this precondition is not met in the future, the compiler could panic because the memory allocation info will not be available.
> refactor: initcode generation

- tests/parser/functions/test_addmod.py
- tests/parser/functions/test_ec.py
- tests/parser/functions/test_mulmod.py
- vyper/builtins/functions.py
ecadd, ecmul, addmod, mulmod
in the case that the arguments have side effects, they could be evaluated out of order
chainsec june 2023 review 5.1
patch for https://github.com/vyperlang/vyper/security/advisories/GHSA-4hg4-9mf5-wxxq
> fix: order of evaluation for some builtins

- vyper/ast/pre_parser.py
- vyper/cli/vyper_compile.py
As title.
```bash
chore: add `asm` option to cli help
```
N/A.
> chore: add `asm` option to cli help

- vyper/builtins/functions.py
slight cleanup: refactor ecadd and ecmul to use make_setter and share code, so we don't need to do pointer arithmetic
> refactor: `ecadd()` and `ecmul()` codegen

- tests/parser/functions/test_ecrecover.py
- vyper/builtins/functions.py
fix an edge case that was not coverd by 019a37ab98ff53f04fecfadf602b6cd5ac748f7f
```
this commit fixes an edge case in `ecrecover()` that was not covered by
019a37ab98ff5. in the case that one of the arguments to ecrecover writes
to memory location 0, and the signature is invalid, `ecrecover()` could
return the data written by the argument. this commit fixes the issue by
allocating fresh memory for the output buffer (which won't be written to
by evaluating any of the arguments unless the memory allocator is
broken).
```
> fix: `ecrecover()` edge case

- setup.py
- tests/compiler/test_bytecode_runtime.py
- vyper/compiler/output.py
- vyper/compiler/phases.py
- vyper/ir/compile_ir.py
this commit adds the runtime code layout to the initcode payload (as a suffix), so that the runtime code can be analyzed without source code. this is particularly important for disassemblers, which need demarcations for where the data section starts as distinct from the runtime code segment itself.
note the specific format for the CBOR payload was chosen to avoid changing the last 13 bytes of the signature. that is, the last 13 bytes still look like b"\xa1evyper\x83...", this is because, as the last item in a list, its encoding does not change compared to being the only dict in the payload.
this commit also changes the meaning of the two footer bytes: they now indicate the length of the entire footer (including the two bytes indicating the footer length). the sole purpose of this is to be …
> feat: add runtime code layout to initcode

- vyper/cli/vyper_compile.py
As title.
```bash
chore: add `ir_runtime` option to cli help
```
chore: add `ir_runtime` option to cli help
> chore: add `ir_runtime` option to cli help

- .github/workflows/build.yml
fix macos universal2 build: https://github.com/vyperlang/vyper/actions/runs/6099031696/job/16550232924
this is a build regression introduced by the inclusion of the `cbor2` package in https://github.com/vyperlang/vyper/commit/96d20425fa2fbebb9e9aeb0402399c745eb80cfe.
build tested here: https://github.com/charles-cooper/vyper/actions/runs/6099390346/job/16551425523
> chore(ci): fix macos universal2 build

- docs/structure-of-a-contract.rst
- tests/ast/test_pre_parser.py
- vyper/ast/pre_parser.py
the npm spec library is buggy and does not handle release candidates
correctly. switch to the pypa packaging library which does pep440.
```
the npm spec library is buggy and does not handle release candidates
correctly. switch to the pypa packaging library which does pep440. note
that we do a hack in order to support commonly used npm prefixes: no
prefix, and `^` as prefix. going forward in v0.4.x, we will switch to
pep440 entirely.
```
> fix: version parsing for release candidates

- .github/workflows/build.yml
rename binary during asset upload to properly escape the filename for the github API call.
(Github API states:
> GitHub renames asset filenames that have special characters,
non-alphanumeric characters, and leading or trailing periods. The "List release assets" endpoint lists the renamed filenames. For more information and help, contact GitHub Support.
)
https://github.com/charles-cooper/vyper/releases/tag/v0.3.10rc5
https://github.com/charles-cooper/vyper/actions/runs/6114530221/job/16596363225
> chore(ci): fix binary names in release asset upload

- setup.py
- tests/ast/nodes/test_evaluate_binop_decimal.py
there is a regression in 8.0.0 which results in the following invalid code being generated for vyper/version.py:
```python
from __future__ import annotations
__version__ : str = version : str = '0.3.11'
__version_tuple__ : 'tuple[int | str, ...]' = \
version_tuple : 'tuple[int | str, ...]' = (0, 3, 11)
```
this is a CI blocker.
fix a linter error, for instance as seen here: https://github.com/vyperlang/vyper/actions/runs/6247580329/job/16960472804?pr=3603
pin setuptools_scm
check that lint passes
> chore: tighten bounds for setuptools_scm

- tests/compiler/ir/test_optimize_ir.py
- tests/parser/functions/test_create_functions.py
- tests/parser/functions/test_raw_call.py
- vyper/builtins/functions.py
- vyper/codegen/ir_node.py
fix for https://github.com/vyperlang/vyper/issues/3609
> fix: memory allocation in certain builtins using `msize`

- docs/built-in-functions.rst
- vyper/builtins/functions.py
- vyper/codegen/function_definitions/external_function.py
- vyper/semantics/analysis/local.py
- vyper/semantics/analysis/module.py
- raw_args kwarg to create_from_blueprint
- fix create_from_blueprint example
- clarify "all but one 64th" behavior when forwarding gas left
> fix some documentation inconsistencies

- tests/parser/functions/test_abi_decode.py
- vyper/builtins/functions.py
tracking for https://github.com/vyperlang/vyper/security/advisories/GHSA-cx2q-hfxr-rj97
```
`_abi_decode()` does not validate input when it is nested in certain
expressions. the following example gets correctly validated (bounds
checked):
```vyper
x: uint8 = _abi_decode(slice(msg.data, 4, 32), uint8)
```
however, the following example is not bounds checked:
```vyper
@external
def abi_decode(x: uint256) -> uint256:
a: uint256 = convert(
_abi_decode(
slice(msg.data, 4, 32),
(uint8)
),
uint256
)
return a  # abi_decode(256) returns: 256
```
the issue is caused because the `ABIDecode()` builtin tags its output
with `encoding=Encoding.ABI`, but this does not result in validation
until that itself is passed to `make_setter` (which is called for
instance when generating an assignment or return …
```
> fix: `_abi_decode()` validation

- tests/parser/syntax/test_abi_decode.py
- vyper/builtins/functions.py
currently, the following code will trigger a compiler panic:
```vyper
@external
def foo(j: uint256) -> bool:
s: bool = _abi_decode(j, bool, unwrap_tuple= False)
return s
```
> fix: type check abi_decode arguments

- tests/cli/vyper_json/test_output_selection.py
- vyper/cli/vyper_json.py
- vyper/compiler/output.py
Fix #3619 
Add `metadata` output to `vyper-json`.
chore: add metadata to vyper-json
Add metadata output for vyper-json.
> chore: add metadata to vyper-json

- examples/tokens/ERC1155ownable.vy
- tests/base_conftest.py
- vyper/compiler/output.py
enabling the `-f metadata` output has an interaction with other outputs because the metadata output format mutates some internal data structures in-place. this is because `vars()` returns a reference to the object's `__dict__` as opposed to a copy of it. the behavior can be seen by trying to call the compiler with `-f metadata,devdoc,userdoc`.
this commit fixes the issue by constructing a copy of the object during metadata output formatting. it also modifies the test suite to include more output formats, to test the interactions between these different output formats. in doing so, it was also found that some examples have invalid natspec, which has also been fixed.
the issue was revealed in (but not introduced by) #3622, because that causes the relevant interaction to happen when …
> fix: metadata output interaction with natspec

- tests/parser/test_selector_table.py
```
this commit improves the fuzz examples for the selector table. the
nested `@given` tests too many "dumb" examples (ex. 0, 1, max_value)
when `max_examples` is not large enough. the nested `@given` strategy
can find falsifying inputs, but it requires the inner `max_examples` to
be set much higher, and the shrinking takes much longer. this setting
of `max_examples=125` with a single `@given` using the `@composite`
strategy in this commit finds the selector table bug (that was fixed in
823675a8dc) after an average of 3 runs.
```
> fix: improve test case inputs in selector table fuzz

- .github/workflows/test.yml
- tests/ast/nodes/test_evaluate_binop_decimal.py
- tests/ast/nodes/test_evaluate_binop_int.py
- tests/ast/nodes/test_evaluate_boolop.py
- tests/ast/nodes/test_evaluate_compare.py
- tests/ast/nodes/test_evaluate_subscript.py
- tests/builtins/folding/test_abs.py
- tests/builtins/folding/test_addmod_mulmod.py
- tests/builtins/folding/test_bitwise.py
- tests/builtins/folding/test_floor_ceil.py
- tests/builtins/folding/test_fold_as_wei_value.py
- tests/builtins/folding/test_keccak_sha.py
- tests/builtins/folding/test_min_max.py
- tests/builtins/folding/test_powmod.py
- tests/conftest.py
- tests/fuzzing/test_exponents.py
- tests/grammar/test_grammar.py
- tests/parser/features/test_internal_call.py
- tests/parser/functions/test_slice.py
- tests/parser/test_call_graph_stability.py
- tests/parser/test_selector_table.py
- tests/parser/types/numbers/test_isqrt.py
- tests/parser/types/numbers/test_sqrt.py
- tests/parser/types/test_bytes_zero_padding.py
for historical reasons, pytest ran with `--allow-reruns` when tests failed because tests would usually fail due to deadline errors. deadline errors have never indicated any meaningful issue with the compiler, they are just a somewhat unavoidable byproduct of the fact that we are running in a CI environment which has a lot of jitter.
this commit changes the hypothesis deadline to `None` for the whole test suite, and removes the `--allow-reruns` parameter in the CI, which should make the test suite much more efficient when there are failures.
> chore: remove deadlines and reruns

- tests/ast/test_pre_parser.py
- vyper/ast/pre_parser.py
- vyper/compiler/README.md
- vyper/compiler/__init__.py
- vyper/compiler/phases.py
```
this commit prevents typos (ex. `# pragma evm-versionn ...`) from
getting unexpectedly ignored. it also fixes an issue with the
`evm_version` pragma getting properly propagated into `CompilerData`. it
also fixes a misnamed test function, and adds some unit tests to check
that `evm_version` gets properly propagated into `CompilerData`.
```
> feat: disallow invalid pragmas

- docs/release-notes.rst
> docs: v0.3.10 release

- docs/structure-of-a-contract.rst
I add a note in the docs that both `pragma` directives `#pragma` and `# pragma` versions are supported. I deem this important as the previous version `# @version` also included a space. Furthermore, I fix a broken link for the _PEP440 version specifiers_.
N/A.
N/A.
```console
docs: add note on pragma parsing
```
docs: add note on `pragma` parsing
> docs: add note on `pragma` parsing

- vyper/codegen/memory_allocator.py
- vyper/exceptions.py
fix https://github.com/vyperlang/vyper/issues/3637
this fixes potential overflow bugs in pointer calculation by blocking memory allocation above a certain size. the size limit is set at `2**64`, which is the size of addressable memory on physical machines.
practically, for EVM use cases, we could limit at a much smaller number (like `2**24`), but we want to allow for "exotic" targets which may allow much more addressable memory.
> fix: block memory allocation overflow

- tests/parser/features/test_memory_alloc.py
should have been added in https://github.com/vyperlang/vyper/pull/3639 but the file was not committed
> fix: add missing test for memory allocation overflow

- .github/PULL_REQUEST_TEMPLATE.md
Fix the PR template link to style guide
Fix broken link to style guide in github PR template
> fix: edit link to style guide

- tests/parser/functions/test_slice.py
- vyper/builtins/functions.py
Fix failing fuzzing [test](https://github.com/vyperlang/vyper/actions/runs/6318947122/job/17158979469) for `slice`.
Make the test contract for each bytesdata location more specific.
See tests.
```
chore: fix test for `slice``
```
Fix test for `slice`.
> chore: fix test for `slice`

- docs/resources.rst
I made the following changes in the `resources.rst` file:
- Added my Vyper GitHub list (the reason is that many have already asked where to find such a list)
- I replaced the `VyperDeployer` for Foundry with my 🐍 snekmate version as the other one is outdated (see https://github.com/0xKitsune/Foundry-Vyper/issues/7#issuecomment-1714346954)
- I added Titanoboa to the references
- I remove the dunder for the links as this is unnecessary and `_` is enough
- Fixed some additional small chore
N/A.
N/A
```console
docs: update resources section
```
docs: update resources section
> docs: update resources section

- tests/abi_types/test_invalid_abi_types.py
- tests/parser/types/test_bytes.py
- vyper/abi_types.py
- vyper/exceptions.py
Filling some coverage holes regarding abi types that cannot be hit with integration testing because the type checker would have, well, caught it
Adding a parametrized unit test
add abi types unit tests
add abi types unit tests
> add abi_types unit tests

- vyper/cli/vyper_compile.py
Removed `hex-ir` from CLI help text. The option is available with the `--hex-ir` flag. A similar change was made to remove the duplicate `no-optimize` and `no-bytecode-metadata` cli format options [here](https://github.com/vyperlang/vyper/commit/593c9b86cfea23f624655d5847ef36ae00d7ccdc#diff-ca71900c54e006e760ac124b89b9790803bbac110c9ba51d9bbf5e5b08d76a0aL40).
fix: remove hex-ir from format cli options
Remove redundant hex-ir from format cli options list
> fix: remove hex-ir from format cli options list

- README.md
- docs/contributing.rst
> docs: add script to help working on the compiler

- examples/crowdfund.vy
- examples/tokens/ERC1155ownable.vy
- examples/tokens/ERC20.vy
- examples/tokens/ERC4626.vy
- examples/tokens/ERC721.vy
- examples/wallet/wallet.vy
discourage people from using them in production (which, apparently people were doing)
> docs: add warnings at the top of all example token contracts

- examples/market_maker/on_chain_market_maker.vy
> docs: typo in `on_chain_market_maker.vy`

- tests/functional/builtins/codegen/test_uint2str.py
- vyper/builtins/functions.py
Closes https://github.com/vyperlang/vyper/issues/3641
Fix type check for `uint2str` at compile-time, closes https://github.com/vyperlang/vyper/issues/3641
> add comptime check for uint2str input

- vyper/ast/nodes.py
for some reason, there is a slot named "keyword" on the Call AST node, which is never used (and doesn't exist in the python AST!).
this commit removes it for hygienic purposes.
> fix: remove .keyword from Call AST node

- tests/conftest.py
right now only certain output formats are tested in the main compiler test harness, namely bytecode, abi, metadata and some natspec outputs. in the past, there have been issues where output formats get broken but don't get detected until release testing or even after release.
this commit adds a hook in `get_contract()` to generate all output formats, which will help detect broken output formats sooner.
> chore: test all output formats

- vyper/cli/vyper_compile.py
this commit adds `-v` and `-O` as aliases for `--verbose` and `--optimize`, respectively.
> feat: add short options `-v` and `-O` to the CLI

- tests/unit/cli/vyper_compile/test_compile_files.py
- tests/unit/compiler/test_input_bundle.py
- tests/utils.py
- vyper/cli/vyper_compile.py
the current behavior is that the current directory does *not* get into the search path when `-p` is specified, which is annoying. (one would expect `vyper some/directory/some/file.vy` to compile no matter what `-p` is specified as).
this commit also handles the addition of multiple search paths specified on the CLI, and adds a long `--path` option as an alternative to `-p`.
> feat: search path resolution for cli

- vyper/venom/ir_node_to_venom.py
Fixed the signature of _append_return_for_stack_operand() to take the context not the basic block
> fix: type annotation of helper function

- vyper/codegen/expr.py
- vyper/codegen/stmt.py
- vyper/exceptions.py
- vyper/semantics/analysis/common.py
QOL improvement -- add annotations where missing to exceptions which happen during code generation
also, moves the `tag_exceptions()` helper to `vyper.exceptions`
> chore: improve exception handling in IR generation

- vyper/codegen/expr.py
- vyper/codegen/stmt.py
- vyper/exceptions.py
this QOL commit improves on 91659266c55a by passing through the `__traceback__` field when the exception is modified (instead of using `__cause__` - cf. PEP-3134 regarding the difference) and improves error messages when an IRnode is not returned properly. using `__traceback__` generally results in a better experience because the immediate cause of the exception is displayed when running `vyper -v` instead of needing to scroll up through the exception chain (if the exception chain is reproduced correctly at all in the first place).
> feat: improve panics in IR generation

- docs/types.rst
The `EXTCODEHASH` of an empty account is not `empty(bytes32)` but `keccak256("") = 0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`. See [EIP-1052](https://eips.ethereum.org/EIPS/eip-1052).
Fixed the docs. Please note that there is _no_ code bug, as any Vyper compiled contract will return `0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470` for an EOA or an empty account (see [here](https://github.com/vyperlang/vyper/blob/2df916ca453ddda4cf08878c4fdaaa55b963686c/vyper/codegen/expr.py#L250)).
- [EIP-1052](https://eips.ethereum.org/EIPS/eip-1052)
- [Geth](https://github.com/ethereum/go-ethereum/blob/d2e3cb894b6deab6ef599c6c241527124d8984bd/core/types/hashes.go#L33)
```console
docs: clarify `address.codehash` for an empty account
```
- docs: clarify …
> docs: clarify `address.codehash` for empty account

- docs/event-logging.rst
Added additional information about EVM opcodes for log records, introduced topics and data, and corrected the limit for indexed arguments.
docs: indexed arguments for events are limited
The number of indexed arguments is limited by the EVM to a maximum of four. Include definition of topics and data.
> docs: indexed arguments for events are limited

- tests/functional/codegen/features/iteration/test_for_in_list.py
- tests/functional/syntax/exceptions/test_syntax_exception.py
- tests/functional/syntax/test_for_range.py
- vyper/ast/parse.py
- vyper/ast/pre_parser.py
- vyper/exceptions.py
Improve diagnostics for invalid loop variable annotation and add tests for #3596.
Compiling this contract throws an error that does not make sense
```
@external
def foo():
for i: uint9 in [1, 2, 3]:
pass
```
```
vyper.exceptions.UnknownType: No builtin or user-defined type named '@exte'. 
contract "tmp/old_for.vy:1", function "foo", line 1:0 
---> 1 @external
-------^
2 def foo():
```
This PR changes the error message to:
```
vyper.exceptions.UnknownType: No builtin or user-defined type named 'uint9'. Did you mean 'uint96', or maybe 'uint8'?
contract "tmp/old_for.vy:3", function "foo", line 3:4 
2 def foo():
---> 3     for i: uint9 in [1, 2, 3]:
-----------^
4         pass
```
Propagate the annotation source code and `For` node locations to the annotation and all its child nodes
See …
> chore: improve diagnostics for invalid for loop annotation

- tests/functional/syntax/test_for_range.py
- vyper/ast/parse.py
- vyper/ast/pre_parser.py
use a parser trick to get always-correct source locations into for-loop target annotations.
follow-up to #3721; reverts the AnnAssign pre-parser change from there.
see commit
check new test will not pass without the parser changes.
````
use a parser trick to get always-correct source locations into for-loop
target annotations.
````
> refactor: for target parsing

- docs/resources.rst
Add 'Vyper Online Compiler' to the resources docs
A Vyper online deployment and compiler has been written using the Sanic framework
Clone the repository or compile and deploy on the website
Add Vyper online compiler tooling
Add 'Vyper Online Compiler' resources
> Add Vyper online compiler tooling

- requirements-docs.txt
apparently, readthedocs requires v5.0 of sphinx or greater now (see failing run at https://readthedocs.org/projects/vyper/builds/23107228/). bump the sphinx dependency.
> chore: bump sphinx version

- vyper/venom/basicblock.py
- vyper/venom/ir_node_to_venom.py
- vyper/venom/venom_to_assembly.py
> feat: add more venom instructions

- tests/unit/compiler/test_opcodes.py
- vyper/compiler/output.py
Fixed the `opcodes` and `opcodes_runtime` outputs as they would not respectively match the `bytecode` and `bytecode_runtime` outputs.
The value following a `PUSH` instruction could be incorrect. For example, when compiling some Vyper code that results in `PUSH2 0x100`:
- The `bytecode` output would be `610100`
- The `opcodes` output would be `PUSH2 0x10` instead of `PUSH2 0x100`
This issue is due to a lack of 0 padding.
In `build_opcodes`, left pad each byte to be concatenated with 0 to have a length of 2 digits
Check the tests
```
Fixed the opcodes and opcodes_runtime outputs as they would not
respectively match the bytecode and bytecode_runtime outputs.
The value following a PUSH instruction could be incorrect. For example,
when compiling some Vyper code that results in `PUSH2 0x0100`: …
```
> fix: `opcodes` and `opcodes_runtime` outputs

- tests/functional/builtins/codegen/test_concat.py
- vyper/builtins/functions.py
fix https://github.com/vyperlang/vyper/issues/3737
```
the `concat()` builtin did not respect the `copy_bytes()` API, it
allocated a buffer in some cases which did not have enough padding.
patches GHSA-2q8v-3gqq-4f8p
```
> fix: concat buffer bug

- docs/_static/css/dark.css
- docs/conf.py
- docs/control-structures.rst
- docs/installing-vyper.rst
- docs/release-notes.rst
- docs/testing-contracts-ethtester.rst
- docs/types.rst
- requirements-docs.txt
- Fixes #3730.
- At the same time, fixed a bunch of Sphinx warnings.
- And updated copytights + Python version.
Read the docs.
> docs: Upgrade dependencies and fixes

- tests/functional/builtins/codegen/test_raw_call.py
- vyper/builtins/functions.py
per title. also removed a couple unneeded expr traces
> fix: disallow `value=` passing for delegate and static raw_calls

- docs/interfaces.rst
- docs/release-notes.rst
- examples/factory/Exchange.vy
- examples/factory/Factory.vy
- examples/market_maker/on_chain_market_maker.vy
- examples/tokens/ERC1155ownable.vy
- examples/tokens/ERC20.vy
- examples/tokens/ERC4626.vy
- examples/tokens/ERC721.vy
- tests/functional/codegen/calling_convention/test_external_contract_calls.py
- tests/functional/codegen/modules/test_stateless_functions.py
- tests/functional/codegen/test_interfaces.py
- tests/functional/syntax/test_functions_call.py
- tests/functional/syntax/test_interfaces.py
- vyper/semantics/analysis/module.py
Fixed Issue #3675 
Honestly I just found and replaced, and it didn't break(??). Would double check but this seems to be working to me
Run the tests, they seem to pass?
Aliased `vyper.interfaces` import to `ethereum.ercs`
Aliased `vyper.interfaces` import to `ethereum.ercs`
This is who you're bullying when your request changes on my PR (jk ... pls do whatever is necessary)
> feat: rename `vyper.interfaces` to `ethereum.ercs`

- tests/functional/syntax/test_constants.py
- vyper/codegen/expr.py
in addition to structs and interfaces, some builtins can also be skipped by the constant folder.
> fix: bad assertion in expr.py

- vyper/codegen/ir_node.py
this results in a 16% improvement in compile time
> perf: reimplement `IRnode.__deepcopy__`

- tests/functional/builtins/folding/test_bitwise.py
this is a regression introduced in c6b29c7f06a; the exception thrown by `validate_expected_type()` was updated to be `TypeMismatch`, but this test was not correspondingly updated. this is a regression in the test suite, not in the compiler itself.
> fix: fuzz test not updated to use TypeMismatch

- Makefile
and remove the separate mypy rule. this makes the development workflow a bit faster
> chore: run mypy as part of lint rule in Makefile

- vyper/cli/vyper_compile.py
this is for external consumers of the compiler library, which may want to be able to replicate how vyper computes the search path
> refactor: `get_search_paths()` for vyper cli

- docs/compiling-a-contract.rst
- vyper/cli/vyper_compile.py
I add all missing CLI flags in the docs. Furthermore, I also add a note due to the patch in https://github.com/vyperlang/vyper/pull/3735. Eventually, I add the missing CLI flag `metadata`.
Compare the output of `vyper --help` with the documentation [here](https://docs.vyperlang.org/en/stable/compiling-a-contract.html#vyper).
Run `vyper --help`:
```console
docs: add missing cli flags
```
docs: Add missing CLI flags.
> docs: add missing cli flags

- tests/functional/syntax/modules/test_initializers.py
- tests/functional/syntax/test_for_range.py
- vyper/exceptions.py
- vyper/semantics/analysis/levenshtein_utils.py
- vyper/semantics/analysis/utils.py
- vyper/semantics/namespace.py
- vyper/semantics/types/base.py
- vyper/semantics/types/user.py
- vyper/semantics/types/utils.py
find some large contract (e.g. CurveStableSwapNG.vy), try `vyc -f annotated_ast` and `vyc -f bytecode`.
```bash
$ time vyc tmp/CurveStableSwap-0.4.0.vy >/dev/null
real	0m4.467s
user	0m4.259s
sys	0m0.206s
$ time vyc -f annotated_ast tmp/CurveStableSwap-0.4.0.vy >/dev/null
real	0m1.681s
user	0m1.625s
sys	0m0.058s
$ time vyc tmp/CurveStableSwap-0.4.0.vy >/dev/null
real	0m4.150s
user	0m3.899s
sys	0m0.250s
$ time vyc -f annotated_ast tmp/CurveStableSwap-0.4.0.vy >/dev/null
real	0m1.427s
user	0m1.390s
sys	0m0.039s
```
```
optimize compile time. `levenshtein` is a hotspot since it is called a
lot during type analysis to construct exceptions (which are then caught
as part of the validation routines). this commit delays calling
`levenshtein` until the last minute, and also adds a mechanism to …
```
> perf: levenshtein optimization

- vyper/ast/nodes.py
- vyper/semantics/analysis/utils.py
a couple compilation-time optimizations. bring total time down by 5% (`vyper -f bytecode`), and time in frontend code down by 20% (`vyper -f annotated_ast`).
cache `VyperNode.get_fields()`, it's a hotspot
optimize `get_common_types`, the line `rejected = [i for i in common_types if i not in common]` is a hotspot
> feat: frontend optimizations

- vyper/ast/nodes.py
optimize frontend compilation time by 10%
check frontend time with `vyper -f annotated_ast`, and full compilation time with `vyper -f bytecode`
> feat: optimize `VyperNode.deepcopy`

- vyper/ast/nodes.py
- vyper/ast/parse.py
- vyper/semantics/analysis/utils.py
- vyper/semantics/types/primitives.py
```
- optimize `VyperNode.get_descendants()` and `get_children()`
- get rid of `sort_nodes()`, we can guarantee ordering the old fashioned
way (topsort)
- optimize `VyperNode.__hash__()` and `VyperNode.__init__()`
- optimize `IntegerT.compare_type()`
optimizes front-end compilation time by another 25%
```
> feat: more frontend optimizations

- tests/unit/compiler/venom/test_duplicate_operands.py
- vyper/ir/compile_ir.py
it was not aggressive enough, and could leave some instructions which mangle the assembly so it can't be turned into bytecode
> fix: assembly dead code eliminator

- tox.ini
- vyper/semantics/analysis/constant_folding.py
also remove a stray `type: ignore` comment
per https://github.com/python/mypy/issues/7771#issuecomment-698077631
run `make lint`, see color. try with a forced error (e.g. get rid of a random `# type: ignore` comment in the codebase)
> chore: add color to mypy output

- docs/resources.rst
- docs/types.rst
- vyper/builtins/_convert.py
- vyper/codegen/core.py
- vyper/codegen/expr.py
- vyper/semantics/README.md
- vyper/semantics/analysis/local.py
- vyper/semantics/analysis/utils.py
- vyper/semantics/types/base.py
- vyper/semantics/types/user.py
Rename occurrences of `enum` by `flag` missed by #3697
control-F "enum", then replace relevant occurrences
It should be straightforward from the changes
chore: replace occurrences of 'enum' by 'flag'
replace occurrences of 'enum' by 'flag'
> chore: replace occurrences of 'enum' by 'flag'

- tests/functional/syntax/test_structs.py
- vyper/ast/parse.py
- vyper/builtins/functions.py
- vyper/codegen/expr.py
- vyper/utils.py
add source information to `vyper_warn()` to give more helpful warnings
write some vyper code with old-style structs, like
```
p: Proposal = Proposal({x: 1, y: 2})
```
see that the warning includes the source location after this commit.
> feat: improve warnings, refactor `vyper_warn()`

- tests/functional/codegen/features/iteration/test_for_in_list.py
- tests/functional/syntax/exceptions/test_constancy_exception.py
- tests/functional/syntax/test_for_range.py
- tests/unit/semantics/analysis/test_for_loop.py
- vyper/semantics/analysis/local.py
looping over a `range` was allowed if the iterator type was `decimal`, this PR prevents this unintended behaviour.
- Ensure the type of the iterator is an `IntegerT`.
- Ensure the literals in the `range()` expression are not only `Num` but `Int`.
See tests
fix: prevent range over decimal
prevent range over decimal
> fix: prevent range over decimal

- tests/functional/syntax/modules/test_initializers.py
clarify the behavior of storage access through nested attribute access
> chore: add another borrowship test

- vyper/compiler/input_bundle.py
- vyper/utils.py
InputBundle has the `_cache` attribute, which was implemented using an anonymous function, which is not pickleable. Change `_cache` to use a dedicated object type.
also refactors `timeit()` to be a contextmanager instead of just a function decorator.
> fix: pickleability of `CompilerData`

- docs/compiling-a-contract.rst
Nit follow-up PR for https://github.com/vyperlang/vyper/pull/3669 to add the newly introduced CLI flag `annotated_ast` to the docs.
See https://github.com/vyperlang/vyper/pull/3669.
Invoke `vyper -h`.
```console
docs: add missing annotated_ast flag
```
docs: add missing `annotated_ast` flag
> docs: add missing `annotated_ast` flag

- tests/functional/syntax/test_interfaces.py
- vyper/semantics/analysis/module.py
improve error message for common issue when upgrading from v0.3.x
> feat[ux]: improve error message for importing ERC20

- tests/functional/codegen/types/test_array_indexing.py
- vyper/codegen/core.py
fix https://github.com/vyperlang/vyper/issues/3762
> fix[codegen]: bounds check for signed index accesses

- vyper/semantics/analysis/module.py
> chore[ux]: improve an exports error message

- .github/workflows/test.yml
- Makefile
- tox.ini
this commit removes the tox rules for lint, as part of a larger movement to remove tox from the codebase (it's slow, confusing, and superseded by environment matrices on github actions).
the rules in the makefile are split apart so they can be run in parallel with `make -j lint`.
> chore: remove tox rules for lint commands

- vyper/builtins/_convert.py
- vyper/builtins/_signatures.py
- vyper/codegen/abi_encoder.py
- vyper/codegen/arithmetic.py
- vyper/codegen/context.py
- vyper/codegen/core.py
- vyper/codegen/expr.py
- vyper/codegen/external_call.py
- vyper/codegen/function_definitions/common.py
- vyper/codegen/ir_node.py
- vyper/codegen/keccak256_helper.py
- vyper/codegen/module.py
- vyper/codegen/return_.py
- vyper/codegen/stmt.py
- vyper/ir/compile_ir.py
- vyper/ir/optimizer.py
go through coverage report of vyper/codegen, fix up bunch of little issues with `pragma: nocover`, branch coverage, delete some apparently dead code.
check coverage report
> chore: improve codegen test coverage report

- setup.py
eth-abi 5.0.1 introduces a regression for eth-abi decoding due to the way that eth-tester enforces decoding of revert strings.
fix CI failures, see for instance https://github.com/vyperlang/vyper/actions/runs/8153520136/job/22285100813?pr=3833#step:5:1331
> chore[ci]: pin eth-abi for decode regression

- vyper/utils.py
Added support for: 
1) Convenience method to get the first member
2) Computing the intersection operation on any number of sets
Add utility methods to OrderedSet()
* first()
* intersection() (class method)
> feat: add utility functions to `OrderedSet`

- .github/workflows/build.yml
this commit fixes a regression introduced in 730679bd553d3487, which is that v4 of the artifact actions breaks the asset upload pipeline. roll back the changes for now
> chore[ci]: roll back GH actions/*artifacts version

- docs/types.rst
per title. cf. https://python-history.blogspot.com/2010/08/why-pythons-integer-division-floors.html
> docs: add rationale for floordiv rounding behavior

- vyper/builtins/functions.py
- vyper/codegen/core.py
> feat[ir]: add `eval_once` sanity fences to more builtins

- .github/workflows/test.yml
reduce the number of jobs, since mypy really belongs in the lint job anyways.
> chore[ci]: merge mypy job into lint

- vyper/codegen/core.py
``STORE()`` unique symbol name is computed as `_freshname(_freshname(f"{op}_"))` instead of `_freshname(f"{op}_")` after #3835. This PR fixes this.
Straightforward
Compiling a contract with a single ``SSTORE`` will lead to an IR containing `[unique_symbol, sstore_1]` where it would previously contain `[unique_symbol, sstore_12`].
fix: unique symbol name
Fix unique symbol name
> fix[ir]: unique symbol name

- vyper/codegen/module.py
Updated the dense selector (used in optimization for codesize) to emit the target constrained `djump` instruction.
Made a list of the possible targets and emitted the `djump` instruction with that.
> feat[ir]: emit `djump` in dense selector table

- docs/compiling-a-contract.rst
- tests/functional/syntax/test_self_balance.py
- tests/unit/cli/vyper_json/test_get_settings.py
- tests/unit/compiler/test_opcodes.py
- tests/unit/compiler/test_pre_parser.py
- vyper/cli/vyper_json.py
- vyper/codegen/expr.py
- vyper/codegen/function_definitions/common.py
- vyper/evm/opcodes.py
per https://github.com/vyperlang/vyper/issues/3365,
- drop istanbul support as it is 4 years old
- drop berlin support since it will be 3 years old by the time of release
also:
- change nonreentrant key values for cancun(!)
```
this commit drops explicit support for the istanbul and berlin hard
forks per the three year rule suggested in VIP 3365
- istanbul hard fork was 2019-12-09, over 4 years ago
- berlin hard fork was 2021-04-15, which should be 3 years ago by the
time of 0.4.0 release (or if we can release sooner, shortly after)
this commit also changes the nonreentrant key values for cancun (since
`PUSH0` takes 1 less byte in the bytecode).
```
> feat: drop istanbul and berlin support

- .github/workflows/test.yml
- setup.py
- tests/functional/builtins/codegen/test_slice.py
- tests/functional/builtins/folding/test_powmod.py
- tests/functional/codegen/types/test_bytes_zero_padding.py
- tests/functional/grammar/test_grammar.py
- tests/functional/syntax/test_structs.py
- vyper/ast/nodes.py
- vyper/ast/parse.py
```
add a python3.12 job in the CI.
also:
- update dependencies
- update tests for new dependencies
- refactor the grammar tests to use less filtering
- python3.12 deprecates the "n" field on constants; remove it
```
> chore[ci]: enable python3.12 tests

- vyper/ast/parse.py
Fix #3865
The exception now displays as:
```
vyper.exceptions.SyntaxException: invalid syntax (<unknown>, line 3)
line 3:31 
2 def foo():
---> 3     s: String[2] = staticcall staticcall concat('a', 'b')
--------------------------------------^
4     return
```
Not sure how to go about writing a test for this
```
chore: improve syntax error handling
This PR improves the handling of syntax errors by obscuring
the underlying exception from the python parser.
```
> chore: improve syntax error messages

- setup.py
```
it is not used, and it conflicts with the requirements specified in
`docs-requirements.txt` (which is _actually_ used, in
`.readthedocs.yaml`).
```
> chore[build]: remove docs rule in `setup.py`

- .github/workflows/pull-request.yaml
ensure PR titles conform to conventional commits. scopes are now required!
> feat[ci]: add PR title validation

- .github/workflows/pull-request.yaml
- docs/constants-and-vars.rst
- tests/functional/syntax/test_block.py
- vyper/codegen/expr.py
- vyper/semantics/environment.py
`block.prevrandao` is an opcode alias for `difficulty`. however, it returns a bytes object at the evm level (cf. for instance py-evm returns the value of `block.mixhash`). this commit changes the signature of block.prevrandao to be more consistent with the VM semantics.
```
`block.prevrandao` is an opcode alias for `difficulty`. however, it
returns a bytes object at the evm level (cf. for instance py-evm returns
the value of `block.mixhash`). this commit changes the signature of
`block.prevrandao` to be more consistent with the VM semantics.
also update PR title regex per conventional commit specification - add
optional `!` which indicates a breaking change
```
> feat[lang]!: change the signature of `block.prevrandao`

- tests/functional/codegen/modules/test_exports.py
- vyper/exceptions.py
- vyper/semantics/analysis/module.py
- vyper/semantics/types/module.py
fix https://github.com/vyperlang/vyper/issues/3881
```
this commit fixes transitive exports, i.e. where `module1` exports
`module2.foo`, but it was previously not exportable from `module1`. this
is because previously exported functions were not added to the
`ModuleT`'s `exposed_functions` list.
a test had previously been written for this case, but it had been marked
xfail since the desired behavior was not clear until user feedback was
received. this commit removes the `xfail` marker from that test case.
```
> fix[lang]: transitive exports

- tests/functional/grammar/test_grammar.py
fixes a fuzz failure, which is that the strategy can put utf-8 characters in strings (which we reject at compile-time). the fix here is to just create programs with ascii. this bug was apparently introduced in 176e7f7f3a6a16bc09ec58d4bbc8dc515c48a0a8 due to the new alphabet parameter passed to the grammar strategy.
fix https://github.com/vyperlang/vyper/issues/3875
> fix[test]: fix failure in grammar fuzzing

- setup.py
hexbytes introduces new behavior how it interacts with strings/bytes. this commit pins hexbytes as a stopgap solution until we update tests.
> fix[ci]: pin hexbytes to pre-1.0.0

- tests/unit/compiler/venom/test_dominator_tree.py
- tests/unit/compiler/venom/test_make_ssa.py
- tests/unit/compiler/venom/test_multi_entry_block.py
- vyper/venom/__init__.py
- vyper/venom/passes/base_pass.py
- vyper/venom/venom_to_assembly.py
I made the pass "manager" to work with instances instead of classes
Updated tha pass handling code, the pass usage code, and the related tests. 
```
future venom passes that are currently under development require that
the pass manager works with pass instances rather than classes. this is
a common change that should be merged upstream in order to carry around
less changes to future pull requests.
```
> refactor[venom]: use venom pass instances

- tests/functional/codegen/features/decorators/test_pure.py
- vyper/semantics/analysis/local.py
20432c505c706ed introduced a regression where type expressions like the following would raise a compiler error instead of successfully compiling:
```
@pure
def f():
convert(..., uint256)  # raises `not a variable or literal: 'uint256'`
```
the reason is because `get_expr_info` is called on `uint256`, which is not a regular expr. this commit introduces a fastpath return to address the issue. longer-term, we should generalize the rule so that ast traversal does not progress into type expressions.
> fix[lang]: allow type expressions inside pure functions

- tests/functional/builtins/codegen/test_convert.py
- tests/functional/codegen/types/numbers/test_decimals.py
- tests/unit/ast/nodes/test_fold_binop_decimal.py
- vyper/ast/nodes.py
- vyper/utils.py
fix a fuzz test, fix #2241, improve boundary conditions for some decimal fuzz tests.
```
the decimal fuzz test `is_valid` condition was based on an ancient
version of decimals which had bounds at `-2**127` and `2**127`. update
the condition to be compatible with the latest version of `decimal`.
also increase the range of decimals produced by the decimal fuzzing
strategy, so that the fuzzer finds overflow issues faster.
an additional issue was found in the fuzz tests, which is that some
decimal operations panic with `decimal.InvalidOperation` instead of a
proper exception. this is a known bug, see GH #2241. this fixes the
issue by catching the exception and raising an `OverflowException`.
misc/refactor:
- refactor several uses of quantize into a utility function
```
> fix[test]: fix a bad bound in decimal fuzzing

- .github/workflows/release-pypi.yml
OIDC is pypi's current recommended best practice (see below). this commit modifies the pypi release pipeline to use the Trusted Publisher mechanism. it has already been configured on the PyPI side.
references:
- https://docs.pypi.org/trusted-publishers/
> feat[ci]: update pypi release pipeline to use OIDC

- tests/unit/ast/test_pre_parser.py
- vyper/ast/pre_parser.py
- vyper/exceptions.py
Fix #3910.
See test
```
this commit adds source code information to the exception thrown in
`validate_version_pragma()` to improve user experience when dealing with
imports with invalid (or incompatible) version pragmas.
```
> fix[ux]: raise `VersionException` with source info

- tests/conftest.py
- tests/unit/cli/vyper_json/test_get_settings.py
- tests/unit/compiler/ir/test_optimize_ir.py
- tests/unit/compiler/test_default_settings.py
- tests/unit/compiler/test_opcodes.py
- vyper/cli/vyper_compile.py
- vyper/codegen/core.py
- vyper/compiler/__init__.py
- vyper/compiler/phases.py
- vyper/compiler/settings.py
- vyper/evm/opcodes.py
- vyper/utils.py
cherry-picked relevant commits from https://github.com/vyperlang/vyper/pull/3905
```
this commit adds a global settings object, unifying various functions
which modify global settings:
anchor_opt_level, anchor_evm_version, _set_debug
```
> refactor[codegen]: make settings into a global object

- tests/conftest.py
- tests/functional/codegen/types/numbers/test_decimals.py
- tests/unit/ast/test_pre_parser.py
- vyper/ast/pre_parser.py
- vyper/cli/vyper_compile.py
- vyper/compiler/phases.py
- vyper/compiler/settings.py
- vyper/exceptions.py
- vyper/semantics/analysis/local.py
- vyper/semantics/types/utils.py
depends https://github.com/vyperlang/vyper/pull/3929
```
hide decimals behind a feature flag. this informally lets us "break the
compatibility contract" with users by moving decimals into
quasi-experimental status; this way we can iterate on the decimals
design faster in the 0.4.x series instead of needing to wait for
breaking releases to make changes.
```
> feat[lang]!: add feature flag for decimals

- .github/workflows/pull-request.yaml
```
we don't need to use single commit validation, because in the github
settings for this repository we use "Pull request title and commit
details", instead of the default settings for squash merge.
```
> chore[ci]: reconfigure single commit validation

- tests/functional/syntax/modules/test_initializers.py
- vyper/semantics/analysis/module.py
```
when a stateless module is accidentally declared as being `used` by a
user, the error message is confusing. update the error message to
clarify `uses` refers to state being used.
```
> fix[ux]: fix `uses` error message

- setup.py
- Removed `vyper-serve` from `setup.py`
- Removed its reference from `entry_points` in `setup.py`
- N/A
```
remove reference to the vyper-serve entry point; it no longer exists as
of 98f502bae
```
resolves #3935 
[Cute hamster](https://unsplash.com/photos/selective-focus-photography-of-brown-hamster-adK3Vu70DEQ)
> chore[tool]: remove `vyper-serve` from `setup.py`

- docs/built-in-functions.rst
As title.
Obvious.
N/A.
```console
chore[docs]: amend `revert_on_failure` kwarg docs for create builtins
```
```console
chore[docs]: amend `revert_on_failure` kwarg docs for create builtins
```
> chore[docs]: amend `revert_on_failure` kwarg docs for create builtins

- tests/unit/ast/test_natspec.py
- vyper/ast/natspec.py
- vyper/compiler/output.py
- vyper/compiler/phases.py
```
prior to this commit, natspec had to be explicitly requested by the user
(`-f userdoc`, `-f devdoc` or `-f combined_json`). this would lead to
discrepancies between development time and verification time, where a
contract could compile locally (because no natspec was requested), but
not on the verifier's pipeline (because the verifier would request the
natspec via one of the above methods). this commit computes the natspec
as part of the dependencies of the analysed AST (the reasoning being
that, a consumer might expect semantic analysis to include natspec
validation). so, there is no way to produce bytecode for a contract
without validating natspec.
```
> chore[ux]: compute natspec as part of standard pipeline

- vyper/cli/vyper_compile.py
I noticed `--hex-ir` was missing a help.
Simple PR adds one.
side nit: I notice inconsistencies with CLI help texts... Some start with capital letter, some have periods at the end, etc.
`help=`
vyper --help
woof
> chore[tool]: add help text for `hex-ir` CLI flag

- tests/functional/codegen/types/numbers/test_exponents.py
- vyper/semantics/types/primitives.py
fix #3948 
```
this commit fixes folding of the `**` operator when the arguments are
constants, but not literals.
```
> fix[lang]: fix `pow` folding when args are not literals

- docs/vyper-by-example.rst
The `endAuction` method in `vyper-by-example.rst` gets truncated before the beneficiary is sent the highest bid. This updates the line numbers to show the entire method
> fix[docs]: fix clipped `endAuction` method in example section

- SECURITY.md
- update the old security policy
- fixes https://github.com/vyperlang/vyper/issues/3467
> refactor[docs]: refactor security policy

- tests/unit/compiler/asm/test_asm_optimizer.py
- vyper/ir/compile_ir.py
Fixed assembly optimizer case where trying to optimize two consecutive `JUMPDEST`s with the same symbol results in no code change, while returning of `True` in changes. 
Made the optimization step return `False` as it should. 
Through the included tests
```
Updates the assembly optimizer to return `False` when trying to 
optimize two consecutive `JUMPDEST`s with the same symbol. 
It used to return `True` when no change was made.
+ unit tests
```
> fix[codegen]: same symbol jumpdest merge

- .github/workflows/test.yml
Always display the evm backend in the test pipeline
> chore[test]: always specify the evm backend

- .github/workflows/test.yml
- tests/unit/compiler/test_source_map.py
- vyper/ast/nodes.py
- vyper/venom/passes/sccp/eval.py
```
fix `exp` evaluation in sccp. the current implementation is incorrect,
which was found by enabling the `venom + -opt-none` pipeline in the CI.
`evm_pow` is correct, as it preserves the correct edge cases when
base/exponent are 0 or 1 (all combinations).
this commit also enables the `venom + -opt-none` and
`venom + -opt-codesize` jobs in the CI, ensuring higher coverage of the
venom pipeline going forward.
```
> fix[venom]: fix eval of `exp` in sccp

- vyper/venom/passes/make_ssa.py
Removed a leftover method in `make_ssa.py`
```
remove unused method in `make_ssa.py`
```
> refactor[venom]: remove unused method in `make_ssa.py`

- vyper/venom/passes/mem2var.py
I fixed mem2var that was creating a bogus instruction in certain cases of returning values. 
```
the `mem2var` venom pass was creating an `mstore` instruction with a
bogus output variable when promoting a variable to memory for `RETURN`s.
```
> fix[venom]: fix return opcode handling in mem2var

- tests/unit/cli/vyper_compile/test_compile_files.py
- tests/unit/cli/vyper_json/test_compile_json.py
- vyper/cli/vyper_compile.py
- vyper/cli/vyper_json.py
- vyper/compiler/__init__.py
- vyper/compiler/output.py
Resolves #1998.
```
this commit adds source map output for initcode
```
> feat[tool]: add source map for constructors

- tests/functional/codegen/storage_variables/test_getters.py
- vyper/semantics/analysis/local.py
- vyper/semantics/types/subscriptable.py
Fixes #3984
- Updated index checks for when the subscript is folded
- Use the reduced (i.e. folded) value when checking the index type
- Tests are included
```
this commit fixes a bug in typechecking of folded values for hashmap
indexes. there was previously a carveout for subscript typechecking for
arrays; however, it should not apply to hashmap indexes.
this was introduced as an edge case resulting from the semantic changes
in 56c4c9dbc0. a related fix was applied in 75fb0594ab3, but it did not
handle hashmaps.
```
`HashMap index is checked when the subscript is folded`
> fix[lang]: typecheck hashmap indexes with folding

- .github/workflows/test.yml
- tests/functional/builtins/codegen/test_slice.py
- tests/unit/compiler/test_input_bundle.py
- tests/unit/compiler/venom/test_liveness_simple_loop.py
- vyper/cli/vyper_json.py
- vyper/compiler/__init__.py
- vyper/compiler/input_bundle.py
- vyper/compiler/output_bundle.py
- vyper/compiler/phases.py
- vyper/semantics/analysis/module.py
```
this commit fixes some `InputBundle` bugs on windows due to how
path-manipulation operations are implemented. it also fixes compilation
of cross-OS archives by settling on using posix paths as standard (this
follows the ZIP archive spec, and is explicit in the python stdlib
implementation of zipfile).
this commit also enables a windows job in the CI for tests, to prevent
bugs like these in the future and increase cross-OS coverage.
references:
- https://stackoverflow.com/a/8177003
- https://hg.python.org/cpython/file/2.7/Lib/zipfile.py#l295
- https://hg.python.org/cpython/file/2.7/Lib/zipfile.py#l1046
```
> fix[tool]: fix cross-compilation issues, add windows CI

- .github/workflows/test.yml
- Expanded the matrix to include macos and windows tests
- Removed unnecessary lines from the matrix definition
- All default values must be in the top-level matrix definition
- The `includes` section should contain alternative runs - these will not have all default values defined
- Therefore reading from the matrix requires passing default values again
- However we can still delete a lot of repetition
- Tests should pass. We should have 2 extra jobs and the existing ones should keep on existing.
```
- Expanded the matrix to include macos and windows tests
- Refactor the matrix and removed unnecessary lines
- Remove now-redundant windows job
Note that all because of the way github creates matrix jobs, default
values must be in the top-level matrix definition. The includes section
should …
```
> chore[test]: add macos to test matrix

- vyper/codegen/core.py
append/pop does not have an eval once fence for the cases where it is in memory. add a fence.
> fix[codegen]: fix double eval in dynarray append/pop

- vyper/venom/__init__.py
- vyper/venom/passes/remove_unused_variables.py
Apply `mem2var` pass after we are in SSA form -as appropriate-, and add an additional store elimination pass after `SCCP`. Improves code size a bit.
```
The `Mem2Var` pass needs to operate on SSA form. This commit 
updates the order of passes to accommodate for this. Additionally
we add an extra `StoreElimination` pass after `SCCP` to further
reduce the generated code size.
Additionally, it updates the `RemoveUnusedVariablesPass` to eliminate
all unused variables without the need to be run multiple times.
```
> feat[venom]: optimize mem2var and store/variable elimination pass sequences

- docs/interfaces.rst
Add a note in the docs that `implements` does not check emitted events.
Brain.
Use hard skills.
```console
as of v0.4.0, `implements` does not check that events are (re-)defined
in the implementing contract
```
Add a note in the docs that `implements` does not check emitted events.
> chore[docs]: `implements` does not check event declarations

- vyper/utils.py
- vyper/venom/__init__.py
- vyper/venom/analysis/dfg.py
- vyper/venom/passes/remove_unused_variables.py
Implemented a better variable elimination pass. This new implementation is efficient and manages to remove all unused variables in one run.
Additionally, this PR adds some extra utility functions to `OrderedSet()`
```
This commit improves the variable elimination pass by efficiently removing 
all instructions that produce unused output. This new algorithm removes all
unused variables in one run.
Additionally, it adds the utility functions `pop()` and `addmany()` to the
`OrderedSet()` class.
The `DFTAnalysis` is also augmented with a method to remove uses:
`remove_use(self, op: IRVariable, inst: IRInstruction)`
```
```
__
/ _)--< 
_.----._/ /          
/          /  Dinosnek          
__/ (  |  (   |             
/__.-'|_|--|__|             
```
> feat[venom]: improve unused variable removal pass

- tests/unit/compiler/venom/test_branch_optimizer.py
- vyper/venom/__init__.py
- vyper/venom/analysis/dfg.py
- vyper/venom/passes/branch_optimization.py
Added a pass to optimize inefficient branches
```
This commit introduces a new pass called `BranchOptimizationPass` 
that optimizes inefficient branches.
More specifically, when a branch is led with a logic inversion `ISZERO` 
we remove the `ISZERO` and invert the branch targets.
```
```
/\_/\  
( o.o ) 
> ^ <   "Please?"
```
> feat[venom]: optimize branching

- tests/functional/codegen/test_call_graph_stability.py
the call graph stability fuzzer could generate an internal function named `foo()`, which is the same name as the entry function in the test contract.
fix https://github.com/vyperlang/vyper/issues/4061
> fix[test]: fix fuzzer test setup failure

- tests/functional/codegen/types/test_dynamic_array.py
- vyper/codegen/context.py
- vyper/codegen/core.py
- vyper/codegen/expr.py
- vyper/codegen/stmt.py
- vyper/semantics/analysis/base.py
fix https://github.com/vyperlang/vyper/issues/4056, which is another make_setter overlap bug
variant of #4037 and https://github.com/vyperlang/vyper/pull/3410
additionally adds an internal assertion to prevent future variants
```
`make_setter` can potentially run into overlap when called from
`dynarray_append`; this commit copies to a temporary intermediate buffer
(as is done in `AnnAssign`) before copying to the destination if the
condition is detected.
this is a variant of the bugs fixed in ad9c10b0b98e2d and 1c8349e867b2b.
this commit also adds a util function to detect overlap, and adds an
assertion directly in `make_setter` so that future variants panic
instead of generating bad code.
```
> fix[codegen]: fix `make_setter` overlap in `dynarray_append`

- vyper/venom/analysis/cfg.py
- vyper/venom/basicblock.py
- vyper/venom/passes/dft.py
- vyper/venom/passes/remove_unused_variables.py
- vyper/venom/venom_to_assembly.py
```
`create` and `create2` are volatile instructions that were missing. the
other ones were already handled by the case for `output is None` in
`removed_unused_variables`.
misc:
- rename `volatile` to `is_volatile` for uniformity
- use `is_bb_terminator` instead of `in BB_TERMINATORS`
```
> fix[venom]: fix list of volatile instructions

- vyper/venom/__init__.py
- vyper/venom/passes/extract_literals.py
extract IRLiterals which are instruction arguments; this reduces pressure on the stack scheduler
not *sure* that this is a good idea, but empirically it seems to work. for example, CurveStableSwapNG-0.4.0.vy goes from from 21849 to 21645 (204 bytes, i.e. 1%)
```
extract `IRLiterals` which are instruction arguments; this reduces
pressure on the stack scheduler because `_emit_input_operands` can cause
stack storms when we hit `_stack_reorder`. by extracting them, we allow
`DFTPass` to reorder literal emission in a more optimized way before
even getting to `_emit_input_operands`
```
> feat[venom]: add `extract_literals` pass

- docs/using-modules.rst
```
- update technical notes in using modules (reference the VIP)
- note about linearization check
- exports of interfaces
```
> feat[docs]: add more detail to modules docs

- tests/functional/syntax/exceptions/test_instantiation_exception.py
- vyper/semantics/types/module.py
prevent modules being initialized as storage variables.
> fix[lang]: prevent modules as storage variables

- tests/functional/syntax/modules/test_initializers.py
- vyper/semantics/analysis/global_.py
the hint is bad because the invalid `uses:` statement might not be in the main contract.
> fix[lang]: fix a hint in global initializer check

- vyper/compiler/output_bundle.py
```
vyper will accept either `"*"` or `["*"]` for `outputSelection`, but
some verifiers expect it to always be a list. make `solc_json` output
choose the common formatting.
```
> fix[tool]: star option in `outputSelection`

- tests/functional/syntax/test_for_range.py
- vyper/venom/ir_node_to_venom.py
```
loop invariant bound check was in the body of the loop, not the entry
block. move it up to the entry so we don't re-check the same assertion
every loop iteration.
```
> fix[venom]: move loop invariant assertion to entry block

- tests/functional/builtins/codegen/test_abi_decode_fuzz.py
- vyper/semantics/types/user.py
```
fuzz with `unwrap_tuple=False`
add fuzzing for structs
follow up to 69e5c0541a9b23
```
> feat[test]: add more coverage to `abi_decode` fuzzer tests

- vyper/venom/ir_node_to_venom.py
```
this commit fixes an `ir_node_to_venom` translation bug. when there is
a default argument to an external function, it can generate multiple
allocas, because the entry points allocate separate symbol tables, but
actually they should all correspond to the same alloca. for instance,
`external 1 foo(uint256)12345` and `external 1 foo()67890` both feed
into the same `external 1 foo()__common`, but the current translator
mistakenly creates different symbol tables for the two "feeder" entry
points, resulting in separate allocas for the same logical variable.
this commit fixes the bug by fusing the symbol tables for multiple
entry points to the same external function.
```
> fix[venom]: alloca for default arguments

- vyper/codegen/ir_node.py
- vyper/venom/ir_node_to_venom.py
fix https://github.com/vyperlang/vyper/issues/4072
```
when `-Onone` is specified along with `--experimental-codegen`,
the unique symbols check does not get run. this calculates the
`ir_node.unique_symbols` property, which implicitly runs the unique
symbols check.
also, change an assertion to a proper panic exception
```
> fix[venom]: add `unique_symbols` check to venom pipeline

- docs/built-in-functions.rst
```
some builtins have undefined order of evaluation of arguments; make a
note in the docs
```
> chore[docs]: add evaluation order warning for builtins

- tests/functional/builtins/codegen/test_extract32.py
- tests/functional/builtins/codegen/test_slice.py
- vyper/builtins/functions.py
alternative to https://github.com/vyperlang/vyper/pull/4156; panic instead of changing codegen
```
`extract32()` and `slice()` have an evaluation order issue when
the arguments touch the same data. specifically, the length and data
evaluation are interleaved with the index/start/length evaluations. in
unusual situations (such as those in the included test cases), this
can result in "invalid" reads where the data and length reads appear
out of order. this commit conservatively blocks compilation if the
preconditions for the interleaved evaluation are detected.
---------
Co-authored-by: trocher <trooocher@proton.me>
Co-authored-by: cyberthirst <cyberthirst.eth@gmail.com>
```
> fix[codegen]: panic on potential eval order issue for some builtins

- tests/functional/grammar/test_grammar.py
Fix a type check warning reported by Pyre@Google, which was outdated after code modifications.
update the return type of function `fix_terminal` from `bool` to `str`, since it could be `str` after commit https://github.com/vyperlang/vyper/commit/176e7f7f3a6a16bc09ec58d4bbc8dc515c48a0a8
> chore[test]: fix a type hint

- tests/unit/compiler/venom/test_algebraic_optimizer.py
- vyper/venom/passes/algebraic_optimization.py
- vyper/venom/passes/extract_literals.py
- vyper/venom/venom_to_assembly.py
Created offset handling for statically resolvable values 
I introduced `offset` instruction that is emited in algebraic pass when the `add` instruction calculates offset with literal values
Created new test in algebraic pass tests 
```
this commit introduces an `offset` instruction that is emitted in the
algebraic pass when the add instruction calculates an offset from a
code label, which is used for immutables. this allows compilation
directly to the magic `OFST` assembly instruction, which does
additional constant folding after symbol resolution.
```
> feat[venom]: offset instruction

- vyper/cli/vyper_compile.py
remove the experimental note in:
```
--evm-version {istanbul,berlin,london,paris,shanghai,cancun}
Select desired EVM version (default shanghai). note: cancun support is EXPERIMENTAL
```
respective code was properly audited
> chore[docs]: remove experimental note for cancun

- tests/functional/syntax/test_interfaces.py
- vyper/semantics/types/function.py
- make interface body stricter to only allow exprs
- fix https://github.com/vyperlang/vyper/issues/4122
- added both a failing and passing tests
````
previously the validation for function bodies in interfaces incorrectly
allowed other types of expressions with the `.value` member, e.g.
```vyper
@external
def some_interface_function():
return ...
```
although the body should only be allowed to be an ellipsis expr (`...`).
this commit correctly rejects the above source code
````
> fix[lang]: fix `.vyi` function body check

- tests/functional/syntax/exceptions/test_constancy_exception.py
- vyper/builtins/functions.py
- fix: https://github.com/vyperlang/vyper/issues/4112
- added tests for pure and view func
> fix[lang]: add `raw_log` constancy check

- tests/functional/codegen/test_interfaces.py
- tests/functional/syntax/test_interfaces.py
- vyper/semantics/analysis/module.py
- vyper/semantics/types/function.py
- vyper/semantics/types/module.py
- as per https://github.com/vyperlang/vyper/issues/4169#issuecomment-2203672462: make `@external` visibility in `vyi` files optional
- also should fix: https://github.com/vyperlang/vyper/issues/4169
- added some tests
```
make `@external` visibility in `.vyi` files optional.
additionally, fix a panic when functions in an interface have the wrong
visibility
```
edit: linked wrong issue
> feat[lang]!: make `@external` modifier optional in `.vyi` files

- vyper/codegen/external_call.py
- fix https://github.com/vyperlang/vyper/issues/4188
```
fix the buffer size passed to the abi encoder from the external call
argument packer. previously, the size was overestimated as it didn't
take into account pointer arithmetic performed on the buffer passed to
abi_encode.
this is a hygienic fix, no security implications were found for this
issue.
```
> fix[codegen]: fix `abi_encode` buffer size in external calls

- tests/unit/semantics/analysis/test_cyclic_function_calls.py
- vyper/builtins/functions.py
- vyper/semantics/analysis/module.py
- fix: https://github.com/vyperlang/vyper/issues/4194
- check if the func called is the func itself
- added test
```
fix cycle detection in `_compute_reachable_set()` by adding a check for
subcycles in the current call path
the function was detecting cycles by checking for a cyclic call to the
*root* of the call path
if the cycle was within the call path (excluding the root) it could
fall into infinite recursion
```
> fix[lang]: fix panic in call cycle detection

- tests/functional/syntax/test_external_calls.py
- vyper/semantics/types/module.py
this doesn't affect anything in vyper codebase, but affects the serialization of interface types for tooling (including titanoboa)
> fix[tool]: update `InterfaceT.__str__` implementation

- vyper/ast/nodes.py
```
fix classification of some AST nodes for proper type checking.
this is a hygienic fix, it should have no observable semantic changes.
```
> fix[tool]: fix classification of AST nodes

- SECURITY.md
> feat[docs]: add bug bounty program to security policy

- tests/unit/ast/nodes/test_hex.py
- vyper/ast/nodes.py
```
improve the error message when a hex literal starts with `0X`. it is
accepted by the parser, but prior to this commit, would result in a
compiler panic. this commit validates the literal and provides a proper
error message.
```
> fix[ux]: improve error message for bad hex literals

- vyper/utils.py
improve time spent in venom by 25%
dict views support set operations, https://docs.python.org/3/library/stdtypes.html#dict-views
check `time vyper --optimize none` vs `time vyper --experimental-codegen --optimize none` for a large-ish vyper contract
```
improve time spent in venom by 25%
dict views support set operations, which allows us to loop, using
`&=`. since our intersections are typically not between a large number
of OrderedSets, this results in faster execution time.
references:
- https://docs.python.org/3/library/stdtypes.html#dict-views
```
> perf[venom]: improve OrderedSet operations

- vyper/venom/basicblock.py
Cleaned up the `VOLATILE_INSTRUCTIONS` from duplicates 
```
Remove duplicate `assert`, `assert_unreachable` from `VOLATILE_INSTRUCTIONS` dictionary
```
> fix[venom]: remove duplicate volatile instructions

- docs/installing-vyper.rst
- Add binaries to the documentation
- Show pip before docker, as it might be more common and easier to install
- Update python requirement
N/A
N/A
```
- Add instructions to install the binaries from github releases to the
documentation
- Show pip before docker, as it might be more common and easier to
install
- Update python requirement in the installation docs
```
N/A
> chore[docs]: add binary installation methods

- tests/integration/test_pickle_ast.py
- vyper/semantics/analysis/base.py
fix a bug where unpickling `annotated_vyper_module` would lead to a crash:
```
AttributeError: 'VarAccess' object has no attribute 'variable'
```
a repro can be found at https://github.com/charles-cooper/vyper/commit/2a5facf43ffb08b66f76d3d2b16b8f72f22d0625.
this is a blocker for tooling, for instance titanoboa relies on pickle/unpickle to cache CompilerData objects:
https://github.com/vyperlang/titanoboa/blob/86df8936654db20686410488738d7abaf165a4c9/boa/util/disk_cache.py#L65-L66
the underlying issue is that `pickle.loads()` calls `obj.__hash__()` for objects that are keys in a hashed data structure - namely, dicts, sets and frozensets. this causes a crash when there is a cycle in the object graph, because the object is not fully instantiated at the time that `__hash__()` is called. this …
> fix[tool]: update VarAccess pickle implementation

- tests/functional/syntax/test_interfaces.py
- vyper/semantics/analysis/imports.py
fix a bug where imports inside of interfaces are not recursed into in the import resolution pass. this is a regression in 6843e7915729f3a3ea0d8c765dffa52033f5818e.
> fix[lang]: fix recursive interface imports

- tests/functional/codegen/features/test_clampers.py
- was running some tests against ivy and found these failing in ivy (but ivy reported the true reason of the failure)
```
was running some tests against ivy and found these failing in ivy (but
ivy reported the true reason of the failure)
```
> fix[test]: fix some clamper tests

- .github/workflows/build.yml
- .github/workflows/release-pypi.yml
fix https://github.com/vyperlang/vyper/issues/4308
````
there is a mismatch between the commit hash in the binary of the github
release vs the pypi release. for example,
```bash
~ $ vyper --version  # pipx install vyper==0.4.0
0.4.0+commit.e9db8d9
```
```bash
~ $ .vvm/vyper-0.4.0 --version
0.4.0+commit.e9db8d9f
```
this is due to how git computes the shorthash. when checkout is run for
release-pypi.yml, it doesn't fetch the full commit history, and so there
are fewer commits, so `git rev-parse --short HEAD` returns a smaller
fingerprint for the commit hash.
this commit amends the pypi release checkout step so that it matches the
github release workflow.
it also adds a debug step to the relevant workflows so that we can debug
the commit hash during the github action.
````
> fix[ci]: fix commithash calculation for pypi release

- vyper/venom/analysis/dfg.py
- vyper/venom/passes/sccp/sccp.py
used DFGAnalysis in SCCP instead of the computing the uses in the SCCP itself
Remove computation from the SCCP and added DFG analysis into it and changed the DFG analysis so it uses OrderedSet
```
use `DFGAnalysis` in `SCCP` instead of duplicating the logic to compute
uses in the `SCCP` itself. also use `OrderedSet` for var uses, this
ensures we don't add the same instruction multiple times (as in `add
%2 %2`) to a var's use set, and also enables a cheaper `remove_use()`
implementation.
```
> refactor[venom]: refactor sccp pass to use dfg

- vyper/venom/README.md
Documents venom IR instructions.
```
expand venom docs. document venom instructions and structure of a venom
program.
```
> chore[venom]: expand venom docs

- vyper/venom/function.py
- vyper/venom/ir_node_to_venom.py
this commit updates `ir_node_to_venom.py` for the `deploy` instruction to properly emit the `exit` instruction. it also removes places in the translator where the `exit` instruction was improperly emitted.
misc:
- update style to continue early in the loop rather than nest.
fix #4317 
> refactor[venom]: update translator for deploy instruction

- vyper/codegen/ir_node.py
reduce legacy IR optimization when venom is enabled. the use of `IRnode._optimized` was there to decide if it was safe to inline an IRnode expression or it required a `with` statement; with venom, we don't need to inline the expressions, since the venom optimizer is more powerful. this leads to a 50% improvement in AST -> IRnode generation, which is a ~15% performance improvement in overall end-to-end compile time.
run `vyper --experimental-codegen` and compare bytecode against master. should be the same.
> feat[venom]: reduce legacy opts when venom is enabled

- tests/unit/ast/test_pre_parser.py
- tests/unit/cli/vyper_json/test_compile_json.py
- vyper/ast/pre_parser.py
- vyper/cli/vyper_compile.py
- vyper/cli/vyper_json.py
- vyper/compiler/settings.py
Make a "venom" alias to "experimental_codegen" flag.
See https://github.com/vyperlang/vyper/issues/4334.
Add the alias to cli, pre-parser, and json parser.
All exisiting tests work with old flas as well as new tests with `venom`.
```
Make "venom" an alternative alias to the "experimental_codegen" flag.
Add the alias to cli, pre-parser, and json parser.
```
> refactor[ux]: add `venom` as `experimental-codegen` alias

- setup.py
testing CI
fixes a blocker in https://github.com/vyperlang/vyper/pull/4342
```
the call to `setup()` would fail on windows when there are unicode
characters in `README.md`, because files are apparently opened with
encoding `cp1252` by default on windows. this commit ensures the file
is opened with `utf-8` encoding.
```
> fix[ci]: fix README encoding in `setup.py`

- tests/unit/compiler/venom/test_branch_optimizer.py
- vyper/venom/passes/branch_optimization.py
```
this is a step towards making the cfg traversal order more "stack
aware". previously we would blindly try to remove `iszero` instructions
before a `jnz`. now, the heuristic is based on which basic block
has a smaller sized dependency on this basic block. only if the two
cfg_out blocks have the same sized dependency, then we try to remove
the iszero.
this creates a slight improvement to codesize due to fewer stack
operations at `jnz` boundaries.
```
> feat[venom]: make cfg scheduler "stack aware"

- tests/functional/codegen/features/test_constructor.py
- tests/functional/codegen/types/test_dynamic_array.py
- tests/unit/compiler/venom/test_branch_optimizer.py
- tests/unit/compiler/venom/test_sccp.py
- vyper/venom/analysis/cfg.py
- vyper/venom/analysis/dominators.py
- vyper/venom/analysis/liveness.py
- vyper/venom/basicblock.py
- vyper/venom/function.py
- vyper/venom/passes/sccp/sccp.py
- vyper/venom/passes/simplify_cfg.py
- vyper/venom/venom_to_assembly.py
move dfs order calculation from domtree to cfg analysis.
remove unnecessary calculation of domtree in sccp
remove redundant `IRFunction.compute_reachability`
change cfg_out order
refactor shared phi fixup code
```
feat[venom]: improve liveness computation
traversing in reverse topsort order improves stack scheduling slightly
this commit also adds a topsort method to CFGAnalysis, and speeds it up
by only checking the terminator instruction instead of iterating over
all the instructions in every basic block.
additional refactors:
- move dfs order calculation from domtree to cfg analysis.
- remove unnecessary calculation of domtree in sccp
- remove redundant IRFunction.compute_reachability
- change cfg_out order
- refactor shared phi fixup code
- remove useless `__eq__()` and `__hash__()` …
```
> feat[venom]: improve liveness computation

- docs/built-in-functions.rst
This PR adds the missing `method_id` parameter to the function signature of `abi_encode` in the documentation.
Skills.
Brain.
```
this commit adds the missing `method_id` parameter to the
function signature of `abi_encode` in the documentation
```
docs[chore]: add `method_id` to function signature of `abi_encode`
> chore[docs]: add `method_id` to `abi_encode` signature

- vyper/venom/passes/sccp/sccp.py
Small optimization of the lattice evaluation method, along with some dead code removal.
```
this commit improves the `_eval()` method in the SCCP pass by trying
to return early when possible and avoid unnecessary set operations. it
also performs some minor code clean up and dead code removal.
```
> refactor[venom]: optimize lattice evaluation

- docs/compiling-a-contract.rst
- docs/structure-of-a-contract.rst
- vyper/cli/vyper_compile.py
- vyper/venom/README.md
Add one sentence about `--venom` and the corresponding pragma.
```
add some notes to the relevant docs that `venom` is an alias for
`experimental-codegen`
```
> chore[docs]: mention the `--venom` flag in venom docs

- vyper/cli/compile_archive.py
- vyper/compiler/__init__.py
- vyper/compiler/phases.py
```
refactor `compile_from_zip()`, and also a generalized
`outputs_from_compiler_data()` so the user can pass a `CompilerData`
instead of `FileInput` + a bunch of settings.
```
> refactor[tool]: refactor `compile_from_zip()`

- vyper/venom/effects.py
per title -- effects.py was missing extcodesize and extcodehash effects.
> fix[venom]: add missing extcodesize+hash effects

- .github/workflows/test.yml
- setup.py
This PR enables Python [`3.13`](https://docs.python.org/3/whatsnew/3.13.html)-based tests in the CI pipeline.
Upgrade the CI test file and `setup.py`.
All tests should successfully pass.
```
enable Python `3.13`-based tests in the CI pipeline.
```
chore[ci]: enable Python [`3.13`](https://docs.python.org/3/whatsnew/3.13.html)-based tests in the CI pipeline.
> chore[ci]: enable Python `3.13` tests

- tests/functional/codegen/types/numbers/test_exponents.py
- vyper/semantics/analysis/utils.py
- vyper/semantics/types/primitives.py
Fix #4383 
Catch `OverflowException` when finding possible types for `BinOp` node.
See test.
```
this commit fixes a false positive for integer overflow in
the typechecker involving nested pow operations by filtering
`OverflowException` in `_validate_op`. the previous code assumed that
`validate_numeric_op` could throw anything besides `InvalidOperation`,
but for the `Pow` binop, it can throw `OverflowException`.
```
> fix[ux]: fix false positive for overflow in type checker

- tests/functional/venom/parser/test_parsing.py
- tests/unit/compiler/venom/test_simplify_cfg.py
- tests/venom_utils.py
- vyper/venom/basicblock.py
- vyper/venom/parser.py
refactor venom tests with new parsing machinery. it should make tests easier to read. add an example of the new testing style
```
refactor venom tests with new parsing machinery. it should make tests
easier to read. refactor `test_simplify_cfg.py` as an example of the
new testing style
additionally add some parser / text format fixes:
- switch order of operands in `phi` text format
- fix `jnz` parsing to match `IRInstruction.__repr__()`
- add comments to venom grammar (`;` indicates a comment a la llvm)
- make data section optional
- fix grammar rule: expr can be any operand.
```
> refactor[venom]: add new venom test machinery

- vyper/venom/parser.py
Implemented alphanumeric variables, and source code comments
```
This commit implements minor improvements to the venom parser. 
Specifically it allows for alphanumeric variable names, and for single 
line source code comments in various styles: ";" "#" and "//"
```
> feat[venom]: allow alphanumeric variables and source comments

- vyper/utils.py
add two new profiling utils, `profileit()` and `cumtimeit()` which run cProfile and printout cumulative time spent in a context, respectively.
the functions both return a context manager, so it can be used both in a with statement or as a function decorator, e.g.:
```python
@profileit()
def foo():
...
@cumtimeit("foo")
def foo():
...
```
in a with statement
```
with profileit():
foo()
with cumtimeit("foo"):
foo()
```
neither of these should be used except for in local dev work, so they are ignored in coverage, and a warning is printed out if they are used as a reminder to remove them before pushing.
Commit message for the final, squashed PR. (Optional, but reviewers will appreciate it! Please see [our commit message style guide](../../master/docs/style-guide.rst#best-practices-1) for what …
> refactor[codegen]: add profiling utils

- tests/unit/compiler/venom/test_memmerging.py
- vyper/venom/__init__.py
- vyper/venom/effects.py
- vyper/venom/ir_node_to_venom.py
- vyper/venom/passes/__init__.py
- vyper/venom/passes/lower_dload.py
- vyper/venom/passes/memmerging.py
- vyper/venom/venom_to_assembly.py
```
this commit propagates `dload` instructions to venom from the frontend.
this improves our ability to merge `dload/mstore` instructions. then,
after the LowerDload pass, we have stripped both `dload` and
`dloadbytes` instructions from venom.
```
> feat[venom]: propagate `dload` instruction to venom

- vyper/venom/__init__.py
- vyper/venom/passes/store_elimination.py
```
remove special cases in store elimination, allowing elimination of
`%ret_ofst` and `%ret_size` store chains. this was previously to
protect correctness in `mem2var`, but it no longer seems to be needed.
running an additional store elimination before `mem2var` results in a
slight bytecode size improvement, since it allows more memory locations
to be promoted to stack variables.
```
> feat[venom]: remove special cases in store elimination

- tests/functional/venom/parser/test_parsing.py
- tests/functional/venom/test_venom_repr.py
- tests/venom_utils.py
- vyper/venom/basicblock.py
- vyper/venom/context.py
- vyper/venom/function.py
- vyper/venom/ir_node_to_venom.py
- vyper/venom/parser.py
- vyper/venom/passes/normalization.py
- vyper/venom/venom_to_assembly.py
add cases for raw bytes (which are generated by `--optimize codesize`) in data section. update parser to parse the new text format. refactor internal representation of data section to not use IRInstruction. remove xfail from previously passing test cases. tweak IRFunction repr to add the function name at close (helpful for debugging).
this is a follow on to #4402.
````
this commit updates the parser and grammar with new syntax for the data
section. it also adds cases for raw bytes (which are generated by
`--optimize codesize`) in the data section, which are required to
round-trip venom produced in `--optimize codesize` mode.
new format:
```
data readonly {
dbsection foo {
db @label1
db x"abcd"
}
}
```
the new "readonly" modifier doesn't have disambiguating power yet, but
it will make it …
```
> feat[venom]: update text format for data section

- tests/functional/venom/parser/test_parsing.py
- tests/functional/venom/test_venom_repr.py
- tests/unit/compiler/venom/test_make_ssa.py
- vyper/venom/basicblock.py
- vyper/venom/passes/make_ssa.py
Fixed the memssa pass to support already existing `phi` instructions.
```
This commit improves the `MakeSSA` pass to handle incoming `phi`
instructions. Following the implementation of the venom parser it
is possible to parse code with existing `phi` instructions in the
code. The old code was expecting the `phi` instructions to have
been self-placed and in "degenerate form" of output == all branch
arguments. The new code does not make this assumption.
This commit additionally:
- refactors the existing `make_ssa` tests to use new test machinery
- adds a phi parsing test (does not test the new code in this commit
since it does not run passes, but does make sure we can at least parse
phis)
- expands the venom round-trip tests to check that we can both
a) run venom passes on parsed venom, and …
```
> fix[venom]: fix `MakeSSA` with existing phis

- vyper/venom/passes/mem2var.py
remove special cases which were necessary before introduction of palloca. now they represent useless variable read/writes which are safe to remove. results in removal of a few instructions on benchmark contracts.
additionally some style-related refactors
> refactor[venom]: refactor mem2var

- docs/control-structures.rst
Resolves #37584of [Attackathon | Ethereum Protocol](https://immunefi.com/bounty/ethereum-protocol-attackathon). Add a note to clarify that `nonpayable` `internal` functions can be called via `external` `payable` functions.
Brain.
Skills.
```
this commit adds a note to clarify that `nonpayable` `internal`
functions can be called via `external` `payable` functions.
```
Add a note to clarify that `nonpayable` `internal` functions can be called via `external` `payable` functions.
> chore[docs]: `nonpayable` `internal` function behaviour

- docs/control-structures.rst
- docs/interfaces.rst
Resolves #37634 of [Attackathon | Ethereum Protocol](https://immunefi.com/bounty/ethereum-protocol-attackathon). Add a note on how the function signature is calculated if default arguments are used.
Brain.
Check function signatures.
```
this commit adds a note on how the function selector is calculated if
default arguments are used.
```
Add a note on how the function signature is calculated if default arguments are used.
> chore[docs]: abi function signature for default arguments

- tests/ast_utils.py
- tests/unit/ast/nodes/test_binary.py
- tests/unit/ast/nodes/test_compare_nodes.py
- tests/unit/ast/test_ast_dict.py
- tests/unit/ast/test_parser.py
- vyper/ast/nodes.py
- vyper/semantics/analysis/imports.py
it is a performance and correctness footgun for the hash and eq implementations to recurse. for instance, two nodes from different source files should never compare equal (you can use deepequals to signal intention there).
i refactored the test suite by temporarily overriding the `__ne__` implementation for VyperNode so that we can find all the `!=` uses in the tests. the CI for this commit (https://github.com/vyperlang/vyper/pull/4433/commits/0a9830b4403f301067d7a59b62b3bb1ffe984dc1) passes (run https://github.com/vyperlang/vyper/actions/runs/12574333551/), and the training wheels are taken off in commit https://github.com/vyperlang/vyper/pull/4433/commits/71726ad7bf3626461e6b756fc1345d9ac837b9f1.
```
it is a performance and correctness footgun for `VyperNode`'s hash and
eq …
```
> refactor[lang]: remove VyperNode `__hash__()` and `__eq__()` implementations

- .github/workflows/build.yml
Fix #4441.
```
This commit bumps the upload-artifact action to v4 because
v3 will be deprecated on 30 Jan 2025.
```
Bump upload-artifact action to v4
> chore[ci]: bump upload-artifact action to v4

- .github/workflows/test.yml
- setup.cfg
Consolidate code coverage files and upload it once.
```
This commit updates the CI to combine code coverage to a single file
and perform just a single upload after all tests finish (rather than
each test run uploading its own coverage report). This should reduce
failures / rate limiting on the codecov app, and also prevent the
codecov app from producing an inaccurate coverage report before all
the tests finish.
references:
- https://coverage.readthedocs.io/en/7.6.10/cmd.html#cmd-combine
- https://coverage.readthedocs.io/en/7.6.10/cmd.html#re-mapping-paths
- https://coverage.readthedocs.io/en/7.6.10/config.html#config-run-relative-files
```
> feat[ci]: use `coverage combine` to reduce codecov uploads

- tests/functional/builtins/codegen/test_ecrecover.py
- tests/functional/codegen/types/test_dynamic_array.py
- tests/functional/codegen/types/test_lists.py
- tests/functional/codegen/types/test_string.py
- tests/utils.py
- vyper/builtins/functions.py
- vyper/codegen/core.py
fix for https://github.com/vyperlang/vyper/security/advisories/GHSA-vgf2-gvx8-xwc3
```
this commit fixes a flaw in code generation for certain
precompiles. specifically, some calls to the ecrecover (0x01) and
identity (0x04) precompiles were not checked for success.
in 93a957947af1088addc, the assert for memory copying calls to the
identity precompile was optimized out; the reasoning being that if the
identity precompile fails due to OOG, the contract would also likely
fail with OOG. however, due to the 63/64ths rule, there are cases where
just enough gas was supplied to the current call context so that the
subcall to the precompile could fail with OOG, but the contract has
enough gas to continue execution after it shouldn't (which is undefined
behavior) and then successfully return out …
```
> fix[codegen]: fix assertions for certain precompiles

- .github/workflows/test.yml
```
this commit separates `coverage combine` (the local tool) and codecov
upload (upload to 3rd party app) into separate steps. it also uploads
the coverage report artifacts. this makes the actions more transparent
since we can download the coverage database to inspect it if there is
an issue, and allows us to set the `coverage report` as a required CI
check, which does not depend on a 3rd party service. (if it depended on
a 3rd party service, we might then be unable to merge PRs if there is
an issue on the 3rd party service's side).
```
> chore[ci]: separate codecov upload into separate job

- .github/workflows/test.yml
Minor improvements to coverage CI:
1. Consolidate upload of coverage artifacts into a single step
2. Change `file` to `files` for `codecov-action@v5`
```
This commit makes minor improvements to the coverage CI:
1. Consolidate upload of coverage artifacts into a single step
2. Change `file` field to `files` for `codecov-action@v5`
references:
- https://github.com/codecov/codecov-action?tab=readme-ov-file#migration-guide
```
> chore[ci]: improve coverage jobs

- vyper/venom/basicblock.py
- vyper/venom/passes/sccp/sccp.py
> refactor[venom]: add `make_nop()` helper function

- .github/workflows/build.yml
per https://github.com/actions/runner-images/issues/11101, the ubuntu-20.04 image will start to be phased out next month. update the image to `ubuntu-latest` so we don't have to manually update anymore.
> chore[ci]: update ubuntu image for `build` job

- tests/unit/compiler/venom/test_memmerging.py
- vyper/venom/basicblock.py
- vyper/venom/passes/memmerging.py
- vyper/venom/passes/remove_unused_variables.py
this is slightly cleaner, since we don't need to remember to call `bb.clear_dead_instructions()` after `mark_for_removal()`, instead they will all be removed in one go whenever `RemoveUnusedVariablesPass` runs.
> refactor[venom]: replace `bb.mark_for_removal` with `make_nop`

- vyper/builtins/functions.py
- vyper/codegen/expr.py
```
historically, the schema generated internally by the `print()` builtin
was not allowed to be larger than 32 bytes, ostensibly to simplify the
code for generating the IR, leading to a panic if the user tried to
print a sufficiently complex type (i.e. with an ABI type larger than
32 bytes).
this commit replaces the code for generating the schema in IR with
`Expr._make_bytelike` (along with a small refactor for `_make_bytelike`
to make it a classmethod instead of an instance method), generalizing
to schemas of any size.
```
> fix[lang]: allow `print()` schema larger than 32 bytes

- tests/functional/codegen/features/iteration/test_for_in_list.py
- vyper/codegen/core.py
- vyper/codegen/stmt.py
fix #4461 
```
the check in `_parse_For_list` is wrong when the iter is a constant
(since the check is syntactic). the fix is to check the `is_literal`
property on the generated IR.
```
> fix[codegen]: fix iteration over constant literals

- docs/compiling-a-contract.rst
- tests/unit/ast/test_tokenizer.py
- tests/unit/cli/vyper_compile/test_parse_args.py
- tests/unit/compiler/test_compile_code.py
- vyper/ast/natspec.py
- vyper/ast/nodes.py
- vyper/ast/parse.py
- vyper/ast/pre_parser.py
- vyper/builtins/functions.py
- vyper/cli/vyper_compile.py
- vyper/cli/vyper_json.py
- vyper/codegen/expr.py
- vyper/compiler/output.py
- vyper/compiler/phases.py
- vyper/compiler/settings.py
- vyper/semantics/types/function.py
- vyper/semantics/types/subscriptable.py
- vyper/semantics/types/user.py
- vyper/utils.py
- vyper/warnings.py
```
this commit adds `-Werror` and `-Wnone` CLI flags which promote
warnings to errors and ignore them, respectively.
also adds some small refactoring for warning handling to simplify the
implementation (allow us to use warnings.simplefilter). this provides
a way moving forward to do fine-grained warnings control, since the
warnings filter allows us to use the exception class in the filter.
```
> feat[tool]: add `-Werror` and `-Wnone` options

- vyper/codegen/ir_node.py
- vyper/codegen/stmt.py
cd318676a0b7bcb (#4462) introduces a gas regression, which is that `IRnode.is_literal` evaluates to true even for pointers (which are not source-level literals). this commit changes the condition to be `not .is_pointer`, which should be the correct condition for needing to strictify into memory.
thanks to @pcaversaccio for spotting!
> fix[codegen]: fix gas usage of iterators

- docs/built-in-functions.rst
- tests/functional/codegen/types/numbers/test_sqrt.py
- vyper/builtins/functions.py
fix for https://github.com/vyperlang/vyper/security/advisories/GHSA-2p94-8669-xg86
prior to this PR, the rounding mode for `sqrt()` is undefined. this PR ensures the result is rounded down.
```
prior to this commit, the rounding mode for `sqrt()` is undefined,
which could be an issue for applications which use `sqrt()` to
determine boundary conditions. this commit ensures the result is
rounded down.
```
> fix[lang]: define rounding mode for sqrt

- .github/workflows/build.yml
```
per ae6ab0d3dc58167cc6, the OS image used to build vyper binaries was
updated. however, this can break users who don't have a compatible libc
(i.e., at least as recent as the latest ubuntu). roll back to an older
ubuntu for those users.
```
> fix[tool]: roll back OS used to build binaries

- tests/functional/codegen/features/test_assignment.py
- vyper/codegen/ir_node.py
- vyper/codegen/stmt.py
- vyper/semantics/analysis/base.py
relax the filter in #4487
```
this commit relaxes the filter introduced in dd5a3d9e0f1e8685. the
filter was valid, but blocked too many user programs. this commit
updates the filter so that the external call check is only applied if
there is a state variable on the lhs. it also updates the external call
check to only consider state-modifying calls, since staticcalls cannot
modify the lhs.
```
> fix[codegen]: relax the filter for augassign oob check

- .github/workflows/pull-request.yaml
- README.md
- docs/release-notes.rst
> release[docs]: add release notes for v0.4.1 ("Tokara Habu")

- vyper/venom/basicblock.py
- vyper/venom/passes/make_ssa.py
```
`IRVariable` construction in `MakeSSA` is a hotspot. remove
constructions of `IRVariable`s when possible.
```
> perf[venom]: improve performance of `MakeSSA`

- vyper/venom/function.py
for when the varnames need to be "freshened" up. can be helpful for debugging
```
add a "freshen_varnames" method to IRFunction, which can help debugging
by renaming all variables, restarting from 0.
```
https://www.youtube.com/watch?v=-JfEJq56IwI&t=58s
> feat[venom]: add varname freshener

- docs/interfaces.rst
Fix doc for `skip_contract_check` to make it match the behavior introduced in #4148 
```
fix docs for `skip_contract_check` to make it match the behavior
introduced in cefb0c5166c605bfd
```
fix[docs]: doc for skip_contract_check
> fix[docs]: update `skip_contract_check` docs

- tests/unit/compiler/venom/test_sccp.py
- vyper/venom/passes/sccp/sccp.py
see commit message
see the unit tests
```
this commit fixes SCCP traversal - when a jnz has a truthy condition
that is not equal to 1, it gets transformed to a `jmp`, however, during
lattice construction, both branches are explored and therefore some
phis are suboptimally resolved to BOTTOM, even though they can
theoretically be resolved to a proper value since one of the input bbs
will actually be pruned from the CFG.
this issue is *not* visible in the regular pipeline, since SCCP is run
multiple times and thus the phis get resolved after the second SCCP run.
however, it is visible in tests, and would be visible in the regular
pipeline if SCCP were only run one time.
this commit also removes a `FlowWorkItem` addition, which is redundant
since all the cfg altering instructions are already …
```
> fix[venom]: fix sccp resolution of truthy `jnz`

- vyper/utils.py
- vyper/venom/analysis/dfg.py
- vyper/venom/passes/algebraic_optimization.py
- vyper/venom/passes/base_pass.py
- vyper/venom/passes/dft.py
- vyper/venom/passes/load_elimination.py
- vyper/venom/passes/machinery/inst_updater.py
- vyper/venom/passes/memmerging.py
- vyper/venom/passes/remove_unused_variables.py
- vyper/venom/passes/store_elimination.py
```
move `InstUpdater` to its own file and use it in more passes - it's
safer and faster for passes which use the `dfg` to modify it in place
using `InstUpdater`, rather than modifying instructions (without
updating the `dfg`), and then relying on a stale `dfg`.
```
> refactor[venom]: use `InstUpdater` in more passes

- vyper/venom/README.md
I was playing around with the venom IR parser and ran into issues when using some of the instructions per the README. The current docs has swapped the usage of labels and the vars a few places.
I got a error message which hinted at the issue
```
File "/Users/brage/Downloads/vyper/vyper/venom/analysis/liveness.py", line 90, in input_vars_from
for label, var in inst.phi_operands:
File "/Users/brage/Downloads/vyper/vyper/venom/basicblock.py", line 374, in phi_operands
assert isinstance(label, IRLabel), "phi operand must be a label"
AssertionError: phi operand must be a label
```
Then I ran the following on a Vyper file which would use the phi function to find a reference
```bash
vyper --experimental-codegen -f bb_runtime 
```
It gave out
```
%ret_size:3 = phi @8_then, %ret_size:5, @9_else, …
```
> fix[docs]: fix venom examples

- tests/functional/venom/test_venom_label_variables.py
- vyper/cli/venom_main.py
- vyper/venom/basicblock.py
- vyper/venom/parser.py
- vyper/venom/passes/sccp/sccp.py
- vyper/venom/passes/simplify_cfg.py
```
this commit allows labels to be assigned to variables. it updates
assumptions in `SCCP` and the venom parser which blocked that behavior.
it also updates the text format for `djmp` to be like `jnz` (condition
is first). it also fixes a bug in SimplifyCFG where `merge_jump` did
not rename label operands.
```
> feat[venom]: allow labels to be assigned to variables

- tests/functional/venom/parser/test_parsing.py
- vyper/venom/basicblock.py
- vyper/venom/context.py
- vyper/venom/function.py
- vyper/venom/ir_node_to_venom.py
- vyper/venom/parser.py
- vyper/venom/passes/function_inliner.py
```
this commit makes `revert` a basic block terminator. previously
`revert` was left as a non-terminating instruction since there could
be the possibility of reordering. however, since it terminates, it is
cleaner to disallow any control flow after the `revert` instruction.
it also fixes a minor bug discovered in `ir_node_to_venom`, where the
translator was appending instructions after a `revert` instruction (it
would have been appending them to a dead block in any case).
```
> feat[venom]: make `revert` a bb terminator

- tests/functional/builtins/codegen/test_abi_decode_fuzz.py
as of hypothesis 6.130.0, nesting `@given` is a health check error. we should probably fix this as it is a performance issue in the CI, but for now, just suppress it.
references:
- https://hypothesis.readthedocs.io/en/latest/changes.html#v6-130-0
> fix[ci]: suppress hypothesis health check

- tests/functional/venom/parser/test_parsing.py
- vyper/venom/parser.py
Added hex parsing support to the venom text format parser
```
This commit adds hex parsing support to the venom text format parser
```
> feat[venom]: parse hex literals in text format 

- vyper/venom/passes/simplify_cfg.py
```
remove unreachable code. the `_optimize_empty_basicblocks` was actually
a no-op, since venom doesn't allow empty basic blocks as they are
non-terminated.
```
> refactor[venom]: simplify `SimplifyCFG` pass

- tests/functional/syntax/test_interfaces.py
- vyper/ast/nodes.py
- vyper/semantics/analysis/local.py
Forbid calling `__default__` by `staticcall` and `extcall`. Depends on https://github.com/vyperlang/vyper/pull/4090. 
Edit: Added dependency on the PR.
In `validate` functions check the attribute name if present.
```
This commit forbids `extcall` and `staticcall`s to `__default__`. This
was not possible before the introduction of `__interface__()` and
`__at__()`; however, now that we have the possibility of casting
a module to its interface, it is possible to actually call the
`__default__()` function, which generates a "normal" ABI-encoded
call including the method id for `__default__()`. That could cause a
selector collision with a different function at target, and also leads
to confusing behavior (`__default__` gets called when no selector
matches).
The error message recommends the …
```
> fix[lang]!: forbid calling `__default__`

- vyper/venom/analysis/dominators.py
- vyper/venom/passes/make_ssa.py
Refactored `DominatorTreeAnalysis` to be more clear. Added a dominator post-order traversal property.
```
Refactor `DominatorTreeAnalysis` to be more clear regarding cfg walk
usage. Add a dominator post-order traversal property.
The `MakeSSA` pass is refactored to use dom tree walk instead of CFG
post walk. Traversing based on the dominator tree is not technically
mandatory but it aligns with the algorithm's reliance on dominance and
simplifies the renaming phase.
```
> refactor[venom]: add dom walk property

- tests/functional/builtins/codegen/test_create_functions.py
- vyper/builtins/functions.py
- vyper/codegen/core.py
failed creates now bubble up revert data. fixes https://github.com/vyperlang/vyper/issues/4147
> feat[lang]: bubble up create revertdata

- vyper/ast/pre_parser.py
- vyper/cli/vyper_compile.py
move pragma parsing into its own subroutine
> refactor[parser]: refactor pragma parsing

- tests/functional/codegen/features/iteration/test_for_in_list.py
- vyper/semantics/analysis/local.py
Fix #4549
Add a check that the type derived for a variable list matches the iterator type specified in the for loop annotation.
See new tests.
```
This commit fixes a compiler panic for `for` loops by properly catching
type mismatch between the iterator and target during semantic analysis
```
Typechecking for loop annotation of variable list
> fix[ux]: typechecking for loop annotation of list variable

- vyper/builtins/interfaces/IERC165.vyi
- vyper/builtins/interfaces/IERC20.vyi
- vyper/builtins/interfaces/IERC20Detailed.vyi
- vyper/builtins/interfaces/IERC4626.vyi
- vyper/builtins/interfaces/IERC721.vyi
in interfaces, `@external` is already implicit. also, in error messages, not having the extra line helps with context
particularly in the context of https://github.com/vyperlang/vyper/pull/4359, the `@view` decorator gets cut off without this PR.
> feat[lang]: remove `@external` decorator from builtin interfaces

- tests/functional/syntax/warnings/test_deprecation_warning.py
- vyper/builtins/functions.py
remove the one-warning limit from most builtins, especially deprecation warnings. `breakpoint()` and `print()` are left as exceptions, since those might be peppered into a codebase while debugging, and the compiler does not need to be so verbose
> feat[lang]: remove one-warning limit from builtins

- vyper/compiler/README.md
Hi! I removed a dead link/reference to `GlobalContext` in the compiler README.md. 
[ref in PR](https://github.com/vyperlang/vyper/pull/3663/files#diff-1200582cf27366676cbf49c64aacae00b158be1eaacbd314c5b39c02f1d9d981)
```
remove dead references to `GlobalContext` from the compiler `README.md`
```
> chore[docs]: remove dead link from internal documentation

- tests/functional/syntax/modules/test_module_instantiation.py
- vyper/semantics/types/base.py
- vyper/semantics/types/module.py
- vyper/semantics/types/subscriptable.py
- vyper/semantics/types/user.py
modules could have been instantiated
```
import lib1
struct A:
a: lib1
h: DynArray[A, 5]
```
a further question is whether to refactor location validation - a module can't be instantiated in storage, yet it's possible as shown in the example above. the location check should  also recurse on the subtypes. i'm for refactor as it will help prevent potential future bugs
````
prior to this commit, modules could be added as a struct member,
as below:
```vyper
import lib1
struct A:
a: lib1
h: DynArray[A, 5]
```
this commit blocks the behavior.
````
> fix[lang]: block modules in structs

- tests/functional/codegen/modules/test_stateless_functions.py
- vyper/compiler/input_bundle.py
- vyper/compiler/output_bundle.py
- vyper/semantics/analysis/imports.py
```
commit 1591a1229cf837ccca introduced a regression in snekmate, which is
that imports of the form `from .. import math` are rejected, due to the
assertion that `level == 0` on L299 inside of _load_builtin_import.
this was already a latent bug for several versions, but was not
previously tripped, since the only builtin namespace was `ethereum.ercs`
(and users presumably didn't have modules named `ethereum`).
this commit fixes builtin detection by protecting the builtin check with
an additional requirement that `level == 0` (indicating an absolute
import).
misc/refactor:
- add `from_builtin` property on FileInputs that come from the builtin
loader
```
> fix[lang]: only reserve builtins at the top level

- vyper/venom/basicblock.py
this commit tunes the function inliner by assigning `param` and `ret` instructions a cost of 0 (in fact, they should probably have negative cost, since those only have cost in the call convention overhead, but when inlined, they disappear).
> feat[venom]: tune function inliner

- tests/unit/compiler/test_source_map.py
- tests/unit/compiler/venom/test_revert_to_assert.py
- vyper/venom/__init__.py
- vyper/venom/passes/__init__.py
- vyper/venom/passes/revert_to_assert.py
this pass adds a revert-to-assert pass, which detects patterns where we `jnz` into a block which simply does `revert 0, 0`, and optimizes that into an `assert`, which is better for instruction reordering.
> feat[venom]: add assert optimizer

- vyper/venom/passes/revert_to_assert.py
the revert-to-assert pass should invalidate the dfg. since cfg invalidation already invalidates the dfg, this commit is just for hygiene.
> fix[venom]: revert-to-assert should invalidate dfg

- setup.py
- vyper/__init__.py
- vyper/utils.py
since we have `pycryptodome` as a requirement, the sha3 import is dead. additionally, pysha3 is no longer maintained.
```
since we have `pycryptodome` as a requirement, the `sha3` import is
dead.  additionally, `pysha3` is no longer maintained.
`importlib.metadata` is no longer provisional as of Python3.10, so we
can remove the backported version.
```
> chore[lang]: remove `sha3` and `importlib_metadata` imports

- setup.py
```
`poetry` depends on a higher version of `packaging`. relax the version
bounds
remove upper bound since packaging uses calendar versioning
```
> chore[tool]: widen version bounds for `packaging`

- setup.py
```
Allow using asttokens 3.0.0 which was released last year.
```
> chore[tool]: widen version bounds for `asttokens`

- tests/unit/compiler/venom/test_venom_to_assembly.py
- vyper/venom/venom_to_assembly.py
````
previously, params were handled one at a time. however, steps 4 and 6
could `POP` or `SWAP` the params while traversing the param list, which
is invalid since the stack is in an invalid state. for example,
```llvm
function foo {
%1 = param  ; dead variable
; --> POP inserted here! <--
%2 = param
%3 = param  ; %3 is scheduled before %2
; --> SWAP inserted here! <--
%4 = param
mstore %4, %3
ret %2
}
```
this was previously not visible because of how `ir_node_to_venom`
generates params; they are very well-behaved (always live, and always
with the same scheduling).
````
> fix[venom]: fix handling of params in `venom_to_assembly`

- docs/statements.rst
- address: https://github.com/vyperlang/vyper/issues/4464#issuecomment-2607668271
> feat[docs]: document order of evalution of arguments of `log` 

- tests/unit/cli/storage_layout/test_storage_layout.py
- tests/unit/cli/storage_layout/test_storage_layout_overrides.py
- vyper/semantics/analysis/data_positions.py
- address https://github.com/vyperlang/vyper/issues/4612
- included also getter definitions when iterating over functions during exports
```
this commit fixes storage layout exports when pragma nonreentrancy is
on for getters (which were not being included in the layout).
```
- added relevant tests
> fix[tool]: fix layout export with nonreentrancy pragma on

- tests/functional/syntax/test_getters.py
- vyper/ast/nodes.py
- address: https://github.com/vyperlang/vyper/issues/4610
```
state variables with getters can currently compile with
duplicate `public` or `reentrant` annotations, e.g.
`x: public(public(uint256))`. this commit blocks the behavior.
it also adds test cases for this behavior, as well as analogous test
cases for `immutable` and the other location annotations (which are
correctly blocked, but good to have the tests as well).
```
- added tests
> fix[lang]: disallow duplicate getter annotations

- docs/control-structures.rst
- setup.cfg
- tests/functional/codegen/features/decorators/test_nonreentrant.py
- vyper/semantics/analysis/getters.py
```
the nonreentrancy pragma enables reentrancy protection for all
public entrypoints, including immutable and constant getters. however
`immutable` and `constant` variables can't change after deployment, and
thus can't lead to issues due to read-only-reentrancy. thus, checking
the lock is undesirable (in other words, the getters should behave more
similarly to `pure` functions than `view` functions).
```
- added relevant tests
> fix[lang]: disable nonreentrant behavior of immutable and constant getters

- tests/functional/builtins/codegen/test_create_functions.py
- vyper/builtins/functions.py
- address the invalid memory read described in: https://github.com/vyperlang/vyper/issues/4596 (does't fix the full issue, kwargs still can evaluate in bad order)
- check for overlap and issue a memory copy if necessary. note that the overlap analysis also checks for calls, which currently aren't problematic (can't change memory)
- the invalid read wasn't observable in userspace, the program was behaving correctly because the memory couldn't have been written between the invalidation and the read
- but we maybe might compile to IR and search for the memory copy? (this isn't currently done)
```
`raw_create` could issue an invalid memory read, if the `value` kwarg
modifies the `initcode` argument (e.g., `DynArray.pop()`).
note that the invalid read was not observable in userspace, the …
```
> fix[lang]: fix invalid memory read in `raw_create`

- tests/hevm.py
- tests/unit/compiler/venom/test_algebraic_binopt.py
- tests/unit/compiler/venom/test_duplicate_operands.py
- tests/unit/compiler/venom/test_load_elimination.py
- tests/unit/compiler/venom/test_single_use_expansion.py
- vyper/venom/__init__.py
- vyper/venom/passes/__init__.py
- vyper/venom/passes/assign_elimination.py
- vyper/venom/passes/single_use_expansion.py
```
the "store" opcode is confusingly named. in the future, we plan to
rename to "assign" or similar. that currently might produce merge
conflicts, so in the meantime we just rename the `StoreElimination` and
`StoreExpansion` pass names to be less confusing.
```
> refactor[venom]: rename "store"-related passes

- vyper/venom/passes/simplify_cfg.py
Optimised `SimplifyCFG`
```
this commit optimizes the performance of the `SimplifyCFG`
pass by scheduling label renaming for batch processing after
`_collapse_chained_blocks()`.
this performance regression was introduced in 2360d629d1607e09d
and 18d0787a737e240d36e21, since `_replace_label()` was added to
`_merge_jump()`, and it is called in a loop.
```
> perf[venom]: optimize time spent in `SimplifyCFG`

- vyper/venom/__init__.py
- vyper/venom/basicblock.py
this allows it to be removed by the `RemoveUnusedVariables` pass.
> feat[venom]: remove `dload` from list of volatile instructions

- vyper/venom/__init__.py
- vyper/venom/passes/sccp/eval.py
- vyper/venom/passes/sccp/sccp.py
this allows us to run it before mem2var, and in the future, will allow us to keep allocas around longer for alias analysis.
> feat[venom]: allow SCCP to run without removing allocas

- docs/structure-of-a-contract.rst
- tests/unit/ast/test_pre_parser.py
- tests/unit/cli/vyper_json/test_compile_json.py
- vyper/ast/pre_parser.py
- vyper/cli/vyper_compile.py
- vyper/cli/vyper_json.py
- vyper/compiler/settings.py
```
`--venom` was added as an alias for `--experimental-codegen` in
471a556f617e550a7. however, users might mistake that as meaning venom
is stable, which it is not (yet).
this commit renames the `--venom` CLI/pragma flag to
`--venom-experimental`, to better communicate that it is still not
stable.
```
> feat[tool]!: rename `--venom` to `--venom-experimental`

- tests/functional/codegen/features/decorators/test_raw_return.py
- vyper/semantics/types/function.py
```
this commit disallows `@raw_return` in `.vyi` files, as the decorator
doesn't have much semantic information for interfaces.
```
> fix[lang]: disallow `@raw_return` in interfaces

- vyper/venom/parser.py
fixes https://github.com/vyperlang/vyper/issues/4417
```
this commit updates the venom parser to use the LALR(1) algorithm,
which is O(n) rather than the O(n^3) earley algorithm.
```
> feat[venom]: rewrite grammar to LALR(1)

- vyper/venom/passes/function_inliner.py
rewrite the IRBasicBlock.parent pointer correctly. this is a well-formedness fix as it doesn't seem to be an observable bug at the moment.
> fix[venom]: fix function inliner `clone` function

- tests/unit/cli/vyper_json/test_compile_json.py
- vyper/venom/function.py
The subgraph labels of the IR contain duplicate double quotes `""` for the internal nodes which create a syntax error when parsing the generated output with graphviz. As a fix, I removed the duplicates so that the output only contains `"` now and can be used with graphviz again.
Changed the string interpolation of the subgraph label
Run tests or manually pipe the compiler output `cfg_runtime` format into `dot`:
```
$ vyper -f cfg_runtime --venom test.vy | dot 
```
```
the subgraph labels of the `-f cfg` and `-f cfg_runtime` output contain
duplicate double quotes `""` for some inlined functions, which create a
syntax error when parsing the generated output with graphviz.
this commit escapes quotes in the labels by serializing with `repr`.
```
Remove duplicate quotes in subgraph labels …
> fix[tool]: fix invalid quotes in `-f cfg` output

- vyper/codegen/core.py
Added some explanations on the heuristic
```
add comments explaining the gas costs for the maxbound heuristic in
more detail
```
chore[docs]: document the copy maxbound heuristic reasoning
> chore[docs]: document the copy maxbound heuristic reasoning
