vyperlang/vyper

- bin/viper
```sh
~/w/s/g/e/viper ❮❮❮ bin/viper -h
usage: viper [-h] [-f {abi,bytecode,ir}] input_file
Viper 0.0.1 programming language for Ethereum
positional arguments:
input_file            Viper sourcecode to compile
optional arguments:
-h, --help            show this help message and exit
-f {abi,bytecode,ir}  Format to print
~/w/s/g/e/viper ❯❯❯ bin/viper contract271.vy
0x600035601c52740100000000000000000000000000000000000000006020526fffffffffffffffffffffffffffffffff6040527fffffffffffffffffffffffffffffffff000000000000000000000000000000016060527402540be3fffffffffffffffffffffffffdabf41c006080527ffffffffffffffffffffffffdabf41c00000000000000000000000002540be40060a05260206020380360c03960c05160205181101558575060206020380360c03960c05160005560016002556101f456600035601c527401000000000000000000000000000000 …
```
> -f flag: abi, bytecode (default), ir

- tests/test_parser.py
- viper/parser.py
did it to solve this issue when running:
bin/viper
.....
AttributeError: module 'sha3' has no attribute '_sha3'
> solving problems running the tests and running the viper script

- tests/test_invalids.py
Just added a few tests to push the coverage needle along.
> Increase coverage for parser.py by 1%

- viper/compiler.py
- viper/functions.py
Hi,
I edited the code to PEP8 compliant for the next files:
- `viper/compiler.py`
- `viper/functions.py`
In `viper/functions.py` I deleted unnecessary imports
> PEP8 Compliant

- .travis.yml
- README.md
- setup.py
You can verify that the [build was successful on my fork](https://travis-ci.org/beaugunderson/viper/builds/258661293).
Closes #292 .
> Add .travis.yml

- tests/setup_transaction_tests.py
- tests/test_parser.py
Moved some of the utility code and imports to their own setup module to break apart that stuff from the tests, and also so I can use the same setup in other tests. Working on other test modules...
> Coverage testing

- viper/types.py
I like the idea of https://github.com/ethereum/viper/issues/303 to change the error copy.
> Fixes #303 Change error message in Map type in functions

- Makefile
- examples/voting/ballot.v.py
- tests/examples/voting/test_ballot.py
This is a voting example written in Viper (based on Solidity docs example).  I've added it to the docs locally but would love to get some eyes on the code to make sure it's right before making a PR for the docs.
@pdaian I used the same style for testing that you did, it definitely sped things up.  Thanks a lot!
@fubuloubu Could you take a look?
> Create voting example

- README.md
a more readable and friendly walk through of Viper installation for both Ubuntu and MacOS.
> Detailed Installation Guide added to README.md

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Creates issue and pr templates in an attempt to make issues and pull requests easier to understand.
> Create issue and pr templates

- README.md
Fix 
https://github.com/ethereum/viper/issues/319
and
https://github.com/ethereum/viper/issues/322
> Change virtualenv and MacOS Python install URL - Fix #319 #322

- README.md
For #332
Missing link for contributing (couldn't find it)
> Updates for contributions and where to discuss

- README.md
- docs/old_readme.txt
Moved extraneous info from README to docs per discussion in #332, #333
First draft, I just moved the current readme to a text file in docs, and rewrote the readme
If others review and like it @DavidKnott @yograterol @JackieXu @vbuterin 
N/A
> README updates

- README.md
> Add Documentation badge

- viper/function_signature.py
Update to function signature to have name be function name, added signature field to abi, fixed abi signature field to reflect return type as well. Fixes #344
ABI Change
> Updates to function name and signature in ABI

- .travis.yml
- README.md
This should hopefully add coveralls integration to Travis CI so that we can get a coverage badge.
Travis CI will run and hopefully not fail, and then we can add a coverage badge
> Add coveralls coverage report from Travis CI

- .travis.yml
- setup.cfg
- viper/compile_lll.py
- viper/exceptions.py
- viper/function_signature.py
- viper/functions.py
- viper/opcodes.py
- viper/optimizer.py
- viper/parser.py
- viper/parser_utils.py
- viper/types.py
- viper/utils.py
Updated parts of code that would throw a `NameError` if reached. Additionally went through the code to update its "Pythonic-ness".
I ran a `flake8` check over the codebase, and ignored line-length and line-continuations warnings.
Do a `pip install flake8` and run `flake8 viper`.
I specifically ignored the following errors:
- E122: Continuation line missing indentation or outdented
- E124: Closing bracket does not match visual indentation
- E127: Continuation line over-indented for visual indent
- E128: Continuation line under-indented for visual indent
- E501: Line length of more than N chars (default N = 79)
- E731: Do not assign a lambda expression, use a `def`.
N/A
> Update code readability and remove unused/non-declared variables

- examples/stock/company.v.py
- examples/stock/test_company.py
Updates to my stock example to provide a means to transfer stock between stockholders
Also updated tests
~~NOTE: This fails due to `msg.sender` bug (see #320)~~
Example update
> Stock example

- examples/auctions/simple_open_auction.v.py
- tests/examples/auctions/test_simple_open_auction.py
This is an open auction example written in Viper (based on Solidity docs example).  Once again, I've added it to the docs locally but would love to get some eyes on the code to make sure it's right before making a PR for the docs.
@fubuloubu Would you mind taking a look at this as well?  (I used pytest from the start this time!) Also I'd be more than happy to review any of your Viper code, just tag me (a second set of eyes always helps)
> Create open auction example

- tests/parser/features/decorators/test_internal.py
- tests/parser/features/iteration/test_break.py
- tests/parser/features/iteration/test_repeater.py
- tests/parser/features/test_assignment.py
- tests/parser/features/test_clampers.py
- tests/parser/features/test_comments.py
- tests/parser/features/test_conditionals.py
- tests/parser/features/test_internal_call.py
- tests/parser/features/test_logging.py
- tests/test_parser.py
Broke `test_parser.py` feature tests into a separate file
I looked through `test_parser.py` and found all feature related tests.
Look over my pr and make sure all the tests are still there.
None
> Break feature tests into folders

- README.md
- docs/index.rst
> Add online compiler note to the README

- viper/compile_lll.py
- viper/functions.py
- viper/optimizer.py
- viper/parser/parser.py
- viper/parser/parser_utils.py
- viper/utils.py
Created 3 constants structures to make handling of the clamp-addresses easier.
Adding additional limits should be much easier now, but most importantly this helps in proper handling of 2** limits, for example optimizer.py never got updated as you can see in the diff.
Created MemoryPositions,SizeLimits and LOADED_LIMIT_MAP. 
Tests verify it. Reading the changes in viper/utils.py especially.
N/A
> Maxmemory constants

- tests/setup_transaction_tests.py
Added a fixture for testing logs
Use it. Let me know if there are problems
NOTE: @DavidKnott, I thought about re-arranging all the code in 'parser/features/test_logging.py' but then I realized you would want to test more of the internals in there. I believe this fixture should probably not be used there, but basically anywhere else logs are used.
> ![Hooray](http://www.funnyanimalsite.com/pictures/Hooray.jpg)
> Added fixture for helping get logs

- examples/stock/company.v.py
- examples/stock/test_company.py
Implement @jacqueswww findings on gitter
> Audit Findings

- docs/installing-viper.rst
Minor doc update
Added a brew install command to docs
Reading.
Not necessary
> Added note about installing gmp-lib for osx users [minor docs fix]

- docs/compiling-a-contract.rst
- docs/index.rst
- docs/installing-viper.rst
1. Improved "Installing Viper"
1.1. Added Docker and online compiler
1.2. Restructured it a little bit
1.3. Added the commands needed to a compile a contract after the tests so users can verify that everything works correctly.
2. Added "Compiling a Contract"
Mostly copied from the readme. Changed wording and adapted the markup.
3. Improved Index
3.1 Added "Compiling a Contract" to the navigation menu
3.2 Improved structure and content
Changed the structure and incorporated parts of the readme. Reworded some things so that they fit better in the layout of the page.
Feedback greatly appreciated!
P.S. English isn't my native language so there might be (I hope not!) multiple errors and strange sounding sentences.
With the powers of Ctrl-C, Ctrl-V, and a little bit of writing :wink:
Read it. …
> Docs: Improvements for Installation, Index and Compiling

- tests/parser/types/numbers/test_num256.py
- viper/functions.py
Fixed a typo in sub num256 and simplified the overflow protection. This is in response to issue #411
Added in overflow tests and got them to pass.
Look at the tests I added.
None
> Fix sub num256

- docs/installing-viper.rst
Change the docs installation to use `make` instead of `make install`
@DustinWehr
Look at my pr
None
> Change make install to make

- docs/contributing.rst
Updated Contributions guideline
> Update Contributions Guideline

- tests/parser/features/test_logging.py
- viper/parser/parser_utils.py
Improved gas estimation for logging.
Now gas estimation include many bytes of data are logged.
Look at the tests I changed.
None
> Improve logging gas estimation

- tests/conftest.py
- tests/parser/features/test_logging.py
- viper/parser/parser.py
- viper/parser/parser_utils.py
- viper/parser/stmt.py
- viper/signatures/event_signature.py
Fix logging so that bytes variables can be logged.
Added more tests.
In response to #413 @jacqueswww 
I added parsing for variables so that they can be logged.
I came up with tests that should be invalid and made sure they were / fixed them if they weren't.
Look over the tests I added and make sure they're working as expected.
None
> Fix logging

- tests/setup_transaction_tests.py
Rename `function` to `func` in `setup_transaction_tests.py`.  Same as #311 
Look over my PR.
None
> Change function to func

- examples/auctions/simple_open_auction.v.py
Fixed trivial spelling in a comment
_i before e except after c_
> Minor spelling fix in comment

- examples/voting/ballot.v.py
- tests/examples/voting/test_ballot.py
#370 
with input from @DavidKnott and @fubuloubu 
run the tests, read the comments
fix voting with delegation example
> fix voting with delegation example

- docs/types.rst
Completely reworked most of the types documentation.
Read it :)
Overhaul of types
> Docs: Overhaul of types

- tests/examples/company/test_company.py
Move `test_company.py` from the `examples/` folder into the `tests/examples/` folder 
Look at my PR
None
> Move test_company file into proper folder

- viper/parser/parser_utils.py
Fixed an error that occurs when running `python scripts/fixed_address_creator.py`
Looked at what was going wrong and added a conditional to account for it.
Try running `python scripts/fixed_address_creator.py` locally and then using my branch.
None
> Fix error when running fixed_address_creator script

- tests/parser/features/decorators/test_constant.py
- tests/parser/features/iteration/test_for_in_list.py
- tests/parser/features/iteration/test_range_in.py
- tests/parser/features/test_external_contract_calls.py
- tests/parser/features/test_internal_call.py
- tests/parser/features/test_logging.py
- tests/parser/functions/test_raw_call.py
- tests/parser/globals/test_getters.py
- tests/parser/integration/test_crowdfund.py
- tests/parser/types/numbers/test_num.py
- tests/parser/types/numbers/test_num256.py
- tests/setup_transaction_tests.py
- viper/functions.py
- viper/optimizer.py
- viper/parser/parser_utils.py
Support gas estimation for constant functions and allow for `add_gas_estimate` to be used from `functions.py`
Looked for where `get_contract_with_gas_estimation` failed and found out what was wrong with the estimation.
Look over my PR.
None
> Improve gas estimation

- docs/structure-of-a-contract.rst
- examples/stock/company.v.py
- tests/examples/company/test_company.py
Added event logging to the company stock example contract.
Added tests for logging events in that contract.
Added an "Events" section to "Viper in Depth / Structure of a Contract"
Cleaned up some whitespace in `company.v.py`
I defined an event for each economic transaction (Transfer, Buy, Sell, Pay) in the company stock example contract and logged the event at the end of the appropriate function.
I added a test to check that exactly one expected event is logged for each of those functions, with the expected value.
Read the `structure_of_a_contract.rst` to verify the "Events" section and run the unit tests to verify the logging.
Documentation updates
> The beginnings of Event and Log documentation

- docs/contributing.rst
- Fixes a link that wasn't displaying correctly.
- Makes some instructions more concise.
- Changes old `:ref:building-from-source`, to link to installation instructions.
> Improve contributing .rst

- tests/parser/features/iteration/test_for_in_list.py
- tests/parser/features/test_assignment.py
- viper/parser/stmt.py
Refactor `stmt.py` `aug_assign` and `assign functions so that they check for the proper invalids.
This fixes #508 and #509
@yzhang90 Thanks again!
I created invalid `assignment` and  `for_in` tests that should've been failing and then got them to fail.
Look at the tests I added in `test_assignment.py` and `test_for_in_list.py`
None
> Fix augassign and assign

- tests/parser/features/test_logging.py
- viper/parser/parser.py
Fix #521, allowing logging using a variable of list type.
Added section that copies list memory section into placeholder, see changes in `parser.py`.
> Fix variable list logging.

- viper/compile_lll.py
Chang `clamps` to use revert opcode 
Switch out `["PC", "JUMPI"] for `["REVERT"]`  
Look at `compile_lll.py`
Change clamps to use revert
> Use revert for clamps

- examples/tokens/vipercoin.v.py
Closes #510 
Links out to resources describing attack vector.
> Improve vipercoin example

- docs/old_readme.txt
- tests/parser/syntax/test_invalids.py
- viper/functions.py
- viper/opcodes.py
- viper/utils.py
Removed suicide per #548
Grep magic
Tests fine!
Removed suicide keyword and opcode
> Removed suicide keyword

- docs/viper-by-example.rst
with ``num`` type > with the ``num`` type
crowdfunding period is over - as determined> crowdfunding period is over—as determined
> Minor edits

- docs/index.rst
> removed extraneous backtick `

- docs/types.rst
> Minor edits types.rst

- docs/structure-of-a-contract.rst
> :ref:`function-calls` > :ref:`Function-calls`

- viper/functions.py
Improve `num256_add` gas cost.
Turn 2 checks into one.
Look at the LLL I changed.
None
> Reduce num256_add gas cost

- examples/market_maker/on_chain_market_maker.v.py
- tests/examples/market_maker/test_on_chain_market_maker.py
Fix on chain market maker contract and tests.
Added some comments.
Looked over the smart contract and got it to do what it's supposed to do. 
Look at the tests I changed and make sure they make sense.
None
> Fix on chain market maker

- README.md
- docs/index.rst
Change Vypers badges to match its new name.
Make sure the links I changed worke
None
> Change badges from viper to vyper

- Makefile
Noticed some extra junk that wasn't getting cleaned out
> Fully clean project

- tests/parser/functions/test_as_num128.py
- viper/functions.py
As discussed in #361 .
See functions.py
See added test.
> Remove address as an input option from as_num128

- viper/opcodes.py
Add opcodes for sharding
Begins implementing #632 
Looked at the opcodes that were needed and added them and remove any that were no longer relevant.
Look at the changes to `opcodes.py`
None
> Add sharding opcodes

- viper/functions.py
Was looking at coverage and this line jumped out at me
Removed it
Verify I didn't make a mistake
> Remove unreachable line

- examples/crowdfund.v.py
- tests/parser/integration/test_crowdfund.py
Removed a stray `@private` and uncommented a line in the crowdfund integration test
In response to #644 
Looked at what was wrong and fixed it.
Make sure all tests are passing
None
> Fix crowdfund example

- docs/index.rst
Fixes #672. By adding a few .rst files to the necessary toctree.
N/A
Just check the html doc output.
> Add missing .rst files to index.rst

- README.md
- docs/compiling-a-contract.rst
> Update online compiler URLs to new vyper.online domain

- README.md
> Added a link to the STATICCALL EIP

- README.md
Changed: vyper yourFileName.v.py
To: vyper your_file_name.v.py
The naming convention is snake case and I think this will prevent any confusion.
ps. I am just fixing and pushing things as I see them. Is that fine or am I supposed to wait for bunch of changes before pushing or something like that?
> Renamed the example file name

- examples/tokens/ERC20.v.py
- tests/examples/market_maker/test_on_chain_market_maker.py
- tests/parser/features/external_contracts/test_erc20_abi.py
- vyper/premade_contracts.py
PR for issue #708 
Added name and getters for ERC20 name and decimals.
Made ERC20 decimals public
> Added getters for name and decimal ERC20

- tests/parser/syntax/test_list.py
- tests/parser/types/test_lists.py
- vyper/parser/stmt.py
> Fix return list, updated.

- vyper/functions/functions.py
Some commented out code that should be removed.
> Remove commented out code.

- vyper/parser/parser.py
Replaced __log__ with event (didn't notice that one when originally renamed...)
Also added commas in the import list for a better convention (some had and some didn't)
> Replaced __log__ with event

- tests/parser/features/test_logging.py
- vyper/parser/parser.py
Fixes #730 and  #731.
Change in log packing when handling list types.  This is not the whole refactor as I plan to do that eventually - but first want to fix the existing bugs to get a better picture of how I can refactor the code ;)
> Fixes #730, proper packing of lists for log statements.

- tests/parser/features/test_logging.py
- vyper/parser/expr.py
- vyper/parser/parser.py
- vyper/parser/stmt.py
Fixes #739.
Read the correct byte len from memory or storage, allowing us copy the correct bytes.
See tests.
N/A
> Fix indexed bytearray logging

- vyper/functions/functions.py
- vyper/parser/expr.py
- vyper/parser/parser.py
- vyper/parser/parser_utils.py
- vyper/parser/stmt.py
Fixes #734, improve error statements.
Passing more`pos` around ;)
Write log event as in #734.
N/A
> Add more exception positions.

- setup.py
Fixes #665.
One line statement.
> Adds python requires 3.6.

- .travis.yml
Attempting to make snap build automatically off master.
> Add snap build to travis.

- docs/installing-vyper.rst
Fix minor typo
Change single letter
Dictionary
N/A
______
|  o  o   \
|    L       \______/\_
\__U___________/
> Update installing-vyper.rst fixing typo

- vyper/functions/functions.py
> Improve gas cost for `shift` function

- tests/parser/types/numbers/test_decimals.py
- vyper/parser/expr.py
> Overflow checking for multiplication.

- tests/parser/functions/test_convert.py
- tests/parser/functions/test_return_tuple.py
- tests/parser/syntax/test_tuple_assign.py
- vyper/parser/expr.py
- vyper/parser/parser.py
- vyper/parser/parser_utils.py
- vyper/parser/stmt.py
Implements #727. Adds support for assign tuples to internal and externals calls.
> Adds tuple assignment

- vyper/compile_lll.py
> Fix upper bound on clamp

- README.md
Remove useless indents in README.md
> Remove useless indents

- .github/VIP_TEMPLATE.md
Changed philosopy to philosophy
Just a typo fix...
> Fixed typo in VIP template

- tests/parser/types/numbers/test_custom_units.py
- vyper/types/types.py
Fix custom units for nested datatypes.
Thanks for @ben-kaufman  for pointing out the bug ;)
See test case.
> Fix custom units for nested datatypes.

- tests/parser/types/numbers/test_int128.py
- vyper/parser/expr.py
Fixes #475.
Turns out the uint256 VIP #764 mostly fixed this issue already. Just added some more tests to make 100 % sure :smile:
> 475 num safe math

- examples/market_maker/on_chain_market_maker.v.py
- examples/safe_remote_purchase/safe_remote_purchase.v.py
- examples/stock/company.v.py
- setup.py
- tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py
- tests/parser/features/arithmetic/test_modulo.py
- tests/parser/features/iteration/test_break.py
- tests/parser/features/iteration/test_repeater.py
- tests/parser/functions/test_ceil.py
- tests/parser/functions/test_floor.py
- tests/parser/functions/test_minmax.py
- tests/parser/globals/test_setters.py
- tests/parser/syntax/test_block.py
- tests/parser/syntax/test_invalids.py
- tests/parser/syntax/test_public.py
- tests/parser/types/numbers/test_decimals.py
- tests/parser/types/numbers/test_int128.py
- tests/parser/types/value/test_as_wei_value.py
- vyper/__init__.py
- vyper/functions/functions.py
- vyper/parser/expr.py
Fixes #716. 
`Expr.arithmetic`
> Implement integer division

- docs/index.rst
- examples/auctions/simple_open_auction.v.py
- examples/market_maker/on_chain_market_maker.v.py
- examples/safe_remote_purchase/safe_remote_purchase.v.py
- examples/stock/company.v.py
- tests/examples/company/test_company.py
- tests/parser/exceptions/test_invalid_literal_exception.py
- tests/parser/features/arithmetic/test_modulo.py
- tests/parser/features/external_contracts/test_erc20_abi.py
- tests/parser/features/external_contracts/test_external_contract_calls.py
- tests/parser/features/test_gas.py
- tests/parser/features/test_logging.py
- tests/parser/functions/test_block.py
- tests/parser/functions/test_block_number.py
- tests/parser/functions/test_send.py
- tests/parser/syntax/test_as_wei_value.py
- tests/parser/syntax/test_block.py
- tests/parser/syntax/test_invalids.py
- tests/parser/syntax/test_timestamp_timedelta.py
- vyper/functions/functions.py
- vyper/functions/signature.py
- vyper/parser/expr.py
- vyper/parser/parser.py
- vyper/parser/stmt.py
- vyper/premade_contracts.py
- vyper/types/convert.py
- vyper/types/types.py
- vyper/utils.py
Fixes #653 and #823.
**NB** converts wei_value and related `msg.*` and `block.*` variables from `int128` to `uint256`.
See tests.
>  uint256 wei value

- docs/types.rst
- vyper/types/convert.py
- vyper/types/types.py
- vyper/utils.py
Fixed an error message.
Fixed a typo.
Removed ``currency1`` and ``currency2`` types, as discussed after adding custom units.
> Removed currency1 and currency2 (and some more)

- bin/vyper
- tests/conftest.py
- tests/parser/features/test_assignment.py
- vyper/compile_lll.py
- vyper/compiler.py
- vyper/opcodes.py
Fixes #838.
Add some debug 'tools'.
Deep dive into compile_lll.
Check added tests.
> Fix for sha3_64

- tests/compiler/test_pre_parser.py
- tests/parser/features/external_contracts/test_external_contract_calls.py
- tests/parser/features/external_contracts/test_modifiable_external_contract_calls.py
- vyper/parser/expr.py
- vyper/parser/parser.py
- vyper/parser/parser_utils.py
- vyper/types/types.py
> Remove redundant contract syntax

- bin/vyper-run
Fixes #839. Vyper-run works again :smile:
> Fix vyper-run to use py-evm/eth-tester.

- docs/built-in-functions.rst
Fixed formatting for keccak256 method
Removed an extra `*`
Documentation : Fixed formatting for keccak256 method
```
____,'`-, 
_,--'   ,/::.; 
,-'       ,/::,' `---.___        ___,_ 
|       ,:';:/        ;'"`;"`--./ ,-^.;--. 
|:     ,:';,'         '         `.   ;`   `-. 
\:.,:::/;/ -:.                   `  | `     `-. 
\:::,'//__.;  ,;  ,  ,  :.`-.   :. |  ;       :. 
\,',';/O)^. :'  ;  :   '__` `  :::`.       .:' ) 
|,'  |\__,: ;      ;  '/O)`.   :::`;       ' ,' 
|`--''            \__,' , ::::(       ,' 
`    ,            `--' ,: :::,'\   ,-' 
| ,;         ,    ,::'  ,:::   |,' 
|,:        .(          ,:::|   ` 
::'_   _   ::         ,::/:| 
,',' `-' \   `.      ,:::/,:| 
| : _  _   |   '     ,::,' ::: 
| \ O`'O  ,',   ,    :,'   ;:: 
\ `-'`--',:' ,' , ,,'      :: 
``:.:.__   ',-',' …
```
> Documentation : Fixed formatting for keccak256 method

- bin/vyper
> Do not put out the full stack trace when using vyper compiler binary.

- tests/compiler/test_pre_parser.py
- tests/parser/features/external_contracts/test_external_contract_calls.py
- tests/parser/features/external_contracts/test_modifiable_external_contract_calls.py
- tests/parser/types/numbers/test_custom_units.py
- vyper/function_signature.py
- vyper/parser/expr.py
- vyper/parser/parser.py
- vyper/parser/stmt.py
- vyper/premade_contracts.py
- vyper/utils.py
> Improve static call keywords

- docs/types.rst
Improved the types documentation
> Improved types documentation

- docs/built-in-functions.rst
Fixes VIP GH-845
Thanks to @mandarvaze,
I removed old convert function documentation
I documented new convert function
check GH-845
> Remove Old Convert Functions from Documentation

- docs/built-in-functions.rst
Improved the documentation for Vyper's built in functions.
> Improved built in functions documentation

- docs/vyper-by-example.rst
Fixed typo from `bidding_time` to `_bidding_time`
> fixed docs typo

- tests/parser/functions/test_convert.py
- tests/parser/functions/test_convert_int128.py
- vyper/parser/stmt.py
- vyper/types/convert.py
> Fix convert units

- examples/wallet/wallet.v.py
- tests/parser/functions/test_default_function.py
- vyper/parser/parser.py
> Support for fallback/default function

- docs/testing-deploying-contracts.rst
Added a documentation for the vyper-run command
> Added documentation for vyper-run

- tests/parser/functions/test_convert.py
- vyper/types/convert.py
> Add support for converting uint256 to decimal.

- snap/snapcraft.yaml
- tests/compiler/test_pre_parser.py
- vyper/__init__.py
- vyper/parser/parser.py
> Version statement

- tests/parser/functions/test_convert.py
- vyper/types/convert.py
> Add support for converting from address->uint256.

- tests/parser/syntax/test_functions_call.py
- tests/parser/syntax/test_invalids.py
- vyper/parser/stmt.py
> Handle unused functions.

- .github/ISSUE_TEMPLATE/general.md
- .github/ISSUE_TEMPLATE/vip.md
GitHub has a new issue template feature I didn't know about it
Setup a folder for `ISSUE_TEMPLATE` and add subitems for each different choice
Not sure, maybe "browse repository at this point" and add a new feature?
This is safe to merge
Added new issue template options
> Issue template

- vyper/utils.py
Fixed a typo in `vyper/utils.py` which irritated me.
Should be relatively straightforward 🤔
👀 at code
Fixed a typo in `vyper/utils.py`.
🐕
> Fix typo: Unknow -> Unknown

- docs/types.rst
- tests/parser/types/numbers/test_constants.py
- vyper/parser/expr.py
Fixes #843. 
Adding bultin constants.
> Add builtin constants

- setup.py
- tests/conftest.py
- tests/parser/syntax/test_invalids.py
- vyper/parser/parser.py
- vyper/parser/stmt.py
> Allow docblocks to exist on functions.

- README.md
Updated README.md to remove references to 'experimental' and 'alpha' as per issue 902
Reading issue 902 and updating README.md
See README.md
Removed experimental and changed alpha to beta in readme.
> Updated to remove alpha and experimental

- examples/name_registry/name_registry.vy
- tests/examples/test_name_registry.py
- tests/parser/types/numbers/test_custom_units.py
Adds an example for a very simple name registry.
> Add simple name registry example

- vyper/parser/stmt.py
> Typo fix: unknow to unknown

- bin/vyper-serve
> Typo fix: emtpy to empty

- examples/crowdfund.vy
Improved whitespace in `crowdfund.vy` example contract.
Did it.
Changes are only whitespace.
> Update crowdfund.vy example contract

- docs/installing-vyper.rst
Just came across vyper and think it is the correct step forward for safer contracts. Therefore, I decided to pick some low hanging fruit. Let me know if anything looks wrong since I have never dealt with reST files before.
Updated the documentation to address an installation issue that can arise if ```python3-dev``` is not installed on Ubuntu.
Updated the docs.
Look at the docs.
Updated the documentation to address an installation issue that can arise if ```python3-dev``` is not installed on Ubuntu.
> Updated documentation to inform Ubuntu install python headers

- tests/parser/functions/test_method_id.py
- vyper/functions/functions.py
- vyper/functions/signature.py
> method_id support for bytes32 and bytes[4]

- tests/parser/exceptions/test_variable_declaration_exception.py
- tests/parser/features/test_logging.py
Fixed typo in multiple locations
> Typo fixes

- .gitignore
I updated the egg-info folder in the .gitignore.
This is a minor change, but helps put my mind at ease. T.
> reflected new egg-info folder in git ignore

- docs/index.rst
- docs/installing-vyper.rst
Fixes #902 .
And adds a note about pulling images from dockerhub.
> Remove experimental wording.

- setup.py
bumped web3 version to v4.5.0
updated `setup.py` with the new web3 version
check if CI turns green.
> test vyper with web3 v4.5.0

- vyper/parser/expr.py
> Optimize multiplication operation on Vyper

- tests/parser/types/numbers/test_uint256.py
- vyper/parser/parser_utils.py
- vyper/types/types.py
> Remove int128() implicit conversion in function signature.

- bin/vyper-lll
- setup.py
- tests/compiler/LLL/test_compile_lll.py
- tests/conftest.py
- vyper/compiler.py
- vyper/parser/s_expressions.py
Fixes #790. 
Very basic for now, see test_lll_from_s_expression for an example.
Couldn't resist, a lisp joke.
> Add vyper-lll.

- bin/vyper
- docs/index.rst
- tests/conftest.py
- tests/parser/functions/test_default_function.py
- tests/parser/functions/test_default_parameters.py
- vyper/compile_lll.py
- vyper/opcodes.py
- vyper/parser/expr.py
- vyper/parser/parser.py
- vyper/parser/stmt.py
- vyper/signatures/function_signature.py
- vyper/utils.py
Fixes #903.
Lots of wrestling, and changing of structs.
Check the tests.
Add support for default parameters.
> Default parameters support

- docs/built-in-functions.rst
Document `blockhash()`
Looking at the source code and tests
Document blockhash function
> Document blockhash function

- docs/index.rst
- docs/logging.rst
- docs/testing-deploying-contracts.rst
Added links to the Testing and Deploying and Event Logging docs so they are findable.  
Added to toctree in index
By building docs
Added links to docs
> Added navigation links

- tests/parser/functions/test_block.py
- vyper/functions/functions.py
Fixes: #981 
Removed ability to use int128 to get blockhash and added tests for getting negative, to far in the past and future blockhash
Look at the `blockhash` function and the tests
> Fixed blockhash bug and added tests

- docs/installing-vyper.rst
- setup.py
> Add pip install vyper to the docs.

- bin/vyper
> Use unique function that maintains order.

- tests/compiler/test_pre_parser.py
- vyper/exceptions.py
- vyper/parser/parser.py
- vyper/parser/pre_parser.py
> Wrap TokenError with StructureException that outputs the line number.

- examples/wallet/wallet.vy
- tests/parser/features/test_conditionals.py
- tests/parser/syntax/test_bool.py
- vyper/parser/stmt.py
> Stricter if and assert

- vyper/parser/global_context.py
Cleaned up some typos in exception messages and also made their formatting more consistent.
Run the tests.
> Tidy up some exception messages

- examples/tokens/vypercoin.vy
vypercoin.vy violated SHOULD requirement of ERC20 standard. Moreover, the code contained some redundant checks, that consumes gas.
By fixing vypercoin.vy file. Let's go over changes:
1. The following part of the code makes a simple check for the overflow in the `totalSupply` variable. I moved it to the beginning of the constructor so that less gas will be spent in the case of failure (since nothing will be written to the storage).
```
assert _initialSupply * 10 ** _decimals >= _initialSupply
self.totalSupply =_initialSupply * 10 ** _decimals
self.balances[msg.sender] = self.totalSupply
```
2. This event SHOULD be present according to the ERC20 standard, since new tokens are created in the constructor.
```
log.Transfer(ZERO_ADDRESS, msg.sender, self.totalSupply)
```
Citation from [standard …
> fix vypercoin erc20 compliance, optimize gas costs

- .github/ISSUE_TEMPLATE/bug.md
Housekeeping on the issues template
GitHub
IDK
N/A
> general.md -> bug.md; removed pyethereum

- docs/installing-vyper.rst
Added install instructions for arch linux package.
> Add arch install instructions

- tests/parser/features/test_logging.py
- tests/parser/features/test_units.py
- vyper/parser/global_context.py
- vyper/parser/parser.py
- vyper/signatures/event_signature.py
- vyper/signatures/function_signature.py
- vyper/types/types.py
Added support for units in ABI output (function inputs/outputs and events). Fixes #983.
Used `print_unit` on `type.unit` where relevant in places where ABI output is assembled.
Create contract with units in it, compile it with `-f abi`
> implemenation of units in ABI

- docs/built-in-functions.rst
Fixed input params of method_id in docs.
Modified docs.
Checked compiler.
Fix input params of method_id in docs.
> Fix input params of method_id in docs

- tests/parser/types/test_bytes.py
- vyper/parser/parser_utils.py
- vyper/parser/stmt.py
> Add bytes32 literal type.

- tests/parser/features/iteration/test_for_in_list.py
- tests/parser/syntax/test_constants.py
- vyper/parser/stmt.py
Fixes #1100 . Couldn't resist the pun in the title.
> Constant Improvement

- docs/built-in-functions.rst
- setup.py
- tests/conftest.py
- tests/parser/functions/test_create_with_code_of.py
- tests/parser/functions/test_raw_call.py
- vyper/functions/functions.py
> Revert create with code of

- docs/vyper-by-example.rst
- examples/auctions/blind_auction.vy
Just some minor fixes to documentation and to the docs. Updating line nos and fixing a comment that got borked.
> Minor documentation update

- examples/safe_remote_purchase/safe_remote_purchase.vy
Update example for safe remote purchase with security phases in the interaction function.
I think the example is correct, although I haven't tested it (I haven't quite got viper running yet on my machine).
Create a contract address to participate in a sample old contract that triggers the exploit (recursive call into the received() function). Check the exploit works.
Try again with the updated example and see if it prevents the exploit.
Updated examples to follow good practice security phases for functions that have external interaction.
What is it with the animals?
> Add security phases to interaction function

- setup.py
Bump versions in setup.py to fix CI errors.
> Bump eth-tester and py-evm versions.

- tests/conftest.py
- tests/parser/types/numbers/test_constants.py
- vyper/parser/global_context.py
- vyper/parser/lll_node.py
Fix literal for Constants.
Tests pass ;)
> Fix literal for Constants.

- docs/built-in-functions.rst
Fixed docs of raw_call
Fix docs of raw_call
> Fix docs of raw_call

- docs/built-in-functions.rst
Specified uint256(wei) for wei value type
Specify uint256(wei) for wei value type
> Specify uint256(wei) for wei value type

- docs/built-in-functions.rst
Added whitespace after `` in docs
Add whitespace after `` in docs
> Add whitespace after `` in docs

- tests/parser/types/test_lists.py
- vyper/parser/expr.py
> Fix check for nested lists.

- examples/crowdfund.vy
- tests/examples/crowdfund/test_crowdfund_example.py
- tests/parser/integration/test_crowdfund.py
Fix crowdfund example in the docs.
> Fix crowdfund example and add crowdfund examples/ test.

- tests/parser/functions/test_return.py
> Add test for #743.

- tests/parser/features/decorators/test_private.py
- vyper/parser/self_call.py
> Add test for calling private function expression.

- tests/parser/features/iteration/test_for_in_list.py
- vyper/parser/stmt.py
> Fix iterator variable to have correct unit type.

- docs/built-in-functions.rst
Fixed the docs about `clear`. `clear` has no outputs.
Fix the docs about `clear`
> Fix the docs about `clear`

- docs/types.rst
Added a member of address `is_contract` to the docs
Add a member of address `is_contract` to the docs
> Add a member of address `is_contract` to the docs

- examples/tokens/ERC20.vy
- examples/tokens/ERC721.vy
- tests/examples/tokens/test_erc20.py
- tests/examples/tokens/test_erc721.py
Cleaned up example tokens:
- Python style comments
- minor fixes
Tests
Clean up example tokens
> Clean up example tokens

- tests/parser/features/test_units.py
- tests/parser/functions/test_convert_to_bool.py
- vyper/functions/signature.py
- vyper/parser/expr.py
- vyper/parser/parser_utils.py
- vyper/parser/stmt.py
- vyper/types/convert.py
- vyper/types/types.py
Fixes #1031. And additional hidden bugs along the way.
> Add literal unit check, when making a call.

- tests/parser/syntax/test_constants.py
- vyper/functions/functions.py
> Better constant() test cases

- .github/ISSUE_TEMPLATE/vip.md
> Added dependencies section

- tests/parser/syntax/test_constants.py
- vyper/functions/functions.py
- vyper/parser/constants.py
> Fix as wei value constant param

- tests/parser/features/test_assert.py
- tests/parser/syntax/test_as_uint256.py
- tests/parser/syntax/test_functions_call.py
- tests/parser/syntax/utils/test_event_names.py
- vyper/parser/expr.py
- vyper/parser/global_context.py
- vyper/parser/parser.py
- vyper/parser/stmt.py
- vyper/signatures/event_signature.py
- vyper/types/types.py
Cleans up a bunch of exception cases.
> Fuzzer fixes

- vyper/parser/parser.py
- vyper/parser/stmt.py
> Fixes #1216, greatly increasing zero-padding efficiency.

- tests/parser/exceptions/test_function_declaration_exception.py
- tests/parser/exceptions/test_invalid_payable.py
- tests/parser/exceptions/test_variable_declaration_exception.py
- tests/parser/syntax/test_return_tuple.py
- tests/parser/syntax/test_sha3.py
- tests/parser/syntax/test_slice.py
- tests/parser/syntax/test_timestamp_timedelta.py
- tests/parser/syntax/utils/test_event_names.py
- tests/parser/syntax/utils/test_function_names.py
- tests/parser/syntax/utils/test_variable_names.py
- vyper/parser/s_expressions.py
- vyper/parser/self_call.py
- vyper/parser/stmt.py
Fix the CI
Fix all lint found in new flake8
```bash
make lint
```
> Fix lint detected in new version of flake8 (3.7.4)

- .github/ISSUE_TEMPLATE/bug.md
> Spruce up the bug reporting template

- examples/tokens/ERC20.vy
> ERC20 contract example: Added comment for clarifying why not using assert

- examples/safe_remote_purchase/safe_remote_purchase.vy
> Fixed commenting aesthetics in example contract

- .github/ISSUE_TEMPLATE/bug.md
- .github/PULL_REQUEST_TEMPLATE.md
Remove cute animals from issues because it can sometimes be annoying
Update the prompt in PR requests to make it clearer how to add cute animals
Also, there were weird dashes in our PR template
GitHub
Dunno
N/A
> Stop being cute!

- docs/logging.rst
num256 to uint256
Grep and Replace
See diff
Update num256 due to obsoleted documentation
Sorry I'm busy ;p
> num256 isn't exist on current Vyper

- docs/installing-vyper.rst
> fix venv path

- examples/tokens/ERC20.vy
> Implement state variable `balances` as public

- tests/conftest.py
- tests/parser/functions/test_abi.py
- vyper/compiler.py
- vyper/parser/parser.py
- vyper/signatures/function_signature.py
> Drop name attribute from init and default function.

- docs/installing-vyper.rst
Improved docker command in the docs.
^.^
> Update docker examples to be usable with mounted files.

- docs/structure-of-a-contract.rst
- tests/parser/features/decorators/test_nonreentrant.py
- vyper/parser/external_call.py
- vyper/parser/global_context.py
- vyper/parser/parser.py
- vyper/signatures/function_signature.py
> @nonreentrant Decorator

- bin/vyper-serve
> vyper-serve: return more compile types

- vyper/parser/context.py
- vyper/parser/stmt.py
Part of #1259.
- Uses context manager patter for assignment, assert, for loop and block scoping.
> Blockspace context managers

- examples/tokens/ERC721.vy
> Add a comment to ERC721 example

- setup.py
Adds flake8-bugbear, which as default mutable args checker included :)
> Add flake8-bugbear as a linting check.

- tests/conftest.py
- tox.ini
Foregoing the animal pictures and descriptions with these lint PRs.  See #1262 and #1276 .
> Lint for tests/conftest.py

- tests/parser/integration/test_basics.py
- tox.ini
Foregoing the animal pictures and descriptions with these lint PRs.  See #1262 and #1276 .
> Lint for tests/parser/integration/*

- bin/vyper
- bin/vyper-lll
- tox.ini
Foregoing the animal pictures and descriptions with these lint PRs.  See #1262 and #1276 .
> Lint for bin/*

- scripts/fixed_address_creator.py
- scripts/forwarder.py
- scripts/rlp_decoder.py
- tox.ini
Foregoing the animal pictures and descriptions with these lint PRs.  See #1262 and #1276 .
> Lint for scripts/*

- Makefile
- bin/vyper
- setup.cfg
- vyper/compile_lll.py
- vyper/functions/functions.py
- vyper/parser/expr.py
- vyper/parser/parser_utils.py
- vyper/types/convert.py
A bit of cleaning, thanks to lgtm.
> Code cleanups

- docs/installing-vyper.rst
> Update snap installation docs.

- tests/parser/functions/test_interfaces.py
- vyper/parser/parser.py
- vyper/signatures/interface.py
> Interface unit fix

- vyper/compiler.py
- vyper/parser/context.py
- vyper/parser/lll_node.py
- vyper/parser/parser.py
- vyper/parser/parser_utils.py
- vyper/signatures/event_signature.py
- vyper/signatures/function_signature.py
> Minor, random lint

- .circleci/config.yml
- README.md
- tox.ini
Added Python 3.7 to Circle CI.
Modified `tox.ini` and `.circleci/config.yml`.
Run tests.
> Add python37 to circle CI

- Makefile
- requirements-dev.txt
`make lint` is no longer the same as CI. This fixes that :)
> Update make lint to use tox

- tests/parser/syntax/test_constants.py
- tests/parser/types/numbers/test_constants.py
- vyper/types/types.py
> Add support for list constants

- vyper/optimizer.py
Made some small lint fixes in `vyper.optimizer`.
Run the tests.
> Some lint fixes in vyper.optimizer

- vyper/optimizer.py
- vyper/parser/lll_node.py
- vyper/types/types.py
> Random whitespace lint

- vyper/exceptions.py
- vyper/parser/global_context.py
- vyper/parser/parser.py
- vyper/parser/parser_utils.py
- vyper/parser/pre_parser.py
- vyper/typing.py
This is a bit random but I was poking around reading the code and decided to bite this off and do some refactors and type annotations in the `parser` submodules.  This will hopefully give an example of some of the kinds of changes I'd like to see in other parts of the code base as well.
Run the tests.
> Some cleanup/type annotations in parser submodules

- tests/parser/syntax/test_string.py
- vyper/parser/expr.py
Fix error message for string comparison.
> Fix error message for string comparison.

- .coveralls.yml
- setup.py
- tox.ini
- upload_coverage.sh
As it turns out, the package we were using for coveralls uploads is more maintained and supposedly works better with circle CI.
> Modify some coveralls config updates

- tests/parser/exceptions/test_invalid_literal_exception.py
- tests/parser/functions/test_convert_to_uint256.py
- tests/parser/parser_utils/test_annotate_and_optimize_ast.py
- vyper/parser/global_context.py
- vyper/parser/parser.py
- vyper/parser/parser_utils.py
- vyper/parser/pre_parser.py
- vyper/typing.py
More parser submodule refactors/cleanup.
* Added various docstrings
* Created more robust post-parsing AST node visitors
* Add tests for new behavior handled by refactored node visitors
* Fixed a bug that prevented certain nested unary subtractions from being recognized as negative literals.
> More parser submodule cleanup

- tests/parser/syntax/test_interfaces.py
- vyper/parser/expr.py
- vyper/parser/external_call.py
- vyper/parser/stmt.py
- vyper/types/types.py
> Add missing persistent address test cases.

- docs/types.rst
- docs/vyper-by-example.rst
Fix spelling and grammatical mistakes
> Fix spelling mistakes

- vyper/optimizer.py
Fix https://github.com/ethereum/vyper/issues/1386#issuecomment-490677420
code that calls push_args for a private function call will generate this.
> Add if_unchecked to ne/xor optimizer

- Makefile
> Makefile: use pip3 over pip if available.

- SECURITY.md
Add a list of known Vyper vulnerabilities and exposures, as well as version history info.
> Add Vyper Vulnerabilities and Exposures (VVE) List

- vyper/compiler.py
> simplify statement

- setup.py
- tests/conftest.py
- tests/parser/features/external_contracts/test_external_contract_calls.py
- tests/parser/functions/test_abi.py
- tests/parser/functions/test_return_struct.py
- vyper/signatures/event_signature.py
- vyper/signatures/function_signature.py
- vyper/types/types.py
> ABI tuple outputs

- tests/parser/functions/test_concat.py
- tests/parser/types/test_string.py
- vyper/functions/functions.py
> Fix length of string types in concat

- bin/vyper
> Add interface codes to combined_json format.

- docs/types.rst
Fix #1436 
Change the comment in docs about short-circuiting rules to say Vyper does not short-circuit.
Improved docs
> Fix docs RE: short-circuiting rules

- bin/vyper
- tox.ini
Added mypy and flake8 checking for additional vyper bins and scripts.
Run the tests.
> Lint improvements

- examples/tokens/ERC20.vy
- examples/tokens/ERC721.vy
https://vyper.readthedocs.io/en/v0.1.0-beta.10/structure-of-a-contract.html#built-in-interfaces
> Import built-in interfaces in token examples

- tests/parser/types/test_string.py
Made more explicit the testing of strings longer than 32 bytes
Updated the tests in `types/test_string.py`
`make test` or `pytest -k types/test_string.py`
Made more explicit the testing of strings longer than 32 bytes
> Added clearer tests for string comparison using `keccak256`

- tests/parser/features/external_contracts/test_external_contract_calls.py
- vyper/parser/external_call.py
Add Support for ListType in external contract call output and added tests
> Add Support for ListType in external contract call output

- .gitignore
- tests/parser/features/test_logging.py
- tests/parser/syntax/test_logging.py
- vyper/parser/events.py
> Log indexed type mismatch

- .bumpversion.cfg
- snap/snapcraft.yaml
Have the bumpversion utility upgrade the version we upload to snapcraft
> Ensure snapcraft version matches setup.py

- .gitignore
- Makefile
Added snapcraft release process (for reference)
> Added snap build process and build files to gitignore

- README.md
Added some badges because who doesn't like badges?
> Added badgers for PyPI and Snapcraft release pages

- README.md
- add hovertext
- add Docker Hub badge/link
> Update badgers again

- tests/parser/types/test_bytes.py
- tests/parser/types/test_bytes_zero_padding.py
- vyper/parser/events.py
- vyper/parser/parser_utils.py
- vyper/parser/stmt.py
> Zero pad rounds fix

- docs/structure-of-a-contract.rst
Write words about what the nonreentrant decorator works. 
In english.
With a computer....
Read it, see if you like it. It could probably be improved tbh.
#############################################################
###################################################   #######
###############################################   /~\   #####
############################################   _- `~~~', ####
##########################################  _-~       )  ####
#######################################  _-~          |  ####
####################################  _-~            ;  #####
##########################  __---___-~              |   #####
#######################   _~   ,,                  ;  `,,  ##
#####################  _-~    ;'                  |  ,'  ; ##
###################  _~ …
> Document meaning of key in nonreentrant decorator

- docs/contributing.rst
We reference having a style guide, but did not have one
So I added it under "Contributing" in the docs
> Add style guide

- docs/release-notes.rst
Please add suggestions to what we should mention in the release notes for b13.
> Beta 13 Release

- docs/release-notes.rst
> Fixed line spacing issue

- docs/structure-of-a-contract.rst
> Use consistent indentation (PEP 8)

- tests/base_conftest.py
- tests/conftest.py
- tests/examples/market_maker/test_on_chain_market_maker.py
- tests/examples/safe_remote_purchase/test_safe_remote_purchase.py
- tests/parser/functions/rlp/conftest.py
Made some cleanup to the test suite to remove some monkeypatches using eth-tester's native genesis param API instead
> Test suite cleanup

- setup.py
- tests/parser/parser_utils/test_annotate_and_optimize_ast.py
- vyper/parser/global_context.py
Wanted to clean up the dependencies a bit. Ended up finding an issue with eth-tester v0.2 (#1645)
> Upgraded depedencies

- docs/structure-of-a-contract.rst
Updated docs for version pragma, fixes: #1449 
Added the section in the docs
Check the modified part
> Add docs regarding version pragma

- SECURITY.md
@trailofbits did an audit of @computablelabs's protocol, linking to the report here for future reference.
Announcement:
https://medium.com/computable-blog/computable-contract-audit-771e3d39ea7
> Added link to Computable Labs audit report

- setup.py
- tests/examples/safe_remote_purchase/test_safe_remote_purchase.py
> eth-tester upgrade

- vyper/optimizer.py
Fix #1306
see https://github.com/ethereum/vyper/issues/1306#issuecomment-548333651, it's not necessary
> Remove unused optimization

- examples/tokens/ERC721.vy
> Missing data type in comment

- docs/release-notes.rst
Please add suggestions to what we should mention in the release notes for b14.
> Beta 14 Release

- .github/workflows/test.yml
- Makefile
- README.md
- tox.ini
- upload_coverage.sh
These are some of the things I found that needed to be updated for the new organization
> Update to new organization

- .coveralls.yml
- .github/workflows/test.yml
- .gitignore
- README.md
- setup.cfg
I think coveralls isn't pushing because of the `parallel` flag being set when the API is called.
> Fix coveralls

- README.md
The nice folks over at Gitter have honored our request to move the gitter into it's own organization here: https://gitter.im/vyperlang/community
> Change Gitter Badge

- Makefile
> Remove coverage and other testing files on clean-test rule

- tests/cli/vyper_json/test_output_dict.py
- tests/parser/types/test_variable_naming.py
- vyper/cli/vyper_serve.py
- vyper/compile_lll.py
- vyper/compiler.py
- vyper/functions/functions.py
- vyper/opcodes.py
- vyper/optimizer.py
- vyper/parser/expr.py
- vyper/parser/global_context.py
- vyper/parser/lll_node.py
- vyper/parser/parser.py
- vyper/parser/pre_parser.py
- vyper/parser/stmt.py
- vyper/signatures/function_signature.py
- vyper/types/convert.py
- vyper/types/types.py
- vyper/utils.py
Wanted to make all constants uppercase
> Standardize Constants

- setup.py
- tests/parser/types/test_bytes_literal.py
- vyper/parser/expr.py
- vyper/types/convert.py
Found a location where f-string was missing
> Forgot f string

- README.md
Added the LGTM badge for Python. Also rearranged the badge in a more logical format.
> Add LGTM badge

- vyper/codegen/abi.py
- vyper/parser/parser_utils.py
- vyper/parser/stmt.py
> Minor fixes.

- vyper/parser/parser_utils.py
Fixed the missing `vyper.ast` import
> fix missing import

- vyper/types/types.py
Also, fixes: #1812 with better error message
> Used more specific error type

- tests/compiler/test_opcodes.py
- tests/parser/functions/test_bitwise.py
- tests/parser/functions/test_get_hash.py
- vyper/opcodes.py
Also added description about how to use the EVM versioning system
> Add ETC fork names

- vyper/parser/expr.py
Fix #1802 
Use `getattr` when checking for `self`
Run the tests.
> fix AttributeError when checking balance on non-address types

- docs/release-notes.rst
Please add suggestions to what we should mention in the release notes for b15
> Beta 15 Release

- .github/workflows/release.yml
Attempt at adding the Snapcraft release process to our CI
Copy the Makefile
I have no idea
> Add Snapcraft Release process

- SECURITY.md
> Add link to audit report

- .github/workflows/test.yml
- docs/conf.py
- docs/contributing.rst
- docs/index.rst
- docs/logging.rst
- docs/testing-contracts-brownie.rst
- docs/testing-contracts-ethtester.rst
- docs/testing-contracts.rst
- docs/types.rst
- examples/storage/advanced_storage.vy
- tox.ini
1. Expand the testing documentation to include examples using [Brownie](https://github.com/iamdefinitelyahuman/brownie)
2. Add a docs build to the CI, fix errors so that it passes
Magic.
Read the docs.
> Docs updates

- docs/compiler-exceptions.rst
- docs/index.rst
updated docs  index.rst file and added compiler-exceptions.rst file to the documentation.
Generated the errors on my terminal, used sphinx and get the docs to update the index and create the new page.  There are code examples and terminal output examples for most as well.  This is my first time using .rst and get the docs, and sphinx.  Please let me know about any formatting etc. that should be fixed.   I would have loved to get to including the links in the compile-time warnings, I just don't have the bandwidth for it at the moment.  I hope that jives.
Look for yourself.
Updated documentation to include compiler exception examples.
That's my cat.  Guess what her name is? 
My gitcoin profile is located here: 
https://gitcoin.co/adrianhacker-pdx   or 
sai address: …
> updated docs

- vyper/ast/nodes.py
Add missing source offsets to nodes.
1. When a node is missing an offset, apply that of the parent node.
2. To ensure a parent node always has it's offsets set prior to the creation of child nodes, I split `BASE_NODE_ATTRIBUTES` into `NODE_BASE_ATTRIBUTES` and `NODE_SRC_ATTRIBUTES`.
Run tests.
> Add missing source offsets to nodes

- docs/release-notes.rst
Please add suggestions to what we should mention in the release notes for b17
> B17 Release notes

- README.md
- docs/conf.py
- docs/contributing.rst
- docs/index.rst
- docs/style-guide.rst
- docs/testing-contracts-brownie.rst
- docs/testing-contracts-ethtester.rst
- docs/testing-contracts.rst
- docs/vyper-by-example.rst
1. Added a style guide within the documentation
2. Added a github contribution guide (it mostly points users to the one at readthedocs)
3. Various minor documentation updates and fixes.
If we're going to refactor this code, we need to do it from a unified front. By agreeing on and adhering to the same style and best practices we'll save a lot of headaches in the future, make the codebase more accessible to new contributors, and be less likely to end up with another iteration of where we are today.
Read the docs.  And please, be opinionated against me if any of this doesn't feel right.
> Style guide

- docs/style-guide.rst
> docs: clarify black line-length option

- tests/ast/nodes/test_evaluate_binop_decimal.py
- tests/ast/nodes/test_evaluate_binop_int.py
- tests/ast/nodes/test_evaluate_boolop.py
- tests/ast/nodes/test_evaluate_compare.py
- tests/ast/nodes/test_evaluate_subscript.py
- tests/ast/nodes/test_evaluate_unaryop.py
- tests/ast/nodes/test_get_children.py
- tests/ast/nodes/test_get_descendants.py
- tests/ast/nodes/test_replace_in_tree.py
- tests/ast/test_folding.py
- vyper/ast/README.md
- vyper/ast/__init__.py
- vyper/ast/folding.py
- vyper/ast/nodes.py
Add functionality for constant folding and replacing nodes within the AST.
* Add `evaluate` method to some Vyper node classes. This method returns a new node representing the literal value, or raises `InvalidType`.
* Add `Module.replace_in_tree` for replacing an existing node with a new one.
* Add `ast/folding.py` for high-level folding methods.
Run the tests. I've added additional cases using `hypothesis` to verify that the folding outcome is the same as the EVM output.
> Constant folding

- setup.cfg
> Add Pytest config file, so it doesn't bark

- docs/index.rst
- docs/versioning.rst
> Add versioning guideline

- tox.ini
@iamdefinitelyahuman was scurred
so I fixed it
> Remove isort from mypy

- .github/ISSUE_TEMPLATE/vip.md
> Add references to VIP template

- docs/structure-of-a-contract.rst
- setup.py
- tests/ast/test_pre_parser.py
- vyper/ast/pre_parser.py
Add semantic versioning to pragma checking.
Use semantic-version library to do the job.
There are tests.
Add semantic versioning to pragma checking.
> Add semantic versioning to pragma checking

- docs/compiler-exceptions.rst
Minor updates to the documentation on compiler exceptions.
This is to reduce the incoming diff on type checking.
Read the docs.
> update documentation on exceptions

- Dockerfile
- Makefile
- hooks/build
Already configured Dockerhub to automatically build `master` on every push, but it was failing with the current Docker setup
Thanks to these two articles
https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1
https://docs.docker.com/docker-hub/builds/
After merge, let's see if it updates...
Enabled automatic dockerhub builds on every push to `master`
> Add Dockhub Automated Build

- .gitignore
- Makefile
- setup.py
- tests/ast/nodes/test_evaluate_binop_decimal.py
- tests/ast/nodes/test_evaluate_subscript.py
- tests/ast/test_natspec.py
- tests/compiler/LLL/test_with.py
- tests/functions/folding/test_bitwise.py
- tests/functions/folding/test_len.py
- tests/parser/exceptions/test_invalid_same_variable_assignment.py
- tests/parser/features/test_assignment.py
- tests/parser/functions/test_empty.py
- tests/parser/functions/test_unary.py
- tests/parser/syntax/test_no_none.py
- tests/parser/syntax/utils/test_event_names.py
- tests/parser/syntax/utils/test_function_names.py
- tests/parser/syntax/utils/test_variable_names.py
- vyper/ast/annotation.py
- vyper/ast/natspec.py
- vyper/ast/nodes.py
- vyper/parser/external_call.py
- vyper/parser/parser_utils.py
- vyper/utils.py
- Added `dev` and `docs` optionals and organized them better
- cleaned up makefile and gitignore a bit
> Streamline Optional Dependencies

- docs/installing-vyper.rst
Reordered and streamlined the installation docs to put Docker first (to reduce the number of issues people have setting up vyper)
> Update Install Instructions

- vyper/cli/vyper_serve.py
> Fix type error in Vyper serve

- .github/workflows/test.yml
> Revert "Change actions trigger"

- tests/functional/context/conftest.py
- tests/functional/context/test_namespace.py
- tests/functional/context/types/test_pure_types.py
- tests/functional/context/types/test_type_from_abi.py
- tests/functional/context/types/test_type_from_annotation.py
- tests/functional/context/validation/test_potential_types.py
- tests/grammar/test_grammar.py
- tests/parser/exceptions/test_argument_exception.py
- tests/parser/exceptions/test_invalid_type_exception.py
- tests/parser/exceptions/test_structure_exception.py
- tests/parser/exceptions/test_variable_declaration_exception.py
- vyper/context/types/bases.py
- vyper/context/types/function.py
- vyper/context/types/indexable/sequence.py
- vyper/context/types/utils.py
- vyper/context/types/value/array_value.py
- vyper/context/validation/local.py
- vyper/context/validation/module.py
- vyper/context/validation/utils.py
- vyper/exceptions.py
* first round of unit tests for `vyper/context`
* refactor out `build_type_from_ann_assign`
* move function constancy checks to `FunctionNodeVisitor`
* properly handle ABI array types
Next up, refactoring (gutting) `parser`
Run the tests...  there are 930-ish new ones.
> Type check tests and refactoring

- tests/functional/context/types/test_pure_types.py
- tests/functional/context/types/test_type_from_abi.py
- tests/functional/context/types/test_type_from_annotation.py
- vyper/context/README.md
- vyper/context/types/__init__.py
- vyper/context/types/bases.py
- vyper/context/types/indexable/mapping.py
- vyper/context/types/indexable/sequence.py
- vyper/context/types/meta/interface.py
- vyper/context/types/meta/struct.py
- vyper/context/types/utils.py
- vyper/context/types/value/address.py
- vyper/context/types/value/array_value.py
- vyper/context/types/value/boolean.py
- vyper/context/types/value/bytes_fixed.py
- vyper/context/types/value/numeric.py
- vyper/context/validation/module.py
- vyper/context/validation/utils.py
- vyper/functions/functions.py
Rename pure type to primitive
lots of grepping
Read it.
> rename pure type to primitive

- tests/functional/context/types/test_type_from_annotation.py
- tests/parser/features/iteration/test_for_in_list.py
- tests/parser/globals/test_getters.py
- tests/parser/syntax/test_structs.py
- vyper/context/types/bases.py
- vyper/context/types/event.py
- vyper/context/types/function.py
- vyper/context/types/indexable/mapping.py
- vyper/context/types/indexable/sequence.py
- vyper/context/types/meta/interface.py
- vyper/context/types/meta/struct.py
- vyper/context/types/utils.py
- vyper/context/types/value/array_value.py
- vyper/context/types/value/numeric.py
- vyper/context/validation/local.py
- vyper/context/validation/module.py
- vyper/functions/functions.py
- vyper/parser/stmt.py
* Add `location` attribute to type objects, represent locations via an `Enum`
* Prevent use of mappings within structs (related issue: #1966)
* Constancy checks in `for` loops
* Remove more dead code in `parser/`
Run tests.
> Location and constancy logic

- vyper/context/types/meta/event.py
- vyper/context/validation/module.py
Refactor `Event` so it's created via a classmethod.
Run tests.
> refactor: create Event from classmethod

- tests/parser/types/value/test_as_wei_value.py
- vyper/functions/functions.py
* Add overflow check for `as_wei_value` when the given value is `uint256`
* Use correct math for `int128`
* Revert on negative values
Fixes #1637 
Modificaions to  `vyper/functions/functions.py::AsWeiValue.build_LLL`
Run tests.  I added cases to verify the outputs and bounds checks.  I also removed an old test that's no longer useful, because the behavior it was testing is now being folded.
> Bounds checks for `as_wei_value`

- docs/types.rst
- tests/parser/syntax/test_code_size.py
- vyper/context/types/value/address.py
- vyper/parser/expr.py
Change the type of `address.codesize` to `uint256`.
With style and grace.
Run the tests.
> Change address.codesize type to uint256

- docs/release-notes.rst
- setup.cfg
- setup.py
Please add suggestions to what we should mention in the release notes
Depends on #2085 being merged
> 0.2.0 Release Notes

- setup.cfg
- setup.py
We don't really need bumpversion anymore, so there's no need to have to manually change the version in two places.
> Remove bumpversion

- docs/release-notes.rst
- setup.py
> Release v0.2.4

- README.md
> chore: add vyper.fun in README

- vyper/parser/stmt.py
Refactor `Stmt.parse_For`
* removed the `_is_list_iter` method in favor of a simple check that the iterator is or isn't a `range()` - because we can't get here without passing type checking, the original check is mostly redundant.
* move the range logic into an internal function `_parse_For_range` to be consistent with `_parser_for_loop`
* apply the block scope rules prior to calling either internal parsing function. Previously there was no scoping applied when parsing a list iteration.
* remove the final `del self.context.vars[var]` - this is handled by the scoping context context manager and so not required
Run tests.
> Refactor `stmt.parse_For`

- vyper/parser/context.py
- vyper/parser/memory_allocator.py
Apply fixes based on review of #2197
> Fixes re: memory scoping code review

- setup.py
> Pin web3py to v5.12.3 to solve encoding bug

- examples/crowdfund.vy
Adapted the assertion comments to match with the assertion
)
> Fix comments

- docs/interfaces.rst
Amended 'seperate' to 'separate' in interfaces.rst
> docs: fix typo in interfaces.rst

- tests/functional/context/types/test_event.py
- vyper/context/types/meta/event.py
Add `event_id` to new Event type objects.
See code, should be fairly easy to understand.
Run the test suite.  I added some new tests to verify the behaviour.
> Add `event_id` to new Event type objects

- docs/release-notes.rst
> Release Notes for v0.2.11

- examples/tokens/ERC20.vy
- tests/examples/tokens/test_erc20.py
Minor improvements to ERC-20 example
Minor improvements to ERC-20 example
> feat: improve ERC20 example

- tests/functional/codegen/test_abi_encode.py
- tests/parser/syntax/test_abi_encode.py
- vyper/builtin_functions/functions.py
Fix https://github.com/vyperlang/vyper/issues/2408
Try it out
Add method_id kwarg to _abi_encode builtin function
> Add method_id kwarg to _abi_encode builtin

- Makefile
- quicktest.sh
- setup.py
It's pretty small but makes testing a lot easier.
Add more pytest options
`make quicktest`
> add an alias for quicker test dev cycle

- docs/release-notes.rst
> fix v0.2.16 release notes rst syntax

- docs/release-notes.rst
- setup.py
- tests/parser/functions/test_return_struct.py
> chore: v0.3.0 release

- docs/release-notes.rst
> Add release notes for v0.3.1

- docs/release-notes.rst
> chore: fix typo(s) in release notes

- .github/workflows/build.yml
There's always v0.3.2 for automatic artifact generation
Check: https://github.com/skellet0r/vyper/actions/runs/1523836936
> fix: artifact generation regex

- setup.py
so downstream tools can handle it
for non-release versions, change
`0.3.2-dev2+g199c1cb6` to `0.3.2+commit.199c1cb6`.
Also this matches pre-v0.3.1 behavior.
> fix version string to be semver compatible

- setup.py
Update `pytest` version in `setup.py`.
#2561 
Check error message and `pytest` versions.
Run `python setup.py`.
Update pytest to v6.2.5.
> fix: update pytest version in setup.py

- docs/built-in-functions.rst
> docs: add docs for #2482

- docs/built-in-functions.rst
- docs/constants-and-vars.rst
- docs/event-logging.rst
- docs/scoping-and-declarations.rst
- docs/statements.rst
- docs/types.rst
Made minor improvements and updated type conversion table.
1. Read through documentation.
2. Refer to `vyper/builtin_functions/convert.py`.
See above.
Improvements to documentation.
> docs: minor improvements and update type conversion table

- vyper/lll/optimizer.py
> add an LLL optimization to fold constant ceil32

- .github/workflows/test.yml
- setup.py
- vyper/compiler/__init__.py
To raise `black` and `isort` lint errors in CI
WIP
WIP
> chore: raise black and isort lint errors in CI

- vyper/compiler/output.py
fix `-f metadata` for signatures with kwargs
> fix metadata kwarg serialization

- vyper/codegen/expr.py
rhs of `x in xs` could get evaluated multiple times, which might cause
multiple side effects to occur.
for instance,
```python
@internal
def foo() -> uint256[3]
self.counter += 1
return [0,0,0]
@external
def bar() -> uint256
self.counter = 0
t: bool = self.counter in self.foo()
return self.counter  # what is self.counter??
```
guard the rhs by caching the pointer when necessary
> fix multiple evaluation of haystack

- docs/types.rst
> docs: dynamic arrays

- docs/testing-contracts-brownie.rst
Fix missing curly bracket on doc for testing brownie
> Fix missing curly bracket on doc for testing brownie

- vyper/codegen/core.py
fix dynamic array validation when child type needs validation (https://github.com/vyperlang/vyper/pull/2640/files#diff-d791908f2752921e3a897668bf4c1ed864af3ee089228e1e0f21577bf1f33285R477)
```vyper
@external
def foo(b: DynArray[int128[5], 2]) -> DynArray[int128[5], 2]:
return b
```
modify `_needs_clamp` util to recurse into member types appropriately
merge this into @tserg 's test/dynarray branch and check that the clamper tests pass
fix dynamic array validation when child type needs validation
> fix _needs_clamp heuristic for dynarrays

- docs/types.rst
> doc: hex literals for Bytes no longer allowed

- docs/types.rst
- vyper/ir/README.md
> doc: update decimal bounds and reserved memory

- tests/parser/types/numbers/test_uint8.py
- vyper/builtin_functions/convert.py
- vyper/codegen/types/types.py
- vyper/utils.py
fix https://github.com/vyperlang/vyper/issues/2722, refactor conversion clamps to clarify the edge cases
this causes some codesize regressions, but i will address those in a follow up PR, once we can get #2714 in as guardrails
> conversion fixes

- tests/parser/functions/test_convert.py
- tests/parser/functions/test_unsafe_math.py
- vyper/builtin_functions/convert.py
- vyper/codegen/types/types.py
- vyper/utils.py
refactor conversion tests to cover more edge cases. also fix some minor bugs in literal handling, and update the bounds for decimals in generated code.
added more edge cases, and rewrote the test cases around a core "spec" function, `_py_convert`, which implements the conversion rules on python objects.
:eyes: 
> refactor conversion tests

- vyper/codegen/context.py
- vyper/codegen/self_call.py
add source location info so users know where to look for the issue
> improve FunctionDeclarationException error message

- vyper/cli/vyper_compile.py
it's easier to remember this way
> rename CLI option --ir-hex to --hex-ir

- docs/built-in-functions.rst
- docs/types.rst
- requirements-docs.txt
- document new types, conversion rules, unsafe math builtins
> docs: new types, conversions, builtins

- docs/types.rst
Fix errors in Types documentation.
Fix types documentation
Fix types documentation
> docs: minor fixes

- docs/release-notes.rst
add release notes for 0.3.2
check readthedocs build
> release notes for 0.3.2

- docs/release-notes.rst
> add v0.3.3 release notes

- vyper/builtin_functions/functions.py
> fix error message for min/max

- tests/parser/features/decorators/test_pure.py
- vyper/semantics/validation/local.py
> fix: calling pure functions from pure functions

- vyper/builtin_interfaces/ERC20Detailed.py
> fix: add view modifier to erc20detailed signatures

- docs/structure-of-a-contract.rst
> Fix small typo on contracts docs

- docs/interfaces.rst
> docs: update interfaces to use more idiomatic vyper

- docs/compiling-a-contract.rst
- docs/scoping-and-declarations.rst
- docs/types.rst
> docs: fix old description of reference types

- docs/built-in-functions.rst
- add a warning about deploying unguarded factories
- update some variable names
check the preview - https://vyper--2931.org.readthedocs.build/en/2931/built-in-functions.html#create_from_factory
> docs: factory code offset

- vyper/compiler/phases.py
replace manual caching of members with `@cached_property`
> chore: cleanup CompilerData class

- vyper/ast/signatures/function_signature.py
- vyper/codegen/function_definitions/common.py
enable tooling inspection of the memory frame
just export context.vars
> feat: add variable info to frames

- tests/parser/ast_utils/test_ast_dict.py
- vyper/compiler/output.py
Fix for #2955, until unfolded AST is stable.
> fix: update AST output

- vyper/codegen/core.py
- vyper/codegen/external_call.py
as title. some error messages were missing
> fix: add error messages for external call checks

- vyper/builtin_functions/functions.py
- vyper/evm/opcodes.py
add a breakpoint builtin; follow the syntax of python breakpoint() (PEP 553)
add a BREAKPOINT opcode 
> feat: breakpoint function

- vyper/builtin_functions/functions.py
hardhat's `print()` is compatible with only a pre-defined list of
signatures. add a new print mode which can handle any signature
see https://github.com/NomicFoundation/hardhat/issues/2666#issuecomment-1117183000, hopefully tooling will standardize around this
some slightly messy code
VM implementation here: https://github.com/vyperlang/titanoboa/blob/3e211f4fdfe3112482b4577584f50c1799bda2a5/boa/env.py#L74-L82
> feat: add generic mode to print

- vyper/builtin_functions/convert.py
- vyper/codegen/arithmetic.py
- vyper/codegen/core.py
- vyper/ir/optimizer.py
also reorder a couple constraints in safepow for clarity
> chore: change some `pragma: nocover` to `pragma: no cover`

- docs/compiling-a-contract.rst
> Docs — `compiling-a-contract.rst` Fixes

- docs/built-in-functions.rst
Result of method_id() example was missing.
Added the result
Publish result of method_id example
> docs: Add result of method_id() example 

- docs/built-in-functions.rst
> docs: document print modes

- tests/parser/types/numbers/test_signed_ints.py
- vyper/codegen/arithmetic.py
> fix: safepow constraints

- docs/release-notes.rst
> docs: add v0.3.5 release notes

- docs/release-notes.rst
> add release notes for v0.3.6

- vyper/compiler/README.md
- vyper/semantics/README.md
Fixed all the broken links in the READMEs throughout the repo.
Replaced the broken links with the correct link matching the files.
Check the .md files.
> fix: broken links in various READMEs

- README.md
> doc: add examples of `-f abi, -f bytecode`

- docs/built-in-functions.rst
document the gas stipend instroduced in #3158 
> doc: send() gas kwarg

- .github/workflows/test.yml
> chore(ci): cancel older jobs in same PR and same workflow

- vyper/semantics/README.md
Replace brownie with vyper in the example of how to import the `get_namespace` method.
Update brownie import with vyper
> Update brownie import with vyper

- docs/natspec.rst
> Change `@licence` to `@license` in NatSpec docs

- docs/built-in-functions.rst
- docs/control-structures.rst
- docs/statements.rst
- docs/types.rst
Updated some parts of the documentation to match the latest version of Vyper.
chore: update some documentation
> chore: update documentation

- vyper/semantics/environment.py
> fix: SelfT does not compare with address

- vyper/semantics/analysis/data_positions.py
- vyper/semantics/types/subscriptable.py
fix minor CI regressions introduced in 0bb7203b584e771b23536ba065a
> chore: fix lint

- vyper/ir/README.md
> docs: `unique_symbol` in IR

- docs/resources.rst
Fix broken markup
Manual fix
Resources page looks good
```
|\      _,,,---,,_
ZZZzz /,`.-'`'    -.  ;-;;,_
|,4-  ) )-,_. ,\ (  `'-'
'---''(_/--'  `-'\_)  Felix Lee 
```
> Fix broken reST on Resources page on Docs

- tests/ast/test_natspec.py
- vyper/ast/natspec.py
> chore: add `custom:` natspec tags

- docs/natspec.rst
> Add `custom` NatSpec tag to docs

- docs/control-structures.rst
> docs: add docs for default parameters

- .github/workflows/test.yml
the tests seem out of balance lately
> chore: update test durations file

- tox.ini
> chore: update black target to 3.11

- tests/parser/features/decorators/test_private.py
- tests/parser/syntax/test_logging.py
- vyper/semantics/analysis/local.py
> fix: disallow logging from pure, view functions

- README.md
microbadger appears defunct, switch to shields.io
switch lgtm to codeql
> chore: fix badges in README

- vyper/semantics/types/base.py
Fix inaccurate comment on `TYPE_T`.
```
chore: fix comment on TYPE_T
```
Fixed comment on TYPE_T
> chore: fix a comment

- docs/release-notes.rst
> chore: clean up 0.3.7 release notes formatting

- docs/release-notes.rst
> add v0.3.9 release notes

- docs/release-notes.rst
> chore: update v0.3.9 release date

- vyper/builtins/functions.py
> fix: send() error message

- vyper/codegen/function_definitions/external_function.py
- vyper/codegen/module.py
> fix: add error message for nonpayable check

- docs/release-notes.rst
> chore: update v0.3.9 release notes

- docs/release-notes.rst
> docs: shanghai is default compilation target

- .github/workflows/era-tester.yml
auto-detect vyper version
only run full llvm matrix on push to master
> chore: fix era compiler tester workflow

- vyper/evm/opcodes.py
per https://github.com/ethereum/EIPs/pull/7074
> chore: update tload/tstore opcodes per latest 1153

- vyper/semantics/analysis/module.py
- vyper/semantics/namespace.py
this makes it picklable, otherwise it fails with `_scope` not being available during `__setitem__`
> chore: add __new__ to Namespace

- tests/parser/features/test_assignment.py
follow on to #3410, add a test for storage assignments
> chore: test complex storage assignment

- docs/release-notes.rst
As titled.
ctrl x + ctrl v
```
docs: fix yanked version in release notes
```
> docs: fix yanked version in release notes

- docs/built-in-functions.rst
Fix #3505.
Add docs for `epsilon`.
See docs
```
docs: epsilon
```
Documentation for epsilon builtin.
> docs: epsilon builtin

- .pre-commit-config.yaml
> Change flake8 from gitlub to github

- docs/release-notes.rst
> chore: `v0.3.10rc1` release notes

- .github/workflows/build.yml
- .github/workflows/publish.yml
> chore(ci): publish pre-release (release candidate) builds

- .github/workflows/build.yml
> chore(ci): build binaries on pull requests

- setup.py
setup regression introduced in 294d97c2b853fb / #3593 
> fix: dependency specification for `packaging`

- README.md
Add a temporary banner at the top of the README to advertise the audit competition
Advertise the audit competition in README
Bold sentence and links
Let's audit it
```
,     ,
___('-&&&-')__
'.__./     \__.'
_     _     _ .-'  6  6 \
/` `--'( ('--` `\         |
/        ) )      \ \ _   _|
|        ( (        | (0_._0)
|         ) )       |/ '---'
|        ( (        |\_
|         ) )       |( \,
\       ((`       / )__/
|     /:))\     |   d
|    /:((::\    |
|   |:::):::|   |
/   \::&&:::/   \
\   /;U&::U;\   /
| | | u:u | | |
| | \     / | |
jgs | | _|   | _| |
/ \""`   `""/ \
| __|       | __|
`"""`       `"""`
```
> docs: add README banner about Vyper audit competition

- tests/parser/test_selector_table.py
- tests/parser/test_selector_table_stability.py
> chore: add tests for selector table stability

- vyper/codegen/function_definitions/common.py
- vyper/codegen/module.py
> chore: add notes to selector table implementation

- docs/compiling-a-contract.rst
> docs: mcopy is enabled with cancun target

- docs/release-notes.rst
> docs: fix nit in v0.3.10 release notes

- examples/tokens/ERC721.vy
- tests/functional/syntax/exceptions/test_invalid_payable.py
- vyper/semantics/README.md
fix typos
Commit message for the final, squashed PR.
> chore: fix typos

- docs/types.rst
Follow-up to #2937
```
docs: floordiv
This PR updates the documentation for the introduction of floordiv in #2937.
```
> docs: floordiv

- docs/index.rst
- docs/release-notes.rst
> docs: prepare v0.4.0 beta

- docs/release-notes.rst
> docs: fixup release date

- tests/conftest.py
- tests/unit/ast/test_ast_dict.py
- vyper/ast/nodes.py
- vyper/semantics/analysis/base.py
- vyper/semantics/analysis/local.py
export variable reads/writes in the ast
cc @ritzdorf @trocher 
> feat[tool]: export variable read/write access

- .github/workflows/build.yml
fix another regression from 730679bd553d with incorrectly setting the name of the file.
see test run at https://github.com/charles-cooper/vyper/actions/runs/8178816832/job/22363615165
> fix[ci]: release artifacts

- tests/functional/builtins/codegen/test_convert.py
> docs: typo in test comment

- FUNDING.json
Add a json file to verify Vyper on https://www.drips.network/app/projects
> chore[docs]: add `FUNDING.json` for drips funding

- FUNDING.json
Update funding.json for Optimism RetroPGF grant
> chore[tool]: update `FUNDING.json` for optimism RPGF

- vyper/venom/passes/sccp/sccp.py
small cleanup tasks for sccp pass. remove dead variables and stray comments.
> fix[venom]: clean up sccp pass

- docs/installing-vyper.rst
add installation instructions via `pipx` and `uv tool`. add a note that `pip install vyper` is not generally recommended to do site-wide.
> feat[docs]: add installation via pipx and uv

- README.md
> feat[docs]: add Telegram badge to README.md

- .github/workflows/test.yml
might fix some rate limiting errors we have been seeing recently. opening as draft to check the CI
> chore[ci]: update codecov github action to v5

- FUNDING.yml
```
Add link to Vyper on Giveth for GIVbacks eligibility:
https://giveth.io/project/vyper
```
> chore[docs]: add giveth to `FUNDING.yml`

- docs/release-notes.rst
> fix[docs]: update v0.4.1 release date

- tests/functional/examples/thirdparty/yearnfi/VaultV3.vy
fix warnings by updating the syntax for logs.
> fix[test]: fix warnings in thirdparty tests

- vyper/venom/basicblock.py
- vyper/venom/passes/float_allocas.py
```
add `annotation=` kwarg to `IRBasicBlock.append_instruction()`, and
some other small fixes to improve debugging
```
> refactor[venom]: add annotation to append_instruction

- docs/control-structures.rst
code block needs a line break to be formatted properly, otherwise it disappears.
thanks to @pcaversaccio for catching
> fix[docs]: fix code block rst formatting

- docs/release-notes.rst
> chore[docs]: add v0.4.2 release notes

- vyper/venom/passes/single_use_expansion.py
don't expand vars that are already single use.
> fix[venom]: reduce single-use expansion

- .gitignore
long overdue, add a bunch of folders that are commonly used by the developers in development workflows to the gitignore.
> chore[ci]: update gitignore

- tests/unit/cli/vyper_json/test_output_selection.py
- vyper/compiler/output.py
```
this commit adds metadata for functions which are only reachable from
the ctor.
```
> fix[tool]: add metadata for ctor functions

- docs/control-structures.rst
> feat[docs]: add docs for `@raw_return` decorator

- docs/release-notes.rst
> feat[docs]: add v0.4.3 release notes

- docs/compiling-a-contract.rst
> fix[docs]: change `"settings"` field to required
