vyperlang/vyper

.gitignore
README.md
examples/crowdfund.vy
viper

- Global type assignments were old in the example. 
- Added a .gitignore as I saw `__pycache__` dir generated
- a small cli tool called ./viper 
- examples dir to populate, in spirit of Serpent repo. 
What should viper file extension be? I chose *.vy but maybe *.py is enough

Fix type assignments in example

---

Makefile

This PR is in response to issue #276 and allows users to run `python setup.py install` with `make`

Fix make installation

---

.gitignore
Makefile
setup.cfg
setup.py
tests/test_invalids.py
tests/test_parser.py

Configuration of setup.py for py.test
Updates to .gitignore
setup.cfg added to produce terminal report and generate detailed html report
tests/test_invalids.py - updated to encapsulate each individual test for py.test via having must_fail/must_succeed add to a list of tests and running those tests at the end of the file, with an update stream-lining exception handling.
tests/test_parser.py - moved all logic after "setup" portion to be encapsulated in individual functions for py.test, with a small update to one of the print statements referencing the wrong code (fix in f4c13ec).

Move testing to use py.test

---

setup.cfg
setup.py

After this pull request is accepted, create a new tag with `bumpversion`

Add automatic versioning

---

tests/test_parser.py
viper/functions.py

This PR is in response to issue #310.  This PR changes `send` so that it throws on failure and tests the added functionality.  I tried to be as minimalistic as possible.

`send` throws on failure

---

tests/setup_transaction_tests.py
tests/test_invalids.py
tests/test_parser.py

PR related to https://github.com/ethereum/viper/issues/295
Added two functions:
1 - `gas_estimation_decorator`: wrap the ABI function and call `check_gas` after the contract function is called.
2 - `get_contract_with_gas_estimation` create the contract from the source code adding by default `language="viper"`, get  the functions from the contract and wrap the contract function to use `gas_estimation_decorator`. 
3 - `get_contract` create the contract from the source code adding by default `language="viper"`.
TODO
Note: We need to review `check_gas` in the future to make the function more accurate.

Wrapper contract_with_gas_estimation

---

setup.cfg
tests/examples/voting/test_ballot.py

I updated the test discovery option in `setup.cfg` so that pytest also looks into the subdirectories of `tests/`.
Additionally a small update to resolve an `ImportError` that was raised in one of the tests that wasn't being tested.
Changed `setup.cfg`
If you run `python setup.py test` without these changes, and again with these changes, you will see more tests being run in the latter case.
N/A

Fix test path

---

README.md
docs/installing-viper.rst

I've moved the installation instructions that were in the original README file to the docs.
Also added some extra instructions, and reworded some things for simplicity.
Just another step into getting #291 resolved. Similar things to #336, but moves a different section.
Moved things from README, and edited the text, and tried things using different operating systems.
Check out the pull request (it's my `docs-update` branch) and run a `make docs`.
Moved installation instructions and added information.

Moving installation instructions to documentation

---

bin/viper

- For easy copy-paste purposes, I found that I constantly had to convert the python ABI output from the command line, this just does a simple json.dumps to make it easier.
- Minor pep8 fixes in the same file.
Inserted a json.dumps ;)
Run `./viper_bin.py examples/crowdfund.vy -f json` and check the output.
Use JSON ABI output instead of python output (-f abi).

Format the ABI output to be JSON.

---

docs/index.rst
docs/structure-of-a-contract.rst
docs/types.rst
docs/viper-in-depth.rst

Added `structure of contract` and `types` pages to the docs.
I did it by looking at the Solidity docs for formatting and then added parts of the old readme file to the docs.
Clone down this branch and enter `make docs`

Move readme to docs

---

tests/parser/features/test_logging.py
tests/setup_transaction_tests.py
viper/compiler.py
viper/functions.py
viper/parser.py
viper/parser_utils.py
viper/signatures/event_signature.py
viper/types.py

I added the ability for developers to create events (using the logging evm opcodes).
This PR is in response to issue #346 and #297.
1)  Changed the abi output for events so that it'd show bytes maxlen (this `bytes3` instead of `bytes`). This was necessary for events logged to be decoded
1) Created the event signature class which shows the necessary information for events (`event_id`, `topics`, `data`, etc)
2) Added checks for logs at the top of files to the parser
3) Added `pack_logging_topics` and `pack_logging_data` to pack the logging args correctly (`pack_arguments` used a different format which didn't work with the abi decoder and used more memory)
4) Added the logging opcode itself with topics and args.
5) Added typ checking for logging
6) Created tests for logging (More still need …

Create event/logging functionality

---

tests/parser/types/numbers/test_num.py
tests/parser/types/numbers/test_num256.py
tests/test_invalids.py
tests/test_parser.py
viper/functions.py
viper/parser.py

Added support for num exponents (`num**num`) and num256 exponents (`num256_exp(num256,num256)`).  This pr is in response to issue #363.
I did it by parsing for `**` and `num256` and then utilizing the exponent opcode (`exp`)).
Look at my pr (especially the tests)
Support integer exponents

Add exponents

---

tests/parser/features/test_logging.py
tests/test_parser.py
viper/__init__.py
viper/signatures/__init__.py

Fixed logging tests timestamps and flake8 formatting to get travis passing.
Then I uncommented `ecadd` and `ecmul` because they now pass (they're reliant on Ethereum 2.0.5)
I did this by looking at what was broken and fixing it.
Check that travis is passing
None

Fix travis and uncomment ec tests

---

docs/installing-viper.rst
docs/old_readme.txt

Changed fancy quotes to normal quotes. If you copy paste, it will just export the variable with fancy quotes... and you won't know why `scrypt` is failing to install on Mac.
`grep -r "”" . -l`
Just check... also if you're developing on a Mac, disable this by default under `Preferences > Keyboard > Text`. 
- Replaced fancy quotes with normal quotes in the installation documentation.

Don't use fancy quotes

---

tests/parser/types/numbers/test_num256.py
viper/function_signature.py
viper/parser.py
viper/parser_utils.py
viper/types.py

- Altered the max values that get stored in memory for clamps to compare against.
- Added support for num(num256) function signatures.
- Edited base_type_conversion (Thanks @DavidKnott !)
- Applied changes in BaseType and canonicalize_type to generate the appropriate ABI signature.
Check tests and play with function using the `num(num256)` signature:
```
def _num256_to_num(x: num(num256)) -> num:
return x
```
Added support for num(num256) function signatures.

Add num256 to num casting (in function signature)

---

setup.py
viper/compile_lll.py
viper/compiler.py
viper/functions.py
viper/optimizer.py
viper/parser.py
viper/parser/parser.py
viper/parser/parser_utils.py
viper/parser/stmt.py

I broke the `parse_stmt` method out into it's own class.
1) Turned the `parse_stmt` conditional into a dictionary
2) Move `parser.py` into a parser folder
3) Create a seperate `stmt.py` file
Look through my PR to make sure my refactors increase simplicity and don't change any functionality.
None

Refactor parser parse_stmt method

---

tests/parser/features/test_logging.py
viper/parser/parser.py
viper/parser/stmt.py

Refactored the logging functionality and added support for logging the same event with topics multiple times.  This PR is in response to #373
I cleaned up how event topics and data are parsed.
Look at my pr, particularly the test I added: `test_logging_the_same_event_multiple_times_with_topics`
None

Fix repeated logging with topics

---

bin/viper
bin/viper-serve

Fix fails paths so that `viper` and `viper-serv` commands work.
I did this by looking at where `parser.py` was located.
Look at my PR
None

Fix file pathing to parser.py

---

tests/parser/features/test_external_contract_calls.py
viper/parser/parser.py

I added a check to external contract calls so that they can't be used internally.
I did this by checking that the `external_address != current_address`.
Look at the test I wrote.
None

External contract calls cannot be used internally

---

tests/parser/functions/test_is_contract.py
viper/parser/parser.py

Added `is_contract` attribute to addresses which returns a bool telling wether the given address is a contract or not.  In response to #365.
I expanded upon the existing `codesize` address function.
Look at my pr / try using it in your code.
Add is_contract

Add is_contract address attribute

---

setup.py

Upgraded the required version of `pyethereum` from `2.0.5` to `2.1.0`.
Simply updated `setup.py`
Passed CI
None

Upgraded the required version of pyethereum to 2.1.0

---

examples/safe_remote_purchase/safe_remote_purchase.v.py
tests/examples/safe_remote_purchase/test_safe_remote_purchase.py

Implemented and cleaned up the "Safe remote purchase" from the Solidity documentation (https://solidity.readthedocs.io/en/develop/solidity-by-example.html#safe-remote-purchase)
Edit: Fixed missing spaces in last line.
Translated the code from Solidity to Viper.
Differences:
- Used selfdestruct() where applicable
- ~~Locked state is determined by the contract balance~~ Didn't pass tests and could be exploited.
- Comments explaining transaction details added
- Value does not need to be a multiple of two
Auditing code. Test cases could be implemented.
Added "Safe remote purchase" example

Added safe remote purchase example

---

README.md
docs/old_readme.txt

Updated 'eth-viper.readthedocs.io' to 'viper.readthedocs.io'
```bash
bash:~/viper$ grep -r "eth-viper" .
```

Update 'readthedocs' URL from 'eth-viper' to 'viper' (yay!)

---

tests/parser/types/numbers/test_num256.py
viper/functions.py

Added overflow protection to `num256` functions.
I did this by looking at Solidity's `SafeMath.sol` and writing it in `LLL`.
Look at the tests I added, especially the ones that fail because of overflow.
Add num256 overflow protection

Add overflow protection to num256 functions

---

viper/signatures/event_signature.py

I was fooling around with logs and noticed the exceptions for reserved and duplicate wouldn't post because of `arg.arg` where `arg` is a string (and therefore doesn't have an inner member arg)
Run a test raising these two exceptions and verify that they now show you what specific log argument is reserved or duplicated
Bug with Log Exceptions

BUG: Log exceptions have error and don't post the right message

---

tests/parser/functions/test_return_tuple.py
tests/parser/syntax/test_return_tuple.py
viper/function_signature.py
viper/parser/parser.py
viper/parser/stmt.py
viper/types.py

Contracts can return tuple types now.
*Note* this doesn't cover tuple assignment yet.
- Patched function signature.
- Altered parse_return in stmt.py, lots of work to handle dynamic type in the tuple (ByteArray only for now).
- More details have be placed in the commits ;)
Check the tests.
Added support for return a tuple from a contract.

Return tuple support

---

viper/functions.py
viper/parser/expr.py
viper/parser/parser.py
viper/parser/stmt.py

Refactor the `parse_expr` into `Expr` class.
I pulled out all `parse_expr` functionality into its own file and changed the conditional checks into a dictionary.
This can be verified by looking over my pr and making sure that I haven't changed any functionality (only how it looks).
None

Break expr related functions in Expr class

---

tests/parser/exceptions/test_parser_exception_pos.py
viper/exceptions.py
viper/parser/parser.py
viper/parser/parser_utils.py
viper/parser/stmt.py

- Added optional pos parameters, which can be used by various TypeMismatchException 's to show the programmer where the error occurred.
- #415 
Looked at TypeMismatchException ;)
Example program:
```python
x: num
def __init__():
self.x = "test"
```
Will generate a more useful exception now:
```
viper.exceptions.TypeMismatchException: line 5:4 Base type conversion from or to non-base type: bytes <= 4 num
```

Add extra line numbers to exceptions.

---

tests/parser/functions/test_only_init_abi.py
viper/compiler.py
viper/parser/parser.py

Fixes single __init__ function contract error in mksignature. See #423
- Looked at how gas_estimate interprets the LLL code layout, doesn't take into account a scenario where there are no additional function after the init code section.
Check test, create a a single __init__() contract.

Fixes generating of ABI, if only __init__ function exists.

---

tests/parser/features/test_gas.py
viper/parser/expr.py

Add msg.gas call functionality.
Add lines on msg.gas into expr.py and create test_gas.py for tests.
You can now use `msg.gas` in a contract to check for remaining gas.
Add msg.gas call functionality.

Add msg.gas functionality

---

tests/parser/features/test_logging.py
tests/setup_transaction_tests.py
tests/test_parser.py
viper/parser/parser_utils.py

Changed how `for` loop gas estimates are calculated.
Now `gas estimation` has to to be at most 1.5 times the `actual`.
Temporarily change the optimizer's lowering of gas estimates, this feature will be re-added after all gas estimation is over the actual gas costs.
Now it's based of the number of rounds the loop's iterating.
Look at the code I added to `parser_utils.py`
None

Improve gas estimation

---

tests/parser/features/iteration/test_range_in.py
viper/parser/expr.py
viper/types.py

Implements #428, we can now use `x in [1, 2, 3, 4]` syntax :smiley_cat: 
- Added handling for the specific case in expr.py/Expr.compare function.
Check tests, and write some code:
```python
allowed: num[10]
def set():
self.allowed = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
def in_test(x: num) -> bool:
if x in self.allowed:
return True
return False
```

If in a list support

---

viper/parser/expr.py
viper/parser/parser.py
viper/utils.py

Switch logging topic packaging to compile time to save gas.
Move string literals translation (`strings to bytes`) to the compiler level instead of the evm level.
Look at the code I changed to make sure the end functionality is the same.
None

Fix logging gas estimation

---

tests/parser/exceptions/test_variable_declaration_exception.py
tests/parser/globals/test_setters.py
viper/parser/parser.py

Globals could contain reserved words. I added a check for "is_varname_valid()".
See "parser.py".
Additionally, "test_setters.py" had to be changed, since it contained the opcode "pop" as a variable.
See "test_variable_declaration_exception.py".
Globals can not have invalid names anymore.

Added 'is_varname_valid()' check for globals

---

docs/installing-viper.rst

little doc fix
find it when i install viper
i don't know if it is ok while os is not Ubuntu16.04
fix it when install python3.6 and use virtualenv
: -D

fix the problems when install viper in Ubuntu16.04

---

tests/parser/features/iteration/test_for_in_list.py
tests/parser/syntax/test_nested_list.py
viper/parser/parser.py
viper/parser/stmt.py

#438 
- Adds support for, `for i in list` syntax. Allowing you to iterate over lists.
- Alter Stmt.parse_for, and added Stmt.parse_for_list function.
Check tests ;)
Something like this will work now:
```python
def data() -> num:
s = [1, 2, 3, 4, 5, 6]
for i in s:
if i >= 3:
return i
return -1
```
Adds support foreach like for statements.

For in list support

---

tests/examples/tokens/test_vipercoin.py
tests/setup_transaction_tests.py

Added `get_logs()` function to retrieve the list of logs produced by a contract in a given receipt, optional filtering argument to only collect logs of a specific type
Changed `get_log` fixture to use this new function (returning the last log in the filtered list)
Tests all work, let me know if there are any concerns
Added get_logs(), redefined get_log fixture to use get_logs()

Added method to get list of logs with optional filtering

---

examples/stock/test_company.py
tests/examples/auctions/test_simple_open_auction.py
tests/examples/safe_remote_purchase/test_safe_remote_purchase.py
tests/examples/tokens/test_vipercoin.py
tests/examples/wallet/test_wallet.py
tests/parser/features/test_external_contract_calls.py
tests/parser/features/test_logging.py
tests/parser/types/numbers/test_num256.py
tests/setup_transaction_tests.py

I noticed that `assert_tx_failed()` fixture required a reference to `tester` that could just be referenced internally, fixing some usage issues people have been having. I wanted to also get rid of needing `lambda: ` but couldn't at this point
Greped for all uses in `tests/` and updated `setup_transaction_tests.py`
Check out what tests I changed
Run pytest
Modified assert_tx_failed() to remove reference to tester as tester reference was already provided internally

Remove tester ref from assert_tx_failed()

---

bin/viper
tests/parser/features/decorators/test_internal.py
tests/parser/features/test_assignment.py
tests/parser/features/test_clampers.py
tests/parser/features/test_gas.py
tests/parser/functions/test_is_contract.py
tests/parser/functions/test_return_tuple.py
tests/parser/globals/test_setters.py
tests/parser/types/numbers/test_decimals.py
tests/parser/types/numbers/test_num.py
tests/parser/types/numbers/test_num256.py
tests/parser/types/test_bytes.py
tests/parser/types/test_lists.py
tests/parser/types/test_string_literal.py
tests/test_parser.py
viper/opcodes.py
viper/parser/parser_utils.py

- Added --show-gas-estimates to work with -f ir; this was really helpful in for to figure out what is going on with the gas estimates on the LLL level. So I figured it can be added for more improvement ;)
- Replaced get_contract with get_contract_with_gas_estimation in most places, internal/external call tests abd RLPList are still outstanding, but are perfect for another PR (this one is quite a number of changes already).
Started replacing get_contract with get_contract_with_gas_estimation. Starting at the LLL, checking the gas estimate tree and then a bit of trial and error on each test cases the subsequently failed.
Run the tests, and check out --show-gas-estimates..
Improved gas estimates.

Fixes some gas estimates

---

tests/compiler/test_clamps.py
tests/conftest.py
viper/compile_lll.py

Fixed clamps in `compile_lll.py`
Added a fixture to make it easier to test `LLL`
Created `LLL` clamp tests
In response to issue #450, thanks @daejunpark
Corrected clamp constant checks in `compile_lll.py` 
Look at the tests I created in `tests/compiler/test_clamps.py`.
None

Fix issue #450: buggy translation of constant clamp expressions

---

viper/functions.py

Get `RLPlist` function's `gas_estimate` closer to the actual amount of gas used.
Kept reducing the `gas_estimate` without allowing it to go under the actual amount of gas used.
Look over the gas numbers I changed for `_RLPlist` in `functions.py`
None

Improve rlp list gas estimation

---

.github/ISSUE_TEMPLATE.md
.github/VIP_TEMPLATE.md
docs/contributing.rst

Create VIP (Viper Improvement Proposal) template to facilitate discussion around the addition features to Viper. 
I looked at the Ethereum EIP (Ethereum Improvement Proposal) template and took what I felt would be relevant for Viper
Read the template
None

Create vip template

---

tests/examples/company/test_company.py
tests/parser/features/test_external_contract_calls.py
viper/opcodes.py
viper/parser/parser.py

Waiting to merge STATICALL or any byzantium features for the next ~30 days.
Add the `staticcall` opcode for `@constant` calls.
Parser now checks if a function is `constant` made before making a call.
Look at the test I added.
Add staticcall opcode for constant function calls

Add staticcall opcode for constant external function calls

---

tests/parser/exceptions/test_structure_exception.py
viper/parser/parser.py
viper/parser/stmt.py

Fixes #410 adds tests.
Figured out it has to do with `.value` attribute on annotate assign.
The following will fail to compile now:
```python
def foo() -> num:
q:num = 111
return q
```
Fixes ambiguous assign on annotate syntax.

Add checks preventing assigning values on defining types.

---

tests/compiler/LLL/test_repeat.py
viper/compile_lll.py

Fix `repeat` LLL in `compile_lll.py` so that it throws if `iteration_count <= 0`
Fixes #451, thanks @daejunpark
Added a conditional the checks for invalid iteration counts
Look at the code I changed
None

Fix issue #451: buggy translation of `repeat` when #iteration <= 0

---

tests/compiler/test_sha3_32.py
viper/compile_lll.py

Fix issue #448: compile_lll.py: buggy translation of LLL operator `sha3_32`
As suggested in #448.
Look over the change made and verify that all tests are still passing.
None
```
__   __
__ \ / __
/  \ | /  \
\|/
_,.---v---._
/\__/\  /            \
\_  _/ /              \
\ \_|           @ __|
hjw \                \_
`97  \     ,__/       /
~~~`~~~~~~~~~~~~~~/~~~~
```

fix issue #448: buggy translation of LLL operator `sha3_32`

---

tests/compiler/LLL/test_with.py
viper/compile_lll.py

Fix `with` statement error in `compile_lll.py` which led to `SWAP17` turning into `LOG0` (because `SWAP17` doesn't exist)
Fixes issue #449, thanks @daejunpark 
Added a conditional that throws with a with statement that's too deep.
Look at the code I added
None

Fix issue #449: inconsistency in checking invalid cases

---

tests/parser/features/iteration/test_range_in.py

Added `@public` to three tests that didn't have it.
Found three tests without the `@public` decorator that should have it.
Look at my PR
None

Add public decorator to tests

---

docs/index.rst
docs/structure-of-a-contract.rst
viper/function_signature.py

Made the example in "Structure of a Contract / Functions" correct.
Clarified the error message when visibility declaration is missing.
Added `@public` to the example in the Structure of a Contract / Functions.
Changed `function` to `def` in that example (that's correct right?)
Added a hint to the error message that it expects `@public` or `@internal`
Documentation and error message updates

function visibility doc and error message updates

---

snap/snapcraft.yaml

This package will let you publish the latest viper in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery. That will release every change in the master branch to the edge channel in the store, were it can be tested by early adopters before releasing to the stable channel.
A snap package for viper.
Addinng the metadata file and running the snapcraft command.
In Ubuntu 16.04 or later, call snapcraft on the root of this branch.
Add the packaging metadata to build the viper snap

Add the packaging metadata to build the viper snap

---

docs/installing-viper.rst

This requiries #445, and enabling the continuous delivery on https://build.snapcraft.io
Added instructions to install the viper snap
I fought a little with rst syntax :)
After #445 lands and the snap is published to the edge channel in the store, run the documented command.
Add the install instructions for the Viper snap
(I only have one cute animal, sorry)

Add the install instructions for the Viper snap

---

viper/types.py

Fix https://github.com/ethereum/viper/issues/488
Remove duplication of `ceil32()` method.
Remove the definition in `types.py` and import `utils.ceil32` there.
```sh
$ git grep "def ceil32"
viper/utils.py:def ceil32(x):
```

types.py: Remove duplicated method

---

bin/viper
tests/compiler/test_bytecode_runtime.py
viper/compiler.py
viper/parser/parser.py

Adds -f bytecode_runtime support. For populus integration the runtime bytecode is required, this adds a format to the viper binary. The solc equivalent would be: `--bin-runtime`.
Came up for the populus integration. Traced the lll output from -f ir.
Hmm not sure, place a debugger in `def compile` and check the lll value.
Adds support for -f bytecode_runtime.

Adds -f bytecode_runtime support.

---

tests/parser/features/test_assert.py
viper/compile_lll.py
viper/opcodes.py

Assert now uses the `revert` opcode behind the scenes so gas is refunded when it's used. 
This PR is in response to VIP #478 
I added in the revert opcode and changed `assert` in `compile_lll.py` to use `REVERT` instead of `PC, JUMPI`.
Look at `test_assert.py` to verify that unused gas is actually being refunded.
Modify assert to use revert opcode

Use revert opcode for assert statements

---

tests/conftest.py
tests/examples/auctions/test_simple_open_auction.py
tests/parser/features/arithmetic/test_modulo.py
viper/parser/expr.py

Added a non zero clamp to modulo between `num%decimal`.
This PR is in response to #493 @yzhang90
Created a test that should throw an error (`1 % 0`) and changed the `LLL` so that it now throws an error.
Look at the LLL and tests I added.
None

Fix modulo doesn't clamp_nonzero when divisor is decimal

---

examples/tokens/vipercoin.v.py
tests/examples/tokens/test_vipercoin.py

Change `transfer` and `transferFrom` to throw if conditions are invalid instead of returning false.
This PR is in response to #505 
Changed the `test_vipercoin.py` to expert `TransactionFailed` as opposed to `False`.
Changed `vipercoin.v.py` to pass the new test requirements.
Look at the tests/code I changed.
None

Change vipercoin from returning false to throwing

---

viper/parser/parser_utils.py

Use `with` statement to decrease gas costs.
I saw some `LLL` on gitter that looked repetitive so I looked for where it was being created and refactored it. 
```
def foo():
v = "abc"
```
Run the following benchmark with and without my PR and confirm the following results:
Decreases deployment by ~7,000 gas saving
Decreases function call by ~10,000 gas saving
None

Use `with` to decrease gas costs

---

tests/parser/functions/test_as_num256.py
viper/functions.py

Add a signed check to `as_num256` that throws if `as_num256` is called on a negative input (`num256 is unsigned).
This PR is in response to #469
I created a test that called `as_num256` on a negative value and then I made it fail.
Look at the test I created.
None

Add check to as_num256 to make sure number is greater than 0

---

viper/function_signature.py
viper/parser/parser.py

Make the error show the line number.
By passing the ast object into the exception and conversion function.
Test code
```py
SomeLog: __log__({
_var: num256
})
some_var: num
def some_func(a: num):
log.SomeLog(self.some_var) # Error here
```
Stack trace
```
viper.exceptions.StructureException: line 8: Function visibility must be declared (@public or @internal)
def some_func(a: num):
```
```
viper.exceptions.TypeMismatchException: line 9: Typecasting from base type num to num256 unavailable
log.SomeLog(self.some_var)
-------------^
```

Show lineno and code on bunch of error

---

docs/index.rst
docs/old_readme.txt
docs/structure-of-a-contract.rst
tests/parser/features/decorators/test_private.py
tests/parser/features/decorators/test_public.py
tests/parser/syntax/test_invalids.py
viper/function_signature.py
viper/parser/parser.py

Implements https://github.com/ethereum/viper/issues/471.
Was quite simple, just renamed internal in function_signature.py to private, and then replaced all other occurrences.
Compile something like:
```python
@private
def _add(a: num, b: num) -> num:
return a + b
@public
def add(a: num, b: num) -> num:
self._add(a, b)
```
And check/ttest the abi and contract output.

Change @internal decorator to @private decorator.

---

tests/parser/features/test_logging.py
viper/parser/parser.py
viper/parser/stmt.py

Add a check to make sure the number of logging arguments inputed match the number of  logging arguments declared.
Fixes #519 
Add support for data byte arrays of different sizes.
Fixes #520
Added a conditional that checks to make sure a log is receiving the correct number of arguments.
Change the offset of `bytearray_to_num` to be the `maxlen` of a bytearray though this needs to be refined further (I'm thinking in a future PR) because the current bytes output padding is reversed (see below):
```
MyLog: __log({arg1: bytes <= 20})
def foo(_arg1: bytes <= 20):
log.MyLog(_arg1)
```
```
c.foo('hello')
outputs => b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00hello'
should be => b'hello\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
Look at the tests I added …

Add logging error to argument number mismatch and improve bytes support

---

tests/parser/exceptions/test_invalid_literal_exception.py
viper/parser/expr.py

Fix for #504 clamping of decimal literal.
Just used suggested limit of den * MAXNUM/MINNUM & added test.
Check test.

Clamping decimal literals correctly.

---

tests/parser/types/numbers/test_num.py
viper/parser/expr.py

Fix incorrect exponents when dealing with units so that now the following is invalid:
```
+def foo():
a: num(wei)
b: num(wei)
c = a ** b
```
Fixes #530 
Created a test that shouldn't work and made it invalid.
Look at the tests I added in `test_num.py`
None

Fix exponents with units

---

tests/parser/syntax/test_list.py
viper/parser/stmt.py

Adds Fix #531.
Was a bit trickier to detect the subtypes, I opted using split() because it interprets nested lists as well, without having to chain down to subtype.typ.subtype scenario, using `re` was actually the cleaner option! :smile:  
Check the issue #531, basically return a list of a different type.
N/A

 Check return type of lists match.

---

tests/parser/features/external_contracts/test_external_contract_calls.py
viper/function_signature.py
viper/parser/expr.py
viper/parser/parser.py
viper/parser/stmt.py
viper/types.py

Make it possible to declare contracts as discussed on the bimonthly Viper call:
The following syntax can now be used to make external contract calls:
```
contract_1 = """
@public
def bar() -> num:
return 1
"""
contract_2 = """
class Bar():
def bar() -> num: pass
bar_contract: Bar
@public
def foo(contract_address: contract(Bar)) -> num:
self.bar_contract = contract_address
return self.bar_contract.bar()
"""
c1 = get_contract(contract_1)
c2 = get_contract(contract_2)
assert c2.foo(c1.address) == 1
```
1) Allow for external contracts to be used when declaring variables
2) Create a special contract data type that can be used to save the address of an external contract
Look at the tests I added and make sure that I didn't break any existing functionality
Add contract data type

Create contract data type

---

setup.py

Updated the version of `ethereum` to 2.1.3. `make init` fails right now because `setuptools` v38 doesn't like `sets` or `dicts` anymore. See this commit in pyethereum for the fix there: https://github.com/ethereum/pyethereum/commit/6b6f9a8e27dc3c2a4fb3ba095a8c96849e22c0a0
The error I get while installing the current master is as follows:
```
Collecting ethereum==2.1.0 (from -r requirements.txt (line 1))
Downloading ethereum-2.1.0.tar.gz (156kB)
100% |████████████████████████████████| 163kB 2.8MB/s
Complete output from command python setup.py egg_info:
error in ethereum setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Unordered types are not allowed
```
Updated install_requires in setup.py.
Attempt the installation …

Update version of ethereum

---

tests/parser/features/test_internal_call.py
viper/functions.py
viper/optimizer.py
viper/parser/expr.py
viper/parser/stmt.py

- Improve internal contract call gas estimates.
- Added annotations so the LLL repr is easier to read.
Found places in expr.py & stmt.py were internal calls are handed, then looked up the gas of those calls.
Check tests ;)

Internal contract call gas estimates

---

docs/viper-by-example.rst
examples/safe_remote_purchase/safe_remote_purchase.v.py

Split comments over two lines where necessary to fit on the page on readthedocs in the safe remote purchases example Python code. Update Safe Remote Purchases doc: line numbers, minor edits.

Split comments over two lines and minor edits: safe remote purchases

---

docs/installing-viper.rst

Related:
https://github.com/ethereum/viper/issues/573

Add a note on how to fix `fatal error: openssl/aes.h: No such file or directory` in the `make` output

---

docs/installing-viper.rst

For setting up a virtual environment command, I modified the interpreter to python3.6 instead of the path to python3.6, which in my case the former did work while the latter didn't.
Related: https://github.com/ethereum/viper/issues/558

virtualenv -p /usr/local/lib/python3.6/bin/python3 > virtualenv -p python3.6

---

viper/parser/stmt.py

Improve for loop error message. @khotkevych is is this error clearer?
Fixes #562 
Looked at what caused the error and changed the error message to match it. 
Look at the error I changed.
None

Improve for loop error

---

tests/parser/features/test_logging.py
viper/signatures/event_signature.py

Added length checking to event topics
Fixes #546 
Moved the length check outside of a conditional in `event_signature.py` so it's never skipped
Look at the tests I added
None

Add length check to event topics

---

tests/parser/exceptions/test_invalid_payable.py
tests/parser/features/external_contracts/test_external_contract_calls.py
tests/parser/syntax/test_invalids.py
tests/parser/syntax/test_list.py
tests/parser/syntax/test_missing_return.py
viper/parser/parser.py
viper/parser/stmt.py

Partial fix for #590.
Check for a minimum of 1 return statement if specified.
Added a count in the function context.
```python
@public
def foo() -> num:
pass
```

Check for missing return statement

---

docs/viper-by-example.rst

add a comma > to vote, and each
add a comma > to vote, or

Minor edits voting: added commas

---

Dockerfile
Makefile

Modified the Dockerfile to use http://label-schema.org/rc1/ syntax to label the docker image and switched the base image to use the latest slim 3.6 base image.
This decreases the docker image size from `740MB` to `278MB` without any usage/compatibility changes.
- Removed deprecated `MAINTAINER` directive.
- Added new `LABEL` directives adhering to `label schema` specific to the repository.
- Modified the base image from `python:3.6` to `python:3.6-slim`
- Modified installed dependencies to install only whats necessary and purge them following build of package.
- Switch from cloning the github repository to using the existing repository, since we're already in the repo.
- Run `make docker-build`
- Switch Dockerfile to `python:3.6-slim` from `python:3.6` to decrease size from `740MB` to …

Update dockerfile to use slim image base

---

tests/parser/features/test_logging.py
viper/signatures/event_signature.py
viper/types.py
viper/utils.py

Change `event_signature.py` so that types with units can be logged as data.
Fixes #525 
Looked at where units were being interpreted in `event_signature` and changed it to allow units be parsed correctly.
Look at the test I added.
None

Fix logging with units

---

docs/built-in-functions.rst
docs/viper-in-depth.rst

Created a docs page for Vipers built-in functions
Looked over the functions  in `functions.py` and wrote documentation for them.
Read the documentation
None

Add built-in function docs

---

tests/parser/types/numbers/test_num256.py
viper/functions.py

Add num256 modulo checks to make sure that `num%zero` throws.
Thanks @yzhang90 
Added `assert_tx_failed` tests with `num%zero` and got them to throw.
Look at the tests I added
None

Add num256 modulo math checks

---

tests/compiler/test_calldatacopy.py
viper/parser/parser_utils.py

Change gas estimation to account for unknown copy sizes.
Fixes #594 
Looked at what was failing and fixed it.
Look at the test I added
None

Fix call data copy gas estimation

---

docs/index.rst
tests/parser/features/iteration/test_continue.py
viper/compile_lll.py
viper/opcodes.py
viper/parser/stmt.py

Implement `continue` which skips to the end of an iteration in a `for` loop.
Looked at how `break` works and added `continue`.
Added a `JUMPDEST` to where `continue` skips to.
Look at the tests I created.
Implement `continue`

Implement continue

---

examples/tokens/ERC20.v.py

Discovered that it doesn't compile by trying to compile all of the
example contracts in `examples/`. This fixes ERC20.v.py by resolving
compiler complaints.
Fixed compilation of `ERC20.v.py` in `examples/tokens`
Addressed compiler complaints by adding `@public` to all the public functions (which was all of them).
The easy way:
```
viper examples/tokens/ERC20.v.py
```
Verify that all examples compile:
```
find examples/ -name "*.v.py" | parallel -j1 "viper {}"`
```
Fix example ERC20 token

Fix example ERC20 token compilation

---

tests/parser/features/test_internal_call.py
viper/parser/parser.py

Add an arg count for internal function calls as previously internal function calls with more args then expected were allowed to compile.
Realized that the following was allowed to compile:
```
def foo():
pass
def bar():
self.foo(1)
```
Look at the test I added.
None

Add internal call arg count check

---

tests/parser/syntax/test_unit_exponents.py
viper/parser/expr.py

- Fixes #547.
- Correct builds unit type when using ` ** `.
See changes on `Expr.arithmetic`.
```python
@public
def foo():
a : num(wei)
b : num(wei**2)
a = 2
b = a**2
````
N/A

Fix unit exponent expressions

---

tests/parser/exceptions/test_undef_function.py
viper/parser/expr.py

Previously, the compiler would error ungracefully if an undefined top-level function was called, due to an unhandled case in `Expr.call`. I filled in the missing case so that an appropriate error is raised instead.
I also made it so that the compiler offers suggestions when a non-existent top-level function
is mistakenly called instead of a contract method, e.g. `bar(..)` instead of `self.bar(..)`.
I modified the existing handling of top-level functions in `Expr.call` so that the case where the function name is _not_ in the `dispatch_table` is handled correctly.
Run the tests in `tests/parser/exceptions/test_undef_function.py`.
Add an error message for calls to undefined top-level functions

Add an error message for calls to undefined top-level functions

---

.gitattributes
README.md

I added a small phrase in the README explaining how one can enable syntax highlighting for Vyper on GitHub using `.gitattributes`
1. Create a new repository
2. Create a `.gitattributes` file as explained in the phrase
3. Add a `.vy` file
4. Commit!

Add `.gitattributes` syntax highlighting trick

---

tests/parser/exceptions/test_insufficient_arguments.py
viper/functions.py

Fixed the error message that is displayed when a Vyper function is called without enough arguments.
Added a `%` so that the string formatting actually happens, and pulled the function name from the `ast.Call` object using `element.func.id` (assuming the inner part of the `Call` is a `Name(id=...)`).
Run the included test case in `tests/parser/exceptions/test_insufficient_arguments.py`, or compile the example Vyper program therein.
Fix the error message for functions called without enough arguments
A pademelon, from Australia :D

Fix err msg for functions without enough arguments

---

.travis.yml

fixed syntax on flake8 script to run on travis
- deleted comma between directories viper and tests
- [Flake8 Man](http://flake8.pycqa.org/en/latest/manpage.html)
- can also verify manually, by running
```python
flake8 viper/, scripts/, examples/
```
it will return only the last directory.
With fix (removing commas) it will return all requested directories. 
*pass*

edited travis script for flake8

---

tests/parser/globals/test_setters.py
tests/parser/syntax/test_list.py
tests/parser/syntax/test_nested_list.py
tests/parser/types/test_lists.py
viper/parser/expr.py
viper/types.py

Removes the possibility to create mixed lists.
Removed MixedType and added an exception where it would usually be created.
```python
@public
def test():
a = [1, 1.33]
```
should throw necessary exception.
Mixed list support removed.

Prevent mixed lists

---

docs/index.rst
setup.cfg
setup.py
tests/parser/functions/test_as_num256.py
viper/functions.py
viper/parser/expr.py

Remove `as_num256` safety check for `bytes32` type.
Change version from 0.0.2 to 0.0.3
Removed the  >= 0 clamp for `as_num256` with `bytes32`
Look at the test I added
Change version from `0.0.2` to `0.0.3`

Remove as_num256 safety check for bytes32

---

viper/parser/expr.py

Added some extra exceptions for paths in the compiler that would not produce a result when more types are added.
Looked for underdefined paths in this specific function
No change to testing, would only appear when a new type is added. If not applied, then in the future when that type is added, compiler would give a very cryptic error that would be difficult to debug
Please feel free to change the exception types or messages as necessary

Underdefined Paths in compiler, added Exceptions

---

docs/installing-viper.rst

When running `make` for the installation of Viper, I got the following error:
```
clang -bundle -undefined dynamic_lookup -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include build/temp.macosx-10.13-x86_64-3.6/ext/_yaml.o -lyaml -o build/lib.macosx-10.13-x86_64-3.6/_yaml.cpython-36m-darwin.so
ld: library not found for -lyaml
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
```
This is clearly caused by the YAML library (libyaml) not being found on macOS.
I checked whether `libyaml` was installed correctly using `brew info libyaml`: it was. I just changed the suggested compile flags from …

macOS library not found libyaml fix

---

docs/index.rst
tests/parser/exceptions/test_invalid_literal_exception.py
tests/parser/functions/rlp/test_rlp_list.py
tests/parser/globals/test_getters.py
tests/parser/syntax/test_as_wei_value.py
tests/parser/syntax/test_block.py
tests/parser/syntax/test_create_with_code_of.py
tests/parser/syntax/test_raw_call.py
tests/parser/syntax/test_send.py
tests/parser/types/numbers/test_decimals.py
tests/parser/types/value/test_as_wei_value.py
viper/functions.py

Change `as_wei_value` to accept `as_wei_value(num, "unit")` instead of `as_wei_value(num, unit)`.  Having the unit in quotes is clearer because perviously it was easy to mistake the unit for a variable.
In response to #595 
Changed what `as_wei_value` acceptions in `functions.py`.
Look at the tests I changed.
Change ``as_wei_value`` to use quotes for units.

Improve as wei value

---

tests/parser/features/iteration/test_range_in.py
viper/parser/expr.py

Add a check to `in_range` so it fails if there's a type mismatch.
Fixes #581 
Added a types check
Look at the test I added
None

Fix in range with different types

---

docs/index.rst
examples/auctions/simple_open_auction.v.py
tests/examples/auctions/test_simple_open_auction.py
tests/examples/company/test_company.py
tests/examples/market_maker/test_on_chain_market_maker.py
tests/examples/safe_remote_purchase/test_safe_remote_purchase.py
tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_1.py
tests/examples/tokens/ERC20_solidity_compatible/test/erc20_tests_2.py
tests/examples/voting/test_ballot.py
tests/parser/features/external_contracts/test_external_contract_calls.py
tests/parser/functions/test_return_tuple.py
tests/parser/globals/test_getters.py
viper/parser/parser.py

Change `public` variable getters from `get_var` to `var`
Implement VIP #518
Remove `get_` from the getter the compiler creates in `parser.py`
Look at the tests I changed.
Change getter from get_var to var.

Change get var to var

---

tests/parser/exceptions/test_constancy_exception.py
vyper/parser/expr.py
vyper/parser/stmt.py

…ction.
Fixes #638. 
Added checks in `expr.py` and `stmt.py`.
```python
f:num
@public
def a (x:num)->num:
self.f = 100
return x+5
@constant
@public
def b():
p: num = self.a(10)
```
Should throw exception.

Disallow calling non-constant function in a constant function

---

docs/index.rst
examples/tokens/vypercoin.v.py
tests/parser/exceptions/test_structure_exception.py
tests/parser/exceptions/test_variable_declaration_exception.py
tests/parser/globals/test_setters.py
tests/parser/integration/test_crowdfund.py
tests/parser/syntax/test_invalids.py
tests/parser/syntax/test_list.py
tests/parser/syntax/test_maps.py
vyper/parser/parser.py

Make it illegal for function names to match global variable names.
Response to #516 
Add a check when functions are being created again global variable names.
Look at the tests I changed.
Functions cannot have the same name as globals

Fix function name global variable shadowing

---

docs/index.rst
examples/market_maker/on_chain_market_maker.v.py
examples/safe_remote_purchase/safe_remote_purchase.v.py
examples/stock/company.v.py
tests/conftest.py
tests/parser/features/iteration/test_repeater.py
tests/parser/features/test_assignment.py
tests/parser/functions/test_ceil.py
tests/parser/functions/test_floor.py
tests/parser/syntax/test_block.py
tests/parser/syntax/test_invalids.py
tests/parser/syntax/test_public.py
tests/parser/types/numbers/test_num.py
vyper/functions/functions.py
vyper/parser/expr.py

Change division by `num` to output a `decimal` instead of a `num`. 
Add `ceil` built in function for rounding up.
Remove support for:
```
x: num = 7
x /= 5
```
Changed `def arithmetic` in `expr.py` to return `decimal` instead of a `num` when dividing by a `num`.
Look at `test_ceil.py`, `test_num.py`, and all the other tests I changed.
Division by num returns decimal type.

Fix num division

---

Dockerfile

Fixed a typo in the dockerfile label pointing to readthedocs.
Removed an unnecessary `r`? 
Review and check the URL
Fixed bad documentation URL label in the Dockerfile

Fix bad readthedocs url in Dockerfile label

---

docs/index.rst
tests/parser/features/decorators/test_constant.py
vyper/function_signature.py

Ban functions with both `payable` and `constant` decorators because `constant` functions have not need to accept value.
In response to #675
Add a check for `payable` and `constant` decorators to `function_signature.py`
Look at the test I added to `test_constant.py`
Ban functions with payable and constant decorators

Ban functions with payable and constant decorators

---

examples/tokens/ERC20.v.py

Just changed num to use int128. Also, updated totalSuppy variable to be public and removed totalSupply method.
Replacing the code.
Run and compile the erc20.v.py source code.
Described above.

Fixed ERC20 contract to use int128 instead of num

---

README.md
vyper/compile_lll.py
vyper/functions/signature.py
vyper/parser/parser.py
vyper/parser/parser_utils.py
vyper/parser/stmt.py
vyper/types/types.py

Changed eg. to e.g.
Search and change (although there are more eg. in old_readme.txt, there is a pull request deleting old_readme so I didn't touch old_readme.txt)
By reading the docs. Dictionary says "exempli gratia", for example in Latin, is e.g.
Only one commit, changing eg. to e.g.

Change eg. to e.g.

---

docs/vyper-by-example.rst

The example code sections did not match the discussion text. I made them match. Relates to #579 
Rather than including specific line numbers, where possible I used the `pyobject` option to match the function being discussed. This way, if the source code file is updated, the docs will follow automatically once rebuilt. I learned about this by reading the Sphinx [docs](http://www.sphinx-doc.org/en/master/markup/code.html#includes) related to showing code examples.
Read the docs! Specifically, any of the Vyper By Example sample code in line with the explanatory paragraphs.
Fix example code shown shown in line with Vyper By Example docs.
A very cute albino Tanuki!

change lines included in code examples to match discussion text

---

docs/structure-of-a-contract.rst

For some reason there was a } in the end of an example of a function in the docs. Someone probably confused with Solidity.

Removed } from end of the function

---

docs/types.rst

There was an extra comma in the struct example.
I guess it's a mistake but I noticed the code still compiles with no errors.
I don't know if it matters but I am asking just to make sure.

Removed unnecessary comma

---

docs/index.rst

Added * **2018.03.20**: Renaming ``__log__`` to ``event`` to the Compatibility-breaking Changelog in the docs.
As requested for issue #704.

Updated changelog with the __log__ to event change

---

README.md

I removed a link that was leading to a 404 page.
Just removed the line from the README file.
Open the readme and click the testing link.
Remove dead testing link from README
I have plants

Remove dead testing link from README

---

tests/parser/functions/test_ceil.py
tests/parser/functions/test_floor.py
vyper/functions/functions.py
vyper/optimizer.py
vyper/parser/parser_utils.py

Corrected the implementations of `floor` and `ceil` so that they behave correctly for negative inputs.
Modified both `floor` and `ceil` to conditionally branch, and use an appropriate signed division to get the right rounding behaviour.
Read the code and run the included tests.
Make floor and ceil round towards negative and positive infinity respectively, rather than 0
https://www.flickr.com/photos/ekilby/4844114344

 Fix floor and ceil for negative inputs

---

tests/parser/features/iteration/test_for_in_list.py
tests/parser/syntax/test_ann_assign.py
vyper/parser/stmt.py

Fixes #703 .
-  Structs and lists where not properly type-checked on assignment.
Turns out the variable location the was allocated always assumed the the type of the right hand side. Instead of using the information from the stmt.annotation. So simple fix, added necessary fail tests so we can pick this up again.
Check tests.
N/A

Fix assignment checks

---

tests/parser/exceptions/test_structure_exception.py
tests/parser/features/test_map_delete.py
vyper/parser/stmt.py

Fixes #715.
Added parse_delete to handle the specific case.
Check tests `del self.big_map["test"]` should now work.
Add deleting support for a map.

Adds support deleting for nested map keys.

---

requirements-dev.txt
setup.py
vyper/opcodes.py
vyper/parser/parser_utils.py

To address #735, 
- Removed pyethereum installation dependency
- Moved `bumpversion`, `pytest-cov`, and `pytest-runner` out of `install_requires`.
Copy pasting from [py-evm constants](https://github.com/ethereum/py-evm/blob/master/evm/constants.py#L83-L84)
check if new constants in `vyper/opcodes.py` fit [py-evm constants](https://github.com/ethereum/py-evm/blob/master/evm/constants.py#L83-L84) and  [pyethereum opcodes](https://github.com/ethereum/pyethereum/blob/develop/ethereum/opcodes.py)

fixed #735, removed pyethereum dependency

---

tests/parser/features/test_map_delete.py
vyper/parser/stmt.py

Fixes `del map[1]` syntax when a struct is being stored.
Using Nulltype instead of hardcoded LLL fixes, by deleting all members of the struct as well.

Fix deleting a struct from a map.

---

examples/safe_remote_purchase/safe_remote_purchase.v.py
tests/compiler/test_bytecode_runtime.py
tests/parser/syntax/test_bool.py
tests/parser/syntax/test_list.py
tests/parser/syntax/test_maps.py
tests/parser/syntax/test_missing_return.py
vyper/parser/expr.py

Fixes #742 .
Removed them from expr.py.
try to do anything with true, false and null. :tongue: 
Remove lowercase true, false and null.

Remove true,false,null keywords.

---

.gitignore

`.pytest_cache/` was showing up when I ran the tests
so I got rid of it in the `.gitignore`
run the tests, no folder should be unrecognized in git

Add py.test's cache to gitignore file

---

docs/vyper-by-example.rst

Added the word `and` into the sentence so it's clear that both the `asserts` need to return true on Line 33 and Line 35 (https://github.com/ethereum/vyper/blob/master/examples/auctions/simple_open_auction.v.py#L33), and that the previously stored highest bid is not equal to 0 on Line 36 (https://github.com/ethereum/vyper/blob/master/examples/auctions/simple_open_auction.v.py#L36)
Added the word `and` into the sentence
Check that the sentence is now more readable with the word `and`
N/A
,^^^^^^^.
|  Y o Y  |
\TTTTT/

Update vyper-by-example.rst with minor grammar fix

---

tests/parser/features/iteration/test_break.py
tests/parser/syntax/test_bool.py
vyper/parser/expr.py

Fixes #737.
Prevents implicit conversion when comparing.

Fixes #737, disallowing implicit conversion when comparing.

---

vyper/types/types.py
vyper/utils.py

Removes the obsolete `real` and `real128x128` ABI types (they have been replaced with `fixedMxN`). 
It also removes them from being restricted keywords, though I am not sure if that is desired.

Real abi type

---

docs/types.rst
tests/parser/syntax/test_custom_units.py
tests/parser/types/numbers/test_custom_units.py
vyper/function_signature.py
vyper/parser/context.py
vyper/parser/expr.py
vyper/parser/parser.py
vyper/parser/stmt.py
vyper/signatures/event_signature.py
vyper/types/types.py
vyper/utils.py

Implements #752, custom units.
Added support for units as a custom global keyword.
```python
units: {
cm: "centimeter",
km: "kilometer"
}
a: int128(cm)
@public
def test() -> int128(km):
b: int128(km)
b = 100
return b
```
See tests and exceptions in parser.py

752 custom units

---

examples/tokens/ERC20.v.py
examples/tokens/vypercoin.v.py
tests/parser/features/test_assignment.py
tests/parser/functions/test_convert_int128.py
tests/parser/functions/test_minmax.py
tests/parser/types/numbers/test_uint256.py
vyper/functions/functions.py
vyper/parser/expr.py
vyper/parser/parser_utils.py
vyper/parser/stmt.py
vyper/types/convert.py
vyper/types/types.py
vyper/utils.py

Implements #764. uint256 improvements.

uint256 improvements

---

setup.py
tests/parser/types/test_bytes.py
vyper/functions/signature.py
vyper/parser/expr.py
vyper/parser/parser_utils.py

Fixes #732. Adds support for super cool python-like binary notation. 
Most the work was done in `expr.py`.
See the tests.
Adds support for binary literals.

Add support for binary literals.

---

setup.py
tests/parser/features/external_contracts/test_external_contract_calls.py
vyper/parser/expr.py
vyper/parser/parser.py

Fixes #800.
Added `_get_external_contract_keywords()` to Expr class.

Add support for setting value and gas on external contract call.

---

tests/parser/features/test_logging.py

In a new version of rlp these `topics` becomes a tuple. This is a backwards-compatible change to support that.
Unit tests

cast `topics` to tuple

---

setup.py

`sharding` repo has [a dependency hell of eth-tester/pyetherem/py-evm/vyper](https://github.com/ethereum/sharding/issues/86#issuecomment-388955286
). Since the only thing that Vyper "package" needs from `py-evm` is importing constants (`from evm.constants import GAS_IDENTITY, GAS_IDENTITYWORD`), the easy way to solve the problem is making Vyper package doesn't require a fixed `py-evm` version and only use fixed version for testing.
Modified the requirement of `py-evm` from
```python
install_requires=['py-evm>=0.2.0a12]
```
to
```python
install_requires=['py-evm>=0.2.0a12,<1.0.0']
...
tests_require=[
...
'py-evm==0.2.0a12',
],
```
CI passed.
Modified the requirement of py-evm

Modified the requirement of py-evm

---

docs/installing-vyper.rst

Quick fix for fresh install on OSX, I had to `brew install leveldb` to get it going

add `brew install leveldb` requirement for OSX

---

examples/tokens/vypercoin.v.py

Changed all ``int128`` usage to ``uint256``, as now ``uint256`` has full support in Vyper.

Changed Vypercoin int128 usage to uint256

---

examples/tokens/ERC20_solidity_compatible/ERC20.v.py

Fix an issue compiling Phil Daian's ERC20 token impl
```
vyper.exceptions.TypeMismatchException: line 22: Expecting one of ('num_literal', 'int128', 'bytes32') for argument 1 of convert
_value: uint256 = convert(msg.value, 'uint256')
```
Converted `uint256` values to type `uint256(wei)`.
**Good question!** I ran the full test suite for the project, and noticed that it did not test this token. 
I also tried running this [test file](https://github.com/ethereum/vyper/blob/patch/updateERC20/tests/examples/tokens/ERC20_solidity_compatible/run_tests.py 
), but I got an error with the rlp lib: 
```
from rlp.utils import decode_hex, encode_hex, ascii_chr, str_to_bytes
ImportError: cannot import name 'decode_hex'
```
Update ERC20 Compatible token

Update ERC20 Compatible token 

---

tests/parser/types/numbers/test_uint256.py
vyper/parser/expr.py

Fix comparison operators when comparing literals  to uint256 variables.

---

tests/parser/functions/test_slice.py
tests/parser/types/test_variable_naming.py
vyper/utils.py

Disallow variables to have the name of a built in function.
Didn't have the time to open an issue for that since I want it to be in the beta release.
What do you think?

Disallow variables with built in functions name

---

docs/types.rst

Updated docs as a deprecated function was still being recommended. Developers should now use `convert(_literal, 'uint256')` instead of `as_uint256(_literal)`.
Doc change.
Visual verification should be sufficient.

Cleanup docs - literals are not always interpreted as int128's & correct typecasting example

---

tests/parser/functions/test_convert.py
vyper/types/convert.py

Closes #888 
`convert(1, 'int128')` should fail

Disallow conversion of int128 to int128

---

docs/built-in-functions.rst

Mentioned the correct way to use the assert function in the docs.
I think we should consider removing one of the assert syntaxes.
Currently, both ``assert 1 < 2`` and ``assert(1 < 2)`` will work the same. We might want to remove one of them for uniformity.

Fixed the assert documentation

---

examples/tokens/vypercoin.vy

Attack vectors like the one described here:
https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM/edit#heading=h.m9fhqynw2xvt
and discussed here:
https://github.com/ethereum/EIPs/issues/20#issuecomment-263524729
Fixes Attack vectors for ERC20 coin vyper port
I added the code to set allowance to 0 before setting it to the amount from parameter
Check File change

Prevent Attack vectors from vypercoin.vy

---

tests/parser/functions/test_send.py

Fixes #893.
The correct assert already existed.

Add test case to check non-payble function throws on sending it ether.

---

tests/parser/syntax/test_bytes.py
tests/parser/types/test_bytes.py
vyper/parser/expr.py

- Fixes #861. 
- Forces binary literals to be multiples of 8 / without auto zero padding.

Remove auto-zero padding for binary literals.

---

.github/ISSUE_TEMPLATE/vip.md

Removed the preamble
We don't use the preamble for anything right now.
This style was copied from the EIPs, which auto-build a webpage mirroring the current EIPs. We don't do that right now. I don't think we really need most of what's in the preamble.

Remove preamble. We don't use it.

---

tests/parser/types/numbers/test_constants.py
tests/parser/types/numbers/test_int128.py
vyper/parser/expr.py
vyper/parser/stmt.py
vyper/utils.py

Fixes #926 - make integer division consistent.

Fix literal int division

---

bin/vyper

Closes #948. Support multiple output formats while running `vyper filename -f`.
- If the format option is skipped the existing behavior continues.
- If a single format is specified only that format is printed.
- If two or more formats are specified they are both printed - with a `\n` between them.
---
Since the method `print_asm`/`get_asm` has also undergone a change I recommend testing the output asm on master and this branch. I've compared the two and the diff checker indicated that there was no difference.
The compiler can now print multiple formats simultaneously, use `[-f {abi,json,bytecode,bytecode_runtime,ir,asm} [{abi,json,bytecode,bytecode_runtime,ir,asm} ...]]`.

Support multiple output formats

---

docs/structure-of-a-contract.rst

Documented new default function usage.
Read the source changes, researched a bit about the EVM execution sematics to communicate a stronger understanding.
Generate docs and visit `structure-of-a-contract.html`
Documented default functions of contracts (fallback funcs).

Documentation for default funcs

---

bin/vyper

When implementing multiple args, we didn't realise that the old use case of `vyper -f abi inputfile.vy` wasn't working anymore.
This changes multiple args to us comma separate list instead. Because it seems like argparse as absolutely no way of handling `-f abi -f json`.

Fix multiple args.

---

docs/vyper-by-example.rst

Changed the spacing of text in the docs to result in proper formatting when viewing them.
Edited the docs/vyper-by-example.rst file in the GitHub web editor.  I previewed the output and saw if it matched other notes on the page.  It did, and when I generated HTML from the changed doc files, they were correctly formatted.
Clone my fork, generate the HTML files from the doc files, and view them.
Fixed issue in formatting in "Vyper By Example" doc file.

Fix formatting issue in docs

---

bin/vyper
bin/vyper-lll
bin/vyper-serve

The command line vyper now can print version number with  
vyper --version
https://docs.python.org/3/library/argparse.html
`parser.add_argument('--version', action='version', version='%(prog)s 2.0')`
vyper --version
I did "make test" and all tests were passed (96% coverage)
command line print version number

added version option in command line

---

docs/built-in-functions.rst

Removed duplicate description about `convert()` function in docs.
Looking at the source code
Removed the latter.
```
def convert(inp, out) -> b:	
:param inp: variable to be converted	
:type inp: type of the variable	
:param out: type to convert(e.g. 'int128', 'uint256', 'decimal', 'bytes32')	
:type out: String	
:output b: converted variable	
```
The former still remains.
```
def convert(a, b) -> c:
:param a: value to convert
:type a: either decimal, int128, uint256 or bytes32
:param b: the destination type to convert to
:type b: str_literal
:output c: either decimal, int128, uint256 or bytes32
```

Remove duplicate description about convert() function in the document

---

docs/built-in-functions.rst

Replaced `num128` in docs with `int128`
Replaced `num128` in docs with `int128` in the description of `extract32()` function
Replaced `num128` in docs with `int128`

replace num128 in docs with int128

---

docs/built-in-functions.rst

Modified slice() function's keyword argument `length` to `len` in docs
Replaced `length` in the description of slice() function with `len`
Modified slice() function's keyword argument `length` to `len` in docs

modified slice() function's keyword argument `length` to `len` in docs

---

docs/types.rst

Capitalized the first letter of boolean in docs
Replaced `true` with `True` and `false` with `False` in docs.
Capitalized the first letter of boolean in docs

capitalize the first letter of boolean in docs

---

bin/vyper
docs/compiling-a-contract.rst

Changed the ABI formatting options in the following way:
* Python formatted output (single quotes, uppercase True and False): `abi` -> `python_abi`
* standard JSON output: accept `abi` in addition to the existing `json` option (the latter is now an alias)
The rationale is in Issue https://github.com/ethereum/vyper/issues/989 - vanilla `abi` option should produce the fully standards compliant result.
Searched for which lines to change using this query:
https://github.com/ethereum/vyper/search?q=json&unscoped_q=json
1. Checkout my branch and `make`.
2. Run automated tests: `make test`
3. Manually check new and old formatting options: `vyper -f [abi, python_abi, json] examples/auctions/simple_open_auction.vy`
Running automated tests:
```
(vyper-venv) Highgarden:vyper kkom$ make test
python …
```

ABI formatting: change behaviour of "abi", introduce "abi_python"

---

docs/types.rst
vyper/signatures/event_signature.py
vyper/types/types.py
vyper/utils.py

Remove instances of `int256` and clean up code (for readability).
Ran `grep -rw 'int256' *` to find all instances of `int256` and removed unnecessary occurrences. Formatted some additional code for easier readability.
Ran the full suite of tests and confirmed they all still pass. Visually examined each change and confirmed that they would not break anything. 
Remove int256 and clean up code for readability

Remove int256 and clean up code for readability

---

examples/voting/ballot.vy
setup.py
tests/parser/integration/test_escrow.py
tests/parser/syntax/test_bool.py
vyper/optimizer.py
vyper/parser/expr.py

Fixes #999.
Altered unary_operations function.
See tests in test_bool.py
not may only be used with boolean expressions.

Not only foor bool expressions

---

examples/tokens/ERC721.vy
tests/examples/tokens/test_erc721.py

Adapted a version of @maurelian's ERC721 example for our repository
Added default argument support for `safeTransferFrom()` per merge of #987
Copy, paste, compile
compile, write some tests (TODO)
Added ERC721 example

Add ERC721 example

---

Dockerfile
docs/installing-vyper.rst

Fix the following errors which occurred building docker image and running tests within that according to  [docs/installing-vyper.rst](https://github.com/ethereum/vyper/blob/master/docs/installing-vyper.rst)
```sh
$ docker build https://github.com/ethereum/vyper.git -t vyper:1 
$ docker run -it vyper:1 /bin/bash                                                                                                                
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 40: invalid start byte
$ docker run -it --entrypoint /bin/bash vyper:1
root@42d73a0c0c5a:/code# make test
bash: make: command not found
root@42d73a0c0c5a:/code# python setup.py test
... snip...
unable to execute 'gcc': No such file or directory
error: Setup script exited with error: command 'gcc' failed …
```

Fix Dockerfile to be able to run tests

---

vyper/types/types.py

Noticed some possible improvements to be made to the API for equality checking in `NodeType` subclasses.  Did a tiny bit of cleanup there.
* Added `__eq__` implementation on `NodeType` base class which always checks that two instances are of the same class.  This should be more future proof since it doesn't require the class to be explicitly stated.
* Converted `NodeType` to abstract base class
* Added abstract method `eq` which checks for equality particular to each subclass
Run the test suite.
Internal change.  No need for description.

Define equality checking of types more cleanly

---

.gitignore

changed the reference to egg-info in .gitignore
with vi
build now does not leave the vyper.egg-info with changed files. Like they did before the change.
update reference to egg-info from eth_vyper.egg-info to vyper.egg-info

small fix to .gitignore, now has the right reference to egg-info

---

bin/vyper-serve
vyper/compiler.py

Add Access-Control-Allow-Origin: * to all vyper-server requests.

---

setup.py
tests/parser/features/test_assert.py

- Using transactionReceipt with a transact={}, is clearer and shows web3 usage as well.
- Bump eth tester versions.

Fix test assert refund.

---

tests/parser/exceptions/test_type_mismatch_exception.py
vyper/parser/stmt.py

If a function declares a non-tuple return type and, in the function body, the return expression is a tuple type, it causes an uncaught `AttributeError` to be raised.  I modified the code to act similarly to when a base type value is returned but not expected.
Updated `Stmt.parse_return` to include another condition and raise a `TypeMismatchException`.  Added a test for raising of this exception.
Run the tests.
An incorrect exception type was being raised when a function body returned a tuple type but the function signature specified a base type.  A more appropriate exception is now raised.

Fix AttributeError on tuple return type mismatch

---

bin/vyper
bin/vyper-serve
scripts/rlp_decoder.py
tests/conftest.py
vyper/compile_lll.py
vyper/compiler.py
vyper/parser/parser.py

Fixes #870.
Add vyper source map. `-f source_map`.
I spent quite a bit of time to try and get something like solidity's, but came to the conclusion that we should do our own version first. Mostly because python ast outputs line_no/col_offset.
Also as part of the vyper debug changes, it came clear that we should probably move the global/locals part of the source map here. But left that out as this would be out of scope.
https://github.com/status-im/vyper-debug/blob/master/vdb/source_map.py#L39
The source map linenumber map format is: `{148: [1, 0]}` / `{pc_pos: [line_no, col_offset]}`.
The breakpoints are just a list of line numbers, one would want to insert a breakpoint, which is currently also produced by the `vdb` statement.
Best way is to wait for vyper-debug to be updated (6_use_pc …

Add source map

---

bin/vyper

os.environ.get returns a string, which made traceback limit not work properly.

Fix VYPER_TRACEBACK_LIMIT

---

tests/parser/functions/test_convert.py
vyper/types/convert.py

Allow bytes that have a smaller max length on bytes, to be converted to `bytes32`.

Allow convert to bytes arrays smaller 32 bytes.

---

vyper/__init__.py

`sys` and `pkg_resources` were showing up if you imported `vyper` as a module, so I made them *disappear*
underscores and magic
`import vyper` does not import anything
NOTE: We should probably change that :)

Ensure that import doesn't leak sys and pkg_resources

---

docs/vyper-by-example.rst

Documentation updates. The `public` getter example was inconsistent with the changes made from https://github.com/ethereum/vyper/pull/650. 
Keyboard ⌨️ 
Eyes 👁 
None.

Fixes Getter Example and Typo

---

docs/types.rst

#1042 has changed the convert function to include type as itself.
I changed the doc's content
I removed '' from the argument for destination of ``convert()``
Check #1042

Change doc due to the changes on #1042

---

tests/examples/auctions/test_simple_open_auction.py
vyper/functions/functions.py
vyper/parser/context.py

I corrected a small typo that I saw in a comment in 
/functions/functions.py. 
1 x (argyument -> argument)
/tests/examples/auctions/test_simple_open_auction.py
3 x (higest-> highest)
/parser/context.py
1x (expressiong -> expression)

Correct typos ✔️

---

tests/parser/types/test_bytes.py
vyper/types/convert.py

Fixes #1074
Updated `convert.py` to allow for conversion from bytes to address. Added tests to `test_bytes.py` to test both the existing functionality of converting from address to bytes and also test new functionality of converting from bytes to address.
`make test`
Added functionality to allow conversion from bytes to address.

Allow conversion from bytes to address

---

docs/built-in-functions.rst

Fixed the input and output type of ecadd and ecmul in docs.
Modified the docs.
Checked the compiler.
Fix the input and output type of ecadd and ecmul.

Fix the input and output type of ecadd and ecmul in docs

---

tests/parser/syntax/test_bool_ops.py
vyper/parser/expr.py

Implemented support for BoolOps with greater than two arguments. Closes #1075 
Made sure all expressions in [BoolOps `values`](https://docs.python.org/3.7/library/ast.html#abstract-grammar) were iterated through and handled.
Review test file `test_bool_ops.py` and run `make test`.
Add support for BoolOps with greater than two arguments

Support BoolOps for > 2 arguments

---

examples/tokens/ERC721.vy
tests/examples/tokens/test_erc721.py

Update example implementation of [ERC721](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md) token. Specifically, 
- supported ERC165 (it's required in the EIP)
- added mint/burn function
- made it clear that assertions required in the EIP is implemented. 
- commented about other assertions not included in the EIP but needed.
- added tests with more test cases
I referred to the previous implementation and [OpenZeppelin's Solidity implementation](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721.sol).
Test. Formal verification is [WIP](https://github.com/LayerXcom/verified-vyper-contracts/tree/master/erc721). 
Update example ERC721 token

Update ERC721 token

---

tests/parser/functions/test_convert_int128.py
tests/parser/types/numbers/test_int128.py
vyper/types/convert.py

Related somewhat to conversation on #1082. Catch at compile-time if trying to convert `bytes` array of max length greater than 32 to `int128` type.
Updated `convert.py` to do a check on max length when converting from bytes type (my understanding as to why `SizeLimits.in_bounds()` doesn't work for `bytes` type is that it is being passed by reference not by value?).
Added relevant tests to `test_int128.py`
`make test`
Patch to prevent conversion from bytes array greater than 32 bytes to int128.

Do not allow conversion from bytes array > 32 to int128 at compile time

---

tests/parser/functions/test_convert_int128.py
vyper/types/convert.py

In the process of starting work on a better spec-ed table of expected conversion outcomes per @fubuloubu and I's conversation on #1072, I noticed some pretty strange behavior that allowed for converting from _some_ uint256 that were outside of the maximum allowed range for `int128`.
More specifically I found that when running this test:
```python
def test_convert_from_uint256(get_contract_with_gas_estimation):
code = """
@public
def test(foo: uint256) -> int128:
return convert(foo, int128)
"""
c = get_contract_with_gas_estimation(code)
assert c.test(0) == 0
assert c.test(2**127 - 1) == 2**127 - 1
assert c.test(2**256 - 1) == -1 # FIXME: This line I expected to throw a runtime exception but didn't.
assert c.test(2**127) # FIXME: Whereas this line through the expected runtime exception.
``` …

Fix bug with convert(2**256 - 1, int128)

---

tests/parser/features/external_contracts/test_external_contract_calls.py
vyper/parser/parser.py

Fixes external contract call calling breaking parser if a typle is returned.

Add returner for TupleType return.

---

tests/parser/exceptions/test_invalid_type_exception.py
vyper/parser/global_context.py
vyper/parser/parser.py
vyper/parser/parser_utils.py
vyper/parser/pre_parser.py
vyper/types/types.py

As we know handling of class types was really a kludge, and caused a error on master if defined as `class ClassName()` (with parenthesis).
This approach is much cleaner and maintainable, and fixes the bug (was nearly impossible to do without it).

Fix Pre-Parser for contract & struct.

---

vyper/types/types.py

Dicts are not guaranteed to use insertion order until python3.7+

Ensure struct keys are insertion ordered

---

make.cmd

Basic make.cmd that only has init and test, so initial instructions work on Windows.
Fixes #1127 
Also partially addresses #1079 (it will install, but will have to be run manually as the python script installed is a shell script; there is another bug to fix that)
Add a make.cmd file to the root, with very basic handling for init and test, which call the same python commands as Makefile.
Windows does not have make, so the basic instructions, to call `make` and then `make test` do not work on Windows.
This file implements those two commands, with a structure for adding the others. Some of the others (e.g. recursive delete of files matching a pattern) are more complicated. Powershell would be better, but there are ways in Cmd (e.g. robocopy the pattern to MOV to a temp dir, then delete the …

Basic make.cmd for Windows

---

tests/parser/syntax/test_send.py
vyper/signatures/function_signature.py
vyper/utils.py

Fix #1068
Created new set in `utils.py` called `function_whitelist` for whitelisting for function names words that are otherwise reserved words. 
I added a test case that tests this to `tests/parser/syntax/test_send.py`.
Test with `pytest -k tests/parser/syntax/test_send.py`.
Whitelist the `send` keyword for function definitions

Whitelist the `send` keyword for function definitions

---

vyper/parser/global_context.py
vyper/types/types.py
vyper/utils.py

This is a very minor improvement, replaces the lists being used in `utils.py` with sets. Given that they are used for testing the membership of a given item against the set, this will be slightly faster.
See above.
`make test`
Use sets not lists in utils.py

Use sets not lists in utils.py

---

vyper/types/convert.py

Tiny PR, makes sure there are no lingering usages of clamping against literals in conversions. Related to #1134 (now closed).
Above.
`make test`
No conversion clamping against literals.

Be consistent in clamping against max/min in memory

---

tests/parser/types/numbers/test_constants.py
vyper/parser/expr.py

Added better tests, refactored, and made op-code generation for built-in constants more efficient.
This also fixes #1121
Built-in constants should use the values from `SizeLimits` in `utils.py`
`make test`
Make built-in constant op code generation more efficient.

Make built-in constant op code generation more efficient

---

bin/vyper
docs/compiling-a-contract.rst

Just docs changes: `--asm` and `--ir` were missing from compiler help.
Also it looks like `--python_abi` was renamed to `--abi_python` at some
point and is identical to `--abi`.
Updated compiler help and docs
```
$ vyper -h
$ vyper -f abi_python <foo.vy>
```

Update docs and help for compiler options

---

tests/parser/features/test_assignment.py
vyper/parser/stmt.py

Fixes #1107. Check for and disallow implicit type conversion in Assign statements.
Also did some _minor_ refactoring of the assignment validity checking logic.
Added type checking step to `assign(self)` handler in `stmt.py`.
Added corresponding tests in `test_assignment.py`
`pytest -k test_assignment.py`
Check for and disallow implicit type conversion in Assign statements.

Check for and disallow implicit type conversion in Assign

---

examples/auctions/simple_open_auction.vy
tests/examples/auctions/test_simple_open_auction.py

I switched the simple auction code example to use the withdraw pattern. This avoids a security vulnerability where a malicious contract places a bid and then refuses all refunds (preventing others from outbidding them).
I removed the `send` from `bid()` and instead added a `pendingReturns` state variable like in the blind auction example. I added a `withdraw()` function for bidders to actually pull those funds out.
I made sure the code still compiles, but I didn't do any other testing to verify functionality.

Use the withdraw pattern to avoid the 'King of the Ether' security vulnerability

---

docs/built-in-functions.rst

Fixed the type of the params of `concat` in docs
Fix the type of the params of `concat` in docs

Fix the type of the params of `concat` in docs

---

docs/types.rst

Updated types section of docs.
The tables of `uint256`and `decimal` operators were not displayed correctly.
Update types section of docs

Update types section of docs

---

docs/built-in-functions.rst

Clarified the third param of `extract32` is optional in docs
Clarify the third param of `extract32` is optional in docs

Clarify the third param of `extract32` is optional in docs

---

docs/compiling-a-contract.rst

Recommendation was for file extension `.vy` to have Python syntax highlighting, I assume this is meant to be `.py` and fixed it.

Fix typo in file extension

---

tests/parser/functions/test_return_tuple.py
vyper/parser/parser_utils.py

Fix #1006 
Set the destination type correctly for `make_setter` to typecheck in the tuple return code
See test
Fix typecheck for tuple return

Fix tuple return

---

bin/vyper-lll

Handle the new format for `assembly_to_evm`
```bash
vyper-lll -f bytecode /dev/stdin <<EOF
(mstore 0 (pop pass))
EOF
<outputs 0x50600052>
```
Fix `bytecode` output for `vyper-lll`

Fix vyper-lll binary

---

vyper/types/types.py

The call to <make_struct_type> has a missing argument, which may cause a run-time failure. This commit fixes the call to include the correct number of arguments.
I added the missing <constants> parameter to the call to <make_struct_type>
I work for Semmle, and noticed the bug with our LGTM code analyzer:
https://lgtm.com/projects/g/ethereum/vyper/snapshot/dist-1506710546241-1548102310071/files/vyper/types/types.py?sort=name&dir=ASC&mode=heatmap#x62d2d89c83c310e4:1
I helped develop LGTM's code quality algorithms, and I'm interested in knowing how much fixing and clean-up effort is required to move a project up a grade. E.g., Vyper is doing great for JavaScript but has a few issues in Python.
[![Language grade: JavaScript](https://img.shields.io/lgtm/grade/javascript/g/ethereum/vyper.svg?log …

Ensure call to function make_struct_type has correct number of arguments

---

bin/vyper

Add a `--debug` flag which doesn't set the traceback limit to 0. In the future we can add more debug info, and also remove `VYPER_TRACEBACK_LIMIT`
```bash
vyper --debug /dev/stdin <<EOF
> nonsense
> EOF
```
Add a `--debug` flag to the vyper binary.

Add a --debug flag

---

docs/types.rst

Removed `len()` from the table of the `bytes32` operaters
Remove `len()` from the table of the `bytes32` operaters

Remove `len()` from the table of the `bytes32` operators

---

examples/tokens/ERC20.vy
tests/examples/market_maker/test_on_chain_market_maker.py
tests/examples/tokens/test_erc20.py
tests/parser/features/external_contracts/test_erc20_abi.py
vyper/premade_contracts.py

Fixed the types of `name` and `symbol` in ERC20.
(Thanks @fubuloubu !)
`bytes` is more appropriate as a substitute for `string` in Solidity so I changed the type of `name` and `symbol` in ERC20 example.
Tests.
Fixed the types of `name` and `symbol` in ERC20.

Fix the types of name and symbol in ERC20

---

docs/types.rst

`None` is not supported (#1106) so I removed the description from docs.
Removed the description of `None` from docs

Remove the description of `None` from docs

---

vyper/compiler.py
vyper/parser/parser.py
vyper/signatures/interface.py

Fix some "Unknown interface" exceptions (from gitter, cf. https://gitter.im/ethereum/vyper?at=5c61fbf3adf6cb0b2ca19a72)
Pass interface_codes for other compiler flags
```bash
$ cat repro_impl.vy 
import repro_iface as Interface
implements: Interface
@public
@constant
def method1(addr: address) -> bool:
return msg.sender == addr
$ cat repro_iface.vy 
@public
@constant
def method1(addr: address) -> bool:
pass
$ vyper -f abi repro_impl.vy # repeat for abi,asm,source_map,method_identifiers,interface,external_interface
```
Enable imports for other compiler outputs

Fix "Unknown interface" exceptions

---

docs/index.rst

Removed duplicated 'Event Logging' in side menu.
Edited index.rst
Removed duplicated 'Event Logging' in side menu.

Removed duplicated 'Event Logging' in index.rst

---

vyper/compiler.py

The `find_nested_opcodes` used a list comprehension inside of the `any` check, which meant that the list would need to be fully evaluated before the `any` check executed.  However, since `any` only needs a single value to be truthy, this does extra work.t
Removed the `[]` from the comprehension to convert it to a lazy generator, which allows `any` to exit early as soon as it finds any truthy value.
- Minor performance improvement to compilation by making nested opcode check lazy.

Make check for nested opcodes in compiler run lazy

---

vyper/compile_lll.py
vyper/functions/signature.py

Two decorator functions which didn't use `functools.wraps` which means that the resulting functions will all end up having the same `__name__`, thus making them a bit harder to reason about when digging around in the vyper code from a CLI.
Ensure that the inner functions are decorated with `functools.wraps`

Use functools.wraps for decorators

---

vyper/compiler.py

The body of the `mk_full_signature` function was a little confusing to follow, using an `enumerate` based loop and then indexing back into the main data structure being looped over.
I modified the loop to just modify the dictionary in place which is currently still taking advantage of the mutable data structures so that the changes propagate to the returned `abi` value.
I also cleaned up how the function name was being extracted and added a few comments to explain why certain control flows are in place.

Cleanup loop in mk_full_signature to be easier to read

---

vyper/compiler.py

The functions `vyper.compiler.compile_code` and `vyper.compiler.compile_codes` use a list as a default for a function argument.  This is a common error.  While the current usage was benign, were this value to be mutated during the course of the function, those mutations would persist through the next function call.
The function now uses a default argument of `None` and has new logic to put the appropriate default in place if no value has been explicitly provided.
- Remove usage of mutable default for function argument in `vyper.compiler.compile_code` and `cyper.compiler.compile_codes`

Remove mutable data structure as default function argument

---

Makefile
setup.cfg
setup.py
tests/conftest.py
tests/examples/auctions/test_blind_auction.py
tests/examples/market_maker/test_on_chain_market_maker.py
tests/examples/safe_remote_purchase/test_safe_remote_purchase.py
tests/examples/wallet/test_wallet.py
tests/parser/features/test_assert.py
tests/parser/functions/test_default_parameters.py

- Fixes #1273 - wasn't stake leakage but pytest scope.
- Bumps pyevm, eth-tester, web3py versions.
- Enables pytest-xdist for `make test`.
Faster tests.

Bump pyevm versions for tests

---

setup.cfg

-n4 runs will run just as fast, and save on process spawning time.
^.^

Containers (and CircleCI) don't detect allocated cpu count correctly.

---

docs/built-in-functions.rst
docs/index.rst
tests/parser/exceptions/test_constancy_exception.py
tests/parser/exceptions/test_invalid_literal_exception.py
tests/parser/exceptions/test_structure_exception.py
tests/parser/features/test_assert.py
tests/parser/functions/test_create_with_code_of.py
tests/parser/functions/test_raw_call.py
tests/parser/syntax/test_block.py
tests/parser/syntax/test_create_with_code_of.py
vyper/functions/functions.py

Fixes #1177.
Rename create_with_code_of to create_forwarder_to.

Create forwarder to

---

tox.ini
vyper/parser/expr.py
vyper/types/convert.py

I think because of all the rebasing/merging, some files accidentally got left in the lint whitelist.  Also, there were a couple of final little lint errors that needed fixing.

Fix some final lint errors

---

tests/parser/features/test_gas.py
vyper/parser/parser.py

Call me crazy, but I think Vyper has been inserting an unnecessary `seq` construct into all initializer code.
**Update**: @jacqueswww has pointed out that this extra `seq` is optimized away.
Took it out.  Fixed one broken test.
Run tests.

Remove redundant 'seq' in initializer code

---

tox.ini

Add an env var passthrough in the tox config for coveralls.

Add env var passthrough for coveralls

---

tests/parser/exceptions/test_variable_declaration_exception.py
tests/parser/syntax/test_ann_assign.py
vyper/functions/functions.py
vyper/utils.py

Fixed problem mentioned in issue #1364 .  Updated reserved words list and did some other miscellaneous cleanup.
Run the tests.
* The keywords `struct` and `msg` were incorrectly being allowed as variable names.  Those keywords are now properly treated as reserved words.

Fixes/updates in vyper.utils

---

tests/compiler/LLL/test_compile_lll.py
vyper/compile_lll.py

For help in developing and checking bytecode output, inserting `pc_debugger` is super useful.
- Also added to vyper-debug to consume the breakpoint.
- Has no effect on the bytecode.
Add secondary debug LLL macro.
Check the test.

PC debugger output

---

tests/parser/syntax/test_functions_call.py
vyper/parser/parser_utils.py
vyper/types/types.py

Fix ContractType address base_type_conversion

---

docs/installing-vyper.rst

Relavent to issue #1374 
Updated _installing-vyper.rst_ 
Modified doc file to include `ethereum/vyper`
Documentation page for `Installing Vyper` now includes the correct `docker run` commands

Documentation - Fixed docker command to include ethereum/vyper when calling docker run

---

Makefile

`setup.py install` no longer does the right thing.

Update the makefile install rule

---

tests/parser/features/external_contracts/test_external_contract_calls.py
vyper/parser/external_call.py

Doesn't guarantee that dynamic pack/unpacking will work, just allows it
in the simple case.
Fix #1392 
Relax the case analysis in `get_external_contract_call_output`

Allow external calls which return struct

---

tests/compiler/LLL/test_optimize_lll.py
vyper/compile_lll.py
vyper/optimizer.py
vyper/parser/lll_node.py

Saves 3 gas / one word of bytecode per usage
Rewrite ne with xor (https://github.com/ethereum/vyper/issues/1386) in jumpi statements
Add an optimizer case
```
$ vyper -f ir /dev/stdin <<EOF
> @public
> def foo():
>   assert 1 != 2
> 
> @public
> def bar() -> bool:
>   return 1 != 2
> EOF
[seq,
[return,
0,
[lll,
[seq,
[mstore, 28, [calldataload, 0]],
[mstore, 32, 1461501637330902918203684832716283019655932542976],
[mstore, 64, 170141183460469231731687303715884105727],
[mstore, 96, -170141183460469231731687303715884105728],
[mstore, 128, 1701411834604692317316873037158841057270000000000],
[mstore, 160, -1701411834604692317316873037158841057280000000000],
[if,
[eq, [mload, 0], '3264763256' <foo()>],
[seq,
[assert, [iszero, callvalue]],
[assert, [xor, 1, 2]],
stop]],
[if,
[eq, [mload, 0], …
```

Rewrite ne (!=) with xor

---

examples/tokens/ERC20.vy

I replaced `unter` to `under`
By hand.
By your eyes.
Trivial typo in comment fixed.

Typo in comment ✍

---

setup.py
vyper/parser/parser.py

This is my first PR in this repo so please be gentle. I was looking for a simple task to fire up my brain after vacation :)
- Upgraded to mypy 0.701 [which comes with lots of improvements](https://mypy-lang.blogspot.com/2019/04/mypy-0700-released-up-to-4x-faster.html)
- Changed version in `setup.py`
- added a cast for a failing check that was previously uncaught. The `cast` is needed because the return type of `ast.parse` depends on the `mode` which defaults to `exec` and returns an `ast.Module` in that case.
run `tox -e lint`

Upgrade to mypy 0.701

---

docs/logging.rst
docs/structure-of-a-contract.rst

Fixed typos.
Made the statements grammatically correct.
**Older:**
`@payable |  The contract is open to receive ethereum.`
**Updated**
`@payable |  The contract is open to receive Ether.`
Followed the warnings given by WebStorm editor and fixed the typos.
Also used Google to verify the spellings.
Open the structure-of-a-contract.rst in WebStrom editor, apart from vyper (Vyper), Ethereum (ethereum), Clampett, nonrentant, STATICCALL, and inlined there are no typo warnings raised by the editor.
Changed ethereum to Ether in Decorators.
Fixed typos in structure-of-a-contract.rst

Fixes typos for structure-of-a-contract.rst

---

tests/parser/features/decorators/test_private.py
vyper/parser/self_call.py
vyper/types/types.py

Fix https://github.com/ethereum/vyper/issues/1418.
The dynamic push_args segment was inappropriately used for backing up static arrays onto the stack. However, it happened to back up the elements correctly when the array elements were nonzero. This removes dynamic push_args and fixes the length count for the static push_args segment.
Check the new test which passes a zeroed out static array to a private function.
Fix static array packing for private functions

Fix static array frame for private functions

---

bin/vyper

Fix #1394.
```bash
$ vim myContract.vy  # Contents of #1394
$ vyper myContract.vy 
Exception: Imported interface "foobar{.vy,.json}" does not exist.
$ vim foobar.json  # Just put `{}` inside
$ vyper myContract.vy 
0x6100...
```

Fix path missing exception.

---

docs/installing-vyper.rst

Created a bash script to install vyper on ubuntu systems.
Added those changes in the installing-vyper.rst
After following the **Installing Vyper** Section on **Read the Docs**, I thought about creating a bash script for installation purpose.
The script can be found at:
[Bash script to install vyper on Ubuntu](https://github.com/balajipachai/Scripts/blob/master/install_vyper/install_vyper_ubuntu.sh)
> wget https://github.com/balajipachai/Scripts/blob/master/install_vyper/install_vyper_ubuntu.sh
> chmod 775 install_vyper_ubuntu.sh
> ./install_vyper_ubuntu.sh
Added bash script to install vyper in installing-vyper.rst

Updated installing-vyper.rst with option to install Vyper by using a bash script

---

tests/parser/exceptions/test_constancy_exception.py
vyper/parser/context.py
vyper/parser/stmt.py

Fix #1397 
Add another type of block (range_scope) which can set constancy.
See tests added in https://github.com/ethereum/vyper/pull/1424/commits/d299235a6023f6ea5ac72396266c866a90dc88ac
Add constancy protection to range expressions

Add constancy protection to range expressions

---

SECURITY.md

Add an entry to the VVE table for #1418 disclosure. It was determined that no known wide-scale usage of Vyper would be affected.

Add Disclosure for #1418

---

tests/parser/features/decorators/test_private.py
vyper/parser/self_call.py

Fix #1463 
The dynamic section copier skipped null elements in case there was a difference between len(array) and maxlen(array) since elements past-the-end of memory are null. However, that could fail if the array length was nonzero but it had null elements. This fixes the dynamic section copier by explicitly using the length specified in the ABI encoding for byte arrays.

Fix private underflow

---

tests/parser/types/test_lists.py
vyper/exceptions.py
vyper/parser/parser_utils.py

Fix #1478 and #1483 
TODO:
This goes back to commit 444870548f1008b9c6b42723ae8fdcb367acbf97.
Before that, the type of the index was inferred. After that, it changed
to be the default numeric type in the language, `num` (now `int128`).
Array index types should generally be uint256.
Check IR of following:
```python
xs: uint256[10]
@public
def signed_bounds_check(ix: int128) -> uint256: 
return self.xs[ix]
@public
def uint256_index(ix: uint256) -> uint256: 
return self.xs[ix]
```
Check this throws compile-time exception:
```python
xs: uint256[10]
@public
def compile_time_bounds_check() -> uint256: 
return self.xs[10]
```
- Allow array index to be uint256 or int128
- Fix runtime bounds checks for signed indices
- Convert runtime bounds checks into compile-time check for literal
indices.

Allow array index to be uint256

---

vyper/parser/parser_utils.py

Optimize compiler-generated array copies. Depends on #1479 because of a conflict
Remove bounds checks for when a loop is compiler-generated.
Check before/after IR for this contract
```python
BIG_VALUE: constant(uint256) = 100
@public
def do_work(a: uint256[BIG_VALUE]):
assert self != msg.sender
@public
def do_something(a: uint256[BIG_VALUE]):
self.do_work(a)
```
Optimize compiler-generated array copies

Array copy optimization

---

docs/installing-vyper.rst

@jacqueswww Not sure if we want to add this here or not (feel free to close if not) but may save a bit of headache for people who are getting the tests running for the first time (or first time in a while like me 😓😅)
Added a couple lines to docs.
N/A
N/A
Added `make dev-deps` to docs.

Add `make dev-deps` to installation docs

---

vyper/signatures/function_signature.py

Allow boolean as default parameter

---

vyper/parser/self_call.py

Reduced contract code size due to excessive pushing/popping of locals.
Changed `push_local_vars` and `pop_local_vars` in `self_call.py` to LLL code that implements a loop equal in semantics.
All the tests pass.
Compile the following contract.
```python
struct Animal:
Name: uint256
Exists: int128
COLLECTION_SIZE: constant(uint256) = 1000
contractOwner: address
daddy: address
collection: map(address, Animal)
count: int128
@private
@constant
def isZookeeper(sender: address) -> bool:
return sender == self.contractOwner or sender == self.daddy
@public
def addToCollection(animals: address[COLLECTION_SIZE]):
assert self.isZookeeper(msg.sender)
for animal in animals:
if animal == ZERO_ADDRESS: break
if self.collection[animal].Exists == 0:
self.count += 1
self.collection[animal].Exists = …
```

Wrap pushing and popping of locals into a loop.

---

docs/built-in-functions.rst
docs/types.rst
examples/auctions/blind_auction.vy
examples/wallet/wallet.vy
tests/parser/exceptions/test_invalid_literal_exception.py
tests/parser/exceptions/test_structure_exception.py
tests/parser/features/test_internal_call.py
tests/parser/functions/test_keccak256.py
tests/parser/integration/test_basics.py
tests/parser/syntax/test_keccak256.py
tests/parser/syntax/test_unbalanced_return.py
tests/parser/types/test_variable_naming.py
vyper/functions/functions.py
vyper/parser/stmt.py
vyper/signatures/event_signature.py
vyper/signatures/function_signature.py
vyper/utils.py

Implemented #1328 
Replaced instances of `sha3` in docs, tests, examples, and language implementation with `keccak256`. 
Added thrown exception when `sha3` is used instead of `keccak256` + added tests for this.
Did _not_ make any changes to the LLL/opcodes. 
Run the tests:
`make test`
Remove sha3 alias

Remove sha3 alias

---

docs/built-in-functions.rst
docs/types.rst

This PR is mostly pulling content from #1093 into the docs.
The main outstanding blocks of work to do towards that VIP at this point (at least that are currently on my radar) are:
1. adding full support for conversions to-from `bytes` type
2. adding full support for conversions to-from `address` type
These are both outlined already in the table in #1093, and are something I'll be making commits toward. 
However, I figured given that a lot is implemented at this point, it would be worth adding a table that defines the current state of things somewhere in the docs, as otherwise the current specification is a bit buried in Github.
^^
`make docs`
Added current state of type conversions support to docs.

Added current state of type conversions support to docs

---

vyper/compiler.py

Fixed a couple of typos in a warning message.  Also update message to be emitted by `warnings` module.

Use warnings module/fix typos in warning message

---

bin/vyper
bin/vyper-serve
tests/compiler/test_bytecode_runtime.py
tests/compiler/test_opcodes.py
tests/parser/functions/test_abi.py
tests/parser/functions/test_interfaces.py
vyper/compiler.py
vyper/signatures/interface.py
vyper/typing.py

Added type annotations for a number of functions encountered during the first stages of invoking the `vyper` binary.  Also did some refactors to facilitate type checking and annotation.
Run the tests.  Reviewers might also find it helpful to look at each commit individually instead of the entire branch diff.
- The API of `vyper.compile_codes` has been simplified to always return an `OrderedDict` mapping vyper code file names to their respective compilation results.  This means that this function no longer accepts an `output_type` keyword argument.  Users wishing to duplicate the functionality of passing `output_type='list'` should convert the results of this function to a list like so: `list(compile_codes(...).values())`.

Type annotations for early stage compiler functions

---

tests/parser/functions/test_convert_to_bytes32.py
vyper/types/convert.py

Added support for conversion _to_ `bytes32` _from_ `decimal`. Minor part of #1093
Minor change to `convert.py`.
Run the tests:
`make test`
Or more specifically:
`pytest -k test_convert_to_bytes32`
Added support for conversion _to_ `bytes32` _from_ `decimal`.

Added `bytes32` as target type for `decimal` conversion

---

make.cmd

Updated the make.cmd file for windows dev environments (There was also a TODO). It is modeled exactly like the MAKEFILE with one exception:
MAKEFILE runs `sphinx-apidoc -o docs/ -d 2 vyper/`, which I could not figure out why it is needed. Please let me know if this needs to be added to make.cmd as well or if it can even be removed from the MAKEFILE. It seems to produce unnecessary .rst files which are included nowhere.
Added the following commands: make 
- dev-deps: install test and lint dependencies
- lint: run lint
- docs: clean compile and open docs
- clean: Run all three clean commands
- clean-build / clean-pyc / clean-test: delete unnecessary files and folders
Modify the make.cmd file 
make [lint clean clean-pyc clean-build clean-test docs] on a windows machine
Extended make.cmd …

Added new commands to make.cmd: dev-deps, lint, docs, clean

---

tests/parser/features/decorators/test_private.py
tests/parser/syntax/test_tuple_assign.py
tests/parser/types/numbers/test_constants.py
vyper/parser/context.py
vyper/parser/events.py
vyper/parser/expr.py
vyper/parser/function_definitions/parse_public_function.py
vyper/parser/lll_node.py
vyper/parser/parser_utils.py
vyper/parser/self_call.py
vyper/parser/stmt.py
vyper/signatures/function_signature.py

Fixes #1381.
This is an optimisation I am glad I finally got to make! Basically we were copying variables to memory unnecessarily, by using the calldata directly one not only gets better speed - but also ensures on the EVM level the variables are read-only (yes we had a test that actually was altering a parameter in a tuple assign).
This changes affects these these function parameter types.
- Arrays
- All Base Types
Note: Turned out ByteArrays were too difficult optimise, especially when they tend to have to be packed, which one would have to just allocate them again. Also one looses out not being able to always re-use the identity / mem copy contract.
Taking some files from the examples directory:
Blind Auction -> 73 % less bytecode (!!!)
ERC20 -> 4.9 % less bytecode
ERC720 -> 6.3% less …

Add calldata located variables.

---

tests/signatures/test_method_id_conflicts.py
vyper/signatures/interface.py

It's possible to compile a vyper contract that contains conflicting methods.  That is, if a contract has two or more methods that produce the same internal routing ID (used for method selection during contract execution), it will still compile and create a contract with a security vulnerability.
Added a check for duplicate method IDs in the contract interface.
Run the tests.
* Fixed a bug that allowed contracts with conflicting methods (methods that produce the same internal routing ID) to compile without error.

Disallow conflicting method IDs

---

tests/parser/features/decorators/test_nonreentrant.py
vyper/parser/context.py
vyper/parser/function_definitions/parse_function.py
vyper/parser/parser_utils.py
vyper/parser/self_call.py

Return statements where missing unlock statements.

Nonreentrant return fix

---

docs/installing-vyper.rst

The 'installing vyper' page included instructions for Ubuntu and MacOS only.
Since Windows is a very popular OS, explaining what are the possibilities for Windows users is important.
This PR fixes https://github.com/ethereum/vyper/issues/1531
Added the 2 options for windows: docker and linux subsytem for windows.
Simply edited docs/installing-vyper.rst
Observe docs/installing-vyper.rst

Add instructions for Windows users.

---

vyper/interfaces/ERC20.py

Added the 'indexed' keyword, so vyper/interfaces/ERC20.py would comply with ERC20 specification.
This PR fixes https://github.com/ethereum/vyper/issues/1502

Add 'indexed' keyword to ERC20 interface

---

.gitignore
bin/vyper
setup.py
vyper/__init__.py

Revisited Charles' original PR #1220 , and all seems to work well if one uses `package_data=` instead of `data_files=`.
Git commit hash shown as part of version output.

Inject git version.

---

snap/snapcraft.yaml

Noted we were using an older version of Python 3.6. Also noted we were missing a base snap leading to inconsistent build results.

Updates to snapcraft build config

---

tests/signatures/test_invalid_function_decorators.py
vyper/parser/parser.py
vyper/signatures/function_signature.py

Fixes #1544.  Constant, non-reentrant functions such as the following were compilable in certain cases:
```python
@public
@constant
@nonreentrant('lock')
def nonreentrant_foo() -> uint256:
return 1
```
Added a failing test for the above contract.  Modified the handling of certain values in the `FunctionSignature.from_definition` method.
Run the tests.
- Fixed a bug that allowed a function to be decorated with both `@constant` and `@nonreentrant(...)`.

Fix compilable constant, nonreentrant functions

---

bin/vyper
bin/vyper-serve
tests/test_utils.py
vyper/ast.py
vyper/exceptions.py
vyper/parser/lll_node.py
vyper/settings.py
vyper/utils.py

Today, I realized it's a bit hard to know anything about an instance of `vyper.ast.VyperNode` without inspecting its values.  While debugging some things, I hacked together a `__repr__` implementation for `VyperNode` and decided it could be useful to add to the project.
Added a utility function `vyper.utils.annotate_source_code` that annotates a position nicely in a source code file based on a `lineno` and `col_offset`.  Added usages of this new function in both `ParserException.__str__` and `VyperNode.__repr__`.  Also created a `settings` module that acts as a central store of settings pulled from environment variables.  Added two new settings vars to that module to control how source annotations are printed in compiler error messages.
Added some tests for the formatting.  Run the tests. …

Add better source error printouts and VyperNode.__repr__

---

tests/parser/features/test_internal_call.py
vyper/parser/self_call.py

Fixed an bug stemming from #1470 - calls to private functions that had a bytes list following an integer list of length > 1 were underflowing.
In the following example calls to `bar` would underflow, but `bar2` would succeed:
```python
@private
def _foo(y: int128[2], x: bytes[5]) -> int128:
return y[0]
@private
def _foo2(x: bytes[5], y: int128[2]) -> int128:
return y[0]
@public
def bar() -> int128:
return self._foo([1, 2], b"hello")
@public
def bar2() -> int128:
return self._foo2(b"hello", [1, 2])
```
Used `get_static_size_of_type` to verify the memory size of each argument during iteration.
I have included a test as the first commit, if you run it without the 2nd commit you can see the bug in action.
* Bugfix - multiple arrays as inputs in a private function

Bugfix - calls to private functions with multiple lists as parameters

---

tests/parser/features/test_internal_call.py
vyper/parser/self_call.py

Raise when kwargs are used in `private` function calls (#1554)
`parser.self_call.call_self_private` raises a `TypeMismatchException` if any kwargs are given
I added tests to `tests/parser/features/test_internal_call.py`.
* Disallow keyword arguments in private function calls

Disallow kwargs in private function calls

---

vyper/parser/self_call.py

Moved the recently added kwarg check for self calls to a more meaningful location.  Now, the check is done just before the line of code where it makes a difference.
Run the tests.

Move kwarg check to more meaningful location

---

vyper/parser/stmt.py

Added context information for a couple of compiler exceptions.

Add context information to some error messages

---

bin/vyper
vyper/signatures/interface.py

Replace `os.path` with `pathlib.Path` - it makes for much cleaner code and reduces headaches when dealing with Windows file systems.
Run the tests.

use pathlib instead of os.path

---

tests/parser/types/numbers/test_sqrt.py

Per https://github.com/ethereum/vyper/pull/1560#issuecomment-518024254, I increased the deadline for `test_sqrt_valid_range` to 1 second.  It keeps failing locally and makes me want to do a murder.
Run the tests and enjoy non-flaky results.

increase test deadline to 1 second

---

tests/parser/features/external_contracts/test_external_contract_calls.py
tests/parser/features/test_internal_call.py
vyper/parser/external_call.py
vyper/parser/parser_utils.py
vyper/parser/self_call.py

Added a check for calls to private functions where no args are given but the call expects args. Prior to this PR, the following code would compile:
```python
@private
def bar(a: int128) -> int128:
return 1
@public
def foo() -> int128:
return self.bar()
```
I also tweaked the inputs to `pack_arguments`, allowing for code highlights in the exceptions raised there.
* `vyper.parser.self_call.call_self_private`
* added a check when no args are given that raises if args were expected
* `vyper.parser.parser_utils.pack_arguments`
* replaced input arg `pos` with `stmt_expr`, derive position using `getpos(stmt_expr)`
* include `stmt_expr` when raising exceptions
Run the tests.  I've added tests to check for args when none should be given, no args when args should be given, and the wrong number of …

Compile-time check for missing args in private calls

---

docs/installing-vyper.rst
docs/structure-of-a-contract.rst
docs/testing-contracts.rst
docs/vyper-by-example.rst
examples/stock/company.vy
examples/voting/ballot.vy
tests/parser/features/decorators/test_private.py
tests/parser/features/external_contracts/test_self_call_struct.py
tests/parser/features/test_internal_call.py
tests/parser/features/test_logging_from_call.py
tests/parser/features/test_units.py
tests/parser/functions/test_interfaces.py
tests/parser/functions/test_return_tuple.py
tests/parser/integration/test_basics.py
tests/parser/syntax/test_invalids.py
tests/parser/syntax/test_send.py
tests/parser/syntax/test_tuple_assign.py
vyper/parser/external_call.py
vyper/parser/self_call.py

Prevent calls to public functions via `self` - fixes #1199
This is an amended version of #1561 without the awful mess I made rebasing.
* In `vyper/parser/self_call.py`, raise `StructureException` where previously there was a call to `call_self_public`
* Update tests
* Update examples
* Update documentation
Run the tests.
* Disallow calls to public functions via self

Disallow self.* calls to public functions - round 2

---

Dockerfile
snap/snapcraft.yaml

Wasn't able to build snap or docker images for the library, noticed the `git` subprocess was failing because it wasn't installed

Build process was missing git as a dependency for containers

---

setup.py

For a while now, I noticed the main docs page doesn't render quite effectively. I realized that the field 'long_description_markdown_filename' does not automatically set the content type to markdown, and instead it is rST. This should fix the problem of proper rendering in the docs.

Added markdown content type for readme

---

Makefile

Cleaned up and added commands for an explicit release process, which should make it easier to perform correctly.
Biggest changes were:
- Ask whether to apply devnum part number change and push new tag upstream
- Split release process into pypi, snapcraft, and docker release processes
- Added new clean rules
Perform it yourself!
Note: All login credentials must be provided separately during the login steps of each build platform release step.

Added more detailed release process

---

tests/cli/vyper_compile/test_import_paths.py
vyper/cli/vyper_compile.py

When using the `vyper` command line script, allow contract paths outside of the root path
If a contract path is given that is outside of the root path, vyper still attempts to compile it but does not search for interfaces from the root path.
I added a test case to `vyper/cli/test_import_paths.py`.

CLI - Allow compiling contracts outside of root path

---

tests/parser/exceptions/test_structure_exception.py
vyper/signatures/function_signature.py

As the code currently stands, only a single nonreentrant decorator is supported.

Add check for only single @+@nonreentrant decorator.

---

vyper/__main__.py

In order to not have to rely on shell scripts to be deployed with `setup.py` and be able to call vyper from various non-venv python installations, this PR adds the option to execute the vyper module and sub-functionality directly via `python -m vyper [--vyper-compile | --vyper-lll | --vyper-serve] <args>`.
- `python -m vyper <args>` - by default calls `vyper_compile(args)`
- `python -m vyper --vyper-compile <args>` - calls `vyper_compile(args)`
- `python -m vyper --vyper-lll <args>` - calls `vyper_lll(args)`
- `python -m vyper --vyper-serve <args>` - calls `vyper_serve(args)`
- added `__main__.py` with minimal dispatching code. No existing code modified :)
- run `python -m vyper <args>`. see section **"What I did"** for a complete list of dispatched commands.
```console
~/w/p/vyper ❯❯❯ …
```

Feature: Add option to execute vyper cli via `python -m vyper <args>`

---

tests/parser/functions/test_default_parameters.py
tests/parser/syntax/test_ann_assign.py
vyper/parser/parser_utils.py
vyper/signatures/function_signature.py

* Fixed #1469 
* Fixed https://github.com/ethereum/vyper/pull/1466#issuecomment-504485443
* Added a type check for integer arrays, prior to this PR the following code would compile:
```python
@public
def foo():
a: uint256[2] = [-1, -1]
```
* `vyper/parser/parser_utils.py` in `make_setter`, raise `InvalidLiteralException` when left type is `BaseType` and right value is out of bounds. This works for arrays as well because `make_setter` recursively calls itself until the left type is reduced to a `BaseType`.
* `vyper/signatures/function_signature.py` moved param check to `validate_default_values` to allow recursive calls for checking arrays
I added test cases for default parameters and array assignment.

Typechecks for default parameters and int arrays

---

docs/built-in-functions.rst
docs/conf.py
docs/index.rst
docs/installing-vyper.rst
docs/logging.rst
docs/release-notes.rst
docs/structure-of-a-contract.rst
docs/testing-contracts.rst
docs/vyper-by-example.rst

Various fixes and updates to documentation.
* Rebuilt `docs/built-in-functions.rst` to use sphinx directives - closes #1513 
* Fix explanations for `ecadd` and `ecmul` - closes #1533 
* Fixed broken and forwarded links, replaced broken `:pyobject:` references - closes #1562 
* Added documentation for `assert_modifiable` - closes #1581 
* Fixed markdown-style code highlights that display as italics in RST
* Highly opinionated reorder of table of contents, feels much more logical to me now :)
Read the docs.

Documentation fixes and updates

---

docs/compiling-a-contract.rst
docs/structure-of-a-contract.rst
setup.py
tests/cli/vyper_json/test_compile_from_input_dict.py
tests/cli/vyper_json/test_compile_json.py
tests/cli/vyper_json/test_get_contracts.py
tests/cli/vyper_json/test_get_settings.py
tests/cli/vyper_json/test_interfaces.py
tests/cli/vyper_json/test_output_dict.py
tests/cli/vyper_json/test_output_selection.py
tests/cli/vyper_json/test_parse_args_vyperjson.py
tests/compiler/test_source_map.py
vyper/ast_utils.py
vyper/cli/vyper_compile.py
vyper/cli/vyper_json.py
vyper/cli/vyper_lll.py
vyper/cli/vyper_serve.py
vyper/compile_lll.py
vyper/compiler.py
vyper/exceptions.py
vyper/typing.py

Added `vyper-json` CLI tool - closes #1520
See the [updated documentation](https://github.com/iamdefinitelyahuman/vyper/blob/13db68acfbee9084c4e4664bdff868117fcbc302/docs/compiling-a-contract.rst) for a detailed explanation of how `vyper-json` works.
Other changes in this PR:
* `vyper/compiler.py`: `compile_codes` accepts a dict of lists for `output_formats`, for specifying different outputs for each contract. Added annotations to make this clearer when reading the code.
* `vyper/compiler.py`: Added `source_id` arg to various functions, to allow different IDs when compiling multiple contracts
* `vyper/compile_lll.py`: modified `assembly_to_evm` to allow source maps from constructor bytecode
* `vyper/cli/vyper_compile.py`: Renamed variables in to be more verbose / consistent with …

Add vyper-json CLI tool

---

tests/parser/functions/test_default_parameters.py
vyper/parser/expr.py
vyper/signatures/function_signature.py

Allow builtin constants and environment variables to be used as defaults for keyword arguments - closes #1525 
This does NOT allow custom constants.
* `vyper/parser/expr.py` - added `BUILTIN_CONSTANTS` and `ENVIRONMENT_VARIABLES`
* `vyper/signatures/function_signature.py` - add checks to `validate_default_values`
Run the updated tests.
* Allow constants and environment variables to be used as defaults for keyword arguments

Allow environment variables and constants as default values

---

tests/parser/features/test_assert.py
vyper/compile_lll.py

As discovered by @michwill and reported on Gitter, the following code was not compiling due to an assertion error:
```python
@public    
def g():
ok: bool = False
for i in range(5):
assert ok, "Reasons"
```
The issue was in `vyper/compile_lll.py` - several calls to `compile_to_assembly` were not including the `existing_labels` argument:
https://github.com/ethereum/vyper/blob/089d0c4046a5e71412b46205788a89e76d7646ea/vyper/compile_lll.py#L273-L275
Added `existing_labels` as an argument in `compile_to_assembly` calls where it was missing.
See the new test cases in `tests/parser/features/test_assert.py`.  I also added checks for proper behavior of the iterated assertions.

Fix incorrect compile_to_assembly call args

---

tests/parser/functions/test_default_function.py
vyper/parser/parser.py

Fix #1603 
Implemented the solution from https://github.com/ethereum/vyper/issues/1603#issuecomment-529238275
Check tests, also look at IR of following code:
```python
@public
@payable
def blockHashAskewLimitary(v: uint256): # function selector: 0x00000000
send(msg.sender, self.balance)
@public
def __default__() -> uint256:
return 1`
```
Fix edge case in function selector with 0 calldata

Check calldatasize before loading func selector

---

docs/conf.py
docs/constants-and-vars.rst
docs/index.rst
docs/types.rst

Added documentation for environment variables.
Split the "Types" section into two pages, the new one is called "Constants and Environment Variables".  Moved the information on constants to this new page, then added docs for environment variables.
Read the docs.

Add documentation for environment variables

---

vyper/parser/events.py
vyper/parser/parser_utils.py

Fix #1599, #1610 
See mentioned issues for discussion
Fix zero padding conditions in ABI encoder

Fix termination condition in zero_pad

---

vyper/functions/functions.py
vyper/parser/expr.py

* Modified the error messages raised on incorrect decimal precision to include the maximum allowable number of decimals
* Renamed some variables in `as_wei_value` to make the code more readable
Check the diff, run the tests

Improved decimal precision error messages

---

tests/parser/exceptions/test_invalid_same_variable_assignment.py
tests/parser/functions/test_unary.py
vyper/parser/expr.py

Fixed: #1636 
- Reject Unary negation on unsigned integers
- Clamped that unary negation must be strictly greater than minimum value for signed integer
Fixed unary negation bug

Fixed 1636 unary negation bug

---

vyper/parser/events.py
vyper/parser/lll_node.py
vyper/parser/parser_utils.py
vyper/parser/stmt.py

Increase clarity and efficiency of zero-padder. Currently overlaps with #1611 - fixes #1599, #1610. See the discussion in those issues as well as https://github.com/ethereum/vyper/issues/1603#issuecomment-529239131.
CALLDATACOPY writes zero bytes into memory when the location in calldata is >= calldatasize.

Zero pad from calldata

---

tests/parser/exceptions/test_syntax_exception.py
vyper/ast.py
vyper/parser/stmt.py

We don't support For .. orelse. We should not let it blindly not generate code.
```
^.^
```

Remove for orelse for For

---

.github/ISSUE_TEMPLATE/vip.md

Everytime I enter a new VIP I think why "Simple Summary" and "Abstract" should both be in the template. I can't think of a good reason! So maybe let's remove it?

Remove Abstract as redundent from VIP template

---

tests/parser/types/numbers/test_sqrt.py
vyper/functions/functions.py

* Fixed an overflow when attempting to calculate the sqrt of `2**127`
`vyper/functions/functions.py` line 1213, divide before adding.
Run the tests. I've added a new test case to specifically check the upper and lower bounds, as this was discovered by fuzzing.
* Bugfix: sqrt overflow on upper bound of Decimal

Avoid overflow on sqrt of Decimal upper bound

---

tests/parser/features/iteration/test_repeater.py
tests/parser/features/test_conditionals.py
vyper/optimizer.py
vyper/parser/stmt.py

Fix #1511 and #1620 
Seq will issue a pop after every univalent statement but the last one.
However, if and for statements should have zerovalent bodies. This PR
forces even the last statement to get a pop if it is univalent.
See new tests
Fix stack valency issues in if and for statements.

Force parse_body to be zerovalent

---

docs/vyper-by-example.rst

Added an explanation for `pendingUsers` parameter in `Vyper By Example` doc. 
Was going through the documentation for "Vyper By Example" and if one goes through it copying directly from the snippets then they'll get a compiler error because the snipper forgoes `pendingUsers`. 
I added the code to the snippet and a small line explaining what the variable does.

Expand snippet to include pendingReturns map

---

tests/parser/types/test_lists.py
vyper/parser/expr.py

Fix off-by-one in list type checking
The loop wanted to check if there were any elements in the output list yet, but the check should have been `>= 1` instead of `> 1`
Fix off-by-one in check for homogeneous list element types.

Fix off-by-one in list type checking

---

tests/parser/types/numbers/test_constants.py
vyper/parser/expr.py

- Fix https://github.com/ethereum/vyper/issues/1658
- Always precompute both sides into an LLL reference (pre_alloc for call
no longer needed), so generally more gas efficient if the arguments
are more than ~2 ops
- Remove a jumpi for mul uint256
- Simplify type calculation / pos calculation
- Use clamps instead of seq-assert where it's clearer
- Use similar styles for similar output (e.g. mul uint256 looks like mul
int128)
Use references to break the exponential behavior in #1658

Simplify Expr.arithmetic

---

.circleci/config.yml
tox.ini
vyper/ast.py
vyper/ast_utils.py

Add support for Python 3.8
* Replace `Constant` python AST type with deprecated type names when generating Vyper AST nodes.
* Add python3.8 build to CI
Run the tests
* support for Python3.8

Add support for Python3.8

---

tests/parser/types/numbers/test_constants.py
tests/parser/types/test_variable_naming.py
vyper/utils.py

Fix #1697  and related bugs
Add `zero_wei` to list of reserved words (also `tx`, `block`, and a missing comma between `empty_bytes32` and `max_int128`)
Run the tests, I added parametrized cases to check builtin constants when assigned in memory, storage, and function signatures.

Reserved keywords fix

---

vyper/compiler.py

Fix #1701 
Append `\n` to all source code before compiling.
Run tests.

Comment at EOF bugfix

---

docs/built-in-functions.rst
tests/parser/features/test_logging.py
vyper/functions/functions.py

I found this was quite necessary in some cases. Also we need to start supporting the other uint* types, keep seeing them in the wild, and then I have to do hacks like mining function signature + raw_log + raw_call.

Add support raw_log data of bytes32.

---

tests/parser/types/test_bytes.py
vyper/parser/expr.py
vyper/parser/stmt.py
vyper/types/types.py

Fix https://github.com/ethereum/vyper/issues/1717
There is a rewrite rule but was only intended for literals.

Only rewrite bytes32 when they are literals

---

tests/parser/exceptions/test_invalid_literal_exception.py
tests/parser/syntax/test_constants.py
vyper/parser/parser_utils.py

fixes: #1680
Raise `InvalidLiteralException` when scientific notation is used for a literal value (either for a constant, or in a method)
WIP
Well, tests fail...
Added additional verification of literals to ensure scientific notation was not used (as Python interprets as a float)

Make scientific notation an invalid literal declaration

---

FUNDING.yml

Added a link for using [GitHub Sponsors](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository). Needs to be enabled in settings though.

Add link to Gitcoin Grant for Github Sponsors Button

---

vyper/types/convert.py

Fixed #1725 
tiny edit to change `fornat` to `format`
run code from #1725
Fix typo in an error message for bad converts

Fix fornat typo

---

tests/parser/syntax/test_constants.py

I added a snippet of the test case discovered in #1725 (which uncovered a separate spelling bug). I was curious why that particular path wasn't being hit, and was getting strange results in the error message, so I decided to add this test case failure to ensure it's always being tested in case a parsing change makes it work differently.

Added testcase from #1725

---

Dockerfile

I updated the build to Python 3.7 because I couldn't get 3.6 to work, and also it was time.
Note: Larger build size

Updated docker image to Python 3.7

---

setup.cfg

https://docs.codecov.io/docs/about-code-coverage

Add branch coverage reporting

---

tests/parser/globals/test_setters.py
vyper/parser/expr.py
vyper/parser/parser_utils.py

Fix https://github.com/ethereum/vyper/issues/1686
fix the order of the RHS arguments in make_setter
cf. tests
Fix order of assignment statements in struct assignment

Fix struct assignment order

---

.github/workflows/test.yml

Codecov _should_ merge these?
(see https://docs.codecov.io/docs/merging-reports)
---
This is important for catching coverage data in case we make version-specific imports for a feature

Added coverage reporting to Python 3.7/3.8

---

.gitignore

When `pytest-xdist` runs coverage in parallel, it makes filenames with an ending in order to orchestrate it. This ignores those files.

Ignore parallel coverage files

---

tests/cli/vyper_json/test_compile_from_input_dict.py
tests/parser/syntax/test_bool.py
tests/parser/syntax/test_create_with_code_of.py
tests/parser/syntax/test_raw_call.py
tests/parser/types/test_identifier_naming.py
vyper/ast_utils.py
vyper/exceptions.py
vyper/utils.py

Added some more things to the internal reserved keyword list
Fixes: #1710
grep-foo
Added all reserved keywords to test. Added test for function names.
N/A

Added reserved keywords

---

tests/parser/exceptions/test_invalid_literal_exception.py
tests/parser/syntax/test_constants.py
tests/parser/types/numbers/test_decimals.py
tests/parser/types/value/test_as_wei_value.py
vyper/parser/parser_utils.py

Actual solution to #1680, allowing scientific notation literals (e.g. `3e6`, `1e-10`) to be used in vyper programs.
See: https://python-reference.readthedocs.io/en/latest/docs/float/scientific.html
- ~~Need to work out semantics. Does a positive exponent get translated to an integer literal, or remain a decimal? Should it always be parsed a decimal?~~ Parsing as a decimal always works
- ~~Needs significant test cases to prove equivalency of constant expressions to their runtime equivalent (avoid issues like #1693)~~ Increased precision in fde6d2b avoids floating point issues
Added support for decimal literals using scientific notation

Feature: Allow scientific notation for literals

---

tests/parser/functions/test_unary.py
vyper/parser/expr.py

Fix #1757 
get_min_val_for_type makes a check that the input type is an integer type, which is incorrect.
see test
Fix bug introduced in #1638 and allow decimals to be negated again

Fix overspecificity in get_min_val_for_typ

---

setup.cfg

`pytest-xdist` adds the ability to parallelize tests using the `-n [NUM]` flag. It also allows dynamically checking how many are available: https://github.com/pytest-dev/pytest-xdist#speed-up-test-runs-by-sending-tests-to-multiple-cpus

Upgrade to use as many CPUs as available locally

---

vyper/functions/functions.py
vyper/parser/parser_utils.py

Fix #1761 
Put all available gas (i.e., `['gas']`) for calls to precompiled contracts, especially:
- `ECREC` (1)
- `ID` (4)
- `ECADD` (6)
- `ECMUL` (7)
Note that calls to `SHA256` (2) are already given the full gas.
Check if the changes affect only (and all of) the calls to precompiled.
Fix potentially insufficient gas stipend for precompiled contract calls

Fix #1761: potentially insufficient gas stipend for precompiled

---

LICENSE

This PR changes our license from MIT to Apache 2.0, applicable for all future versions of Vyper.
Being a move from a less permissive license to a more permissive license, there is no requirement to obtain approval from previous contributors as your copyright extends even after this change has been made.
---
More about licenses:
- [MIT](https://choosealicense.com/licenses/mit/)
- [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/)

Change License to Apache 2.0

---

vyper/parser/global_context.py
vyper/parser/parser_utils.py

* Fixed the source offsets for public getter functions
* Added source offsets to array index bounds checks
* `parser/parser_utils.py` - added a method `set_offsets` that recursively adjusts column and line offsets for a node and all it's children
* `parser/global_context.py` - call `set_offsets` method on each generated getter to modify offsets to the correct values
* `parser/parser_utils.py` - added `pos` to the `LLLnode`s related to array clamping
Run tests.

Fixes to source map offsets

---

tests/parser/syntax/test_interfaces.py
vyper/signatures/interface.py

When importing a Vyper contract as an interface, a `StructureException` is raised if that file includes an `implements` statement.
In `vyper/signatures/interface.py`, I modified `extract_sigs` to exclude AST nodes related to `implements`.
Run the tests. I added a new test case around this behavior.

Bugfix - Importing an interface that contains an 'implements' statement

---

tests/parser/functions/test_minmax.py
vyper/functions/functions.py

Fix an error in `min` and `max` that caused incorrect evaluation with signed comparators - closes #1690 
Simplify / adjust logic in `vyper/functions/functions.py` - see code, it's fairly straightforward.
Run the tests.  I added a new test case to check the example given in #1690.

Minmax signing

---

vyper/cli/vyper_json.py

To prevent imports outside of the the root path, `vyper-json` prepends import paths with `/__vyper` and then ensures the final resolved path is still a subfolder of that path.  On Windows this check is failing with `ValueError: 'C:\\__vyper\\path.vy' does not start with '\\__vyper'`.  Oopsies.
You can see a detailed traceback for the issue [here](https://travis-ci.com/iamdefinitelyahuman/brownie/jobs/269839445).
Perform the `relative_to` check against a `Path` object, so that it works on any filesystem.
I confirmed that it works in a Windows 10 VM. Not sure if anyone wants to add Windows to the CI...

Fix Windows path issue when importing interfaces

---

tests/parser/syntax/test_tuple_assign.py
vyper/parser/stmt.py

Add constancy checks for tuple assignment - fixes #1711 
Minor tweak to `vyper/parser/stmt.py`
Run the tests, I added a test case using the example from #1711

Tuple constancy checks

---

docs/built-in-functions.rst
tests/parser/types/numbers/test_uint256.py
vyper/functions/functions.py

* remove overflow checks on `uint256_addmod` and `uint256_mulmod` - closes #1689 
* add basic documentation about these methods
Mostly I used the delete key.
Run the tests. I modified a couple of test cases to make sure it works.

addmod / mulmod

---

docs/built-in-functions.rst
docs/constants-and-vars.rst
docs/contributing.rst
docs/index.rst
docs/release-notes.rst
docs/structure-of-a-contract.rst
docs/types.rst

* Added basic documentation for `self` - closes #1716 
* Minor formatting fixes / edits
Read the docs.

Add documentation for self

---

tests/parser/functions/test_unary.py
vyper/parser/expr.py
vyper/parser/parser_utils.py

Fixed some issues with negating constants.
The following example was failing because bounds checks caught `2**127` as an overflow before applying the `-`:
```python
@public
def foo() -> int128:
return -2**127
```
The following example was also failing with a clamping error:
```python
a: constant(decimal) = 1.1
@public
def foo() -> decimal:
return -a
```
When an unary operation is applied to a constant, return the negated value without applying bounds checks on the original value.
Run the tests. I added some new test cases to verify that the issue is fixed.

Unary operations on literals

---

setup.py
vyper/ast_utils.py

Python 3.8 has changed how line-based offsets are determined for some nodes. For example, with a `FunctionDef` that includes decorators, the decorators are included within the offsets in `<3.8`, they are not in `3.8`.
`asttokens` determines offsets using tokens - it does not have the same inconsistency between Python versions.
In `vyper/ast_utils.py` when generating the fields for nodes in `_build_vyper_ast_init_kwargs`, `asttokens` is used for both the line-based offsets and the absolute offset field `src`. The line-based offsets are then replaced by the Python AST offsets during the `get_slots()` iteration, creating an inconsistency between them and `src`.
Ignore all fields returned by `get_slots()` if they are in `vyper.ast.BASE_NODE_ATTRIBUTES`.
Run the tests.

Fix inconsistent AST offsets in Python 3.8

---

docs/compiling-a-contract.rst
docs/constants-and-vars.rst
tests/base_conftest.py
tests/cli/vyper_compile/test_compile_files.py
tests/cli/vyper_json/test_compile_from_input_dict.py
tests/cli/vyper_json/test_get_settings.py
tests/compiler/test_opcodes.py
tests/parser/syntax/test_chainid.py
tests/parser/syntax/test_self_balance.py
vyper/cli/vyper_compile.py
vyper/cli/vyper_json.py
vyper/cli/vyper_serve.py
vyper/compile_lll.py
vyper/compiler.py
vyper/exceptions.py
vyper/opcodes.py
vyper/parser/expr.py
vyper/parser/lll_node.py
vyper/parser/parser.py
vyper/typing.py

* Add the ability to target multiple EVM versions - closes #1230 
* Use the `SELFBALANCE` opcode when targeting istanbul - closes #1654 
* Expanded `vyper/opcodes.py`:
* Added missing opcodes
* Where gas cost changes between versions, a tuple is used instead of an integer. Values correspond to (byzantium, constantinople, istanbul) - `None` means the opcode is not available, and where the length is < 3 it means the price does not change for future versions.
* Use getter functions for opcodes, instead of directly importing constants into other modules
* `vyper.compiler.compile_codes` now accepts `evm_version` as a kwarg. If not given, the default value is used (`vyper.opcodes.DEFAULT_EVM_VERSION`, currently byzantium)
* Added the option to select EVM version in `vyper.cli` modules 
Run the …

Evm versions

---

tests/parser/functions/test_default_parameters.py
tests/parser/syntax/test_invalids.py
tests/parser/syntax/test_logging.py
vyper/parser/parser_utils.py

Fix #1694
Moved a check in `vyper/parser/parser_utils.py` from `make_setter` to `base_type_conversion`.
Run the tests. I added cases to verify the intended fix.

Add type check for target type in base_type_conversion

---

tests/parser/ast_utils/test_ast_dict.py
tests/parser/syntax/test_constants.py
vyper/ast_utils.py
vyper/cli/vyper_compile.py
vyper/parser/context.py
vyper/types/convert.py

Fix several low-hanging fruit issues.
* `KeyError: self` when attempting to assign a function to a constant - closes #1671 
* Allow bytes literal when creating AST dict - closes #1788 
* In `vyper.cli.vyper_compile`, move `translate_map` to `compile_files` to allow consistency with CLI inputs - closes #1670 
* Fix `convert` max length error messages - closes #1700 
See code.  All of these were very minor fixes, the implementations should be obvious.
Run tests.

Minor bugfixes

---

docs/compiling-a-contract.rst
tests/cli/vyper_json/test_compile_from_input_dict.py
tests/cli/vyper_json/test_compile_json.py
tests/cli/vyper_json/test_output_selection.py
tests/cli/vyper_json/test_parse_args_vyperjson.py
vyper/cli/vyper_json.py

* In the input json, allow `outputSelection` to be given as a subfield within `settings` - this is how Solidity formats it.
This is a cherry-pick from #1778 now that #1783 has merged.

vyper-json - expect outputSelection within settings

---

docs/compiling-a-contract.rst
tests/parser/functions/test_bitwise.py
vyper/functions/functions.py

* use `SHL`/`SHR` for bitshifting when targeting `>=constantinople` EVM ruleset - closes #1268 
* bitshift bytecode optimizations
`functions.functions.shift`: When `_shift` is a literal, do not include `IF SLT 0` or resulting unreachable bytecode.
Run the tests. I added some new test cases and parametrized existing ones.

Implement SHL/SHR for bitshifting

---

vyper/parser/stmt.py

Simplify the type check when returning lists - closes #1691
Copypasta
Run tests.

simplify list return type check

---

docs/built-in-functions.rst
docs/compiling-a-contract.rst
tests/parser/functions/test_get_hash.py
vyper/functions/functions.py

Add `get_hash` method for access to `EXTCODEHASH` opcode - closes #1765
This is a draft pending discussion at #1759 - once the syntax is finalized I'll edit and mark as ready for review.
* `vyper/functions/functions.py`:
* add `get_hash` method with checks for EVM ruleset >= constantinople
* include method in `DISPATCH_TABLE`
Run the tests. I added new cases.

Support for EXTCODEHASH

---

tests/signatures/test_method_id_conflicts.py
vyper/signatures/interface.py

Include private methods when checking for function selector collisions - closes #1687 
`vyper/signatures/interface.py` - do not exclude functions marked as private
Run tests. I added test cases.

Include private methods when checking function selector collisions

---

tests/parser/features/iteration/test_for_in_list.py
vyper/parser/stmt.py

* Raise `StructureException` while parsing, when the number of rounds on a for loop is less than 1. Previously this wasn't caught until the LLL stage and raised a `CompilerPanic` - fixes #1655
* Improve error messages for invalid range argument count, non-iterables, decimals in a range and nested lists - closes #1427, closes #1709
Added and expanded checks in `vyper/parser/stmt.py`
Run the tests. I added some test cases. I also got a bit carried away and parametrized the rest of the test module.

improvements to for loop exceptions

---

examples/factory/Exchange.vy
examples/factory/Factory.vy
tests/examples/factory/test_factory.py

Added an example showing how to use `get_extcodehash` to create a registrar pattern where a child contract is deployed and registered separately from the parent, but the relationship is safely enforced.

Factory example

---

docs/built-in-functions.rst
docs/compiling-a-contract.rst
docs/types.rst
examples/factory/Factory.vy
tests/parser/syntax/test_codehash.py
vyper/functions/functions.py
vyper/parser/expr.py

Modify #1801, change syntax for accessing `EXTCODEHASH` from `get_extcodehash` to `address.codehash`
See code.
Run tests. I updated the related test cases.

Changes to extcodehash

---

tests/cli/vyper_compile/test_parse_args.py
vyper/cli/vyper_compile.py

Fix #1828 
In `vyper/compile.py`, iterate directly over the returned compile data rather than the input args. This is required because when the original path is relative to the current working directory, it is changed to a relative path prior to being returned.
Run the tests. I added a new test that checks the `vyper` cli behavior for an absolute path, a relative path, and an absolute path that is in a subfolder of the current working directory.

Absolute import fix

---

docs/vyper-by-example.rst

In case to declare one key difference between Vyper and Solidity about dynamic arrays, the example code that show in documentation should be lines: 26-29 instead of lines: 22-25.
Changing lines of example code from 26-29 to 22-25 in lines: 154-155's documentation.
Just delete and type it.
Nothing
Nothing

Changing line of example code in Blind Auction

---

vyper/codegen/abi.py

Fix #1409. list-inside-tuple returns were mostly fixed in https://github.com/vyperlang/vyper/pull/1723 but this was a lingering bug. This also fixes #955 .
`add_variable_offset` expects the index to have a vyper type.
check that the example in #1409 compiles.
Fix returning of lists within tuples

Fix abi tuple return for lists

---

vyper/signatures/sig_utils.py

Fix a compiler issue when generating method identifiers for a function returning a struct.  Related to #1838 (in that I found the bug while examining that issue)
Add a missing kwarg in `vyper/signatures/sig_utils.py`
Run tests.

Bugfix: generating method identifier for struct return type

---

tests/parser/features/test_units.py
tests/parser/functions/test_abi.py
tests/parser/functions/test_return_tuple.py
vyper/signatures/function_signature.py

1. Include a `name` field in the ABI when representing tuple types. For inputs, the name is equal to the variable name of the struct. For outputs, the name is `""`. This is consistent with how Solidity represents tuples.
2. For output types, change the given name from `"out"` to `""`. Again - this makes the Vyper ABI more consistent with Solidity.
This is related to, but does require, #1842. As @michwill pointed out, there is a bug when attempting to import a JSON interface that uses structs. Adding the `"name"` field fixes the bug and leads to another conversation: we do not currently support tuple types when importing interfaces. And that will be the subject of another PR :)
Modifications to `vyper/signatures/function_signature.py`. See diff.
Run the tests. I updated cases that were …

Modifications to how ABI data types are represented

---

tests/parser/functions/test_interfaces.py
vyper/signatures/interface.py

Fix issues with `bytes`, `string` and `fixed168x10` when importing an ABI as an interface. Fixes #1832  
1. When determining if an interface has been implemented, ignore the length on `bytes` and `string`.
2. Substitute `fixed168x10` for `decimal` when converting ABI to AST.
3. For `bytes` and `string` arrays, use a length of `1024*1024` in inputs, `1` in outputs. The compiler does not implicitly truncate values so this does not create an issue when a limit is exceeded.
Run the tests. I expanded the cases around ABIs as interfaces to check each type as an input and output.

ABI interface fixes

---

tests/grammar/test_grammar.py
tests/parser/ast_utils/test_ast_dict.py
vyper/ast/annotation.py
vyper/ast/nodes.py
vyper/ast/pre_parser.py
vyper/ast/utils.py
vyper/functions/utils.py

1. Refactor logic when generating AST nodes.
2. Add / expand docstrings using [NumPy style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy).
This is another step toward #1806.
1. `ast/utils.py`:
a. Eliminate `parse_python_ast` and `_build_vyper_ast_init_kwargs` methods. Additional fields for the init kwargs is now added to the python nodes during annotation, and the logic around generating the vyper nodes happens within `VyperNode.__init__`.
2. `ast/nodes.py`:
a. Individual nodes are now created using the `get_node` method. They can be generated from a python node, or dict.
b. For compatibility with python3.8's  `Constant` node, I added a `_translated_fields` class attribute that remaps `value` to `n` or `s`.
c. Nodes are converted to dicts using …

Ast refactor step 2

---

tests/parser/parser_utils/test_annotate_and_optimize_ast.py
vyper/ast/annotation.py
vyper/ast/nodes.py
vyper/ast/utils.py
vyper/functions/signatures.py
vyper/parser/constants.py
vyper/parser/expr.py
vyper/parser/parser_utils.py
vyper/signatures/function_signature.py
vyper/signatures/interface.py
vyper/types/types.py

Step three and (hopefully) my last major PR related to ASTs prior to starting on #1806 properly.
1. Link vyper nodes to one another via `_parent` and `_children` members.  This is a first step toward methods for traversing the node which should be in my next PR.
2. Add `node_source_code` member to nodes, and move `source_code` to `full_source_code`.
3. Split vyper `Num` node class into `Int`, `Decimal`, `Binary`, `Hex` and `Octal`, refactor accordingly.
1. When generating nodes, the parent node includes itself during as an arg the call to `get_node`. The child node then adds itself to the parent's `_children` set at the end of it's `__init__` method.
2. `node_source_code` is generated using the end offsets that are made available by `asttokens`. This is useful in a few places, notably …

Ast refactor part 3

---

vyper/exceptions.py

Fixed a bug I introduced :astonished: that was preventing proper source annotations during exceptions.
change `source_code` reference in exception to `full_source_code`
Write some bad code and check out the traceback.  ...we should probably have test cases for this at some point.

bugfix: source annotations on exceptions

---

docs/compiler-exceptions.rst
tests/cli/vyper_json/test_compile_from_input_dict.py
tests/parser/exceptions/test_vyper_exception_pos.py
tests/parser/features/test_assignment.py
tests/parser/functions/test_default_parameters.py
tests/parser/syntax/test_bool.py
tests/parser/syntax/test_create_with_code_of.py
tests/parser/syntax/test_functions_call.py
tests/parser/syntax/test_raw_call.py
tests/parser/types/test_identifier_naming.py
vyper/ast/annotation.py
vyper/ast/nodes.py
vyper/ast/utils.py
vyper/cli/vyper_serve.py
vyper/exceptions.py
vyper/functions/functions.py
vyper/parser/expr.py
vyper/parser/global_context.py
vyper/signatures/interface.py
vyper/types/convert.py

1. Add docstrings for all custom exceptions.
2. Expand some of the more commonly used exceptions into different types that are more specific to what is happening.
3. Rename `ParserException` to `VyperException` and explicitly declare it to be an inherited base exception.
4. Update documentation and tests.
Related to #1869 - I think it's good to have all custom exception types very clear prior to major refactoring. I also think we should have a policy that the compiler never intentionally raises a builtin exception. An end-user receiving a builtin exception should be a clear sign of a bug within the compiler.
I don't intend to change any raise statements throughout the existing code. But I __do__ want to enforce their use in any code we add going forward, specifically in the refactors on …

Expand and document custom exceptions

---

tests/parser/syntax/test_invalids.py
vyper/ast/nodes.py
vyper/parser/stmt.py

Store function docstrings in the `doc_string` field of the related AST node.
1. `vyper/ast/nodes.py` - When `FunctionDef.body[0]` is an `Expr` containing a `Str`, remove the `Expr` from `body` and add `Str.s` to `FunctionDef.doc_string`.
2. `vyper/parser/expr.py` - remove logic for `Str` - the only use it had was to raise if a value _wasn't_ a docstring.
Run the tests. I updated a test case that was failing.

Move docstring out of body in FunctionDef AST

---

docs/types.rst

Fix a typo in the documentation. `bitwise_not` expects one argument, not two.

Fix typo in docs

---

tests/parser/exceptions/test_structure_exception.py
vyper/ast/annotation.py
vyper/ast/nodes.py
vyper/parser/stmt.py
vyper/types/types.py
vyper/utils.py

This PR includes a mix of new features and bugfixes related to #1869. I've separated them out to reduce the size of the diff once the main PR is ready for review.
1. Add `UNSUPPORTED_NODE_REASONS` var and remove node types which are disallowed later in compilation.
2. Add `get_children`, `get_all_children`, and `get` methods to `NodeBase`. These are useful for targeted traversal of the AST, see the docstrings for implementation details.
3. Add `value` property to `Num` nodes as a standard way to access the actual value of the node. Eventually I would like to remove `n` and `s` altogether, this is a first step towards that.
4. Add `description` property to nodes. Useful for giving more descriptive error messages.
5. Disallow use of `from ...` syntax in `raise` statements.
6. Fix a bug when …

AST Round 4

---

vyper/ast/nodes.py

1. Change sequencing of node classes to follow that of [Green Tree Snakes](https://greentreesnakes.readthedocs.io/en/latest/nodes.html#) docs. The only difference is that I put the top-level nodes at the start instead of the end.
2. Remove unused `Op` and `stmt` classes.
Run tests. Shouldn't affect much.

Reorder AST node classes

---

docs/compiling-a-contract.rst
docs/installing-vyper.rst

Remove https://vyper.online/ from the docs.
With the delete key.
Read the docs.  More importantly, see that the docs CI build passes.

remove vyper.online references in docs

---

tests/parser/exceptions/test_structure_exception.py
tests/parser/exceptions/test_syntax_exception.py
vyper/ast/nodes.py
vyper/parser/expr.py
vyper/parser/stmt.py

Simplify the structure of `Compare` and `Assign` nodes.
1. Python comparisons allow more than 2 comparators:  `x < y < z`. Because of this, `Compare` has a rather complex structure. Since Vyper only allows `x < y`, I've changed the `Compare` structure to be identical to `BinOp`.  Members are now `left`, `op`, `right`.
2. Python allows multiple targets for assignment: `a = b = 42`. Vyper does not.  To standardize `AnnAssign` with `Assign`/`AugAssign`, I've converted the `AnnAssign.targets` list member into a single `AnnAssign.target`.
Both of these changes occur in the respective `__init__` methods for the nodes and raise `SyntaxException` if syntax is valid python but not valid vyper.  This is the only user-facing change - prior to this PR these situations would raise …

Ast modifications

---

docs/built-in-functions.rst
tests/parser/exceptions/test_structure_exception.py
tests/parser/functions/test_raw_call.py
tests/parser/syntax/test_raw_call.py
vyper/functions/functions.py

1. Make `gas` and `outsize` into optional kwargs in `raw_call`.
2. When `outsize` is `0`, do not return a value.
3. When `gas` is not given, forward all available gas.
Closes #1890 
Modifications to `vyper/functions/functions.py` - I refactored / optimized the LLL a bit, if `outsize` is 0, the return value isn't copied to memory. I added comments, hopefully it's clear enough.
Run tests. I added a few new cases, mostly around `gas`.

Modifications to raw_call arguments

---

tests/parser/features/test_internal_call.py
tests/parser/features/test_logging_from_call.py
tests/parser/functions/test_length.py
tests/parser/functions/test_slice.py
tests/parser/syntax/test_block.py
tests/parser/syntax/test_chainid.py
tests/parser/syntax/test_slice.py
tests/parser/types/test_bytes.py
tests/parser/types/test_bytes_literal.py
tests/parser/types/test_bytes_zero_padding.py
tests/parser/types/test_string.py
vyper/functions/functions.py

Change `start` and `length` to be positional args in the builtin `slice` function. Closes #1879 
Modify the signature, update failing tests.
Run tests.

Make slice args positional only

---

setup.cfg
tox.ini

1. Move the `--showlocals` flag to `tox.ini` - it's useful information in the CI, but locally it can be overwhelming and there's no flag that can be used to disable it.
2. Remove the external links check in the `docs` build.
Let the CI do it's thing.

CI updates

---

vyper/ast/annotation.py
vyper/ast/nodes.py
vyper/functions/functions.py
vyper/parser/expr.py
vyper/parser/parser_utils.py
vyper/signatures/interface.py
vyper/types/convert.py

Modified the members of `Constant` ast nodes.
1. Values are now always stored at `value`, instead of `n`/`s`. This is a change that Python introduced in version 3.8.
2. `ast.Decimal.value` is set as a `decimal.Decimal` immediately when the node is created.
3. Values for `ast.Hex`, `ast.Binary`, and `ast.Octal` are represented as strings instead of their `int` equivalent.
Mostly it involved modifying `ast/annotation.py` and deleting some now redundant code.
I've also added `n` and `s` `@property` members as `value` aliases, so these attributes are still available. It is the path of less resistance as opposed to changing every reference within the remaining existing code base.  As we refactor many of those references will be removed anyway.
Run the tests.

Adjust constant AST fields

---

tests/compiler/test_pre_parser.py
tests/parser/syntax/test_rlplist.py
vyper/ast/pre_parser.py
vyper/exceptions.py

1. Add `VyperException.with_annotation` method, for raising exception from a specific ast node. My envisioned use:
```python
try:
do_thing_with_a_node(node)
except VyperException as exc:
raise exc.with_annotation(node)
```
2. In `vyper/ast/pre_parser.py`, raise `SyntaxException` rather than `StructureException`.
3. Add docstrings to `VyperException`.
See above, see diff.
Run the tests.

Exception modifications

---

vyper/ast/annotation.py
vyper/ast/nodes.py

Add a new node type, `DocStr`, to differentiate between regular strings and docstrings.
Closes #1908 
1. Apply changes during `nodes/annotation.py` so that the new node class is properly created.
2. Remove docstring logic from `TopLevel.__init__`
Run the tests

add DocStr node class

---

docs/style-guide.rst

Fix the broken link to `black` in the style guide.
`_`
Read the docs.

docs: fix broken link in style guide

---

examples/auctions/blind_auction.vy
examples/tokens/ERC721.vy
examples/wallet/wallet.vy

Update example contracts to use `_value` instead of `_value` per #1877 
Run tests.

refactor: change value to _value in example contracts

---

tests/parser/functions/test_raw_call.py
vyper/functions/functions.py

In `raw_call`, change the `delegate_call` kwarg to `is_delegate_call`. It was already listed this way in the documentation.
Run tests.

Change raw_call kwarg

---

docs/built-in-functions.rst
docs/types.rst
examples/crowdfund.vy
tests/parser/functions/test_clear.py
tests/parser/functions/test_empty.py
tests/parser/globals/test_setters.py
tests/parser/integration/test_crowdfund.py
tests/parser/syntax/test_list.py
tests/parser/syntax/test_structs.py
tests/parser/types/test_node_types.py
vyper/ast/nodes.py
vyper/functions/functions.py
vyper/parser/expr.py
vyper/parser/lll_node.py
vyper/parser/parser_utils.py
vyper/parser/stmt.py
vyper/types/types.py
vyper/utils.py

- Fix #1675 by introducing syntax for initializing new arrays with zero
- Get rid of NullType from codebase. Zeroing operations are now from the None sentinel value alone.
- Factor mzero into a function
See tests
- Introduce syntax for initializing new arrays with zero
- Check array assignment is always between arrays of same length

Add zeroing function for arrays

---

docs/_static/css/dark.css
docs/_static/css/toggle.css
docs/_static/js/toggle.js
docs/_templates/versions.html
docs/conf.py

Add a toggle button to switch between day and night mode in the docs.  It replaces the "edit on Github" button in the header of each page.
You can see the effect in action by checking out the latest [Brownie docs](https://eth-brownie.readthedocs.io/en/latest/).
Hacky copy-pasta and a lot of trial and error.
Build and read the docs.

Toggle button for day/night mode in docs

---

docs/compiler-exceptions.rst
docs/compiling-a-contract.rst

Updated the names of exceptions in the docs
Resolves #1924  
EMVVersionException changed to EvmVersionException
InvalidTypeException changed to InvalidType
TypeMismatchException changed to TypeMismatch
KeyError was removed since it was replaced by JSONError
Read the docs

Docs: Updated exception names

---

vyper/functions/functions.py

fixes: #1929
Our precompiled calls were using `CALL` instead of `STATICCALL`, overpaying by 660 gas per call. This change switches out how the call is made to cost less gas. No changes required for testing.
Optimize precompiles to use `STATICCALL`

Optimize precompiles to use STATICCALL

---

.github/workflows/test.yml

Allow Github Actions to run on every branch and pull request.
This is useful because it also means actions will run on branches of forked repos.  Less time waiting for the CI to finish on pull requests, more information for contributors as they work.
Modify the actions yaml.
Watch actions in..  action?

chore: allow actions to run on every branch and PR

---

tox.ini

Remove references to circle CI and coveralls environment variables in `tox.ini`
Check that CI isn't broken.

remove old environment vars in tox

---

vyper/utils.py

fixes: #1938
There's no reason for certain LLL keywords to be reserved for use with Vyper syntax
I removed:
`push`, `dup`, `swap`, `call`, `stop`

Remove some reserved keywords

---

docs/style-guide.rst
tests/ast/test_folding.py
vyper/ast/folding.py

Add folding logic for builtin and user-defined constants.
The core functionality was added in #1912 as `ast.folding.replace_constant`. This PR adds two methods, `replace_builtin_constants` and `replace_user_defined_constants` that make use of this functionality.
Run the tests.  I expanded on the test cases in `tests/ast/test_folding.py`.

Folding for builtin and user-defined constants

---

Makefile

Added the removal of `.hypothesis/` in `make` target `clean-test`.
To quickly check, you can run this command:
```shell
$ mkdir -p .hypothesis && ls -al .hypothesis && make clean-test && ls -al .hypothesis
```
the output should be similar to:
```shell
drwxr-xr-x  2 orange orange 4096 May  1 06:45 .
drwxr-xr-x 14 orange orange 4096 May  1 06:45 ..
Cleaning test files...
ls: cannot access '.hypothesis': No such file or directory
```
where `orange` is your user id and group id (`id -un` and `id -gn`).
Alternatively, instead of running the above command:  
* Check that the `.hypothesis` directory is there. If not create it or run a test, which will create the directory.
* Run `make clean` or `make clean-test` to be more precise.
* Check that the `.hypothesis` directory is no longer there. …

Remove .hypothesis/ via make target clean-test

---

tests/parser/features/test_assignment.py
vyper/parser/stmt.py

Checked that during assignment the value being assigned is not None
In Vyper, there is no null option like most programming languages have so I assumed that any valid assignment should not be assigning a None value.
Added a test for the same where the returned NoneType value is being assigned to a variable
Resolves #1862 
Resolves #1821 
Raised a `TypeMismatch` Exception when a NoneType is being assigned.
Run the test
Check for `NoneType` assignment is added to `vyper/parser/stmt.py`
`test_invalid_nonetype_assignment` added in `tests/parser/features/test_assignment.py`

Valid Assignment: Check that value being assigned in not None

---

tests/ast/nodes/test_evaluate_compare.py
vyper/ast/folding.py
vyper/ast/nodes.py
vyper/exceptions.py

1. Introduce `VyperInternalException` and subclasses.
2. Use internal exceptions to make failed calls to `evaluate` stronger.
Run the tests.

Feat internal exception

---

tests/ast/test_folding.py
tests/functions/folding/test_addmod_mulmod.py
tests/functions/folding/test_bitwise.py
tests/functions/folding/test_floor_ceil.py
tests/functions/folding/test_fold_as_wei_value.py
tests/functions/folding/test_keccak_sha.py
tests/functions/folding/test_len.py
tests/functions/folding/test_min_max.py
vyper/ast/__init__.py
vyper/ast/folding.py
vyper/ast/validation.py
vyper/exceptions.py
vyper/functions/functions.py

Add constant folding logic for builtin functions.
* folding logic is found in the `evaluate` method of each class in `vyper/functions/functions.py`
* the high level execution is handled via `replace_builtin_functions` in `vyper/ast/folding.py`
* test cases are in `tests/functions/folding/`
The only folding implementation I'm not testing is `method_id`. This function should _always_ fold, so verifying the result of folding vs not-folding seems redundant. Once we add folding into the compiler process we can update the existing test cases around this function.
Things to do next that are outside the scope of this PR.
* add documentation
* updates to "Types" and "Builtin functions" within RTD
* add docstrings to classes in `vyper/functions/functions.py`
* add `README.md` to `vyper/functions`
* …

Folding builtins

---

tests/ast/test_natspec.py
vyper/ast/natspec.py
vyper/compiler.py
vyper/parser/parser.py
vyper/signatures/interface.py
vyper/signatures/sig_utils.py

_(This PR requires and is built on top of #1960)_
Refactor methods for LLL, natspec and interface generation.
Each of these functions requires either the source code or AST as an input, in order to generate a `GlobalContext` object. I've modified them so that they now receive `GlobalContext` as an input.  This way we can make the core logic in `vyper/compiler.py` more linear.
* In several methods, modified the input arguments from `code` or `ast` to `global_ctx`.
* Adjusted `vyper/compiler.py` to generate `global_ctx` prior to calling each of these methods.
The only place that a `GlobalContext` is generated now, outside of `compiler.py`, is when handling interfaces.  I think it will be possible to refactor this out as well, but I didn't want to do too much in a single PR.
Run the tests.

Refactor generation of GlobalContext

---

tests/parser/features/decorators/test_private.py
vyper/parser/self_call.py

Fix a memory offset issue when returning tuple types from a private function.
Fixes #1847 
In `parser/self_call.py`:
* update the offset by the actual size of the value rather than 32
* ensure there is a new `mstore` for each value of an array inside a tuple.
Run tests. I added some new cases.

Bugfix: returning tuples from private functions

---

docs/built-in-functions.rst
tests/parser/functions/test_raw_call.py
vyper/functions/functions.py

Add `is_static_call` kwarg to `raw_call` as a way to perform a `STATICCALL`.
Closes #1971
Minor tweaks to the `RawCall.build_LLL` logic in `vyper/functions/functions.py`:
* use of `is_static_call` and `is_delegate_call` together raises
* `raw_call` may now be used in `@constant` functions, ONLY when `is_static_call=True`. If the kwarg is omitted, the exception message suggests it's use to the user.
Run the tests. I added a few cases to verify that it works.

Allow STATICCALL using raw_call

---

tests/ast/nodes/test_evaluate_binop_decimal.py

Fix a hypothesis test issue where the expected value could be out of bounds for `decimal`.

fix: adjust test to consider bounds

---

docs/built-in-functions.rst
examples/wallet/wallet.vy
tests/examples/wallet/test_wallet.py
tests/parser/exceptions/test_constancy_exception.py
tests/parser/exceptions/test_structure_exception.py
tests/parser/exceptions/test_syntax_exception.py
tests/parser/features/test_assert.py
tests/parser/features/test_conditionals.py
tests/parser/functions/test_method_id.py
tests/parser/functions/test_raw_call.py
tests/parser/functions/test_send.py
tests/parser/syntax/test_constants.py
tests/parser/syntax/test_raw_call.py
vyper/functions/functions.py

Do not return empty calldata in `raw_call`. Fixes #1976 
Compare `RETURNDATASIZE` to `outsize` and copy the smaller number of bytes to memory.
Run tests. I added / updated some cases.  I also had to adjust some failing ones in `test_wallet` where the spirit of the test was that the call should succeed, but there was a check that it returned a non-empty value. Because of this change the value is now empty.

Fix raw call outsize

---

tests/parser/features/test_assert.py
vyper/parser/stmt.py

Fixes #1981
Code generation for `assert_reason` generates incorrect length for revert string which leads to [issues with revert reason decoding](https://etherscan.io/tx/0xa0f0aa5fc4f56771a0b49ff66c752bcad2a32844ec4b173337086d6610571d65).
Fixed length of memory passed to revert opcode generated by assert_reason.
Check that [assert tests](https://github.com/vyperlang/vyper/blob/master/tests/parser/features/test_assert.py) are still passing.
Removed 32 bytes of junk at the end of revert reasons.

Fix memory length generated by assert_reason

---

tests/parser/exceptions/test_invalid_literal_exception.py
tests/parser/exceptions/test_overflow_exception.py
tests/parser/exceptions/test_structure_exception.py
tests/parser/exceptions/test_syntax_exception.py
tests/parser/functions/test_convert_to_int128.py
vyper/ast/nodes.py
vyper/ast/validation.py
vyper/compiler/phases.py
vyper/utils.py

Validate constant values prior to folding.
Add a `validate` method to some AST nodes that raises if the node's value cannot be typed. This is useful for ensuring descriptive exceptions for e.g. numeric bounds issues, without having to duplicate code.
The `validate` methods are called from `ast.validate.validate_literal_nodes`, which runs after AST generation and prior to constant folding.
This PR results in the some dead code in `functions/functions.py` and `parser/**.py`.  I intend to handle that as part of the larger coming soon:tm: type-checker PR.
Run the tests.

Validate constants

---

vyper/parser/arg_clamps.py

Remove misleading comments, as they were added during #1488, and do not reflect the code's operation.
Hit delete.
Remove misleading comments.

Remove misleading comments

---

examples/tokens/ERC20.vy

Remove inaccurate information from the `transferFrom` docstring in the ERC20 example.
Compare new docstring against the ERC20 spec.

fix: remove incorrect natspec comment in transferFrom

---

tox.ini

Add `semantic_version` as a known 3rd party library in `isort` config. This was causing me issues locally.

add semantic_version to isort known_third_party

---

docs/structure-of-a-contract.rst
tests/ast/test_natspec.py
vyper/ast/natspec.py

Add license tag to NatSpec.
Add the "license" tag in the permitted fields.
There is a test case.
Add license tag to NatSpec.

Add license to NatSpec

---

.github/workflows/publish.yml

Added an action that triggers whenever a new tag is created (via new release)
How this should work is that when a tag is pushed (or created through "Releases"), this should get triggered and make a release to PyPI with the latest tag

Add Publishing Action

---

vyper/cli/vyper_serve.py

Fix 'TypeError: can only concatenate str (not "bytes") to str'  in do_GET. Encoding should be after concatenation.

Fix TypeError in do_GET

---

vyper/context/validation/utils.py
vyper/exceptions.py
vyper/functions/signatures.py
vyper/parser/constants.py
vyper/parser/context.py
vyper/parser/expr.py
vyper/parser/external_call.py
vyper/parser/global_context.py
vyper/parser/parser_utils.py
vyper/parser/stmt.py
vyper/types/types.py

Remove dead code and replace `VyperException` subclasses with `VyperInternalException` subclasses in `vyper/parser/*.py`
Type-check related logic in `parser` has been removed, or replaced with internal exceptions that indicate an unexpected compiler error:
* when the check involves structure validation of a node, such that a later attempt to access the incorrect structure will result in an attribute or key error, I've removed the check altogether
* when I'm not certain the mistake would get caught in the above manner, I've instead replaced it with an internal error or be returning `None`
In the major functions, I'm using a pattern where a check is made on the return value, and if `None`, an internal error is raised.  This reduces the number of unreachable lines of code while still …

Remove dead code, round 1

---

tests/parser/exceptions/test_call_violation.py
tests/parser/exceptions/test_constancy_exception.py
tests/parser/features/iteration/test_for_in_list.py
tests/parser/syntax/test_constants.py
vyper/context/validation/local.py
vyper/parser/stmt.py

Add misc checks that were missing from the type check logic:
* `assert` with an empty reason string
* calls to builtin functions where the output is not assignment
* constancy checks for contract functions
* for loop correctness
Run tests.

Missing type checks

---

docs/built-in-functions.rst
tests/functions/folding/test_len.py
tests/parser/features/test_constructor.py
tests/parser/features/test_internal_call.py
tests/parser/functions/test_length.py
tests/parser/integration/test_basics.py
tests/parser/syntax/test_len.py
vyper/functions/functions.py
vyper/parser/parser_utils.py

Modify builtin `len` to return `uint256` instead of `int128`
Closes #1979 
* Adjust the return value in `vyper/functions/functions.py`
* Update test cases
* Update documentation
In the documentation, the example format I used is one I'd like to apply to all the builtins before the next release ships.
Run the tests, read the docs.

Adjust return type of len

---

docs/built-in-functions.rst
tests/parser/features/test_internal_call.py
tests/parser/functions/test_slice.py
tests/parser/syntax/test_block.py
tests/parser/syntax/test_chainid.py
tests/parser/types/test_bytes_literal.py
tests/parser/types/test_string.py
vyper/functions/functions.py

Adjust input arguments for builtin function `slice` to use `uint256` instead of `int128`.
Closes #1986 
* Adjust the return value in `vyper/functions/functions.py`
* Update test cases
* Update documentation
Run tests, read docs.

Use uint256 in slice

---

tests/functional/context/test_namespace.py
tests/functional/context/types/test_type_from_abi.py
tests/functional/context/types/test_type_from_annotation.py
tests/functional/context/validation/test_cyclic_function_calls.py
tests/functional/context/validation/test_potential_types.py
vyper/context/README.md
vyper/context/namespace.py
vyper/context/validation/__init__.py

Simplify the `Namespace` object.
Remove `Namespace.enter_builtin_scope`, and instead add the builtins when initializing `Namespace`.  This makes for simpler code and solves an issue I'm having when implementing #1980.  I'm not sure why I didn't do it this way to begin with :grimacing: 
Run tests.

Refactor Namespace object

---

docs/built-in-functions.rst
examples/tokens/ERC721.vy
tests/examples/tokens/test_erc721.py
tests/parser/functions/test_method_id.py
tests/parser/functions/test_raw_call.py
vyper/functions/functions.py

Make the `type` argument in `method_id` optional.
Closes #1980
* the keyword is set as `output_type`
* if not given, the default is `bytes[4]`
Run tests.

default type arg in `method_id`

---

docs/built-in-functions.rst
tests/parser/functions/test_extract32.py
tests/parser/functions/test_raw_call.py
tests/parser/syntax/test_extract32.py
vyper/functions/functions.py

Change keyword in `extract32` from `type` to `output_type` to be consistent with #2035
Run tests.

Extract32 kwarg

---

vyper/parser/global_context.py

When generating an array getter, use `uint256` as the input argument.  Closes #1983 
Modification to `parser/global_context.py` - in the future we should refactor this logic to use the new AST mutation ability.
Run tests.

use uint256 for input in array getter methods

---

tests/ast/nodes/test_evaluate_binop_decimal.py
tests/ast/test_folding.py
tests/parser/functions/test_convert_to_decimal.py
tests/parser/functions/test_convert_to_int128.py
tests/parser/types/numbers/test_uint256.py
vyper/ast/nodes.py

Fix a constant folding issue where nested math operations were able to overflow as long as the final result was in bounds.
For example, prior to this PR the following statement was valid because the binary operation was completely folded prior to the overflow check:
```
a: uint256 = 2 ** 256 - 1
```
However, the following would revert during runtime because `2 ** 256` overflows:
```
a: uint256 = 256
b: uint256 = 2 ** a - 1
```
Although writing `2 ** 256 - 1` may be convenient, I feel strongly that folding should always have a consistent behavior with the outcome at runtime.
Closes #2046 
In `vyper/ast/nodes.py`, immediately check the bounds on results after folding all `BinOp` and `UnaryOp` nodes.
Run the tests.  I added some new cases to test the behavior.
Note that I also encountered …

Overflow checks during constant folding

---

tests/parser/exceptions/test_structure_exception.py
vyper/parser/global_context.py

Remove restrictions on ordering of elements within the module-level namespace of a contract.
The only restriction this _does not_ remove is that functions may only call upward - that logic is fairly intertwined with `global_context` and will take some work to eliminate.
* Removed some checks in `global_context`
* Removed failing tests
* Checked the documentation - this behavior was never documented so nothing needs to be changed there
Run tests.

Remove module-level order restrictions

---

docs/structure-of-a-contract.rst
tests/parser/features/external_contracts/test_external_contract_calls.py
tests/parser/functions/test_interfaces.py
vyper/parser/external_call.py

Ease restrictions on a contract calling into itself:
* remove the runtime assertion
* remove the compile-time check on an interface cast to `self`
Closes #1696
* Deleted a couple of checks in `vyper/parser/external_call.py`
* Minor documentation update - we never really explicitly said this _didn't_ work, so there wasn't much to modify here.  I could write more, but..  I'll do a proper documentation update soon:tm:, promise
Run the tests. I flipped a few tests around that were verifying this behavior wasn't working, now they check that it works.

Ease restrictions on self-call

---

vyper/parser/external_call.py
vyper/parser/parser_utils.py
vyper/parser/self_call.py

Do not write a signature to memory when preparing args for a private function call.  Fixes #1695 
In `vyper/parser/parser_utils.py::pack_arguments`, replaced the `return_placeholder`  kwarg with `is_external_call`. When `False`, the signature is stored in memory.
I had to adjust some memory offsets to make this work, but I think the resulting code is a bit cleaner.
Run the tests.  I didn't add any cases, but I did confirm that we have sufficient coverage around this functionality.

Do not add signature to memory for private function calls

---

tests/parser/features/test_logging.py
vyper/parser/events.py
vyper/signatures/event_signature.py
vyper/types/types.py

Hash non-value types when they are used as indexed topics.  Closes #1699 
This introduces a significant change in that we no longer convert e.g.` bytes[1]` to `bytes1` - bytes and string arrays are always represented as `bytes` and `string` in the event ABI, regardless of length.
We can now also support use of bytes or string arrays >32 bytes, and array types.
In `vyper/parser/events.py`, expanded the logic of `pack_event_topics`.
Run the tests. I had to modify quite a few based on this change, and I added some new cases to ensure that indexed topics are correct when reading variables from memory, storage, and calldata.

Indexed array types

---

tests/examples/voting/test_ballot.py
tests/parser/features/external_contracts/test_external_contract_calls.py
tests/parser/globals/test_getters.py
vyper/parser/global_context.py

Closes: #1702
We had some funky handling prior for struct members because of a bug in web3py. This PR makes the correct change to support returning structs from public getters directly, making it compatible with how Solidity handles it.
Just returning the struct name as a type directly instead of iterating over it's members
I updated the tests to use the tuple sequence returned from the public getter. Also note the xfail on the one test case that couldn't be handled by web3py's current configuration. We can remove this once web3py releases a fix, or we change to using Brownie
Public getters for structs now return the whole struct

Update Struct public getter to return whole Struct

---

tests/parser/features/iteration/test_for_in_list.py

The test case described in #1712 did not exist, so I added it. The condition is appropiately caught in #2029, so this just updates the test cases.

Add test for loop var exceeding type bounds

---

vyper/context/README.md
vyper/context/types/function.py
vyper/context/types/indexable/sequence.py
vyper/context/types/meta/interface.py
vyper/context/validation/local.py
vyper/context/validation/module.py

rename `ContractFunctionType` to `ContractFunction`

rename ContractFunctionType to ContractFunction

---

tests/parser/features/iteration/test_range_in.py
vyper/parser/expr.py

Support calldata arrays with the `in` comparator - fixes #1904 
Expand logic in `parser/expr.py` to also handle calldata.
Run tests. I added a test case.

Fix: use of calldata array with `in` comparator

---

docs/types.rst
tests/parser/features/test_short_circuiting.py
vyper/parser/expr.py

Implement short circuiting for boolean operations.  Closes #1817 
Modifications to `parser/expr.py`:
1. Place a label at the end of the `BoolOp` LLL
2. then evaluate each set of values one at time and jump to the end if the conditions are correct
Run the tests. I added quite a few cases, thanks to parametrization.
Added short circuit logic for boolean operations.

Add short circuiting for boolean operations

---

tests/parser/features/test_clampers.py
vyper/parser/arg_clamps.py

Adjust logic for args clamper when dealing with arrays.
Fixes #2003 
* Instead of recursively looping through each array within a multidimensional array, we immediately determine the base type and then check each item within the array.
* If the base type does not require clamping, don't loop
Run tests.  I wasn't able to find many tests around arg clamping so I wrote some to test the entire behavior.

array arg clamps fix

---

tests/parser/functions/test_default_parameters.py
vyper/parser/function_definitions/parse_external_function.py

Properly handle default arguments with a size > 1 word.  Fixes #1987
In `vyper/parser/function_definitions/parse_external_function.py::parse_external_function`, use `get_size_of_type` to determine the size in memory for each default argument.
Run the tests. I added some cases based on the example in the issue.  I also verified the behavior for internal functions.

Fix default params

---

vyper/context/types/bases.py
vyper/context/types/function.py
vyper/context/types/meta/interface.py
vyper/context/validation/module.py

* Add checks for duplicates names when declaring interfaces - fixes #1959 
* Improve the error message for namespace collisions when assigning storage variables. Currently it is "`Member [x] already exists in address`" - not sure how i missed this!
Minor edits.
Run tests.

Namespace collisions

---

setup.py

https://www.python.org/dev/peps/pep-0566/
https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi/
Remove `setuptools-markdown` because it was deprecated, and via PEP-566 there is a standard way to do this
Made a few modifications to `setup.py`
I did:
- `pip install .`
- `python setup.py sdist`
- `python setup.py bdist_wheel`
- `twine check`
None of them had any issues.
But we won't really know until we go to release it :grimacing:

Remove setuptools-markdown (deprecated) in favor of PEP-0566

---

tests/parser/features/external_contracts/test_external_contract_calls.py
tests/parser/functions/test_interfaces.py
vyper/parser/external_call.py
vyper/signatures/function_signature.py
vyper/signatures/interface.py

* Check the length of return data when making an external call.  Closes #1978 
* Validate that returned `bytes` and `string` data does now have a length longer than the max allowed for the given type. Closes #1840 
* Add a check that `RETURNDATASIZE` > expected length -1 after making a call.
* In cases where we are expecting return data, do not include the check involving `EXTCODESIZE`.  An address that is not a contract will not return any data, so this check isn't required.
* For dynamic types (bytes and string), assert that the length of the returned data does not exceed the max allowable length for the contract type
It is still possible for a call to return _more_ data than expected by the interface.  This is consistent with how Solidity handles the check.
Run the tests. I added a few …

Check length of return data from external calls

---

vyper/ast/pre_parser.py

There was a bug where if no version string was specified, and it was _not_ a pre-release version, then NpmSpec would match it as being valid. See https://github.com/vyperlang/vyper/runs/835228433
Added an additional check
Tests pass with this, and with  #2082

Added check that version string is non-zero, as NpmSpec passes it

---

docs/release-notes.rst
setup.cfg
setup.py

0.2.0 had a conflict on PyPI, so releasing 0.2.1 instead

0.2.1 Release Notes

---

vyper/context/types/indexable/mapping.py

Add a `__repr__` method to `MappingDefinition`.  Without this, the error messages related to mappings are weird.

add repr for Mapping

---

vyper/ast/nodes.py

Don't fold literal exponentiation when the power is negative.
Fixes #1926 - which was mostly already fixed by type checking, but it alerted me to this issue.
Run tests.

don't fold exponentiation when power < 0

---

vyper/functions/convert.py

Remove a `print` statement that shouldn't be.
Shamefully.
Grep for other print statements.

fix: remove print statement (oops)

---

vyper/compiler/output.py

Use folded AST when generating Natspec.
This fixes a bug when a function input uses a constant, e.g:
```python
FOO: constant(2)
@external
def foo(a: uint256[FOO]): pass
```
Parsing the natspec fails because the function signature cannot be determined from the unfolded AST.
Run tests.

use folded ast for natspec generation

---

vyper/compiler/phases.py

Adjust the compilation logic so that literals are only validated once per job.
Run tests.

only validate literals once

---

vyper/context/validation/local.py

* Fix a bug in the type checker preventing proper checks during for loops. This wasn't a critical issue, as any failure is still caught in `parser`.
* Improve how exception messages are handled during a failed type check in a for loop
* The main issue was from an improperly indented `return`.  Ooops.
* For the exception message, I'm tracking every exception raised during the iterative check.  At the end, if they're all the same exception, I raise it instead of the more generic "could not determine type for i".
Run tests.

fix: type checking in for loops

---

vyper/context/types/utils.py
vyper/context/validation/module.py

Raise immediately on certain exceptions while type-checking the module scope. This prevents long error messages where other nodes fail the type checking because they rely on a previous node.
Raise immediately on `InvalidLiteral`, `InvalidType`, and `VariableDeclarationException`.  Each of these exceptions will not happen as a result of another node not yet being parsed.
Run tests.

Raise immediately on certain exceptions during module-scope type check

---

vyper/ast/annotation.py
vyper/ast/utils.py
vyper/compiler/phases.py
vyper/context/validation/module.py
vyper/exceptions.py
vyper/parser/global_context.py
vyper/signatures/interface.py

* Display the name of the active contract when raising an exception.  This is useful when an exception occurs while parsing an interface.
* Ensure the correct annotation shows when parsing interfaces.
* Add a `name` field to the `Module` AST node. This gets added via a new kwarg for `parse_to_ast`
* Include the `contract_name` kwarg when generating ASTs in `compiler` and `signatures`
Cause an exception.  It should give output like this:
```python
UnknownType: Not a valid type - value is undeclared
contract "cERC20", function "transfer", line 21:18 
20 @external
---> 21 def transfer(_to: oopsie, _value: uint256) -> bool:
--------------------------^
22     pass
```

Add contract name to exceptions

---

vyper/ast/nodes.py

Adjust `FunctionDef` offset to not include decorators. This ensures a more readable annotation when an exception is raised.
Before:
```python
vyper.exceptions.FunctionDeclarationException: Missing or unmatched return statements in function 'foo'
line 12:0 
11
---> 12 @external
--------^
13 @payable
```
After:
```python
vyper.exceptions.FunctionDeclarationException: Missing or unmatched return statements in function 'foo'
line 14:0 
13 @payable
---> 14 def foo() -> uint256:
--------^
15     pass
```
When converting from Python to Vyper AST, modify `FunctionDef.lineno` to be +1 from the `end_lineno` of the final decorator.
Run tests.

fix: adjust FuncionDef offset to not include decorators

---

vyper/ast/annotation.py
vyper/ast/nodes.py

Adjust the start offset for `FunctionDef` nodes using tokens.  This is a more accurate solution to #2102 
In `ast/annotation.py`, modify `FunctionDef.first_token` by searching for the first `def` token after the final decorator.
Run tests.

adjust FunctionDef offset using tokens

---

SECURITY.md

As Vyper has more disclosures, having to update the Security Policy over and over again will be a bad practice. Instead, we should use GitHub's Security Advisories section and just link to that.

Link to advisories table directly

---

docs/testing-contracts-brownie.rst
tests/functional/context/validation/test_array_index.py
vyper/context/types/abstract.py
vyper/context/types/indexable/sequence.py
vyper/context/validation/utils.py

* Fix a missing type check on array index values.
* Add `__repr__` to abstract types to improve readability of error messages.
When an index value is not a literal integer, call to `validate_expected_type` and expect  `IntegerAbstractType`
Run tests.

Array index typecheck

---

tests/parser/features/iteration/test_repeater.py
vyper/codegen/return_.py
vyper/compile_lll.py

Fix an issue causing a bad jumpdest when returning from inside a for loop.
During a for loop the stack contains the iterator value and a callback pointer to the start of the loop.  When a loop is completed, or exitted via `break`, each of these values is popped off. A `return` statement inside a for loop was missing these pops, leaving unexpected values on the stack after returning.
This is only problematic when the return in a for loop happens at least 2 internal calls deep, because the callback pointer for each internal function is also placed on the stack.  As such, the attempt to return from the next internal function would instead use the for loop iterator value as it's destination - resulting in a bad jumpdest.
To fix this issue, I've added a new LLL macro `exit_repeater` which adds …

Pop for loop values from stack prior to returning

---

vyper/exceptions.py

Fix a bug preventing annotation of end-of-file syntax errors
Append `" "` to source prior to annotation. The EOF error always points to one character beyond the length of the source, as this is the offset the error was encountered at.
Try to compile an incomplete source.

fix: add trailing whitespace for EOF exception

---

tests/parser/syntax/test_interfaces.py
vyper/context/validation/utils.py

When type checking, raise immediately if a non-type value is encountered (e.g. a type primitive or uncalled builtin function)
in `vyper/context/validation/utils.py`, add a kwarg `only_definitions` to `_ExprTypeChecker.get_exact_type_from_node` and `_ExprTypeChecker.get_possible_types_from_node`.  if `True` and any values aren't definitions, raise `InvalidReference`.
Run the tests.

Raise on not-types when type checking

---

vyper/context/validation/local.py
vyper/exceptions.py

Improve exception on a failed for loop type check.
When the target value in a for loop has multiple potential types, and using each type creates a different `TypeMismatch`, display all of the exceptions with an explanation as to what happened.
To do so, I've modified the `nodes` member of `VyperException` to be called `annotations` - it can now also be given as a tuple of `("message", node)`. This lets us attach specific messages to each annotation.  I think there will be other places this is useful in the future.
Run tests.

Improved for loop TypeMismatch exception

---

vyper/ast/annotation.py

When calculating the end offset for AST nodes, ignore trailing newlines.
In some cases the final token given for an AST node is type 4, which is `\n`. This makes for a weird source offset, and under very specific conditions is causing issues in Brownie.
To fix it, I'm checking if the final token is `\n` and if yes: -1 from the given offset.
Run tests.

ignore trailing newline tokens

---

tests/parser/ast_utils/test_ast_dict.py
vyper/ast/nodes.py

Ensure AST nodes as dicts are serializable.  Fixes #2121 
* Add unique `to_dict` and `__init__` logic on the `Decimal` and `Bytes` nodes.
* Expand the test case around this behavior to also include creating and loading a JSON string based on the AST-dict.
Run tests.

Serialize AST

---

vyper/context/types/function.py

Improve the error message when using a `0.1.x` style interface.
* If an interface contains `constant` or `modifying`, inform the user to change it to `view`/`pure` or `payable`/`nonpayable`.
* If an interface is completely wrong, ensure the annotation points at the body
Make sure tests are passing.

Improve exception on incorrect interface

---

Makefile
make.cmd

* directly execute `vyper/cli/vyper_compile.py` so that the version is accurate without having to install vyper
* when freezing, ensure the entire content of `vyper` is included (interfaces are otherwise missed)
* when cleaning, delete spec files
Freeze something.

fix: improve make freeze

---

tests/ast/test_folding.py
vyper/ast/folding.py

Fix a folding issue where constants used in binaries operations inside a subscript were not being correctly folded.
For example, the following currently fails to compile because `FOO+1` is not folded:
```
FOO: constant(int128) = 3
bar: int128[100]
def foo():
self.bar[FOO+1] = 1
```
The existing logic does not fold constants on the left-hand side of an assignment, unless the constant's parent is a `Subscript`. To fix this, I'm now checking that the constant has an _ancestor_ who is a `Subscript`.
Run tests. I expanded the test cases around this functionality to check this specific occurrence.

Fix: constant folding on lhs of assignments

---

tests/functional/codegen/test_tuple_return.py
vyper/codegen/return_.py

Fixed issue: ABI issue with bytes and string arrays inside tuples #1841
I modified below line:
https://github.com/vyperlang/vyper/blob/3eb9e7a9bbb69f578c22db2f8a9c89669b95566c/vyper/codegen/return_.py#L69
In this line, we are checking if the return expression is an external function call, and is it is an external functional we are not encoding the data as the return from the external call is already encoded. Here we forgot to add the condition 
``` sub.args[0].args[0].value == "staticcall"```
Run below test case:
```
def test_bytes_inside_tuple(get_contract):
code = """
@external
def test_return() -> (String[6], uint256):
return "potato", 42
"""
c1 = get_contract(code)
code = """
interface jsonabi:
def test_return() -> (String[6], uint256): view
@external
def test_values(a: address) -> …
```

Fix issue #1841

---

tests/functional/codegen/test_struct_return.py
vyper/parser/external_call.py

Fixed the issue #2142 
https://github.com/vyperlang/vyper/blob/ce88755c57e32fbce39658e28cc9bb31b9e69080/vyper/parser/external_call.py#L92
Changed ```types_list = output_type.members ```  to ``` types_list = output_type.tuple_members()```. In the case of **struct**, ``` output_type.members``` returns a dict object, but types_list should be a list of types
Runt the following test case
```
import pytest
@pytest.mark.parametrize("string", ["a", "abc", "abcde", "potato"])
def test_string_inside_tuple(get_contract, string):
code = f"""
struct Person:
name: String[6]
age: uint256
@external
def test_return() -> Person:
return Person({{ name:"{string}", age:42 }})
"""
c1 = get_contract(code)
code = """
struct Person:
name: String[6]
age: uint256
interface jsonabi:
def test_return() -> Person: view …
```

Fix issue: #2142

---

tests/functional/codegen/test_struct_return.py
tests/functional/codegen/test_tuple_return.py
tests/parser/features/external_contracts/test_external_contract_calls.py
tests/parser/features/test_internal_call.py
vyper/codegen/abi.py
vyper/codegen/return_.py
vyper/parser/external_call.py
vyper/parser/parser_utils.py
vyper/parser/self_call.py

I fixed the issue: #2155 
* Both internal and external function return abi-encoded data. But we were not decoding the return data. So I corrected the abi_decode function and then used it when parsing function calls
https://github.com/vyperlang/vyper/blob/39cbd404f0cfdd7f93ef40738c9a02421fe1f3da/vyper/codegen/abi.py#L408
* abi-decode function was not being used earlier so to pass the test cases of tuple return we were partially decoding tuples in make_setters util function. But now that we are using the abi-decode function properly, so to avoid decoding already decoded data I had to make changes here too.
https://github.com/vyperlang/vyper/blob/39cbd404f0cfdd7f93ef40738c9a02421fe1f3da/vyper/parser/parser_utils.py#L713
* Changed how tuple return statements were being compiled. …

Corrected abi_decode function, used it when compiling function calls and changed how we were handling the tuple/struct return

---

tests/parser/syntax/test_blockscope.py
vyper/context/validation/local.py
vyper/parser/context.py
vyper/parser/global_context.py

fixes: #2127
No longer throws when a local variable has the same name as a global, due to the namespacing by `self.`

Remove Excessive Scoping Rules on Local Variables

---

examples/tokens/ERC721.vy

Fix typo in parameters in natspec.
Just like that.
vyper  -f userdoc examples/tokens/ERC721.vy

Fix NatSpecSyntaxException error when compiling ERC721.vy with userdoc format

---

vyper/parser/expr.py

Remove the safemath check when dividing by a literal value.
If the divisor is a literal, remove the `clamp_nonzero` instruction within the LLL.
Run tests.

Optimization: division safemath when divisor is a literal

---

tests/parser/features/test_clampers.py
tests/parser/syntax/test_self_balance.py
vyper/optimizer.py
vyper/parser/arg_clamps.py

Optimizations around size clamps.
* When compiling for >= constantinople rules, handle sizelimits for `address` and `bool` using `shr` instead of a comparison to the in-memory size limit.
* During LLL optimization, check for unused size limit values. If any are found, remove the initial `mstore` operation to reduce the size of the bytecode.
Run tests.

Size limit optimizations

---

tests/parser/features/decorators/test_payable.py
tests/parser/features/test_gas.py
tests/parser/functions/test_send.py
vyper/parser/function_definitions/parse_external_function.py
vyper/parser/function_definitions/parse_function.py
vyper/parser/parser.py

When a contract contains no payable functions, only perform a single `ASSERT CALLVALUE ISZERO` at the beginning of the bytecode instead of at the start of each function.
Closes https://github.com/vyperlang/vyper/issues/1776
* In `parser.parser::parse_tree_to_lll`, prior to parsing the individual functions, check the signature of every function to see if any are payable.
* Pass the result of this check to `parser.function_definitions.parse_external_function::parse_external_function`, so the per-function check may be omitted.
* If required, insert the check at the start of the LLL once it has been generated.
Run the tests.  I added some new test cases to verify that this behavior works as expected.

Optimize nonpayable checks

---

Makefile
make.cmd
setup.py
vyper/__init__.py

Adjust how the version and commit hash are stored.  This simplifies the process of creating standalone binaries - with the current approach, because the binary is not installed by pip, the version shows as `0.0.0-development`.
* Along with recording the commit hash in `vyper_git_version.txt`, the version is also saved.
* The lookup process for the version is reversed. The first checks is the text file, and if this fails it falls back to `pkg_resources`.
* The version in `setup.py` is recorded as `__version__` at the top, so it's accessible when writing the text file
* `init` is added as a requirement for `freeze` in the makefile, to ensure the version txt exists and is up-to-date prior to building the binary.
Build some binaries.

Changes to how version and commit hash are stored / retrieved

---

vyper/optimizer.py

Add an optimization for zeroing multiple memory slots at once.
Closes https://github.com/vyperlang/vyper/issues/2144
When the LLL contains multiple sequential instructions to `MSTORE n 0` or `CALLDATACOPY m CALLDATALSIZE n`, and the locations being zero'd within memory are sequential, merge these instructions into a single zeroing via calldatacopy.
Run tests.

Optimization for multiple memory-zeroing instructions

---

tests/parser/exceptions/test_variable_declaration_exception.py
vyper/context/validation/local.py

Correctly handle an invalid AnnAssign during function-scoped type checking.
Fixes #2157

Fix: invalid AnnAssign exception

---

tests/parser/types/test_lists.py
vyper/parser/parser_utils.py

Fixed: #2183 
In this line it is assumed that size of each subtype of a array/struct is 32, which is wrong:
https://github.com/vyperlang/vyper/blob/51158673c394f5b3decb4fbd5f88eca98c1b2b33/vyper/parser/parser_utils.py#L505
So I replaced the above line with this.
```
staticarray_offset += 32 * (get_size_of_type(typ) - 1)
```
And since the variable count is not needed anymore we can avoid its calculation here:
https://github.com/vyperlang/vyper/blob/51158673c394f5b3decb4fbd5f88eca98c1b2b33/vyper/parser/parser_utils.py#L501

fix-#2183: Incorrect output while passing multi-dimensional array as argument

---

tests/functional/context/types/test_type_from_annotation.py
vyper/context/validation/utils.py

Improve the exception raised on an invalid subscript.
Prior to the general "Subscript must be a literal integer", first check that the subscript is a valid _something_.  If it isn't, the exception raised can be more useful in determining what went wrong.  For example, a typo in a constant variable name.

Better exception on invalid subscript

---

tests/parser/syntax/test_return_tuple.py
vyper/codegen/return_.py
vyper/parser/expr.py
vyper/parser/self_call.py

Fix a memory corruption issue when performing a function call inside a tuple or as an argument inside another function call.
The issue was happening because each argument/item was parsed without knowledge of the other items. When pushing memory to the stack prior to performing nested call, previous items were not accounted for and so not correctly preserved.
You can see the bug in action by run the test cases I've added against the current master branch.
To fix this, I've expanded the logic for parsing tuples and function call arguments. All nested calls are performed separately, prior to building the tuple/args. This way memory is correctly preserved.
Run the tests.  I've added some new cases to verify that the bug no longer exists.

Fix: function calls within tuples / nested calls

---

tests/parser/features/test_clampers.py
vyper/functions/convert.py
vyper/functions/functions.py
vyper/parser/arg_clamps.py
vyper/parser/expr.py
vyper/parser/parser_utils.py

Refactor the process of clamping `int128` using bitshifting.
The new check can be expressed as:
```python
assert abs(n) >> 127 == 0
```
This check produces smaller bytecode and uses less gas at runtime.
The logic is handled in a new `int128_clamp` function within `vyper.parser.arg_clamps`. All the locations where clamping previously happened are now calling to this function.
Run the tests.
I still need to verify how well tested this behavior is.

Refactor int128 clamps

---

vyper/codegen/return_.py
vyper/parser/context.py
vyper/parser/function_definitions/parse_external_function.py
vyper/parser/function_definitions/parse_internal_function.py
vyper/parser/memory_allocator.py
vyper/parser/stmt.py

Allow for releasing and reuse of memory slots.
* Within the memory allocator, add a method `release_memory` that accepts an offset and length.  Released memory is tracked in a a list using `FreeMemory` objects. These objects are essentially 2 item lists, but I think the special class makes the code more readable.
* Calls to `increase_memory` check for available slots in released memory, and if found they are reused instead of expanding memory.
* Upon exiting the `make_blockscope` context manager, all memory variables that are no longer accessible are released.
* Added a new context manager `internal_memory_scope`. It works identically to `make_blockscope`. I added it to differentiate between an actual user-defined scope (for loop, if branches) and an internal scope (event generation, …

Reuse memory slots

---

vyper/parser/parser_utils.py

When accessing an array in memory, calculate the offset during compile-time instead of runtime.
In `parser_utils`, I added a private method `_make_array_index_setter` that generates different LLL if the target value is in memory and the offset is fixed. I also avoid the use of `with` where possible, so no values are needlessly placed on the stack.
Run the tests.  I didn't add any new cases, but this behavior is well tested within the existing suite.

Calculate array index offsets at compile time

---

tests/parser/exceptions/test_argument_exception.py
vyper/context/types/bases.py
vyper/context/types/function.py
vyper/context/types/indexable/sequence.py
vyper/context/types/meta/struct.py
vyper/context/types/value/array_value.py

Raise `ArgumentException` when using a dynamically-sized struct as a function input.
* Added `is_dynamic_size` attribute to all type objects within `vyper.context`
* When generating the function signature, raise if an input is a struct with dynamic size.
Run the tests. I added some new cases.

Improve exception for invalid use of dynamically sized struct

---

vyper/codegen/return_.py
vyper/functions/functions.py
vyper/parser/context.py
vyper/parser/events.py
vyper/parser/expr.py
vyper/parser/external_call.py
vyper/parser/function_definitions/parse_internal_function.py
vyper/parser/keccak256_helper.py
vyper/parser/parser_utils.py
vyper/parser/self_call.py
vyper/parser/stmt.py

Merge `Context.get_placeholder` and `Context.get_internal_variable`
Both of these methods served an identical purpose and `get_internal_variable` was only used twice in the codebase.  I've merged the logic into a single function and added docstrings to make it more clear what is happening.
Run tests.

Merge `Context.get_placeholder` and `Context.get_internal_variable`

---

setup.py
vyper/codegen/return_.py
vyper/parser/context.py
vyper/parser/function_definitions/parse_external_function.py
vyper/parser/function_definitions/parse_internal_function.py
vyper/parser/memory_allocator.py

Refactor the memory allocator.
* Change increase/release to allocate/deallocate
* Add docstrings
* Update references
Longer term I think the memory allocator should be a private object, only referenced directly by `Context`. The current logic for handling function args is fairly reliant upon direct access, and I think this code deserves a larger-scale refactor using, so for now I've left it how it is.
Run tests.

Refactor the memory allocator

---

vyper/parser/context.py
vyper/parser/events.py
vyper/parser/stmt.py

Ensure that multiple internal variable placeholders are ordered sequentially.  This fixes an error in events and revert strings that was introduced by #2188 
* Add `Context.new_sequential_vars`, which generates multiple sequential memory offsets.
* Use the new method in `parser/stmt` where sequential memory offsets are required (events, revert reasons, returning bytes arrays).
Run tests.

Ensure sequential memory for internal variables

---

.github/workflows/test.yml
tests/conftest.py
tests/examples/conftest.py
tests/fixtures/memorymock.py
tests/parser/features/external_contracts/test_external_contract_calls.py
tests/parser/features/test_assert.py
tests/parser/features/test_internal_call.py
tests/parser/features/test_logging.py
tests/parser/features/test_logging_from_call.py
tests/parser/features/test_packing.py
tests/parser/functions/test_raw_call.py
tests/parser/functions/test_return_struct.py
tests/parser/functions/test_return_tuple.py
tests/parser/functions/test_sha256.py
tests/parser/syntax/test_return_tuple.py
tests/parser/types/test_string.py
tox.ini
vyper/codegen/return_.py
vyper/parser/context.py
vyper/parser/events.py
vyper/parser/function_definitions/parse_external_function.py
vyper/parser/function_definitions/parse_function.py
vyper/parser/function_definitions/parse_internal_function.py
vyper/parser/memory_allocator.py
vyper/parser/self_call.py
vyper/parser/stmt.py
vyper/signatures/function_signature.py

Deallocate internal memory variables between statements.
Upon exiting `internal_memory_scope`, all internal variables declared within the scope are deallocated. The scope is applied prior to parsing each statement node.
Run tests.

Memory scoping

---

vyper/functions/functions.py

Optimize the LLL for `shift` when the distance being shifted is a literal.
Avoid pushing to the stack when not necessary.
Run tests.  I didn't add any - the behaviour is already well tested.

Optimize shift when 2nd arg is a literal

---

tests/parser/syntax/test_constants.py

Add a test for #1538 (bytes constant creation fails when the length of the constant is equal to max length of the type)
I assumes`bytes` has been renamed to `Bytes` since that issue was created
Fixes #1538

add test for bytes constant creation (gh-1538)

---

docs/structure-of-a-contract.rst

I fixed a small typo in the documentation

Fix typo in documentation

---

tests/examples/auctions/test_simple_open_auction.py

EXPIRY variable is 16, implying 16 seconds, however, the comment says 5 days.
In order to avoid comments being missed, removed the hardcoded value
edited comment

Fixed typo in comments

---

tests/examples/auctions/test_simple_open_auction.py

Current highest bid is 1
(I think, assertion still fails because 0 quantity bid is also not allowed)
Adapted a test with correct assertions
-
Assertion result doesn't change, so it boils down to code review
Adapted a test with correct assertions about bids same as current highest bid are not allowed

Adapted Simple auction test assertion

---

docs/structure-of-a-contract.rst

Fix a broken link based on issue: #2213 
add ``:ref:`` syntax behind the link
Click on the link?
Fix the link in structure-of-a-contract.rst that suppose to direct the user to Scoping and Declarations page

Fix broken link

---

docs/types.rst

Negation only needs one var
There were two variables for negation. Only one needed.

It implied you need two vars for negation.

---

tests/parser/exceptions/test_namespace_collision.py
vyper/context/types/function.py
vyper/parser/function_definitions/parse_external_function.py

Lift a restriction preventing calldata variable names from shadowing storage variable names.
Related to #2166 
Fixes #2219 
Remove the checks in `context` and `parser` subpackages.
Run tests.

Lift restriction on calldata variables shadowing storage variables

---

setup.py
tests/parser/syntax/test_create_with_code_of.py
tests/parser/syntax/test_raw_call.py
vyper/ast/annotation.py

Update the `vyper.ast` subpackage to handle changes introduced in the python AST in version 3.9.
Related to #2182 
Closes #2205 
Closes #2206
The only change in 3.9 relevant to Vyper was the deprecation of the [`Index`](https://greentreesnakes.readthedocs.io/en/latest/nodes.html#Index) node class:
> Deprecated since version 3.9: Old classes `ast.Index` and `ast.ExtSlice` are still available, but they will be removed in future Python releases. In the meantime, instantiating them will return an instance of a different class.
This node is exclusively used within `slice` attribute of the `Subscript` node - starting in 3.9, `slice` now contains `Index.value` directly.
I had to get hacky to sidestep the logic that prevents direct instantiation of `Index`. It works, I've explained it in the …

Updates to support python 3.9 AST

---

tests/parser/functions/test_slice.py
vyper/parser/parser_utils.py

Allow slicing `bytes32` calldata variables.
Fixes #2200 
In `vyper/parser/parser_utils.py::make_byte_slice_copier`, added `calldata` as a valid source location.
Run the tests.  I've added some new cases for this functionality.

Fix: allow use of `slice` with `bytes32` in calldata

---

tests/parser/syntax/test_nested_list.py
vyper/context/validation/local.py

Explicitly disallow iteration of a list of structs
Fixes #2223 
Add a check within the type checking pass. This behaviour is disallowed in parser, but without the exception in type checking it raises a `CompilerPanic`
Run the tests. I added a new test to verify this behavior.

Explicitly disallow iteration of list of structs

---

tests/ast/nodes/test_hex.py
vyper/ast/nodes.py
vyper/context/types/value/address.py

Validate address checksums during AST generation.
Closes #2216
Since we only use `Hex` for `address` and `bytes32`, I've moved the checksum validation into `Hex.validate`. This is the earliest point we can catch the issue, and ensures it can't be missed in one of several spots within type checking.
Run the tests.  I've added some cases to verify this.

Address checksum validation

---

vyper/ast/nodes.py

Represent bytes as hex in the AST output. This fixes an issue where some bytestrings produce compilable code, but cannot be serialized as the AST dict.
Closes #2163 
See code, pretty self explanatory.
Run tests.

fix: convert bytes to hex when generating ast dict

---

tests/parser/functions/test_convert_to_address.py
vyper/functions/convert.py
vyper/parser/arg_clamps.py

Allow conversion of `uint256` to `address`.
Closes #2215 
* refactor address clamping logic
* add clamps to `address` conversion
* add `uint256` as a possible input type for address conversion
Run the tests.  I've added new test cases.

Convert uint256 -> address

---

tests/grammar/vyper.lark
tests/parser/features/iteration/test_range_in.py
vyper/ast/nodes.py
vyper/context/validation/utils.py
vyper/parser/expr.py

Add support for the `not in` comparator
Closes #2218 
* Added the `NotIn` ast node
* Expand the list comparator logic in `parser` to support `not in`
Run the tests. I added some new cases to test this behaviour.

Add support for `not in` comparator

---

tests/parser/functions/test_empty.py
vyper/parser/parser_utils.py

Allow use of `empty(Bytes[n])` as an argument within a function call.
Closes #2112
* In `vyper.parser.parser_utils::pack_arguments`, add a branch of logic to handle `empty`.  Because empty implies a length of 0 bytes, the logic here is very simple: add 64 empty bytes from the end of calldata.
* As an optimization, I'm also applying the same logic for literal `b""` and `""`.  The overhead of the bytes copier is unnecessary in these situations.
* I've added an optimization where the dynamic pointer is not updated after storing the final dynamic type.
Run the tests.  I added some cases.

Allow `empty` as an argument in a function call

---

tests/parser/exceptions/test_structure_exception.py
tests/parser/functions/test_empty.py
vyper/parser/events.py

Allow use of `empty` with static-sized arrays, inside an event logging statement.
Closes #2158 
Expanded logic in `parser.events` - this is very similar to logic in #2234 
Run tests.  I added some cases.

Fix: `empty` static-sized arrays within log statement

---

tests/parser/features/test_bytes_map_keys.py
vyper/parser/expr.py
vyper/parser/parser_utils.py

Fix two compile-time issues related to bytearray types as `HashMap` keys:
* bytearrays that are part of a struct
* bytearrays in storage
Closes #2237
1. In `vyper/parser/parser_utils.py`, do not assume that the key is a memory offset. This allows the use of structs.
2. In `vyper/parser/expr.py`, add a special case when the key is a bytearray in storage. Because `sha3` only works on memory, we must first copy the bytearray to memory.
Run the tests.  I've added several new cases to target this (and related) behavior.

Fixes for bytearrays as hashmap key

---

vyper/context/types/bases.py
vyper/context/types/function.py
vyper/context/types/meta/struct.py
vyper/context/types/value/array_value.py
vyper/context/types/value/numeric.py

Add `canonical_type` and `method_id` property methods to type objects within `vyper.context`
This is a small step toward annotating the AST prior to LLL generation.
Fairly self explanatory, see code.

`canonical_type` and `method_id`

---

tests/parser/exceptions/test_function_declaration_exception.py
vyper/context/types/function.py
vyper/parser/function_definitions/parse_external_function.py
vyper/parser/function_definitions/parse_internal_function.py

Move several function-level type checks out of `parser` and into `context`:
* Visibility of `__default__`
* Use of args in `__default__`
* Use of default values in `__init__`
Copy-paste, mostly.  See the diff - it's fairly self explanatory.
Run the test suite.  Two of these behaviors were already well tested, I've added a test case for the 3rd.

Refactor: function-level type checks

---

vyper/compiler/phases.py
vyper/functions/utils.py
vyper/parser/context.py
vyper/parser/function_definitions/parse_function.py
vyper/parser/parser.py

Remove the `origcode` attribute from the `Context` object.
This attribute was not in use anywhere. Removing it helps to reduce the size of the input arguments in several `parser` functions - a small step toward refactoring,
See diff.
Confirm that the existing test suite still passes.

refactor: remove origcode member from Context

---

setup.cfg
setup.py

Add the license file to the wheels, this will make working on https://github.com/vyperlang/vyper/issues/2214 easier.
Also saw that `MIT` was still mentioned in setup.py instead of Apache, fixed that

fix: add license to wheel

---

tests/parser/types/test_node_types.py

There is a small typo in tests/parser/types/test_node_types.py.
Should read `unknown` rather than `unknow`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, unknow -> unknown

---

tests/functional/context/types/test_size_in_bytes.py
vyper/context/types/bases.py
vyper/context/types/indexable/sequence.py
vyper/context/types/meta/struct.py
vyper/context/types/value/array_value.py

Add a `size_in_bytes` attribute to each of the new type objects within `vyper.context`
This is a small but significant piece required to phase out the old type objects in favor of the new.
Self explanatory.
Run the test suite.

Add `size_in_bytes` to new type objects

---

vyper/parser/events.py
vyper/parser/stmt.py

Remove redundant type checks when generating LLL for events.
Mostly should be self explanatory. All of the raised exceptions were dead code, because the checks happen in the new type checking pass.
Of note is line 84 in `parser/events.py` - the call to `base_type_conversion` was not actually performing a conversion, this was just a way to validating the argument type prior to generating the logging topic.
Confirm that the test sutie is still passing.

Remove redundant type-check logic in event LLL-gen

---

tests/functional/context/types/test_event.py
vyper/context/types/indexable/sequence.py

Add the `canonical_type` property method to `ArrayDefinition`.
See code.
Run the tests.  I've added some new cases related to event IDs - an incorrect event ID for decimal arrays is how I found this issue.

Add canonical_type to ArrayDefinition

---

vyper/parser/context.py
vyper/parser/stmt.py

Remove unused context managers.
In `parser/context.py` there are several context managers that have been made redundant thanks to the new type checking pass.  I've removed them and confirmed that nothing breaks.  It's one less piece to consider as we refactor.
Confirm that the test suite is still passing.

Remove unused context managers

---

tests/parser/functions/test_interfaces.py
vyper/context/types/meta/event.py
vyper/context/types/meta/interface.py

During type checking. consider events when validating the `implements` statement.
Expand the existing code for `implements` - most of the logic is just ported over from how we check functions.
Verify the test suite is still passing. This is already very well tested so I have not added further cases.

Consider events during type-check "implements:"

---

vyper/context/types/function.py
vyper/context/types/meta/interface.py
vyper/context/validation/module.py
vyper/context/validation/utils.py
vyper/signatures/interface.py

Move the logic for checking for unique method IDs into the type checker.
* expand `ContractFunction.method_id` to return a list of method IDs (required when a function uses default values)
* add `validate_unique_method_ids` to the validation utils, to perform the actual check.  This is called during the module-level type check, and when generating `InterfacePrimitive` objects.
* remove the now-ded logic in `signatures`
Run the tests. The behaviour is already well tested so I did not add any new tests.

Move method_id collision check into type checker

---

vyper/compiler/output.py
vyper/signatures/interface.py

Refactor the `interface` and `external_interface` compiler outputs.
The old logic used `EventSignature` and `FunctionSignature`. The new logic is nearly identical but uses the new `InterfacePrimitive` type. This is another chunk of the `signatures` module refactored out.
Run the test suite, confirm everything still passes.

Refactor interface outputs

---

vyper/parser/parser.py
vyper/parser/parser_utils.py
vyper/signatures/function_signature.py
vyper/signatures/interface.py

Remove redundant checks within the `parser` and `signatures` submodules.  All of these checks are now handled within type checking and all of this is unreachable code.
Delete!
1. Confirm the tests are still passing.
2. Check the latest coverage report on master to verify that all of the deleted code is unreachable.

Remove redundant checks in parser/signatures

---

vyper/context/types/function.py
vyper/signatures/function_signature.py

Refactor and remove function-level checks out of `signatures`
The only missing check was for a reentrancy guard on a view/pure function. I've added it during type checking, and then removed all the checks from `FunctionSignature`.
Confirm the test suite still passes

Refactor function-level checks

---

tests/ast/test_natspec.py
vyper/ast/natspec.py
vyper/compiler/output.py
vyper/context/types/function.py
vyper/context/validation/utils.py
vyper/signatures/sig_utils.py

Refactor how the method_identifier and natspec outputs are generated to eliminate dependency on the `signatures` subpackage.
* Modify `ContractFunction.method_ids` to return a dict rather than a list. Not sure why I did it as a list initially :grimacing:  but it wasn't in use in many places
* Use the new dict format for generating the refactored outputs, eliminating a need to generate `FunctionSignature` objects.
* Remove now-unused functions within `signatures`
* Fix failing tests related to natspec
Run the test suite.

Refactor method identifier and natspec outputs

---

vyper/ast/validation.py
vyper/context/types/function.py

Adjustments to the `ContractFunction` api to aid readability as I refactor out `FunctionSignature`.
* Add `is_constructor` and `is_fallback` property methods. This replaces `func.name == "__init__"`  comparisons.  More readable and makes it easier to refactor in the future.
* Replace `arg_count` with `min_arg_count` and `max_arg_count`.  The prior was a sometimes-int, sometimes-tuple and led to repeated `if isinstance(arg_count, tuple)` checks which aren't immediately obvious to the reader what's happening.
* Add `has_default_args` property method to check if max args > min args
Check that tests are passing.

Refactor ContractFunction

---

vyper/codegen/return_.py
vyper/parser/function_definitions/parse_external_function.py
vyper/parser/function_definitions/parse_internal_function.py
vyper/parser/function_definitions/utils.py

Use `ContractFunction` for reentrancy locks
Of note: the function type is annotated onto return statements as `func_type`.
The rest is fairly straightforward.
Check that tests are still passing.

Use ContractFunction for reentrancy locks

---

tests/parser/functions/test_empty.py
vyper/parser/events.py
vyper/parser/parser_utils.py
vyper/parser/stmt.py

Remove `base_type_conversion` from `parser_utils`
At one point this method did stuff, but now that type checking handles all the unhappy paths it's mostly just a roundabout way to call `unwrap_location`.
1. Replaced calls to `base_type_conversion` with `unwrap_location`.
1. Added a new branch in `unwrap_location` to support `empty`.
The `is_decimal_int128_conversion` is a relic from when we allowed implicit conversions between decimals and integers - you can check recent code coverage, this is now unreachable.
Run the tests. See that nothing is broke'd.

Remove base_type_conversion

---

tests/parser/functions/test_raw_call.py
vyper/functions/functions.py

fixes: #2269 
Copy some stuff
- Manual inspection
- Deploy to Etherscan and verify proxy working
Updated forwarder proxy bytecode to ERC-1167 compliance

Change forwarder proxy bytecode to ERC-1167

---

vyper/compile_lll.py

* find and remove unreachable instructions within the assembly
* merge sequential jumpdests
Added some logic in `assembly_to_evm` within `compile_lll.py`
Both of these situations occur as a result of LLL generation happening in small chunks that don't see the "bigger picture" around them. There is likely a more elegant solution here, but this is effective and simple to implement. I've left comments about what's happening, we can try to address this properly as we refactor out `parser` in the future and give ourselves more effective data structures to catch and fix this as it happens rather than after the fact.
Run tests, confirm that nothing broke.  If this created any issues we'd see tests failing everywhere, especially within the e2e tests of the examples.
Notice me senpai!

Assembly-level optimizations

---

vyper/compiler/utils.py
vyper/parser/function_definitions/parse_external_function.py
vyper/parser/function_definitions/parse_internal_function.py
vyper/parser/function_definitions/utils.py
vyper/parser/parser.py

Reorder functions within the bytecode and refactor how the function selector is checked.
Functions were previous sequenced in the same way as they are found in the source. Internal functions were jumped over following an inefficient `PUSH1 0x0 ISZEZO` check.
This PR places all internal functions __after__ the fallback, so they cannot be reached without being explicitely jumped to from an internal function. Thus, all the jumping logic can be removed and the bytecode size reduced.
The function selector itself was previous written to memory with offset 0, and loaded onto the stack for every comparison. This PR modifies the process so that the selector is kept on the stack and compared via `DUP` operations rather than repeated `MLOAD`. Less bytecode, less gas.
Run the tests, see that nothing …

Reorder functions within the bytecode

---

vyper/compile_lll.py

Consider `RETURN` when searching for unreachable bytecode. An extension of #2304 
Self explanatory - see diff.
Run tests.

fix: add RETURN when looking for unreachable code

---

tests/parser/syntax/test_return_tuple.py
vyper/codegen/return_.py

Simplify the logic around returning tuples, when each member of the tuple is of the same type.
Add a special `if` branch that replicates the logic for returning an array type. This branch is only reached if every member of the tuple has the same type, and that type is a base type (or array of the base type).
This has a not-insignificant effect on the bytecode size.
Run tests (TODO)
Cute aminals are for closers.

Streamlined ABI encoder logic for returning tuple types

---

.pre-commit-config.yaml
setup.cfg
setup.py
tests/examples/auctions/test_simple_open_auction.py
tests/parser/functions/test_raw_call.py
tox.ini

* Bump `isort` to `v5.7.0` in `setup.py` and `.pre-commit-config.yaml`
* Remove now-redundant `known_third_party` field within `setup.cfg`
* Update tox lint job
* Apply linter rules
Check that the lint job in the CI is passing

Bump isort dependency

---

vyper/parser/global_context.py

In storage, place re-entrancy locks immediately after the last used storage slot.
Within `parser/global_context.py`, storage variables are stored in `GlobalContext._globals`. The storage slot for each storage variable is determined from `len(self._globals)` prior to adding the variable into the dict. Arrays, mappings, and other multiple-slot types are always assigned exactly one slot, but their actual location is calculated from a `SHA3` operation (see #769 for more details).
Re-entrancy locks start at slot `0xFFFFFF` and if  more than this many storage variables are defined, a compile-time exception is raised.
This PR sets the initial re-entrancy lock to location `len(self._globals)` - immediately after the last used storage slot. This works because globals are defined while parsing the …

Place re-entrancy lock immediately after used storage slots

---

tests/parser/features/decorators/test_payable.py
vyper/parser/function_definitions/parse_external_function.py
vyper/parser/function_definitions/parse_function.py
vyper/parser/parser.py

Optimize how the nonpayable check is applied within the bytecode
Where possible, external functions are now organized by [payable], [nonpayable] and a single assertion that `msg.value == 0` is placed in between the two sections.
When a contract contains a payable default function, and nonpayable functions, this optimization is not possible and the check is still applied per-function.
Run the tests.  I expanded the testing around the `@payable` decorator to handle all the different possible permutations based on this optimization.

Optimize nonpayable assertion

---

tests/parser/types/test_lists.py
vyper/parser/expr.py

Fix an issue preventing literal lists where some members are literals and others are not.  For example:
```
@external
def foo() -> uint256[2]:
a: uint256 = 123
return [a, 2]
```
This would fail because in `parser/stmt.py` the literal `2` is interpreted as an `int128`. However, we know this to be incorrect because we have already completed the type checking pass.
Remove the now-redundant check that was blocking this at compile-time.  I did some minor voodoo to retain the type information within `parser` so that nothing else breaks later down the line, and left a comment to prevent confusion later when we refactor types out altogether.
Check that tests are passing.

Fix: incorrect `TypeMismatch` when dealing with literals in lists

---

docs/release-notes.rst
setup.py

Pending: https://github.com/vyperlang/vyper/pull/2281

Release v0.2.9

---

tests/parser/globals/test_getters.py
vyper/ast/expansion.py
vyper/context/types/function.py

Fix some issues with public getters:
* incorrect `stateMutability` within the ABI
* compile-time error when declaring a multidimensional array as public
See diff. Both fixes are fairly straightforward.
Run the tests. I added some cases to cover the behaviours where the issue existed. This initially made it to master in #2295, I had assumed that public getters were better covered in the test suite than they actually are :grimacing:

Public getter fixes

---

tests/parser/features/test_memory_dealloc.py
vyper/signatures/function_signature.py

In `VariableRecord`, return the correct size when the related type object is one of the new `context` types.
This fixes an issue with memory corruption caused by excessive deallocation when releasing internal variables :(

fix: Var size when using new type objects

---

.github/workflows/test.yml
pyproject.toml
tox.ini

Hey.
This is my first PR here. :tada: 
1. Create a new action to run `py39` in GitHub Actions;
2. Replace `py36` by `py38` for all CI actions;
3. Force `black` to use `py38`.
Well, I'm not sure if we really need to. My suggestion is to keep an isolated GitHub action for this version until it becomes obsolete.
Check GitHub Actions. :trollface: 
Python 3.9 build is breaking due to davesque/blake2b-py installation.
> The requirement to install Rust is related to davesque/blake2b-py#2 - as soon as this is fixed upstream we plan to roll out official support for Python 3.9.
We must wait davesque/blake2b-py#2 to rebuild.
#2182

Add py39 configs and prepare to drop py36

---

pyproject.toml
tox.ini

* remove `py39` as a version target in the black conf
* remove the `--check` flag when running black and isort in tox

Linter fixes

---

tests/parser/types/test_lists.py
vyper/parser/expr.py
vyper/parser/parser_utils.py
vyper/parser/self_call.py

Fix a runtime bug allowing for memory corruption when making an internal function call inside a literal array or another function call.
The issue is the same as the one outlined in https://github.com/vyperlang/vyper/security/advisories/GHSA-2r3x-4mrv-mcxf and fixed in https://github.com/vyperlang/vyper/pull/2186. In my previous fix I did not fully comprehend the scope of the issue, and so the bug was still present when making a private function call inside a literal array, or when accessing a single indexed value from a private function call returning a list or tuple.
Expand the logic added in #2186, applying it also to `Subscript` and `List` nodes.  I have refactored the check into it's own new function, `parse_sequence`, which is applied on all lists, tuples, and private function calls. …

Fix: memory corruption from nested internal function calls

---

tests/parser/functions/test_convert_to_int128.py
tests/parser/types/numbers/test_sqrt.py
vyper/ast/nodes.py
vyper/functions/convert.py
vyper/parser/arg_clamps.py
vyper/parser/expr.py
vyper/utils.py

Rename some of the `SizeLimits` enum attributes.  This smol PR lays groundwork for adding more number types (and reduces the complexity of the next PR's diff).
Grepping and copy-paste.
Read the diff, verify that tests are still passing. If you're so motivated, you can also grep to check I didn't miss anything.

Rename SizeLimits constants

---

tests/compiler/test_opcodes.py
tests/parser/functions/test_raw_call.py
tests/parser/syntax/test_self_balance.py
vyper/opcodes.py

* Add EIP2929 opcode repricings
* Set default evm version to `berlin`
I took the new pricings from the [EIP2929 spec](https://eips.ethereum.org/EIPS/eip-2929).  I didn't include any logic to account for hot-vs-cold access - in the same way that we always assume an SSTORE to cost 20,000 these values just give an upper-bound estimate.
I also bumped the default evm target to `berlin`. This has no effect aside from the gas estimates, as there are no new opcodes introduced.
All of this is required to make the test suite pass, because the latest release of `eth-tester` now uses berlin as the default ruleset.
Verify that the test suite is passing in the CI.  I had to tweak a few tests, I tried to do so in a way such that we won't have to adjust them again for the next hardfork.

EIP2929 opcode repricing

---

vyper/optimizer.py

Optimize how calldata is loaded into memory.
Within `optimizer.py`, look for sequential instructions of e.g.
```
[mstore, 864, [calldataload, 4]],
[mstore, 896, [calldataload, 36]],
[mstore, 928, [calldataload, 68]],
```
This can be optimized to:
```
[calldatacopy 864, 4, 32 * 3]
```
The optimization is applied with the same logic we use to optimize memory-zeroing actions:
1. Look for sequential `mstore` instructions that reference sequential calldata locations.
2. Merge them into a single `calldatacopy`
Run the tests. I didn't add any new specific cases, but this optimization is applied anywhere multiple input args are taken by an external function so if it weren't working we'd see things failing everywhere.

Optimize calldataload

---

docs/built-in-functions.rst
tests/functions/folding/test_abs.py
vyper/functions/functions.py

Add `abs` as a builtin function to get the absolute value of an `int256`.
Add `Abs` within `vyper/functions/functions.py`. The logic is fairly straightforward - the only possible overflow is with `-2**255` where we end up with the same value, so I do a check that the result is != the original value.
Run the tests. I've added hypothesis tests to verify both the runtime and compile-time behaviour, including the happy path and the reverting path.

Add builtin function `abs`

---

vyper/ast/expansion.py
vyper/parser/global_context.py

Remove `implements` statements from the AST after type checking and prior to LLL gen.
All restrictions imposed by this statement are validated within the type checking pass. Removing it prior to heading into `parser` reduces the complexity as it's one less thing we have to think about.
* Add some logic to `ast/expansion.py`
* Remove references to `implements` within `GlobalContext` in parser.
Run the tests.

Remove `implements` statements after type checking

---

vyper/ast/expansion.py
vyper/context/validation/annotation.py
vyper/context/validation/base.py
vyper/context/validation/local.py
vyper/context/validation/module.py

Expand the AST annotation logic to cover more node types, notably:
* module-scoped `AnnAssign` nodes (storage variables)
* For loops
* structs
* builtin functions
This is more groundwork for eventually removing types from `parser`.
Confirm that the test suite is still passing.  Nothing in this PR has any effect on compilation, so there is nothing new to test at this point.

Expand AST type annotation

---

tests/functional/context/types/test_size_in_bytes.py
tests/functional/test_storage_slots.py
vyper/compiler/phases.py
vyper/context/__init__.py
vyper/context/types/bases.py
vyper/context/types/value/array_value.py
vyper/context/validation/data_positions.py
vyper/functions/convert.py
vyper/functions/functions.py
vyper/parser/events.py
vyper/parser/expr.py
vyper/parser/external_call.py
vyper/parser/keccak256_helper.py
vyper/parser/parser_utils.py
vyper/parser/stmt.py

* Add the start of an expansion pass that assigns variable positions prior to generating the LLL
* Use this new pass to refactor the layout of storage variables
Currently, whenever dealing with a type that requires >1 storage slot, we calculate the storage location in the same way as that of a mapping (using a keccak).  This is inefficient for both gas costs and bytecode size. Because Vyper does not support dynamically-sized variables without a limit on their length, it is possible to calculate the maximum required number of slots for all storage variables and instead place them sequentially to avoid the expensive `SHA3` operation.
To do this, I've added the `DataPosition` class, and related child classes, to represent positions within storage/memory/calldata. After type checking is …

Assign storage locations prior to LLL gen / place arrays sequentially in storage

---

docs/interfaces.rst

Fixed typos in documentation for Interfaces.
Fixed typos.
See commit.

docs: fix typos in interfaces.rst

---

.github/ISSUE_TEMPLATE/bug.md
vyper/cli/vyper_compile.py

I have never ever EVER seen a bug report where the output of `pip
freeze` made a difference. It only ever takes up space.
This commit also brings back the --debug flag, so it's easy for users
to submit the debug info for their bug.

Change guidance for bug reporting

---

tests/functional/test_storage_slots.py
vyper/parser/global_context.py

Fix an issue allowing corruption of storage by re-entrancy locks.
In #2308, the location of re-entrancy locks was moved to the first unused storage slot. This worked fine as long as all multiple-slot types were stored using a sha3, but after #2361 this created a potential overlap between the lock slot and regular storage when the contract contains at least one storage value that occupies multiple slots.
In `vyper/parser/global_context.py`, when calculating the offset for re-entrancy locks, correctly consider the size of each type.
Run the tests. I expanded a test that I'd added in #2361 that focuses on checking the layout of storage - it now also includes checks involving re-entrancy locks.

Fix: storage corruption from re-entrancy locks

---

docs/built-in-functions.rst

In reference to issue [1851](https://github.com/vyperlang/vyper/issues/1851) I added a working code example of `ecrecover ` built-in function.
I followed the same template in the docs, deployed a demo that can be found [here](https://github.com/notaquant/vyper-crypto-demo)
Validate against 
* Update docs/built-in with a working example of `ecrecover ` function in Vyper.

docs(built-in): add ecrecover example

---

vyper/compile_lll.py

See title
All clamps have the following code:
```
(assume condition is on the stack)
ISZERO _revert JUMPI # if not condition goto _revert
PUSH1 0 DUP REVERT
_revert
JUMPDEST
```
Since clamps are super common this code gets repeated. This reduces code
size by adding the PUSH1 0 DUP REVERT to each program's postamble, and
then clamps are simplified to the following
```
(assume condition is on the stack)
_revert JUMPI # if not condition goto _revert
-- cool now 5 opcodes are skipped
```
Then at the end of the contract, the following "postamble" is inserted:
```
_revert
JUMPDEST
PUSH1 0 DUP REVERT # repeated code is shared, yay
```
This commit also optimizes the following common "truthy" sequences:
```
ISZERO ISZERO ISZERO -> ISZERO
ISZERO ISZERO _jumpdest JUMPI -> _jumpdest JUMPI
```
Tests …

Reduce code size by sharing code for clamps

---

tests/functional/test_storage_slots.py
vyper/old_codegen/function_definitions/parse_external_function.py
vyper/old_codegen/function_definitions/parse_internal_function.py
vyper/old_codegen/function_definitions/utils.py
vyper/old_codegen/global_context.py
vyper/old_codegen/return_.py
vyper/semantics/types/function.py
vyper/semantics/validation/data_positions.py

This also refactors the nonreentrant key allocation so the functionality
happens in the same place as global variable allocation.
Apply a894a33e27e02b9742589b19db9cedc6f2f2dcaa to master, see that tests don't pass but they do on this branch

fix: storage slot allocation bug

---

tests/functional/codegen/test_struct_return.py
vyper/old_codegen/return_.py

The optimization for tuples of base types expected anything inside a
tuple to be an int, but that's not always the case.
Luckily logic introduced in 0605abbe9 can actually be generalized to any
tuple type which has no dynamic data in the ABI encoding, so we just
remove the constraints on the child types.
Fixes #2390 
Compile the example in #2390.
Fix type error when returning nested tuples.

Fix return optimization for nested tuple

---

tests/parser/syntax/test_raw_call.py
vyper/semantics/validation/annotation.py

This is a regression in v0.2.14, the way function calls got annotated
was changed but kwargs didn't get the update.
Test case:
```
balances: HashMap[uint256, uint256]
@external
def foo(receiver: address):
raw_call(receiver, b"", value=self.balance - self.balances[0])
```

fix: annotated kwargs for builtins

---

docs/types.rst

In reference to issue [2367](https://github.com/vyperlang/vyper/issues/2367) I updated the documentation to make it clear how to use multidimensional lists.
Added an explanation and an example to the file docs/types.rst
Compile and run the example code, also verify that the explanation is in line with the Solidity documentation because Vyper is modeled after it: https://docs.soliditylang.org/en/v0.6.0/types.html#arrays
Improved documentation of multidimensional lists.

Updated documentation to make it clear how to use multidimensional lists

---

vyper/old_codegen/global_context.py
vyper/old_codegen/types/types.py

The dict of interfaces was not being passed around correctly during
parse_type, resulting in variables like the following not type-checking:
```
interface Foo:
...
foos: HashMap[..., Foo] # didn't type check
```
Fixes #1824
Compile the above example
Allow interfaces in lists, structs and maps

fix: allow interfaces in lists,structs,maps

---

docs/built-in-functions.rst
tests/conftest.py
tests/functional/codegen/test_abi_encode.py
vyper/builtin_functions/functions.py
vyper/old_codegen/abi.py
vyper/old_codegen/global_context.py
vyper/old_codegen/return_.py
vyper/old_codegen/types/types.py
vyper/semantics/types/__init__.py
vyper/semantics/types/value/numeric.py

Implement user-facing abi encode function
This exposes abi_encode to the user. The returned bytestring has a
length of the size bound on the ABI encoded data (size_bound was
refactored in this commit to a convenience function) and the provided
buffer must be large enough to accept the data.
Compile the following example contract:
```python
struct Foo:
a: String[64]
b: int128
c: decimal
@internal
def foo():
x: uint256 = 1
r1: Bytes[32] = abi_encode(x)
y: Foo = Foo({a: "123", b: 234, c: 50.0})
z: Bytes[32] = b"678"
r2: Bytes[288] = abi_encode(x, y, z)
```
To test:
- arrays

Implement abi_encode builtin

---

tests/cli/vyper_compile/test_import_paths.py
vyper/ast/signatures/interface.py

expand parsing to all AST types which might need to be parsed to
semantically understand the top-level items in a module.
Fixes #2359
Compile the example in the issue

fix handling of structs in imported modules

---

vyper/old_codegen/events.py

Added by accident in cea5dd89dab17031b7c508bc5b9feaa47ff2e7db, sorry

remove a debug print statement

---

vyper/old_codegen/arg_clamps.py

and also avoid direct manipulation of the stack
I guess this isn't as important now that the standard is to use int256.
Bit twiddling
Tests still pass
Increase efficiency of int128 clamps

Rewrite the int128 clamp to avoid a branch

---

vyper/cli/vyper_compile.py
vyper/compiler/__init__.py

Fix #2410 
The previous fix in #1720 stopped working because the modified source
code was only being provided to some compilation steps (compile_codes)
but not others (get_interface_codes).
Move the additional newline upstream
Compile the code in the issue

fix trailing newline parse bug

---

docs/types.rst

The documentation is currently [missing a code example on how to define structs](https://vyper.readthedocs.io/en/stable/types.html#structs). That's because the `code-block` RST directive is missing a language argument. This PR fixes it.

Fix code-block directive in struct docs

---

docs/types.rst

As mentioned #2422, the struct example in the docs is slightly wrong. Here's the fix.

Fixes struct example

---

vyper/evm/opcodes.py
vyper/lll/compile_lll.py
vyper/old_codegen/arg_clamps.py
vyper/old_codegen/lll_node.py

In https://github.com/vyperlang/vyper/pull/2416 I implemented some LLL features to make it easier to recover LLL variables at an arbitrary jumpdest. This PR pulls out that functionality so the OVM PR is a bit smaller.
Enable a limited subroutine architecture in LLL, although the functionality is very basic (even more basic than parametrized labels) and mostly relies on convention. The convention is basically
```
(seq_unchecked
_sym__exit ; push exit label onto the stack
arg3 ; push label args reverse order because the stack is LIFO
arg2
arg1
goto my_subroutine
label _exit
dummy ; my_subroutine returns a stack item, this marks it for LLL
)
...
(seq
label my_subroutine
(with arg1 pass (with arg2 pass (with arg3 pass) ... ))
...
_return_value
swap1
jump ; _sym__exit
)
```
In the future this …

refactor: enable limited LLL subroutines

---

docs/installing-vyper.rst

- Update install directions to include directions for `nix`
- Fix minor spelling errors as well.
- Updated pip install method to reflect versioning of more recent compiler versions.
Edited the page.
I installed vyper 0.2.11 via nix on my laptop and compiled a contract successfully.
- Documentation update: Install Vyper via Nix now in documentation. 
No

docs(install): add new install method via nix

---

docs/built-in-functions.rst
tests/conftest.py
tests/parser/functions/test_create_with_code_of.py
tests/parser/syntax/test_create_with_code_of.py
vyper/builtin_functions/functions.py

Extended the `create_forwarder_to` built-in by adding functionality to deploy minimal proxies using the `CREATE2` opcode.
The following is now possible:
```python
@external
def foo(_target: address, _salt: bytes32) -> address:
return create_forwarder_to(_target, salt=_salt)
```
The deployment address of the proxy can be determined with the following:
```python
keccak256(0xff ++ deployingAddr ++ salt ++ keccak256(bytecode))[12:]
```
where `bytecode` is equal to:
```python
pre = "0x602D3D8160093D39F3363d3d373d3d3d363d73"
post = "0x5af43d82803e903d91602b57fd5bf3"
bytecode = pre ++ target ++ post
```
Modified the built-in to accept and handle new keyword `salt`.
Check the new tests added. A set of tests verifying syntax, and a test verifying runtime execution.
Added support for deterministic …

feat: deterministic proxies with CREATE2 and EIP1167

---

.github/workflows/test.yml
pyproject.toml
tox.ini
vyper/__init__.py

Major operating systems (Ubuntu, MacOS) have already moved on, plus it
doesn't have dataclasses.

Drop python3.6 support

---

vyper/cli/vyper_compile.py

add the flag "-o" to generate output files. this will write abi, bin and combined files. other options like ast, lll, opcodes need to be handled separately.
add a flag to argparser and write the files

Output flag

---

vyper/old_codegen/abi.py
vyper/old_codegen/expr.py
vyper/old_codegen/function_definitions/external_function.py
vyper/old_codegen/parser_utils.py
vyper/old_codegen/return_.py
vyper/old_codegen/self_call.py
vyper/old_codegen/stmt.py
vyper/old_codegen/types/check.py

Optimize and simplify make_setter, cleaning out some inefficient bytecode that was introduced in https://github.com/vyperlang/vyper/pull/2447

Reduce stack operations in make_setter

---

.github/workflows/build.yml

Allow manually triggering CD workflow for building binaries, as well as adjusting it to run on tags being pushed instead of new releases being created.

fix: allow build CD workflow to be manually triggered

---

vyper/old_codegen/external_call.py

the number of args passed could be somewhere in between
base args + 0 kwargs and
base args + all kwargs
Fix #2520 and #2374 
An assertion introduced in #2447 was too aggressive. The rest of the code works.
`vyper -f ir` of the code in the issues
Fix calls to external functions involving kwargs

relax an assertion in packing external call args

---

tests/base_conftest.py
tests/parser/features/external_contracts/test_external_contract_calls.py
tests/parser/features/test_assert.py
vyper/builtin_functions/functions.py
vyper/old_codegen/external_call.py
vyper/old_codegen/parser_utils.py

Fix #2529 
Change straight `assert (call ...)` to
```
if !(call ...) (seq
(returndatacopy 0 0 returndatasize)
(revert 0 returndatasize)
))
```
Check out tests
Propagate revert data when external call fails

propagate revert data when external call fails

---

tests/ast/test_folding.py
vyper/ast/folding.py

Fix #2329 
Relax a restriction on when constant folding can happen
See the test / compile the example in #2329 
Allow constant folding of <address>.balance

fix constant folding of attributes

---

tests/parser/types/test_lists.py
vyper/old_codegen/expr.py

Fix #2156 and #2130 
Note that a bug similar to #2130 can still be triggered with a list of ambiguous type. For instance, `MY_LIST: constant(uint256[1]) = [1]`. I used a `decimal` in the test to demonstrate that the array literals pass but the type checker issue still needs to be addressed.
Expand the logic in `Expr.parse_Subscript` to handle constants/literals
See test
Allow variable access on constant/literal arrays

allow variable access on constant/literal arrays

---

tests/parser/features/test_immutable.py
tests/parser/functions/test_raw_call.py
tests/parser/syntax/test_immutables.py
vyper/builtin_functions/functions.py
vyper/old_codegen/events.py
vyper/old_codegen/expr.py
vyper/old_codegen/keccak256_helper.py
vyper/old_codegen/parser_utils.py
vyper/old_codegen/stmt.py

There is a common pattern in the codebase which checks if a bytestring is in memory and copies if not. This abstracts the pattern into a function, and additionally applies it to the `raw_call` function for about 20 bytes savings per usage of raw_call (when the input is already in memory).
See code is cleaner, new tests pass
Optimize raw_call

refactor: abstract `ensure_in_memory` pattern
